----- VHDL Libraries
-- IEEE Standard Libraries
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_unsigned.all;
-- Standard library text io
use std.textio.all;
library work;

/* Testbench for FPSigmoid.vhd: for the configured generics it drives every possible input through the DUT.
   Each output is compared against the expected integer value read from "sig_approx_fp.txt", which must sit in the simulation directory and is generated by FPSigmoid_test.m.
   The test passes when every output matches. */
entity FPSigmoid_tb is
end FPSigmoid_tb;

architecture test of FPSigmoid_tb is
	----- Constants
	-- FPSigmoid generics: keep these equal to the defaults declared in FPSigmoid.vhd.
	constant	X_M_BITS	: integer := 3;
	constant	XY_N_BITS	: integer := 15;
	constant	RHO			: integer := 2;
	
	----- DUT (FPSigmoid) Port Signals
	signal 		X    		: std_logic_vector((X_M_BITS + XY_N_BITS) downto 0);
	signal		X_int 		: integer := -(2**(X_M_BITS + XY_N_BITS -1));
	signal 		Y    		: std_logic_vector(XY_N_BITS downto 0);
	signal		Y_int 		: integer;
begin
    -- DUT instantiation; the generics are left at the defaults declared in FPSigmoid.vhd.
    DUT: entity work.FPSigmoid 
        port map    (
			X		=> X,
			Y		=> Y
        );

	-- Exhaustive sweep of the input range, one reference value per line of the golden file.
    SIM_PROCESS: process
		----- Process variables and constants
		constant XMin 				: integer := -(2**(X_M_BITS+XY_N_BITS));	
		constant XMax 				: integer := ((2**(X_M_BITS+XY_N_BITS))-1);	
		variable Ysw 				: integer;
		variable Yhw				: integer;
		----- File I/O
		-- Expected integer outputs of the approximation, produced by MATLAB.
		file y_sw_file				: text open read_mode is "sig_approx_fp.txt";
		variable y_sw_file_line		: line;
    begin
		-- Walk every possible input and compare the hardware output against the reference.
		for XCurr in XMin to XMax loop
			readline(y_sw_file, y_sw_file_line);
			read(y_sw_file_line, Ysw);
			X <= std_logic_vector(to_signed(XCurr, X'length));
			wait for 10 ns;
			Yhw := to_integer(signed(Y));
			if (Ysw /= Yhw) then
				report "ERROR: For X = " & integer'image(XCurr) & ", outputs do not match! Y HW = "
						& integer'image(Yhw) & 	"Y SW = " & integer'image(Ysw)
						severity error;
			end if;
		end loop;
		file_close(y_sw_file);
        report "Test Passed! SW & HW outputs matched for all possible inputs!" severity error;
    end process;
end test;