-- VestaRV: NFC testbench
-- Standalone, self-checking bench for the NFC ISO 14443A tag/card-emulation peripheral, using periph_tb_pkg, nfc_bfm_pkg and the independent behavioral reader model nfc_reader_model.vhd.
-- The DUT is declared as a COMPONENT so the bench analyzes standalone; default binding resolves it to work.NFC at elaboration.
-- Three clock domains: clk (smclk, free-running, drives the CDC synchronizers), ClkMem (the bus clock, FREE-RUNNING as mclk is at the MCU) and rf_clk (the carrier-derived protocol clock generated by the reader model).
-- ClkMem must free-run: NFC carries its volatile read words into the bus domain on work.sync chains and toggle-qualified copies, and a clock gated to one edge per access starves them. The gated form this bench used until 2026-09-15 is not a shape the chip presents.
-- W1C SR bits: after a lane-0 SR write, issue a dummy CR read before re-reading SR so the clear level retires first.
-- GROUP 12 is the read-path group: NFCxSR, NFCxDBG and NFCxDATA read from the bus WHILE their sources move. It is a compatibility group, graded identically against the pre-latch design and against the ClkMem read path.
-- Protocol time is COMPRESSED (ETU=16, SUBCDIV=2, FDT=20 rf_clk ticks) so a full REQA to READ transaction runs in seconds: never scale real 13.56 MHz to wall clock.
-- GROUP 6c is the one check that reaches into the DUT, through a VHDL-2008 external name on state_s2, the SR STATE field register itself. A corrupt STATE word survives exactly one clk period, which no bus read cadence can be relied on to catch, so the field is sampled every clk instead of through rdata_out.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.env.all;
use work.periph_tb_pkg.all;
use work.nfc_bfm_pkg.all;

entity NFC_tb is
end entity NFC_tb;

architecture sim of NFC_tb is

    constant PERIOD  : time := 40 ns;   -- ~25 MHz smclk-domain bus reference
    constant RF_HALF : time := 25 ns;   -- rf_clk half period (compressed carrier)

    -- compressed protocol-time divisors
    constant C_ETU     : natural := 16;
    constant C_HALF    : natural := 8;    -- ETU/2
    constant C_SUBCDIV : natural := 2;
    constant C_PAUSE   : natural := 3;
    constant C_FDT     : natural := 20;

    -- provisioned identity: uid0 goes first on air
    constant UID0 : std_logic_vector(7 downto 0) := x"11";
    constant UID1 : std_logic_vector(7 downto 0) := x"22";
    constant UID2 : std_logic_vector(7 downto 0) := x"33";
    constant UID3 : std_logic_vector(7 downto 0) := x"44";
    constant UIDW : std_logic_vector(31 downto 0) := UID3 & UID2 & UID1 & UID0;
    constant BCC  : std_logic_vector(7 downto 0) := UID0 xor UID1 xor UID2 xor UID3;
    constant ATQA : std_logic_vector(15 downto 0) := x"0044";
    constant SAK  : std_logic_vector(7 downto 0)  := x"00";

    -- DUT entity, declared as a component so the bench compiles standalone.
    component NFC is
        port (
            clk          : in  std_logic;
            resetn       : in  std_logic;
            irq_field    : out std_logic;
            irq_rxf      : out std_logic;
            irq_txdone   : out std_logic;
            irq_crcerr   : out std_logic;
            ClkMem       : in  std_logic;
            EnMemPeriph  : in  std_logic;
            WEn          : in  std_logic_vector(3 downto 0);
            MABPart      : in  std_logic_vector(7 downto 2);
            wdata        : in  std_logic_vector(31 downto 0);
            rdata_out    : out std_logic_vector(31 downto 0);
            rf_clk       : in  std_logic;
            field_detect : in  std_logic;
            rf_rx        : in  std_logic;
            rf_txmod     : out std_logic;
            rf_tx_en     : out std_logic;
            afe_en       : out std_logic;

            -- EVFAB taps: T-mode toggle producers, pre-IE and independent of the SR flags' W1C clears.
            evt_field    : out std_logic;
            evt_rxframe  : out std_logic
        );
    end component;

    -- clocks / reset
    signal clk    : std_logic := '0';
    signal ClkMem : std_logic := '0';
    signal resetn : std_logic := '0';

    -- interrupts
    signal irq_field, irq_rxf, irq_txdone, irq_crcerr : std_logic;

    -- register bus
    signal pbus      : periph_bus_t := PERIPH_BUS_IDLE;
    signal rdata_out : std_logic_vector(31 downto 0);

    -- RF link between the reader model and the DUT
    signal rf_clk       : std_logic;
    signal rf_rx        : std_logic;
    signal field_detect : std_logic;
    signal rf_txmod     : std_logic;
    signal rf_tx_en     : std_logic;
    signal afe_en       : std_logic;

    -- ---- EVFAB taps -------------------------------------------------------
    signal evt_field   : std_logic;
    signal evt_rxframe : std_logic;

    /* ---- continuous EVFAB flip monitor (checker independence) -------------
       Counts toggle FLIPS (XOR of consecutive clk samples) on each producer tap since the last evt_mon_clear pulse.
       Reads only the exported evt_field/evt_rxframe ports, never a DUT internal. */
    signal evt_field_flips, evt_rxf_flips : natural := 0;
    signal evt_field_prev, evt_rxf_prev   : std_logic := '0';
    signal evt_mon_clear                  : std_logic := '0';

    -- reader-model per-transaction config
    signal cfg_field          : std_logic := '0';
    signal cfg_go             : std_logic := '0';
    signal cfg_short          : boolean   := false;
    signal cfg_bytes          : nfc_byte_array(0 to NFC_MAX_BYTES - 1) := (others => (others => '0'));
    signal cfg_nbytes         : natural := 0;
    signal cfg_partial_bits   : natural := 0;
    signal cfg_append_crc     : boolean := false;
    signal cfg_corrupt_parity : boolean := false;
    signal cfg_corrupt_crc    : boolean := false;
    signal cfg_resp_parity    : boolean := true;

    -- reader-model observations
    signal obs_busy         : std_logic;
    signal obs_txn_count    : natural;
    signal obs_saw_response : std_logic;
    signal obs_fdt_ticks    : natural;
    signal obs_sof_ok       : std_logic;
    signal obs_nbytes       : natural;
    signal obs_bytes        : nfc_byte_array(0 to NFC_MAX_BYTES - 1);
    signal obs_nbits        : natural;
    signal obs_first_bit    : std_logic;
    signal obs_parity_ok    : std_logic;
    signal obs_crc_ok       : std_logic;

    /* ---- SR.STATE legality monitor (GROUP 6c) -----------------------------
       rf_state encodes iso_t as 0 to 4, so any other code in the SR STATE field is a word the FSM never held.
       Samples dut.state_s2, the SR STATE field register, every clk: the corrupt word a bit-by-bit crossing produces lasts one clk period, which is shorter than any bus read cadence this bench can sustain. */
    constant ST_MAX : natural := 4;      -- StHALT, the highest legal code
    signal st_mon_en   : std_logic := '0';
    signal st_illegal  : natural := 0;   -- clk samples holding a code above ST_MAX
    signal st_changes  : natural := 0;   -- STATE field changes seen while armed
    signal st_samples  : natural := 0;
    signal st_bad_code : std_logic_vector(3 downto 0) := (others => '0');

    /* ---- GROUP 12d: the WIDTH of an NFCxSR W1C clear level ----------------
       The five clr_* levels reach ASYNCHRONOUS clears in the clk domain, so a
       simulator applies them at any width and the defect is invisible to a value
       check. It is a width: periph_regs retires a held strobe asynchronously on
       deselect, and the MCU's select is one mclk cycle that self-clears on the very
       edge the slave captures, so on the raw strobe the held level is a runt.
       The monitor reads dut.clr_rxframef through a VHDL-2008 external name. */
    signal clr_mon_arm : std_logic := '0';
    signal clr_w       : time      := 0 ns;   -- last high phase seen while armed
    signal clr_n       : natural   := 0;      -- high phases seen while armed

    shared variable sb : scoreboard;

begin

    clr_width_mon : process
        alias a is << signal dut.clr_rxframef : std_logic >>;
        variable t0 : time := 0 ns;
    begin
        wait on a;
        if to_X01(a) = '1' then
            t0 := now;
        elsif t0 > 0 ns then
            if clr_mon_arm = '1' then
                clr_w <= now - t0;
                clr_n <= clr_n + 1;
            end if;
            t0 := 0 ns;
        end if;
    end process;

    state_mon_proc : process(clk)
        alias sr_state is << signal dut.state_s2 : std_logic_vector(3 downto 0) >>;
        variable v    : std_logic_vector(3 downto 0);
        variable prev : std_logic_vector(3 downto 0) := (others => '0');
    begin
        if rising_edge(clk) and st_mon_en = '1' then
            v := to_X01(sr_state);
            st_samples <= st_samples + 1;
            if v /= prev then
                st_changes <= st_changes + 1;
                prev := v;
            end if;
            if is_x(v) or to_integer(unsigned(v)) > ST_MAX then
                st_illegal  <= st_illegal + 1;
                st_bad_code <= v;
            end if;
        end if;
    end process state_mon_proc;

    -- clock / register-bus clock. ClkMem FREE-RUNS, as mclk does at the MCU: NFC now
    -- carries its volatile read words into the ClkMem domain on work.sync chains and on
    -- toggle-qualified copies, and a clock gated to one edge per access starves them.
    clk    <= not clk after PERIOD / 2;
    ClkMem <= clk;

    -- Continuous EVFAB flip monitor (see the signal-declaration comment above).
    evt_mon_proc : process(clk)
        variable f_lvl, r_lvl : std_logic;
    begin
        if rising_edge(clk) then
            f_lvl := to_X01(evt_field);
            r_lvl := to_X01(evt_rxframe);
            if evt_mon_clear = '1' then
                evt_field_flips <= 0;
                evt_rxf_flips   <= 0;
                evt_field_prev  <= f_lvl;
                evt_rxf_prev    <= r_lvl;
            else
                if f_lvl /= evt_field_prev then
                    evt_field_flips <= evt_field_flips + 1;
                end if;
                if r_lvl /= evt_rxf_prev then
                    evt_rxf_flips <= evt_rxf_flips + 1;
                end if;
                evt_field_prev <= f_lvl;
                evt_rxf_prev   <= r_lvl;
            end if;
        end if;
    end process;

    -- DUT
    dut : component NFC
        port map (
            clk          => clk,
            resetn       => resetn,
            irq_field    => irq_field,
            irq_rxf      => irq_rxf,
            irq_txdone   => irq_txdone,
            irq_crcerr   => irq_crcerr,
            ClkMem       => ClkMem,
            EnMemPeriph  => pbus.en_mem,
            WEn          => pbus.wen,
            MABPart      => pbus.addr_periph,
            wdata        => pbus.write_data,
            rdata_out    => rdata_out,
            rf_clk       => rf_clk,
            field_detect => field_detect,
            rf_rx        => rf_rx,
            rf_txmod     => rf_txmod,
            rf_tx_en     => rf_tx_en,
            afe_en       => afe_en,
            evt_field    => evt_field,
            evt_rxframe  => evt_rxframe
        );

    -- Behavioral reader (PCD) model: generates rf_clk, rf_rx and field_detect
    reader : entity work.nfc_reader_model
        generic map ( RF_HALF => RF_HALF )
        port map (
            rf_clk       => rf_clk,
            rf_rx        => rf_rx,
            field_detect => field_detect,
            rf_txmod     => rf_txmod,
            rf_tx_en     => rf_tx_en,
            cfg_field          => cfg_field,
            cfg_go             => cfg_go,
            cfg_short          => cfg_short,
            cfg_bytes          => cfg_bytes,
            cfg_nbytes         => cfg_nbytes,
            cfg_partial_bits   => cfg_partial_bits,
            cfg_append_crc     => cfg_append_crc,
            cfg_corrupt_parity => cfg_corrupt_parity,
            cfg_corrupt_crc    => cfg_corrupt_crc,
            cfg_resp_parity    => cfg_resp_parity,
            cfg_etu            => C_ETU,
            cfg_half           => C_HALF,
            cfg_subcdiv        => C_SUBCDIV,
            cfg_pause          => C_PAUSE,
            obs_busy         => obs_busy,
            obs_txn_count    => obs_txn_count,
            obs_saw_response => obs_saw_response,
            obs_fdt_ticks    => obs_fdt_ticks,
            obs_sof_ok       => obs_sof_ok,
            obs_nbytes       => obs_nbytes,
            obs_bytes        => obs_bytes,
            obs_nbits        => obs_nbits,
            obs_first_bit    => obs_first_bit,
            obs_parity_ok    => obs_parity_ok,
            obs_crc_ok       => obs_crc_ok
        );

    -- stimulus
    stim_proc : process
        variable rdw     : std_logic_vector(31 downto 0);
        variable done_ok : boolean;
        variable fr      : nfc_byte_array(0 to NFC_MAX_BYTES - 1) := (others => (others => '0'));
        variable crc     : std_logic_vector(15 downto 0);
        variable payload : nfc_byte_array(0 to 15);
        variable payload2 : nfc_byte_array(0 to 15);   -- GROUP 5b: the replacement block
        variable wr_passes, na, nb : natural := 0;     -- GROUP 5b burst / tear accounting
        variable txn_tgt : natural := 0;
        variable neg_val : std_logic_vector(7 downto 0) := x"00";
        variable fdt1, fdt2 : natural;
        -- GROUP 12 accounting: bus-side reads of the three volatile words taken WHILE
        -- their sources move, at the free-running ClkMem the MCU presents.
        variable sr_reads, sr_bad, dbg_reads, dbg_bad  : natural := 0;
        variable saw_ready, saw_active, saw_halt       : boolean := false;
        variable rx_cnt, tx_cnt, rx_prev_c, tx_prev_c  : natural := 0;
        variable rx_first, tx_first                    : natural := 0;
        variable guard                                 : natural := 0;
        variable win     : nfc_byte_array(0 to 15);
        variable rxframe : nfc_byte_array(0 to NFC_MAX_BYTES - 1) := (others => (others => '0'));
        variable stcode  : natural := 0;

        -- CR with NFCEN=1, LISTEN=1, AUTOREAD=1 and the four IE bits selectable.
        procedure prog_cr(fie, rie, tie, cie : std_logic) is
        begin
            bus_write(clk, pbus, SlotNFCxCR, nfc_mk_cr('1', '1', '1', fie, rie, tie, cie));
        end procedure;

        -- W1C-clear SR bits, then retire the gated-ClkMem clear pulse with a dummy CR read before the next SR read.
        procedure w1c(mask : std_logic_vector(31 downto 0)) is
            variable r : std_logic_vector(31 downto 0);
        begin
            bus_write(clk, pbus, SlotNFCxSR, mask);
            bus_read(clk, pbus, rdata_out, SlotNFCxCR, r);
        end procedure;

        -- Launch the reader with the currently-set cfg_bytes and the given frame shape, then block (bounded) until the transaction completes.
        procedure do_frame(short : boolean; n : natural; appcrc : boolean;
                           rparity : boolean; partial : natural;
                           cpar : boolean; ccrc : boolean) is
        begin
            cfg_short          <= short;
            cfg_nbytes         <= n;
            cfg_append_crc     <= appcrc;
            cfg_resp_parity    <= rparity;
            cfg_partial_bits   <= partial;
            cfg_corrupt_parity <= cpar;
            cfg_corrupt_crc    <= ccrc;
            wait for 1 ns;                          -- settle cfg_* before launch
            txn_tgt := txn_tgt + 1;
            cfg_go <= '1'; wait for 2 ns; cfg_go <= '0';
            wait until obs_txn_count = txn_tgt for 500 us;   -- bounded (never hangs)
            -- obs_txn_count is published as the reader finishes decoding the tag's EOF, but the sticky SR flags trail it by the rf-to-clk 2-FF sync plus edge detect.
            -- Wait for that CDC before sampling SR.
            wait for 20 * PERIOD;                   -- settle flags into the bus domain
        end procedure;

        -- Launch the reader with the currently-set cfg_bytes and RETURN at once, so the
        -- caller can drive the register bus while the transaction is in flight. Pair it
        -- with a bounded `while obs_txn_count /= txn_tgt` poll; do_frame is the blocking form.
        procedure launch_frame(short : boolean; n : natural; appcrc : boolean;
                               rparity : boolean; partial : natural;
                               cpar : boolean; ccrc : boolean) is
        begin
            cfg_short          <= short;
            cfg_nbytes         <= n;
            cfg_append_crc     <= appcrc;
            cfg_resp_parity    <= rparity;
            cfg_partial_bits   <= partial;
            cfg_corrupt_parity <= cpar;
            cfg_corrupt_crc    <= ccrc;
            wait for 1 ns;                          -- settle cfg_* before launch
            txn_tgt := txn_tgt + 1;
            cfg_go <= '1'; wait for 2 ns; cfg_go <= '0';
        end procedure;

        -- Fill the payload TX window (IDXSEL=0, auto-inc) with 16 bytes.
        procedure fill_payload is
        begin
            bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '0'));
            for i in 0 to 15 loop
                bus_write(clk, pbus, SlotNFCxDATA, x"000000" & payload(i));
            end loop;
        end procedure;

        -- Clear the EVFAB flip monitor's accumulators; call only outside a timing-critical window.
        procedure evt_mon_reset is
        begin
            wait until clk = '0';
            evt_mon_clear <= '1';
            wait until clk = '1';
            wait until clk = '0';
            evt_mon_clear <= '0';
        end procedure;

        -- Bounded poll until the given flip-count signal reaches at least target; timing-insensitive by construction.
        procedure wait_flips_ge(signal cnt : in natural; target : natural;
                                guard_edges : natural; ok : out boolean) is
            variable g : natural := 0;
        begin
            ok := false;
            loop
                wait until clk = '1';
                if cnt >= target then
                    ok := true;
                    exit;
                end if;
                g := g + 1;
                exit when g > guard_edges;
            end loop;
        end procedure;

    begin
        for i in 0 to 15 loop
            payload(i) := std_logic_vector(to_unsigned(16#A0# + i, 8));
        end loop;

        -- Reset
        resetn <= '0';
        pbus   <= PERIPH_BUS_IDLE;
        cfg_field <= '0';
        wait for 6 * PERIOD;
        wait for 1 ns;
        resetn <= '1';
        wait for 6 * PERIOD;

        -- GROUP 0: reset defaults. FDT's reset value is not pinned exactly, so only nonzero is checked.
        report "=== GROUP 0: reset defaults ===" severity note;
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP0: SR resets to 0", rdw, x"00000000");
        bus_read(clk, pbus, rdata_out, SlotNFCxCR, rdw);
        sb.check_slv("GROUP0: CR resets to AUTOREAD=1 only", rdw, x"00001000");
        bus_read(clk, pbus, rdata_out, SlotNFCxUID, rdw);
        sb.check_slv("GROUP0: UID resets to 0", rdw, x"00000000");
        bus_read(clk, pbus, rdata_out, SlotNFCxCFG, rdw);
        sb.check_slv("GROUP0: CFG resets to ATQA=0x0044/SAK=0", rdw, x"00000044");
        bus_read(clk, pbus, rdata_out, SlotNFCxTIM, rdw);
        sb.check_slv("GROUP0: TIM ETU=128/SUBCDIV=8 reset bytes", rdw(31 downto 16), x"0880");
        sb.check_true("GROUP0: TIM FDT reset nonzero (~1236, D17)",
                      to_integer(unsigned(rdw(15 downto 0))) > 0);

        -- GROUP 1: CRC_A known vectors (DUT-independent, locks the utility)
        report "=== GROUP 1: CRC_A vectors ===" severity note;
        -- Hand-computed literal anchor (ISO 14443-3 Annex B): after {0x00} crc=0x51FE, after {0x00,0x00} crc=0x1EA0.
        fr := (others => (others => '0'));
        sb.check_slv("GROUP1: CRC_A({00,00}) = hand literal 0x1EA0",
                     nfc_crc_a(fr, 2), x"1EA0");
        -- Round-trip residue: {data, CRC_lo, CRC_hi} re-run through CRC_A yields the ISO residue 0x0000, with data = {0x30,0x00} (a READ command head).
        fr := (others => (others => '0'));
        fr(0) := x"30"; fr(1) := x"00";
        crc := nfc_crc_a(fr, 2);
        fr(2) := crc(7 downto 0);          -- low byte first on air
        fr(3) := crc(15 downto 8);
        sb.check_slv("GROUP1: CRC_A residue over {data||CRC} = 0x0000",
                     nfc_crc_a(fr, 4), x"0000");

        -- Program the tag identity + compressed timing, then enable.
        bus_write(clk, pbus, SlotNFCxUID, UIDW);
        bus_write(clk, pbus, SlotNFCxCFG, nfc_mk_cfg(ATQA, SAK));
        bus_write(clk, pbus, SlotNFCxTIM, nfc_mk_tim(C_FDT, C_ETU, C_SUBCDIV));
        prog_cr('1', '1', '1', '1');       -- NFCEN|LISTEN|AUTOREAD + all IEs

        -- GROUP 2: field detect sets FIELDF and irq_field, state IDLE
        report "=== GROUP 2: field detect + irq_field ===" severity note;
        cfg_field <= '1';                  -- reader turns the RF field on
        wait for 30 * PERIOD;              -- let the field synchronizer settle
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP2: FIELD_LIVE set", rdw(SrBitFIELDLIVE), '1');
        sb.check_bit("GROUP2: FIELDF set", rdw(SrBitFIELDF), '1');
        sb.check_bit("GROUP2: irq_field asserted (FIELDF & FIELDIE)", irq_field, '1');
        sb.check_slv("GROUP2: state = IDLE", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StIDLE, 4)));
        w1c(x"00000002");                  -- clear FIELDF
        sb.check_bit("GROUP2: irq_field cleared after FIELDF W1C", irq_field, '0');

        -- GROUP 3: REQA answered by ATQA (codec round-trip) plus WUPA, state READY
        report "=== GROUP 3: REQA/WUPA -> ATQA ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"26";                    -- REQA (7-bit short frame)
        cfg_bytes <= fr;
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_bit("GROUP3: tag responded to REQA", obs_saw_response, '1');
        sb.check_bit("GROUP3: response SOF ok (D)", obs_sof_ok, '1');
        sb.check_true("GROUP3: ATQA is 2 bytes", obs_nbytes = 2);
        sb.check_slv("GROUP3: ATQA byte0 = 0x44", obs_bytes(0), x"44");
        sb.check_slv("GROUP3: ATQA byte1 = 0x00", obs_bytes(1), x"00");
        sb.check_bit("GROUP3: ATQA parity ok", obs_parity_ok, '1');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP3: RXFRAMEF set", rdw(SrBitRXFRAMEF), '1');
        sb.check_bit("GROUP3: TXDONEF set", rdw(SrBitTXDONEF), '1');
        sb.check_slv("GROUP3: state = READY", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StREADY, 4)));
        w1c(x"0000000C");                  -- clear RXFRAMEF|TXDONEF

        -- WUPA path
        fr := (others => (others => '0'));
        fr(0) := x"52";                    -- WUPA
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP3: tag responded to WUPA", obs_saw_response, '1');
        sb.check_slv("GROUP3: WUPA ATQA byte0 = 0x44", obs_bytes(0), x"44");
        w1c(x"0000000C");

        -- GROUP 4: anticollision (NVB splits, BCC) and SELECT (SAK), ending in ACTIVE
        report "=== GROUP 4: anticollision + SELECT ===" severity note;
        -- 4a: NVB=0x20 asks for the full UID plus BCC (5 bytes, no CRC)
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        sb.check_bit("GROUP4a: tag streamed UID", obs_saw_response, '1');
        sb.check_true("GROUP4a: UID+BCC = 5 bytes", obs_nbytes = 5);
        sb.check_slv("GROUP4a: uid0", obs_bytes(0), UID0);
        sb.check_slv("GROUP4a: uid1", obs_bytes(1), UID1);
        sb.check_slv("GROUP4a: uid2", obs_bytes(2), UID2);
        sb.check_slv("GROUP4a: uid3", obs_bytes(3), UID3);
        sb.check_slv("GROUP4a: BCC = uid0^uid1^uid2^uid3", obs_bytes(4), BCC);
        sb.check_bit("GROUP4a: first response bit = uid0 bit0", obs_first_bit, UID0(0));
        sb.check_bit("GROUP4a: UID stream parity ok", obs_parity_ok, '1');

        -- 4b: partial-NVB MATCH (SEL, NVB=0x24 plus 4 bits of uid0): the tag resumes at UID bit 4.
        -- The exact NVB bit packing is not pinned, so only the response START OFFSET and the match/silent split are checked, not the bit-level reframing.
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"24"; fr(2) := UID0;
        cfg_bytes <= fr;
        do_frame(false, 2, false, false, 4, false, false);
        sb.check_bit("GROUP4b: match -> tag resumed the UID", obs_saw_response, '1');
        sb.check_bit("GROUP4b: response starts at uid0 bit 4 (split offset)",
                     obs_first_bit, UID0(4));

        -- 4c: partial-NVB MISMATCH (wrong 4-bit prefix) leaves the tag SILENT
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"24"; fr(2) := UID0 xor x"0F";   -- corrupt low nibble
        cfg_bytes <= fr;
        do_frame(false, 2, false, false, 4, false, false);
        sb.check_bit("GROUP4c: mismatch -> tag stays SILENT", obs_saw_response, '0');

        -- 4d: SELECT (NVB=0x70, UID+BCC+CRC_A) is answered with SAK+CRC_A, state ACTIVE
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"70";
        fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
        cfg_bytes <= fr;
        do_frame(false, 7, true, true, 0, false, false);
        sb.check_bit("GROUP4d: SELECT answered", obs_saw_response, '1');
        sb.check_true("GROUP4d: SAK+CRC = 3 bytes", obs_nbytes = 3);
        sb.check_slv("GROUP4d: SAK = 0x00", obs_bytes(0), SAK);
        sb.check_bit("GROUP4d: SAK CRC_A ok", obs_crc_ok, '1');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP4d: state = ACTIVE", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StACTIVE, 4)));
        w1c(x"0000000C");

        -- GROUP 5: Type-2 READ returns the CPU-loaded 16-byte payload plus CRC_A
        report "=== GROUP 5: READ-BLOCK payload ===" severity note;
        fill_payload;                      -- firmware fills the wound record
        fr := (others => (others => '0'));
        fr(0) := x"30"; fr(1) := x"00";    -- READ, block 0
        cfg_bytes <= fr;
        do_frame(false, 2, true, true, 0, false, false);
        sb.check_bit("GROUP5: READ answered", obs_saw_response, '1');
        sb.check_true("GROUP5: 16 payload bytes + CRC = 18", obs_nbytes = 18);
        for i in 0 to 15 loop
            sb.check_slv("GROUP5: READ byte " & integer'image(i) & " = payload",
                         obs_bytes(i), payload(i));
        end loop;
        sb.check_bit("GROUP5: READ response CRC_A ok", obs_crc_ok, '1');
        sb.check_bit("GROUP5: READ response parity ok", obs_parity_ok, '1');
        neg_val := obs_bytes(0);           -- stash the true byte0 for the neg control
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP5: still ACTIVE after READ", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StACTIVE, 4)));
        w1c(x"0000000C");

        /* GROUP 5b: the autoread copy against a firmware NFCxDATA write (W5a-1).
           AUTOREAD answers a READ by copying 16 bytes of payload_mem into resp_bytes on
           ONE rf_clk edge, and AUTOREAD exists so that firmware is NOT in the loop and
           may be rewriting that window while the reader polls. payload_mem is written on
           ClkMem. Nothing used to stand between the two: the copy took whatever the
           bytes held at that instant, the composer CRCed it, and the reader received a
           frame that passes CRC and parity and holds data the tag never had.
           The interlock now snapshots a payload-write toggle, carried into rf_clk on
           u_sync_pay_wr_tgl, at the copy and compares it again before composing. A write
           anywhere in that span drops the reply, and an ISO 14443-3 reader retries.
           The bench drives the race directly: the READ is launched and firmware then
           writes the whole window, pass after pass, ALTERNATING between the old block
           and the new one so that a copy landing anywhere inside a pass is a visible
           mixture and not a coincidence. The writes are back to back and the burst
           outlasts the frame, so the copy edge falls inside it at any clock phase.
           On the pre-W10 RTL this group answers the reader with a block holding some
           bytes of each; the note below prints the split. It is a genuine tear and not a
           simulation artefact: the copy is one edge, so what tears in RTL is the BLOCK,
           and what tears in silicon is additionally the byte. */
        report "=== GROUP 5b: autoread copy vs a firmware NFCxDATA write ===" severity note;

        for i in 0 to 15 loop
            payload2(i) := std_logic_vector(to_unsigned(16#50# + i, 8));
        end loop;

        fr := (others => (others => '0'));
        fr(0) := x"30"; fr(1) := x"00";    -- READ, block 0
        cfg_bytes <= fr;
        cfg_short          <= false;
        cfg_nbytes         <= 2;
        cfg_append_crc     <= true;
        cfg_resp_parity    <= true;
        cfg_partial_bits   <= 0;
        cfg_corrupt_parity <= false;
        cfg_corrupt_crc    <= false;
        wait for 1 ns;
        txn_tgt := txn_tgt + 1;
        cfg_go <= '1'; wait for 2 ns; cfg_go <= '0';

        wr_passes := 0;
        while obs_txn_count /= txn_tgt loop
            bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '0'));
            for i in 0 to 15 loop
                if (wr_passes mod 2) = 0 then
                    bus_write(clk, pbus, SlotNFCxDATA, x"000000" & payload2(i));
                else
                    bus_write(clk, pbus, SlotNFCxDATA, x"000000" & payload(i));
                end if;
            end loop;
            wr_passes := wr_passes + 1;
            exit when wr_passes > 200;     -- bounded (never hangs)
        end loop;
        wait for 20 * PERIOD;

        sb.check_true("GROUP5b: the write burst really spanned the frame, "
                      & integer'image(wr_passes) & " pass(es) of 16 bytes",
                      wr_passes >= 2 and wr_passes <= 200);
        sb.check_bit("GROUP5b: no reply while a firmware NFCxDATA write is in flight",
                     obs_saw_response, '0');
        if obs_saw_response = '1' then
            na := 0; nb := 0;
            for i in 0 to 15 loop
                if obs_bytes(i) = payload(i)  then na := na + 1; end if;
                if obs_bytes(i) = payload2(i) then nb := nb + 1; end if;
            end loop;
            report "GROUP5b: the reader WAS answered during the burst: "
                   & integer'image(na) & " byte(s) from the old block and "
                   & integer'image(nb) & " from the new. A split is the torn copy."
                   severity note;
        end if;
        w1c(x"0000001C");                  -- RXFRAMEF | TXDONEF | CRCERRF

        -- The deferral is a retry, not a loss: with the window quiet the next READ
        -- returns the new block whole.
        for i in 0 to 15 loop
            payload(i) := payload2(i);
        end loop;
        fill_payload;
        fr := (others => (others => '0'));
        fr(0) := x"30"; fr(1) := x"00";
        cfg_bytes <= fr;
        do_frame(false, 2, true, true, 0, false, false);
        sb.check_bit("GROUP5b: the retry is answered once the window is quiet",
                     obs_saw_response, '1');
        sb.check_true("GROUP5b: retry returns 16 payload bytes + CRC", obs_nbytes = 18);
        for i in 0 to 15 loop
            sb.check_slv("GROUP5b: retry byte " & integer'image(i) & " = the new block",
                         obs_bytes(i), payload2(i));
        end loop;
        sb.check_bit("GROUP5b: retry CRC_A ok", obs_crc_ok, '1');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP5b: still ACTIVE after the deferral and the retry",
                     rdw(11 downto 8), std_logic_vector(to_unsigned(StACTIVE, 4)));
        w1c(x"0000000C");

        -- GROUP 6: HLTA enters HALT silently, REQA is ignored, WUPA re-wakes
        report "=== GROUP 6: HLTA + wake rules ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"50"; fr(1) := x"00";    -- HLTA
        cfg_bytes <= fr;
        do_frame(false, 2, true, true, 0, false, false);
        sb.check_bit("GROUP6: HLTA is silent (no response)", obs_saw_response, '0');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP6: HALTED set", rdw(SrBitHALTED), '1');
        sb.check_slv("GROUP6: state = HALT", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StHALT, 4)));
        w1c(x"0000000C");

        -- REQA is IGNORED in HALT (ISO rule)
        fr := (others => (others => '0'));
        fr(0) := x"26";
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP6: REQA ignored in HALT", obs_saw_response, '0');

        -- WUPA re-wakes the tag, which answers ATQA in state READY
        fr := (others => (others => '0'));
        fr(0) := x"52";
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP6: WUPA re-wakes from HALT", obs_saw_response, '1');
        sb.check_slv("GROUP6: WUPA ATQA byte0 = 0x44", obs_bytes(0), x"44");
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP6: state = READY after WUPA", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StREADY, 4)));
        w1c(x"0000000C");

        /* GROUP 6c: back-to-back STATE transitions with the legality monitor armed.
           The tag is in READY here, so each pass walks READY to ACTIVE (SELECT), ACTIVE to HALT (HLTA) and HALT back to READY (WUPA), and ends where it started so GROUP 7's anticollision still has its READY precondition.
           ACTIVE to HALT is 0011 to 0100 and HALT to READY is 0100 to 0010: both change more than one bit, and both have illegal intermediates (0101, 0110, 0111), which is what a bit-by-bit crossing of this binary word can present.
           rf_clk and clk are unrelated and the frames differ in length, so the transitions land at a spread of phases against clk without the bench choosing any. */
        report "=== GROUP 6c: SR.STATE CDC burst ===" severity note;
        st_mon_en <= '1';
        wait for PERIOD;
        for i in 1 to 6 loop
            fr := (others => (others => '0'));          -- SELECT: READY -> ACTIVE
            fr(0) := x"93"; fr(1) := x"70";
            fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
            cfg_bytes <= fr;
            do_frame(false, 7, true, true, 0, false, false);

            fr := (others => (others => '0'));          -- HLTA: ACTIVE -> HALT (three bits)
            fr(0) := x"50"; fr(1) := x"00";
            cfg_bytes <= fr;
            do_frame(false, 2, true, true, 0, false, false);

            fr := (others => (others => '0'));          -- WUPA: HALT -> READY (two bits)
            fr(0) := x"52";
            cfg_bytes <= fr;
            do_frame(true, 1, false, true, 0, false, false);

            w1c(x"0000003E");                           -- retire every sticky flag
        end loop;
        st_mon_en <= '0';
        wait for PERIOD;
        sb.check_true("GROUP6c: the burst moved STATE at least 12 times (monitor not vacuous), saw "
                      & integer'image(st_changes), st_changes >= 12);
        sb.check_true("GROUP6c: SR.STATE never held a code above " & integer'image(ST_MAX)
                      & " over " & integer'image(st_samples) & " clk samples (last bad code "
                      & to_hstring(st_bad_code) & ")", st_illegal = 0);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP6c: state = READY at the end of the burst", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StREADY, 4)));

        -- GROUP 7: parity and CRC injection set PARERRF/CRCERRF and irq_crcerr, and the frame is dropped
        report "=== GROUP 7: parity / CRC injection ===" severity note;
        -- 7a parity: anticollision with a flipped parity bit sets PARERRF and the tag stays silent
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, true, false);   -- cpar=true
        sb.check_bit("GROUP7a: parity-error frame dropped (silent)", obs_saw_response, '0');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP7a: PARERRF set", rdw(SrBitPARERRF), '1');
        sb.check_bit("GROUP7a: irq_crcerr asserted (PARERRF & CRCIE)", irq_crcerr, '1');
        w1c(x"00000020");                  -- clear PARERRF
        sb.check_bit("GROUP7a: irq_crcerr cleared after PARERRF W1C", irq_crcerr, '0');

        -- 7b CRC: SELECT with a corrupted appended CRC_A sets CRCERRF and yields no SAK
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"70";
        fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
        cfg_bytes <= fr;
        do_frame(false, 7, true, true, 0, false, true);    -- ccrc=true
        sb.check_bit("GROUP7b: bad-CRC SELECT unanswered", obs_saw_response, '0');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP7b: CRCERRF set", rdw(SrBitCRCERRF), '1');
        sb.check_bit("GROUP7b: irq_crcerr asserted (CRCERRF & CRCIE)", irq_crcerr, '1');
        w1c(x"00000010");                  -- clear CRCERRF

        -- GROUP 8: compressed FDT, where reprogramming FDT changes the response offset.
        -- Bounded and inconclusive-safe: a missing response reports a note, never a failure.
        report "=== GROUP 8: FDT compressed ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        fdt1 := obs_fdt_ticks;
        sb.check_bit("GROUP8: response seen at base FDT", obs_saw_response, '1');
        w1c(x"0000000C");

        bus_write(clk, pbus, SlotNFCxTIM, nfc_mk_tim(C_FDT * 4, C_ETU, C_SUBCDIV));
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        fdt2 := obs_fdt_ticks;
        w1c(x"0000000C");
        if obs_saw_response = '1' and fdt1 > 0 then
            sb.check_true("GROUP8: larger programmed FDT -> larger response offset",
                          fdt2 > fdt1);
        else
            report "GROUP8: FDT measurement inconclusive (bounded timeout -- " &
                   "expected until a real DUT is connected)" severity note;
        end if;
        bus_write(clk, pbus, SlotNFCxTIM, nfc_mk_tim(C_FDT, C_ETU, C_SUBCDIV));   -- restore

        -- GROUP 9: IRQ lines (rxf/txdone) + NFCEN/LISTEN launch guards
        report "=== GROUP 9: IRQ + launch guards ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP9: irq_rxf asserted (RXFRAMEF & RXFIE)", irq_rxf, '1');
        sb.check_bit("GROUP9: irq_txdone asserted (TXDONEF & TXIE)", irq_txdone, '1');
        w1c(x"00000004");                  -- clear RXFRAMEF
        sb.check_bit("GROUP9: irq_rxf cleared after RXFRAMEF W1C", irq_rxf, '0');
        w1c(x"00000008");                  -- clear TXDONEF
        sb.check_bit("GROUP9: irq_txdone cleared after TXDONEF W1C", irq_txdone, '0');

        -- NFCEN=0 launch guard: a REQA must produce no response
        bus_write(clk, pbus, SlotNFCxCR, nfc_mk_cr('0', '1', '1', '1', '1', '1', '1'));
        fr := (others => (others => '0'));
        fr(0) := x"26";
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP9: NFCEN=0 -> tag deaf (no response)", obs_saw_response, '0');

        -- LISTEN=0 launch guard: enabled but not armed, so still deaf
        bus_write(clk, pbus, SlotNFCxCR, nfc_mk_cr('1', '0', '1', '1', '1', '1', '1'));
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP9: LISTEN=0 -> tag deaf (no response)", obs_saw_response, '0');
        prog_cr('1', '1', '1', '1');       -- re-arm

        -- GROUP G-EV: EVFAB producer taps evt_field/evt_rxframe, T-mode TOGGLE producers flipped at the fieldf_flag/rxframef_flag SET sites in the clk domain, pre-IE and independent of the flags' own W1C clears.
        -- Flip counts come from the background evt_mon_proc, which samples only the exported ports.
        report "=== GROUP G-EV: EVFAB producer taps (evt_field/evt_rxframe) ===" severity note;

        -- G-EVa: field-detect RISE. The field is already live entering this group, so drop it first to make the next raise a real edge.
        -- The drop itself must produce NO flip, since the tap is rise-only.
        evt_mon_reset;
        cfg_field <= '0';
        wait for 40 * PERIOD;              -- settle the field-drop synchronizer
        sb.check_true("G-EVa0: dropping the (already-live) field produces no evt_field flip "
                     & "(rise-only, setup for the rise below)", evt_field_flips = 0);

        cfg_field <= '1';                  -- provoke the field-detect RISE
        wait_flips_ge(evt_field_flips, 1, 200, done_ok);
        sb.check_true("G-EVa1: evt_field reaches 1 flip on field-detect rise (bounded poll)", done_ok);
        sb.check_true("G-EVa1: evt_field flip count is EXACTLY 1", evt_field_flips = 1);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("G-EVa1: FIELDF sets alongside the evt_field flip", rdw(SrBitFIELDF), '1');
        w1c(x"00000002");                  -- clear FIELDF (W1C never touches the toggle)

        -- Drop and re-raise the field for exactly one MORE flip; the drop itself must not flip, verified by zero flips in between.
        cfg_field <= '0';
        wait for 40 * PERIOD;
        sb.check_true("G-EVa2: dropping the field produces NO evt_field flip (rise-only; "
                     & "still 1 total)", evt_field_flips = 1);
        cfg_field <= '1';
        wait_flips_ge(evt_field_flips, 2, 200, done_ok);
        sb.check_true("G-EVa3: re-raising the field reaches 2 total flips (bounded poll)", done_ok);
        sb.check_true("G-EVa3: evt_field flip count is EXACTLY 2 (one MORE flip)",
                      evt_field_flips = 2);
        w1c(x"00000002");

        -- G-EVb: rx frame delivery via REQA, which the FSM accepts from IDLE or READY.
        -- Expect exactly one evt_rxframe flip per frame, firing again on a second frame with no W1C in between, since the toggle is pre-flag.
        evt_mon_reset;
        fr := (others => (others => '0'));
        fr(0) := x"26";                    -- REQA
        cfg_bytes <= fr;
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_bit("G-EVb1: tag responded to REQA", obs_saw_response, '1');
        sb.check_true("G-EVb1: evt_rxframe flips exactly once for one rx frame",
                      evt_rxf_flips = 1);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("G-EVb1: RXFRAMEF set alongside the evt_rxframe flip", rdw(SrBitRXFRAMEF), '1');

        cfg_bytes <= fr;                   -- second frame, RXFRAMEF left set (no W1C)
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_bit("G-EVb2: tag responded to the second REQA", obs_saw_response, '1');
        sb.check_true("G-EVb2: evt_rxframe flips again despite RXFRAMEF still set "
                     & "(no W1C between)", evt_rxf_flips = 2);
        w1c(x"0000000C");                  -- clear RXFRAMEF|TXDONEF now

        -- G-EVc: mask FIELDIE and RXFRAMEIE off; the toggles must still flip, since the taps are pre-IE, while irq_field and irq_rxf stay low because the IRQs are post-mask.
        report "GROUP G-EVc: FIELDIE/RXFRAMEIE masked off" severity note;
        prog_cr('0', '0', '1', '1');       -- FIELDIE=0, RXFRAMEIE=0
        evt_mon_reset;
        cfg_field <= '0';
        wait for 40 * PERIOD;
        cfg_field <= '1';
        wait_flips_ge(evt_field_flips, 1, 200, done_ok);
        sb.check_true("G-EVc1: evt_field still flips with FIELDIE=0 (bounded poll)", done_ok);
        sb.check_true("G-EVc1: evt_field flip count is EXACTLY 1", evt_field_flips = 1);
        sb.check_bit("G-EVc1: irq_field stays low with FIELDIE=0 (masked, unlike evt_field)",
                     to_X01(irq_field), '0');
        w1c(x"00000002");

        fr := (others => (others => '0'));
        fr(0) := x"26";                    -- REQA
        cfg_bytes <= fr;
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_true("G-EVc2: evt_rxframe still flips with RXFRAMEIE=0", evt_rxf_flips = 1);
        sb.check_bit("G-EVc2: irq_rxf stays low with RXFRAMEIE=0 (masked, unlike evt_rxframe)",
                     to_X01(irq_rxf), '0');
        w1c(x"0000000C");
        prog_cr('1', '1', '1', '1');       -- restore FIELDIE/RXFRAMEIE

        -- G-EVd: a quiet window with no field or rx traffic must give zero flips on both taps.
        evt_mon_reset;
        wait for 60 * PERIOD;
        sb.check_true("G-EVd: zero evt_field flips over a quiet window (no field/rx traffic)",
                      evt_field_flips = 0);
        sb.check_true("G-EVd: zero evt_rxframe flips over a quiet window (no field/rx traffic)",
                      evt_rxf_flips = 0);

        /* GROUP 12: the three volatile read words taken from the bus WHILE their sources
           move, at the free-running ClkMem the MCU presents (mclk reaches every peripheral
           ungated). Each of NFCxSR, NFCxDBG and NFCxDATA is owned by a clock this bus does
           not share: SR carries the 4-bit binary NFCSTATE out of the smclk domain, DBG is
           two rf_clk frame counters and DATA is a 64-byte window the rf core writes.
           The group is a COMPATIBILITY group: it states what a read must return and is
           graded against the pre-latch design and against the ClkMem read path alike. */
        report "=== GROUP 12: volatile reads against a moving source ===" severity note;

        -- 12a: SR read continuously across READY -> ACTIVE -> HALT -> READY transitions.
        -- NFCSTATE is BINARY and its four bits must reach the bus as one word: a read may
        -- return the old code or the new one and nothing else, so any code above StHALT is
        -- a word the FSM never held.
        sr_reads := 0; sr_bad := 0; guard := 0;
        for i in 1 to 3 loop
            fr := (others => (others => '0'));          -- SELECT: READY -> ACTIVE
            fr(0) := x"93"; fr(1) := x"70";
            fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
            cfg_bytes <= fr;
            launch_frame(false, 7, true, true, 0, false, false);
            while obs_txn_count /= txn_tgt and guard < 20000 loop
                bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
                guard := guard + 1; sr_reads := sr_reads + 1;
                if is_x(rdw(11 downto 8)) then
                    sr_bad := sr_bad + 1;
                else
                    stcode := to_integer(unsigned(to_X01(rdw(11 downto 8))));
                    if stcode > StHALT then sr_bad := sr_bad + 1; end if;
                    if stcode = StREADY  then saw_ready  := true; end if;
                    if stcode = StACTIVE then saw_active := true; end if;
                    if stcode = StHALT   then saw_halt   := true; end if;
                end if;
            end loop;

            fr := (others => (others => '0'));          -- HLTA: ACTIVE -> HALT
            fr(0) := x"50"; fr(1) := x"00";
            cfg_bytes <= fr;
            launch_frame(false, 2, true, true, 0, false, false);
            while obs_txn_count /= txn_tgt and guard < 20000 loop
                bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
                guard := guard + 1; sr_reads := sr_reads + 1;
                if is_x(rdw(11 downto 8)) then
                    sr_bad := sr_bad + 1;
                else
                    stcode := to_integer(unsigned(to_X01(rdw(11 downto 8))));
                    if stcode > StHALT then sr_bad := sr_bad + 1; end if;
                    if stcode = StREADY  then saw_ready  := true; end if;
                    if stcode = StACTIVE then saw_active := true; end if;
                    if stcode = StHALT   then saw_halt   := true; end if;
                end if;
            end loop;

            fr := (others => (others => '0'));          -- WUPA: HALT -> READY
            fr(0) := x"52";
            cfg_bytes <= fr;
            launch_frame(true, 1, false, true, 0, false, false);
            while obs_txn_count /= txn_tgt and guard < 20000 loop
                bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
                guard := guard + 1; sr_reads := sr_reads + 1;
                if is_x(rdw(11 downto 8)) then
                    sr_bad := sr_bad + 1;
                else
                    stcode := to_integer(unsigned(to_X01(rdw(11 downto 8))));
                    if stcode > StHALT then sr_bad := sr_bad + 1; end if;
                    if stcode = StREADY  then saw_ready  := true; end if;
                    if stcode = StACTIVE then saw_active := true; end if;
                    if stcode = StHALT   then saw_halt   := true; end if;
                end if;
            end loop;
            w1c(x"0000003E");                           -- retire every sticky flag
        end loop;
        wait for 30 * PERIOD;

        sb.check_true("GROUP12a: the SR poll is not vacuous, " & integer'image(sr_reads)
                      & " bus reads of NFCxSR taken while the ISO state moved", sr_reads >= 100);
        sb.check_true("GROUP12a: the poll saw READY, ACTIVE and HALT through the bus",
                      saw_ready and saw_active and saw_halt);
        sb.check_true("GROUP12a: no NFCxSR read returned a NFCSTATE code above "
                      & integer'image(StHALT) & " (" & integer'image(sr_bad) & " bad of "
                      & integer'image(sr_reads) & ")", sr_bad = 0);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP12a: state = READY at the end of the poll", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StREADY, 4)));

        -- 12b: NFCxDBG read continuously while both rf_clk frame counters advance.
        -- The word is [31:16] tx_frame_count, [15:0] rx_frame_count. Neither half may go
        -- backwards, and tx may never lead rx, because a tag transmits only in answer to a
        -- frame it has already counted in. A half assembled from two instants breaks both.
        bus_read(clk, pbus, rdata_out, SlotNFCxDBG, rdw);
        rx_first := to_integer(unsigned(to_X01(rdw(15 downto 0))));
        tx_first := to_integer(unsigned(to_X01(rdw(31 downto 16))));
        rx_prev_c := rx_first; tx_prev_c := tx_first;
        dbg_reads := 0; dbg_bad := 0; guard := 0;
        for i in 1 to 3 loop
            fr := (others => (others => '0'));          -- SELECT, answered with SAK
            fr(0) := x"93"; fr(1) := x"70";
            fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
            cfg_bytes <= fr;
            launch_frame(false, 7, true, true, 0, false, false);
            while obs_txn_count /= txn_tgt and guard < 20000 loop
                bus_read(clk, pbus, rdata_out, SlotNFCxDBG, rdw);
                guard := guard + 1; dbg_reads := dbg_reads + 1;
                if is_x(rdw) then
                    dbg_bad := dbg_bad + 1;
                else
                    rx_cnt := to_integer(unsigned(to_X01(rdw(15 downto 0))));
                    tx_cnt := to_integer(unsigned(to_X01(rdw(31 downto 16))));
                    if rx_cnt < rx_prev_c or tx_cnt < tx_prev_c or tx_cnt > rx_cnt then
                        dbg_bad := dbg_bad + 1;
                    end if;
                    rx_prev_c := rx_cnt; tx_prev_c := tx_cnt;
                end if;
            end loop;

            fr := (others => (others => '0'));          -- WUPA, answered with ATQA
            fr(0) := x"52";
            cfg_bytes <= fr;
            launch_frame(true, 1, false, true, 0, false, false);
            while obs_txn_count /= txn_tgt and guard < 20000 loop
                bus_read(clk, pbus, rdata_out, SlotNFCxDBG, rdw);
                guard := guard + 1; dbg_reads := dbg_reads + 1;
                if is_x(rdw) then
                    dbg_bad := dbg_bad + 1;
                else
                    rx_cnt := to_integer(unsigned(to_X01(rdw(15 downto 0))));
                    tx_cnt := to_integer(unsigned(to_X01(rdw(31 downto 16))));
                    if rx_cnt < rx_prev_c or tx_cnt < tx_prev_c or tx_cnt > rx_cnt then
                        dbg_bad := dbg_bad + 1;
                    end if;
                    rx_prev_c := rx_cnt; tx_prev_c := tx_cnt;
                end if;
            end loop;
            w1c(x"0000003E");
        end loop;
        wait for 30 * PERIOD;
        bus_read(clk, pbus, rdata_out, SlotNFCxDBG, rdw);
        rx_cnt := to_integer(unsigned(to_X01(rdw(15 downto 0))));
        tx_cnt := to_integer(unsigned(to_X01(rdw(31 downto 16))));

        sb.check_true("GROUP12b: the DBG poll is not vacuous, " & integer'image(dbg_reads)
                      & " bus reads of NFCxDBG taken while both counters advanced",
                      dbg_reads >= 100);
        sb.check_true("GROUP12b: both frame counters advanced over the poll (rx "
                      & integer'image(rx_first) & " -> " & integer'image(rx_cnt) & ", tx "
                      & integer'image(tx_first) & " -> " & integer'image(tx_cnt) & ")",
                      rx_cnt > rx_first and tx_cnt > tx_first);
        sb.check_true("GROUP12b: no NFCxDBG read went backwards or showed tx leading rx ("
                      & integer'image(dbg_bad) & " bad of " & integer'image(dbg_reads) & ")",
                      dbg_bad = 0);

        -- 12c: the NFCxDATA window. The payload half is written and read back through the
        -- same auto-incrementing index, and the receive half is read after a known frame,
        -- with NFCxRXST cross-checking the command, length and CRC/parity verdicts.
        for i in 0 to 15 loop
            win(i) := std_logic_vector(to_unsigned(16#C0# + i, 8));
        end loop;
        bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '0'));
        for i in 0 to 15 loop
            bus_write(clk, pbus, SlotNFCxDATA, x"000000" & win(i));
        end loop;
        bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '0'));
        for i in 0 to 15 loop
            bus_read(clk, pbus, rdata_out, SlotNFCxDATA, rdw);
            sb.check_slv("GROUP12c: TX window byte " & integer'image(i)
                         & " reads back through the auto-index", rdw(7 downto 0), win(i));
        end loop;
        -- A fixed index with AINC off returns the same byte on every access.
        bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(5, '0', '0'));
        bus_read(clk, pbus, rdata_out, SlotNFCxDATA, rdw);
        sb.check_slv("GROUP12c: fixed index 5, first read", rdw(7 downto 0), win(5));
        bus_read(clk, pbus, rdata_out, SlotNFCxDATA, rdw);
        sb.check_slv("GROUP12c: fixed index 5, repeated read is the same byte",
                     rdw(7 downto 0), win(5));

        -- The receive window, after a READ frame the tag answers out of AUTOREAD.
        wait for 40 * PERIOD;               -- quiet the window before the autoread copy
        rxframe := (others => (others => '0'));
        rxframe(0) := x"30"; rxframe(1) := x"00";
        crc := nfc_crc_a(rxframe, 2);
        rxframe(2) := crc(7 downto 0);
        rxframe(3) := crc(15 downto 8);
        cfg_bytes <= rxframe;
        do_frame(false, 2, true, true, 0, false, false);

        bus_read(clk, pbus, rdata_out, SlotNFCxRXST, rdw);
        sb.check_slv("GROUP12c: RXST command byte = 0x30 (READ)", rdw(7 downto 0), x"30");
        sb.check_slv("GROUP12c: RXST length = 4 bytes (2 data + CRC_A)",
                     rdw(15 downto 8), x"04");
        sb.check_bit("GROUP12c: RXST CRC ok", rdw(16), '1');
        sb.check_bit("GROUP12c: RXST parity ok", rdw(17), '1');

        bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '1'));   -- RX window, auto-inc
        for i in 0 to 3 loop
            bus_read(clk, pbus, rdata_out, SlotNFCxDATA, rdw);
            sb.check_slv("GROUP12c: RX window byte " & integer'image(i)
                         & " = the frame on air", rdw(7 downto 0), rxframe(i));
        end loop;
        bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '0'));   -- back to the TX window

        /* 12d: the WIDTH of a W1C clear level, measured at the DUT signal, on a plain
           single-cycle write. This is the one check in GROUP 12 that the pre-latch
           design does not pass: on it the level is the select window, about half a bus
           clock, which in silicon is a runt against an asynchronous clear in another
           domain. The ClkMem level replaces the half cycle the removed falling-mclk
           en_q shim used to buy. */
        clr_mon_arm <= '1';
        bus_write(clk, pbus, SlotNFCxSR, x"00000004");    -- ONE-cycle W1C of RXFRAMEF
        wait for 8 * PERIOD;
        clr_mon_arm <= '0';
        sb.check_true("GROUP12d: the clr_rxframef monitor is not vacuous, "
                      & integer'image(clr_n) & " high phase(s)", clr_n = 1);
        sb.check_true("GROUP12d: clr_rxframef is at least two ClkMem periods wide, measured "
                      & integer'image(clr_w / 1 ns) & " ns against "
                      & integer'image((2 * PERIOD) / 1 ns) & " ns", clr_w >= 2 * PERIOD);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP12d: RXFRAMEF reads back cleared on the next access",
                     rdw(SrBitRXFRAMEF), '0');
        w1c(x"0000003E");

        -- GROUP-NEG: NEGATIVE CONTROL, one deliberately wrong expected READ byte.
        -- It MUST report exactly one mismatch, which is how the scoreboard proves it can fail.
        report "=== GROUP-NEG: NEGATIVE CONTROL ===" severity note;
        sb.check_slv("NEGATIVE CONTROL: wrong expected READ byte0 (must FAIL)",
                     neg_val, std_logic_vector(unsigned(neg_val) + 1));

        -- Final verdict: sb.errors must be EXACTLY 1 (the negative control).
        wait for 1 us;
        sb.report_summary("NFC TB");

        if sb.errors = 1 then
            report LF & LF &
                "    ##################################################" & LF &
                "    ##   NFC_TB PASS (1 expected negative-control failure)" & LF &
                "    ##   NFC TB:  ALL CHECKS PASSED" & LF &
                "    ##################################################" & LF
                severity note;
        else
            report LF & LF &
                "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
                "    !!   NFC_TB FAIL (expected exactly 1 failure [negative control], got " &
                integer'image(sb.errors) & ")" & LF &
                "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
                severity warning;
        end if;

        stop;
        wait;
    end process stim_proc;

end architecture sim;
