-------------------------------------------------------------------------------
-- NFC_tb.vhd
-------------------------------------------------------------------------------
-- Standalone, self-checking testbench for the NFC ISO 14443A tag/card-emulation peripheral (hdl/common/periph/NFC.vhd).
-- Written against the FROZEN ENTITY and REGISTER MAP (~/vesta_docs/digperiphs/nfc_design.md, R3 + D17) while the RTL is written in parallel.
-- The DUT is declared as a COMPONENT, not an entity instantiation, so this bench compiles standalone with xmvhdl before NFC.vhd exists; VHDL default binding resolves it to the entity of the same name once NFC.vhd is analyzed into the work library.
-- Mirrors I3C_tb.vhd's structure.
--
-- Uses the shared support packages tb/periph_tb_pkg.vhd (scoreboard and register-bus BFM) and tb/nfc_bfm_pkg.vhd (NFC register-slot constants, CR/CFG/TIM/IDX field packing, the spec-literal CRC_A and parity utilities, bounded SR-bit polls).
-- The behavioral reader (PCD) peer is tb/nfc_reader_model.vhd, an INDEPENDENT implementation of the reader side of the RF link: Miller encode and Manchester-on-subcarrier decode live entirely in that model, NOT in a shared codec helper (see its header and nfc_bfm_pkg's header).
--
-- THREE clock domains (design doc D18): clk (smclk, free-running, drives the CDC synchronizers), ClkMem (GATED bus clock, ticking only while EnMemPeriph='0', see periph_tb_pkg.bus_write/bus_read), and rf_clk (the AFE carrier-derived protocol clock, generated by the reader model).
-- W1C SR bits: after a lane-0 SR write this bench issues a dummy CR read before re-reading SR, the QSPI/UART clear-pulse-retire idiom documented for this tb directory.
--
-- RF loopback: the reader drives rf_clk / rf_rx / field_detect into the DUT, and the DUT drives rf_txmod / rf_tx_en / afe_en back.
-- The link is point-to-point with no shared wired-AND net (it is unidirectional per direction), so no bus resolution is needed.
-- to_X01 normalizes every sampled level where a weak level can appear (the reader model's decode, the SR polls).
--
-- COMPRESSED TIMING (design doc D23/D22): the bench programs NFCxTIM SMALL, ETU=16, SUBCDIV=2, FDT=20 rf_clk ticks, and clocks rf_clk at a modest bench rate, so a full REQA to READ transaction completes well under the 1-minute rule.
-- Never scale real 13.56 MHz to wall clock.
--
-- EVFAB producer taps (event_fabric_spec.md 2026-07-24, EV8/EV9): NFC.vhd grew two new outputs, evt_field and evt_rxframe, T-mode TOGGLE producers in the clk (smclk) domain, flipped at the fieldf_flag/rxframef_flag SET sites, pre-IE and never touched by the flags' W1C clears.
-- GROUP G-EV below follows TIMER_tb.vhd's evt_mon_proc/wait_flips_ge idiom: a continuous background monitor counts FLIPS as the XOR of consecutive `clk` samples on the exported ports only, for checker independence, never on a DUT internal.
--
-- AMBIGUITIES IN THE FROZEN CONTRACT noted while writing this bench, flagged and not resolved (see the bench author's report):
--   * NFCxTIM.FDT reset is documented only as "~1236" (D17), so GROUP 0 checks
--     the ETU(=128)/SUBCDIV(=8) reset bytes exactly but only that FDT is
--     nonzero, not an exact value.
--   * The exact NVB byte-vs-bit packing, and whether the resumed anticollision
--     UID bits carry their own parity, are not fully pinned (D13), so GROUP 5's
--     partial-NVB case checks the response START OFFSET (obs_first_bit) and the
--     match/silent split, not the full bit-level reframing.
--   * The reader model's SOF alignment and subcarrier-detection thresholds (see
--     its header) are inherited uncritically, since this bench cannot run
--     against real DUT timing yet.
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.env.all;
use work.periph_tb_pkg.all;
use work.nfc_bfm_pkg.all;

entity NFC_tb is
end entity NFC_tb;

architecture sim of NFC_tb is

    constant PERIOD  : time := 40 ns;   -- ~25 MHz smclk-domain bus reference
    constant RF_HALF : time := 25 ns;   -- rf_clk half period (compressed carrier)

    -- compressed protocol-time divisors (design doc D23)
    constant C_ETU     : natural := 16;
    constant C_HALF    : natural := 8;    -- ETU/2
    constant C_SUBCDIV : natural := 2;
    constant C_PAUSE   : natural := 3;
    constant C_FDT     : natural := 20;

    -- provisioned identity (D12): uid0 first on air
    constant UID0 : std_logic_vector(7 downto 0) := x"11";
    constant UID1 : std_logic_vector(7 downto 0) := x"22";
    constant UID2 : std_logic_vector(7 downto 0) := x"33";
    constant UID3 : std_logic_vector(7 downto 0) := x"44";
    constant UIDW : std_logic_vector(31 downto 0) := UID3 & UID2 & UID1 & UID0;
    constant BCC  : std_logic_vector(7 downto 0) := UID0 xor UID1 xor UID2 xor UID3;
    constant ATQA : std_logic_vector(15 downto 0) := x"0044";
    constant SAK  : std_logic_vector(7 downto 0)  := x"00";

    -- FROZEN DUT entity (R3), declared as a component so the bench compiles standalone before hdl/common/periph/NFC.vhd exists.
    component NFC is
        port (
            clk          : in  std_logic;
            resetn       : in  std_logic;
            irq_field    : out std_logic;
            irq_rxf      : out std_logic;
            irq_txdone   : out std_logic;
            irq_crcerr   : out std_logic;
            ClkMem       : in  std_logic;
            EnMemPeriph  : in  std_logic;
            WEn          : in  std_logic_vector(3 downto 0);
            MABPart      : in  std_logic_vector(7 downto 2);
            wdata        : in  std_logic_vector(31 downto 0);
            rdata_out    : out std_logic_vector(31 downto 0);
            rf_clk       : in  std_logic;
            field_detect : in  std_logic;
            rf_rx        : in  std_logic;
            rf_txmod     : out std_logic;
            rf_tx_en     : out std_logic;
            afe_en       : out std_logic;

            -- EVFAB taps (event_fabric_spec.md 2026-07-24, EV8/EV9): T-mode toggle producers, see the file header.
            evt_field    : out std_logic;
            evt_rxframe  : out std_logic
        );
    end component;

    -- clocks / reset
    signal clk    : std_logic := '0';
    signal ClkMem : std_logic := '0';
    signal resetn : std_logic := '0';

    -- interrupts
    signal irq_field, irq_rxf, irq_txdone, irq_crcerr : std_logic;

    -- register bus
    signal pbus      : periph_bus_t := PERIPH_BUS_IDLE;
    signal rdata_out : std_logic_vector(31 downto 0);

    -- RF link between the reader model and the DUT
    signal rf_clk       : std_logic;
    signal rf_rx        : std_logic;
    signal field_detect : std_logic;
    signal rf_txmod     : std_logic;
    signal rf_tx_en     : std_logic;
    signal afe_en       : std_logic;

    -- ---- EVFAB taps (event_fabric_spec.md 2026-07-24, EV8/EV9) ------------
    signal evt_field   : std_logic;
    signal evt_rxframe : std_logic;

    -- ---- continuous EVFAB flip monitor (checker independence) -------------
    -- Counts toggle FLIPS (XOR of consecutive `clk` samples) on each producer tap since the last evt_mon_clear pulse.
    -- NEVER reads a DUT internal, only the exported evt_field/evt_rxframe ports (mirrors TIMER_tb.vhd).
    signal evt_field_flips, evt_rxf_flips : natural := 0;
    signal evt_field_prev, evt_rxf_prev   : std_logic := '0';
    signal evt_mon_clear                  : std_logic := '0';

    -- reader-model per-transaction config
    signal cfg_field          : std_logic := '0';
    signal cfg_go             : std_logic := '0';
    signal cfg_short          : boolean   := false;
    signal cfg_bytes          : nfc_byte_array(0 to NFC_MAX_BYTES - 1) := (others => (others => '0'));
    signal cfg_nbytes         : natural := 0;
    signal cfg_partial_bits   : natural := 0;
    signal cfg_append_crc     : boolean := false;
    signal cfg_corrupt_parity : boolean := false;
    signal cfg_corrupt_crc    : boolean := false;
    signal cfg_resp_parity    : boolean := true;

    -- reader-model observations
    signal obs_busy         : std_logic;
    signal obs_txn_count    : natural;
    signal obs_saw_response : std_logic;
    signal obs_fdt_ticks    : natural;
    signal obs_sof_ok       : std_logic;
    signal obs_nbytes       : natural;
    signal obs_bytes        : nfc_byte_array(0 to NFC_MAX_BYTES - 1);
    signal obs_nbits        : natural;
    signal obs_first_bit    : std_logic;
    signal obs_parity_ok    : std_logic;
    signal obs_crc_ok       : std_logic;

    shared variable sb : scoreboard;

begin

    ----------------------------------------------------------------------------
    -- clock / gated register-bus clock (mirrors QSPI_tb / I2C_tb / I3C_tb)
    ----------------------------------------------------------------------------
    clk    <= not clk after PERIOD / 2;
    ClkMem <= clk when pbus.en_mem = '0' else '0';

    ----------------------------------------------------------------------------
    -- Continuous EVFAB flip monitor (see the signal-declaration comment above; mirrors TIMER_tb.vhd's evt_mon_proc).
    ----------------------------------------------------------------------------
    evt_mon_proc : process(clk)
        variable f_lvl, r_lvl : std_logic;
    begin
        if rising_edge(clk) then
            f_lvl := to_X01(evt_field);
            r_lvl := to_X01(evt_rxframe);
            if evt_mon_clear = '1' then
                evt_field_flips <= 0;
                evt_rxf_flips   <= 0;
                evt_field_prev  <= f_lvl;
                evt_rxf_prev    <= r_lvl;
            else
                if f_lvl /= evt_field_prev then
                    evt_field_flips <= evt_field_flips + 1;
                end if;
                if r_lvl /= evt_rxf_prev then
                    evt_rxf_flips <= evt_rxf_flips + 1;
                end if;
                evt_field_prev <= f_lvl;
                evt_rxf_prev   <= r_lvl;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------------
    -- DUT
    ----------------------------------------------------------------------------
    dut : component NFC
        port map (
            clk          => clk,
            resetn       => resetn,
            irq_field    => irq_field,
            irq_rxf      => irq_rxf,
            irq_txdone   => irq_txdone,
            irq_crcerr   => irq_crcerr,
            ClkMem       => ClkMem,
            EnMemPeriph  => pbus.en_mem,
            WEn          => pbus.wen,
            MABPart      => pbus.addr_periph,
            wdata        => pbus.write_data,
            rdata_out    => rdata_out,
            rf_clk       => rf_clk,
            field_detect => field_detect,
            rf_rx        => rf_rx,
            rf_txmod     => rf_txmod,
            rf_tx_en     => rf_tx_en,
            afe_en       => afe_en,
            evt_field    => evt_field,
            evt_rxframe  => evt_rxframe
        );

    ----------------------------------------------------------------------------
    -- Behavioral reader (PCD) model: generates rf_clk, rf_rx and field_detect
    ----------------------------------------------------------------------------
    reader : entity work.nfc_reader_model
        generic map ( RF_HALF => RF_HALF )
        port map (
            rf_clk       => rf_clk,
            rf_rx        => rf_rx,
            field_detect => field_detect,
            rf_txmod     => rf_txmod,
            rf_tx_en     => rf_tx_en,
            cfg_field          => cfg_field,
            cfg_go             => cfg_go,
            cfg_short          => cfg_short,
            cfg_bytes          => cfg_bytes,
            cfg_nbytes         => cfg_nbytes,
            cfg_partial_bits   => cfg_partial_bits,
            cfg_append_crc     => cfg_append_crc,
            cfg_corrupt_parity => cfg_corrupt_parity,
            cfg_corrupt_crc    => cfg_corrupt_crc,
            cfg_resp_parity    => cfg_resp_parity,
            cfg_etu            => C_ETU,
            cfg_half           => C_HALF,
            cfg_subcdiv        => C_SUBCDIV,
            cfg_pause          => C_PAUSE,
            obs_busy         => obs_busy,
            obs_txn_count    => obs_txn_count,
            obs_saw_response => obs_saw_response,
            obs_fdt_ticks    => obs_fdt_ticks,
            obs_sof_ok       => obs_sof_ok,
            obs_nbytes       => obs_nbytes,
            obs_bytes        => obs_bytes,
            obs_nbits        => obs_nbits,
            obs_first_bit    => obs_first_bit,
            obs_parity_ok    => obs_parity_ok,
            obs_crc_ok       => obs_crc_ok
        );

    ----------------------------------------------------------------------------
    -- stimulus
    ----------------------------------------------------------------------------
    stim_proc : process
        variable rdw     : std_logic_vector(31 downto 0);
        variable done_ok : boolean;
        variable fr      : nfc_byte_array(0 to NFC_MAX_BYTES - 1) := (others => (others => '0'));
        variable crc     : std_logic_vector(15 downto 0);
        variable payload : nfc_byte_array(0 to 15);
        variable txn_tgt : natural := 0;
        variable neg_val : std_logic_vector(7 downto 0) := x"00";
        variable fdt1, fdt2 : natural;

        -- CR with NFCEN=1, LISTEN=1, AUTOREAD=1 and the four IE bits selectable.
        procedure prog_cr(fie, rie, tie, cie : std_logic) is
        begin
            bus_write(clk, pbus, SlotNFCxCR, nfc_mk_cr('1', '1', '1', fie, rie, tie, cie));
        end procedure;

        -- W1C-clear SR bits, then retire the gated-ClkMem clear pulse with a dummy CR read before the next SR read (QSPI/UART idiom).
        procedure w1c(mask : std_logic_vector(31 downto 0)) is
            variable r : std_logic_vector(31 downto 0);
        begin
            bus_write(clk, pbus, SlotNFCxSR, mask);
            bus_read(clk, pbus, rdata_out, SlotNFCxCR, r);
        end procedure;

        -- Launch the reader with the currently-set cfg_bytes and the given frame shape, then block (bounded) until the transaction completes.
        procedure do_frame(short : boolean; n : natural; appcrc : boolean;
                           rparity : boolean; partial : natural;
                           cpar : boolean; ccrc : boolean) is
        begin
            cfg_short          <= short;
            cfg_nbytes         <= n;
            cfg_append_crc     <= appcrc;
            cfg_resp_parity    <= rparity;
            cfg_partial_bits   <= partial;
            cfg_corrupt_parity <= cpar;
            cfg_corrupt_crc    <= ccrc;
            wait for 1 ns;                          -- settle cfg_* before launch
            txn_tgt := txn_tgt + 1;
            cfg_go <= '1'; wait for 2 ns; cfg_go <= '0';
            wait until obs_txn_count = txn_tgt for 500 us;   -- bounded (never hangs)
            -- The reader publishes obs_txn_count as it finishes decoding the tag's EOF.
            -- The DUT raises rf_txdone_lvl only AFTER its full EOF symbol, and the sticky TXDONEF flag then needs the rf-to-clk 2-FF sync plus edge detect to cross into the bus domain, a few smclk after the reader's handshake.
            -- Wait long enough for that CDC to complete before sampling SR flags.
            wait for 20 * PERIOD;                   -- settle flags into the bus domain
        end procedure;

        -- Fill the payload TX window (IDXSEL=0, auto-inc) with 16 bytes.
        procedure fill_payload is
        begin
            bus_write(clk, pbus, SlotNFCxIDX, nfc_mk_idx(0, '1', '0'));
            for i in 0 to 15 loop
                bus_write(clk, pbus, SlotNFCxDATA, x"000000" & payload(i));
            end loop;
        end procedure;

        -- Clear the EVFAB flip monitor's accumulators; call only outside a timing-critical window (TIMER_tb.vhd's evt_mon_reset idiom).
        procedure evt_mon_reset is
        begin
            wait until clk = '0';
            evt_mon_clear <= '1';
            wait until clk = '1';
            wait until clk = '0';
            evt_mon_clear <= '0';
        end procedure;

        -- Bounded poll until the given flip-count signal (evt_field_flips or evt_rxf_flips) reaches at least `target`.
        -- TIMER_tb.vhd's wait_flips_ge idiom, timing-insensitive by construction.
        procedure wait_flips_ge(signal cnt : in natural; target : natural;
                                guard_edges : natural; ok : out boolean) is
            variable g : natural := 0;
        begin
            ok := false;
            loop
                wait until clk = '1';
                if cnt >= target then
                    ok := true;
                    exit;
                end if;
                g := g + 1;
                exit when g > guard_edges;
            end loop;
        end procedure;

    begin
        for i in 0 to 15 loop
            payload(i) := std_logic_vector(to_unsigned(16#A0# + i, 8));
        end loop;

        ----------------------------------------------------------------
        -- Reset
        ----------------------------------------------------------------
        resetn <= '0';
        pbus   <= PERIPH_BUS_IDLE;
        cfg_field <= '0';
        wait for 6 * PERIOD;
        wait for 1 ns;
        resetn <= '1';
        wait for 6 * PERIOD;

        ----------------------------------------------------------------
        -- GROUP 0: reset defaults (design doc D17)
        ----------------------------------------------------------------
        report "=== GROUP 0: reset defaults ===" severity note;
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP0: SR resets to 0", rdw, x"00000000");
        bus_read(clk, pbus, rdata_out, SlotNFCxCR, rdw);
        sb.check_slv("GROUP0: CR resets to AUTOREAD=1 only", rdw, x"00001000");
        bus_read(clk, pbus, rdata_out, SlotNFCxUID, rdw);
        sb.check_slv("GROUP0: UID resets to 0", rdw, x"00000000");
        bus_read(clk, pbus, rdata_out, SlotNFCxCFG, rdw);
        sb.check_slv("GROUP0: CFG resets to ATQA=0x0044/SAK=0", rdw, x"00000044");
        bus_read(clk, pbus, rdata_out, SlotNFCxTIM, rdw);
        sb.check_slv("GROUP0: TIM ETU=128/SUBCDIV=8 reset bytes", rdw(31 downto 16), x"0880");
        sb.check_true("GROUP0: TIM FDT reset nonzero (~1236, D17)",
                      to_integer(unsigned(rdw(15 downto 0))) > 0);

        ----------------------------------------------------------------
        -- GROUP 1: CRC_A known vectors (DUT-independent, locks the utility)
        ----------------------------------------------------------------
        report "=== GROUP 1: CRC_A vectors ===" severity note;
        -- HAND-COMPUTED LITERAL anchor (ISO 14443-3 Annex B, hand-verified in
        -- the design doc: after {0x00} crc=0x51FE, after {0x00,0x00} crc=0x1EA0).
        fr := (others => (others => '0'));
        sb.check_slv("GROUP1: CRC_A({00,00}) = hand literal 0x1EA0",
                     nfc_crc_a(fr, 2), x"1EA0");
        -- ROUND-TRIP residue: {data, CRC_lo, CRC_hi} re-run through CRC_A yields
        -- the ISO residue 0x0000 (D10). Data = {0x30,0x00} (a READ command head).
        fr := (others => (others => '0'));
        fr(0) := x"30"; fr(1) := x"00";
        crc := nfc_crc_a(fr, 2);
        fr(2) := crc(7 downto 0);          -- low byte first on air
        fr(3) := crc(15 downto 8);
        sb.check_slv("GROUP1: CRC_A residue over {data||CRC} = 0x0000",
                     nfc_crc_a(fr, 4), x"0000");

        ----------------------------------------------------------------
        -- Program the tag identity + compressed timing, then enable.
        ----------------------------------------------------------------
        bus_write(clk, pbus, SlotNFCxUID, UIDW);
        bus_write(clk, pbus, SlotNFCxCFG, nfc_mk_cfg(ATQA, SAK));
        bus_write(clk, pbus, SlotNFCxTIM, nfc_mk_tim(C_FDT, C_ETU, C_SUBCDIV));
        prog_cr('1', '1', '1', '1');       -- NFCEN|LISTEN|AUTOREAD + all IEs

        ----------------------------------------------------------------
        -- GROUP 2: field detect sets FIELDF and irq_field, state IDLE
        ----------------------------------------------------------------
        report "=== GROUP 2: field detect + irq_field ===" severity note;
        cfg_field <= '1';                  -- reader turns the RF field on
        wait for 30 * PERIOD;              -- let the field synchronizer settle
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP2: FIELD_LIVE set", rdw(SrBitFIELDLIVE), '1');
        sb.check_bit("GROUP2: FIELDF set", rdw(SrBitFIELDF), '1');
        sb.check_bit("GROUP2: irq_field asserted (FIELDF & FIELDIE)", irq_field, '1');
        sb.check_slv("GROUP2: state = IDLE", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StIDLE, 4)));
        w1c(x"00000002");                  -- clear FIELDF
        sb.check_bit("GROUP2: irq_field cleared after FIELDF W1C", irq_field, '0');

        ----------------------------------------------------------------
        -- GROUP 3: REQA answered by ATQA (codec round-trip) plus WUPA, state READY
        ----------------------------------------------------------------
        report "=== GROUP 3: REQA/WUPA -> ATQA ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"26";                    -- REQA (7-bit short frame)
        cfg_bytes <= fr;
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_bit("GROUP3: tag responded to REQA", obs_saw_response, '1');
        sb.check_bit("GROUP3: response SOF ok (D)", obs_sof_ok, '1');
        sb.check_true("GROUP3: ATQA is 2 bytes", obs_nbytes = 2);
        sb.check_slv("GROUP3: ATQA byte0 = 0x44", obs_bytes(0), x"44");
        sb.check_slv("GROUP3: ATQA byte1 = 0x00", obs_bytes(1), x"00");
        sb.check_bit("GROUP3: ATQA parity ok", obs_parity_ok, '1');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP3: RXFRAMEF set", rdw(SrBitRXFRAMEF), '1');
        sb.check_bit("GROUP3: TXDONEF set", rdw(SrBitTXDONEF), '1');
        sb.check_slv("GROUP3: state = READY", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StREADY, 4)));
        w1c(x"0000000C");                  -- clear RXFRAMEF|TXDONEF

        -- WUPA path
        fr := (others => (others => '0'));
        fr(0) := x"52";                    -- WUPA
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP3: tag responded to WUPA", obs_saw_response, '1');
        sb.check_slv("GROUP3: WUPA ATQA byte0 = 0x44", obs_bytes(0), x"44");
        w1c(x"0000000C");

        ----------------------------------------------------------------
        -- GROUP 4: anticollision (NVB splits, BCC) and SELECT (SAK), ending in ACTIVE
        ----------------------------------------------------------------
        report "=== GROUP 4: anticollision + SELECT ===" severity note;
        -- 4a: NVB=0x20 asks for the full UID plus BCC (5 bytes, no CRC)
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        sb.check_bit("GROUP4a: tag streamed UID", obs_saw_response, '1');
        sb.check_true("GROUP4a: UID+BCC = 5 bytes", obs_nbytes = 5);
        sb.check_slv("GROUP4a: uid0", obs_bytes(0), UID0);
        sb.check_slv("GROUP4a: uid1", obs_bytes(1), UID1);
        sb.check_slv("GROUP4a: uid2", obs_bytes(2), UID2);
        sb.check_slv("GROUP4a: uid3", obs_bytes(3), UID3);
        sb.check_slv("GROUP4a: BCC = uid0^uid1^uid2^uid3", obs_bytes(4), BCC);
        sb.check_bit("GROUP4a: first response bit = uid0 bit0", obs_first_bit, UID0(0));
        sb.check_bit("GROUP4a: UID stream parity ok", obs_parity_ok, '1');

        -- 4b: partial-NVB MATCH (SEL, NVB=0x24 plus 4 bits of uid0): the tag resumes at UID bit 4, and the response START OFFSET is the check (D13).
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"24"; fr(2) := UID0;
        cfg_bytes <= fr;
        do_frame(false, 2, false, false, 4, false, false);
        sb.check_bit("GROUP4b: match -> tag resumed the UID", obs_saw_response, '1');
        sb.check_bit("GROUP4b: response starts at uid0 bit 4 (split offset)",
                     obs_first_bit, UID0(4));

        -- 4c: partial-NVB MISMATCH (wrong 4-bit prefix) leaves the tag SILENT
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"24"; fr(2) := UID0 xor x"0F";   -- corrupt low nibble
        cfg_bytes <= fr;
        do_frame(false, 2, false, false, 4, false, false);
        sb.check_bit("GROUP4c: mismatch -> tag stays SILENT", obs_saw_response, '0');

        -- 4d: SELECT (NVB=0x70, UID+BCC+CRC_A) is answered with SAK+CRC_A, state ACTIVE
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"70";
        fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
        cfg_bytes <= fr;
        do_frame(false, 7, true, true, 0, false, false);
        sb.check_bit("GROUP4d: SELECT answered", obs_saw_response, '1');
        sb.check_true("GROUP4d: SAK+CRC = 3 bytes", obs_nbytes = 3);
        sb.check_slv("GROUP4d: SAK = 0x00", obs_bytes(0), SAK);
        sb.check_bit("GROUP4d: SAK CRC_A ok", obs_crc_ok, '1');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP4d: state = ACTIVE", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StACTIVE, 4)));
        w1c(x"0000000C");

        ----------------------------------------------------------------
        -- GROUP 5: Type-2 READ returns the CPU-loaded 16-byte payload plus CRC_A
        ----------------------------------------------------------------
        report "=== GROUP 5: READ-BLOCK payload ===" severity note;
        fill_payload;                      -- firmware fills the wound record
        fr := (others => (others => '0'));
        fr(0) := x"30"; fr(1) := x"00";    -- READ, block 0
        cfg_bytes <= fr;
        do_frame(false, 2, true, true, 0, false, false);
        sb.check_bit("GROUP5: READ answered", obs_saw_response, '1');
        sb.check_true("GROUP5: 16 payload bytes + CRC = 18", obs_nbytes = 18);
        for i in 0 to 15 loop
            sb.check_slv("GROUP5: READ byte " & integer'image(i) & " = payload",
                         obs_bytes(i), payload(i));
        end loop;
        sb.check_bit("GROUP5: READ response CRC_A ok", obs_crc_ok, '1');
        sb.check_bit("GROUP5: READ response parity ok", obs_parity_ok, '1');
        neg_val := obs_bytes(0);           -- stash the true byte0 for the neg control
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP5: still ACTIVE after READ", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StACTIVE, 4)));
        w1c(x"0000000C");

        ----------------------------------------------------------------
        -- GROUP 6: HLTA enters HALT silently, REQA is ignored, WUPA re-wakes
        ----------------------------------------------------------------
        report "=== GROUP 6: HLTA + wake rules ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"50"; fr(1) := x"00";    -- HLTA
        cfg_bytes <= fr;
        do_frame(false, 2, true, true, 0, false, false);
        sb.check_bit("GROUP6: HLTA is silent (no response)", obs_saw_response, '0');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP6: HALTED set", rdw(SrBitHALTED), '1');
        sb.check_slv("GROUP6: state = HALT", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StHALT, 4)));
        w1c(x"0000000C");

        -- REQA is IGNORED in HALT (ISO rule)
        fr := (others => (others => '0'));
        fr(0) := x"26";
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP6: REQA ignored in HALT", obs_saw_response, '0');

        -- WUPA re-wakes the tag, which answers ATQA in state READY
        fr := (others => (others => '0'));
        fr(0) := x"52";
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP6: WUPA re-wakes from HALT", obs_saw_response, '1');
        sb.check_slv("GROUP6: WUPA ATQA byte0 = 0x44", obs_bytes(0), x"44");
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_slv("GROUP6: state = READY after WUPA", rdw(11 downto 8),
                     std_logic_vector(to_unsigned(StREADY, 4)));
        w1c(x"0000000C");

        ----------------------------------------------------------------
        -- GROUP 7: parity and CRC injection set PARERRF/CRCERRF and irq_crcerr,
        -- and the frame is dropped (I3C parity-injection self-test lesson, D23 G3)
        ----------------------------------------------------------------
        report "=== GROUP 7: parity / CRC injection ===" severity note;
        -- 7a parity: anticollision with a flipped parity bit sets PARERRF and the tag stays silent
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, true, false);   -- cpar=true
        sb.check_bit("GROUP7a: parity-error frame dropped (silent)", obs_saw_response, '0');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP7a: PARERRF set", rdw(SrBitPARERRF), '1');
        sb.check_bit("GROUP7a: irq_crcerr asserted (PARERRF & CRCIE)", irq_crcerr, '1');
        w1c(x"00000020");                  -- clear PARERRF
        sb.check_bit("GROUP7a: irq_crcerr cleared after PARERRF W1C", irq_crcerr, '0');

        -- 7b CRC: SELECT with a corrupted appended CRC_A sets CRCERRF and yields no SAK
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"70";
        fr(2) := UID0; fr(3) := UID1; fr(4) := UID2; fr(5) := UID3; fr(6) := BCC;
        cfg_bytes <= fr;
        do_frame(false, 7, true, true, 0, false, true);    -- ccrc=true
        sb.check_bit("GROUP7b: bad-CRC SELECT unanswered", obs_saw_response, '0');
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP7b: CRCERRF set", rdw(SrBitCRCERRF), '1');
        sb.check_bit("GROUP7b: irq_crcerr asserted (CRCERRF & CRCIE)", irq_crcerr, '1');
        w1c(x"00000010");                  -- clear CRCERRF

        ----------------------------------------------------------------
        -- GROUP 8: compressed FDT, where reprogramming FDT changes the response
        -- offset (bounded and inconclusive-safe, the I3C GROUP-8 idiom)
        ----------------------------------------------------------------
        report "=== GROUP 8: FDT compressed ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        fdt1 := obs_fdt_ticks;
        sb.check_bit("GROUP8: response seen at base FDT", obs_saw_response, '1');
        w1c(x"0000000C");

        bus_write(clk, pbus, SlotNFCxTIM, nfc_mk_tim(C_FDT * 4, C_ETU, C_SUBCDIV));
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        fdt2 := obs_fdt_ticks;
        w1c(x"0000000C");
        if obs_saw_response = '1' and fdt1 > 0 then
            sb.check_true("GROUP8: larger programmed FDT -> larger response offset",
                          fdt2 > fdt1);
        else
            report "GROUP8: FDT measurement inconclusive (bounded timeout -- " &
                   "expected until a real DUT is connected)" severity note;
        end if;
        bus_write(clk, pbus, SlotNFCxTIM, nfc_mk_tim(C_FDT, C_ETU, C_SUBCDIV));   -- restore

        ----------------------------------------------------------------
        -- GROUP 9: IRQ lines (rxf/txdone) + NFCEN/LISTEN launch guards
        ----------------------------------------------------------------
        report "=== GROUP 9: IRQ + launch guards ===" severity note;
        fr := (others => (others => '0'));
        fr(0) := x"93"; fr(1) := x"20";
        cfg_bytes <= fr;
        do_frame(false, 2, false, true, 0, false, false);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("GROUP9: irq_rxf asserted (RXFRAMEF & RXFIE)", irq_rxf, '1');
        sb.check_bit("GROUP9: irq_txdone asserted (TXDONEF & TXIE)", irq_txdone, '1');
        w1c(x"00000004");                  -- clear RXFRAMEF
        sb.check_bit("GROUP9: irq_rxf cleared after RXFRAMEF W1C", irq_rxf, '0');
        w1c(x"00000008");                  -- clear TXDONEF
        sb.check_bit("GROUP9: irq_txdone cleared after TXDONEF W1C", irq_txdone, '0');

        -- NFCEN=0 launch guard: a REQA must produce no response
        bus_write(clk, pbus, SlotNFCxCR, nfc_mk_cr('0', '1', '1', '1', '1', '1', '1'));
        fr := (others => (others => '0'));
        fr(0) := x"26";
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP9: NFCEN=0 -> tag deaf (no response)", obs_saw_response, '0');

        -- LISTEN=0 launch guard: enabled but not armed, so still deaf
        bus_write(clk, pbus, SlotNFCxCR, nfc_mk_cr('1', '0', '1', '1', '1', '1', '1'));
        cfg_bytes <= fr;
        do_frame(true, 1, false, true, 0, false, false);
        sb.check_bit("GROUP9: LISTEN=0 -> tag deaf (no response)", obs_saw_response, '0');
        prog_cr('1', '1', '1', '1');       -- re-arm

        ----------------------------------------------------------------
        -- GROUP G-EV: EVFAB producer taps (evt_field/evt_rxframe,
        -- event_fabric_spec.md 2026-07-24 EV8/EV9), T-mode TOGGLE producers
        -- flipped at the fieldf_flag/rxframef_flag SET sites (pre-IE, in the
        -- clk (smclk) domain), independent of the flags' own W1C clears.
        -- Checker independence: the continuous background evt_mon_proc counts
        -- FLIPS as the XOR of consecutive clk samples on the exported
        -- evt_field/evt_rxframe ports only, never a DUT internal
        -- (TIMER_tb.vhd's evt_mon_proc/wait_flips_ge idiom).
        ----------------------------------------------------------------
        report "=== GROUP G-EV: EVFAB producer taps (evt_field/evt_rxframe) ===" severity note;

        -- G-EVa: field-detect RISE, reusing GROUP2's cfg_field stimulus.
        -- The field is already live entering this group (raised in GROUP2 and never dropped since), so drop it first to make the next raise a real edge.
        -- The drop itself must produce NO flip, since the tap is rise-only.
        evt_mon_reset;
        cfg_field <= '0';
        wait for 40 * PERIOD;              -- settle the field-drop synchronizer
        sb.check_true("G-EVa0: dropping the (already-live) field produces no evt_field flip "
                     & "(rise-only, setup for the rise below)", evt_field_flips = 0);

        cfg_field <= '1';                  -- provoke the field-detect RISE
        wait_flips_ge(evt_field_flips, 1, 200, done_ok);
        sb.check_true("G-EVa1: evt_field reaches 1 flip on field-detect rise (bounded poll)", done_ok);
        sb.check_true("G-EVa1: evt_field flip count is EXACTLY 1", evt_field_flips = 1);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("G-EVa1: FIELDF sets alongside the evt_field flip", rdw(SrBitFIELDF), '1');
        w1c(x"00000002");                  -- clear FIELDF (W1C never touches the toggle)

        -- Drop and re-raise the field for exactly one MORE flip; the drop itself must not flip, verified by zero flips in between.
        cfg_field <= '0';
        wait for 40 * PERIOD;
        sb.check_true("G-EVa2: dropping the field produces NO evt_field flip (rise-only; "
                     & "still 1 total)", evt_field_flips = 1);
        cfg_field <= '1';
        wait_flips_ge(evt_field_flips, 2, 200, done_ok);
        sb.check_true("G-EVa3: re-raising the field reaches 2 total flips (bounded poll)", done_ok);
        sb.check_true("G-EVa3: evt_field flip count is EXACTLY 2 (one MORE flip)",
                      evt_field_flips = 2);
        w1c(x"00000002");

        -- G-EVb: rx frame delivery, using REQA and the existing rf-rx machinery, which works from IDLE or READY per the D FSM.
        -- Expect exactly one evt_rxframe flip per frame, firing again on a second frame EVEN IF RXFRAMEF is still set.
        -- There is deliberately no W1C between the two: the toggle is pre-flag and independent of the sticky SR bit's own clear.
        evt_mon_reset;
        fr := (others => (others => '0'));
        fr(0) := x"26";                    -- REQA
        cfg_bytes <= fr;
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_bit("G-EVb1: tag responded to REQA", obs_saw_response, '1');
        sb.check_true("G-EVb1: evt_rxframe flips exactly once for one rx frame",
                      evt_rxf_flips = 1);
        bus_read(clk, pbus, rdata_out, SlotNFCxSR, rdw);
        sb.check_bit("G-EVb1: RXFRAMEF set alongside the evt_rxframe flip", rdw(SrBitRXFRAMEF), '1');

        cfg_bytes <= fr;                   -- second frame, RXFRAMEF left set (no W1C)
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_bit("G-EVb2: tag responded to the second REQA", obs_saw_response, '1');
        sb.check_true("G-EVb2: evt_rxframe flips again despite RXFRAMEF still set "
                     & "(no W1C between)", evt_rxf_flips = 2);
        w1c(x"0000000C");                  -- clear RXFRAMEF|TXDONEF now

        -- G-EVc: mask FIELDIE and RXFRAMEIE off; the toggles must still flip, since the taps are pre-IE, while irq_field and irq_rxf stay low because the IRQs are post-mask.
        report "GROUP G-EVc: FIELDIE/RXFRAMEIE masked off" severity note;
        prog_cr('0', '0', '1', '1');       -- FIELDIE=0, RXFRAMEIE=0
        evt_mon_reset;
        cfg_field <= '0';
        wait for 40 * PERIOD;
        cfg_field <= '1';
        wait_flips_ge(evt_field_flips, 1, 200, done_ok);
        sb.check_true("G-EVc1: evt_field still flips with FIELDIE=0 (bounded poll)", done_ok);
        sb.check_true("G-EVc1: evt_field flip count is EXACTLY 1", evt_field_flips = 1);
        sb.check_bit("G-EVc1: irq_field stays low with FIELDIE=0 (masked, unlike evt_field)",
                     to_X01(irq_field), '0');
        w1c(x"00000002");

        fr := (others => (others => '0'));
        fr(0) := x"26";                    -- REQA
        cfg_bytes <= fr;
        do_frame(short => true, n => 1, appcrc => false, rparity => true,
                 partial => 0, cpar => false, ccrc => false);
        sb.check_true("G-EVc2: evt_rxframe still flips with RXFRAMEIE=0", evt_rxf_flips = 1);
        sb.check_bit("G-EVc2: irq_rxf stays low with RXFRAMEIE=0 (masked, unlike evt_rxframe)",
                     to_X01(irq_rxf), '0');
        w1c(x"0000000C");
        prog_cr('1', '1', '1', '1');       -- restore FIELDIE/RXFRAMEIE

        -- G-EVd: a quiet window with no field or rx traffic must give zero flips on both taps.
        evt_mon_reset;
        wait for 60 * PERIOD;
        sb.check_true("G-EVd: zero evt_field flips over a quiet window (no field/rx traffic)",
                      evt_field_flips = 0);
        sb.check_true("G-EVd: zero evt_rxframe flips over a quiet window (no field/rx traffic)",
                      evt_rxf_flips = 0);

        ----------------------------------------------------------------
        -- GROUP-NEG: NEGATIVE CONTROL (mandatory, LAST), one deliberately wrong
        -- expected READ byte. It MUST report exactly one mismatch, which is how
        -- the scoreboard proves it can fail.
        ----------------------------------------------------------------
        report "=== GROUP-NEG: NEGATIVE CONTROL ===" severity note;
        sb.check_slv("NEGATIVE CONTROL: wrong expected READ byte0 (must FAIL)",
                     neg_val, std_logic_vector(unsigned(neg_val) + 1));

        ----------------------------------------------------------------
        -- Final verdict: sb.errors must be EXACTLY 1 (the negative control).
        ----------------------------------------------------------------
        wait for 1 us;
        sb.report_summary("NFC TB");

        if sb.errors = 1 then
            report LF & LF &
                "    ##################################################" & LF &
                "    ##   NFC_TB PASS (1 expected negative-control failure)" & LF &
                "    ##   NFC TB:  ALL CHECKS PASSED" & LF &
                "    ##################################################" & LF
                severity note;
        else
            report LF & LF &
                "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
                "    !!   NFC_TB FAIL (expected exactly 1 failure [negative control], got " &
                integer'image(sb.errors) & ")" & LF &
                "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
                severity warning;
        end if;

        stop;
        wait;
    end process stim_proc;

end architecture sim;
