----- VHDL Libraries
-- IEEE Standard Libraries
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
-- Standard libraries
library std;
use std.standard.all;
use std.textio.all;
use std.env.all;
library work;
use work.periph_tb_pkg.all;

-------------------------------------------------------------------------------
-- NPU_gemm_tb.vhd : GEMM mode (NPUCR.MODE=3) bench, npu_gemm_design.md D10.
-- A SEPARATE leg from NPU_conv_tb and NPU_xnor_tb, per D10's own recommendation: both of those benches are themselves mode-1/mode-2 compatibility fixtures now, and folding GEMM into either risks their gates.
--
-- Instantiates the SAME NPU entity and staging-RAM model at the MCU/chip generics (X_M=0, W_M=7, Y_M=7, N=24, RHO=2).
-- That is the D10/G8 gotcha: the legacy NPU_tb's own bench-default generics would diverge from silicon and from gen_gemm_vectors.py's golden model.
-- Golden files (npu_gemm_<case>_{cfg,in,w,exp}.txt) are generated by verification/npu/gen_gemm_vectors.py, which reuses npu_fixed.think_layer (D10), and reach this run directory as symlinks, the npu_conv_* / npu_xnor_* mechanism.
--
-- cfg header (FROZEN order, D10): M K N BEN AEN ACTF IVSAR WVSAR OVSAR.
-- in.txt holds A row-major (M*K words, A[m][k] at line m*K+k, Q0.24 signed).
-- w.txt holds B COLUMN-MAJOR (K*N words, B[k][n] at line n*K+k, Q7.24 signed), so one column's K weights are contiguous, the D2/D4 weight-walk contract.
-- exp.txt holds C row-major (M*N words, C[m][n] at line m*N+n, Q7.24, or Q0.24 if AEN).
-- Every in/w/exp value fits the plain 32-bit signed VHDL INTEGER range exactly (Q7.24's [-128,128) span is exactly [-2**31, 2**31-1) at the raw-slv level), so a plain `read` into INTEGER is safe here and no parse_u32 is needed.
-- That is unlike NPU_xnor_tb's in/w files, which are raw packed bit patterns that routinely exceed the signed-32-bit range.
--
-- This bench ALSO writes npu_gemm_<case>_act.txt (one actual per line, same order as exp.txt) for post-mortem, per the kickoff's explicit ask, a capability the sibling conv/xnor benches do not have.
--
-- Generic NEGCTRL (D10 G-NEG):
--   0 (default) : clean run, every case's real expected data used as-is.
--                 The ALL-PASS banner is printed only if the running error tally is 0.
--   1           : deliberately corrupts EXACTLY ONE expected value, a MID-POSITION word of the "asym" case's C matrix (index (M*N)/2, integer division), rather than the first output of the base/X-collapse case.
--                 That is the kickoff's explicit choice for GEMM: the asym case is the one built to be index/transpose/order-discriminant per D10's G-ASYM, so a corrupted MID entry there is a stronger single-error target than corrupting base's output 0 would be.
--                 Every other case is untouched, and the NEGCTRL-PASS banner is printed only if the tally is EXACTLY 1.
--
-- The "base" case invocation is the FIRST thing this bench does after ResetN deasserts, with no warm-up CFG pokes ahead of it.
-- That is the D10 G-XCOLLAPSE proof: the added gemm_m/mK/gemm_yptr/M_m1_run registers must resolve to defined outputs from a cold, X-filled staging RAM once CFG is written.
-- Every one of base's outputs is additionally checked for definedness (no X/U/Z/W/- bit) before the numeric compare.
-- The MMR readback smoke (NPUCFG1 full write/read plus offsets 7/8 reading 0) runs immediately after base and before the rest of the case list, the NPU_conv_tb precedent placement.
-- It is harmless to base's own correctness, since think_start fully overwrites NPUCFG1/NPUCR for every case, and it keeps base as the true first bus transaction for the X-collapse proof.
-------------------------------------------------------------------------------
entity NPU_gemm_tb is
	generic (
		NEGCTRL : integer := 0
	);
end NPU_gemm_tb;

architecture testbench of NPU_gemm_tb is
	----- Clock Information
	-- 25 MHz / 40 ns is the BENCH-DRIVEN closure rate, the digperiphs PERIOD DECISION.
	-- The genus NPU close and its SDF are at 40 ns, NOT the legacy NPU_tb's 100 MHz.
	constant CLK_FREQ   : integer 	:= 25e6;                 -- 25 MHz
	constant CLK_PERIOD : time		:= 1 sec / CLK_FREQ;     -- 40 ns
	constant CLK_DELAY	: time 		:= CLK_PERIOD/2;

	----- Constants
	constant MEM_ASSERT			: std_logic	:= '0';
	constant MEM_DEASSERT		: std_logic	:= '1';
	-- Memory address bus constants (MemoryMap.vhd), defined locally rather than pulling in work.MemoryMap here, following the NPU_tb / NPU_conv_tb / NPU_xnor_tb precedent.
	constant MmrAddrNPUCR		: natural	:= 0;
	constant MmrAddrNPUIVSAR	: natural	:= 1;
	constant MmrAddrNPUWVSAR	: natural	:= 2;
	constant MmrAddrNPUOVSAR	: natural	:= 3;
	constant MmrAddrNPUSR		: natural	:= 4;
	constant MmrAddrNPUCFG1		: natural	:= 5;
	constant MmrAddrNPUCFG2		: natural	:= 6;
	constant MmrAddrNPUCFG3		: natural	:= 7;	-- no storage; always reads 0

	-- FROZEN MCU/chip generics, the npu_gemm_design.md binding inputs.
	-- D10/G8: NPU_tb's own generic DEFAULTS are the bench config Q0.15/Q3.15, NOT these, and using them here would diverge from silicon and from the fixed-point encoding of gen_gemm_vectors.py's golden model.
	constant X_M_BITS					: integer := 0;
    constant W_M_BITS					: integer := 7;
    constant Y_M_BITS					: integer := 7;
	constant N_BITS						: integer := 24;
	constant RHO						: integer := 2;

	-- Bounded poll ceiling: G-MAXFIT (M=K=N=36) predicts T = 1 + 1296*181 + 2 = 234579 NpuClk cycles (D8).
	-- This bound clears that with ~11% margin while staying far short of the 100 ms / 2.4M-cycle tb watchdog.
	constant THINK_POLL_MAX				: natural := 260000;

    ----- NPU Port Signals
    signal Clk			: std_logic;
    signal ResetN		: std_logic;
	signal  MabMmrA		: std_logic_vector(3 downto 0)
							:= (others => '0');
    signal MabMmrD		: std_logic_vector(31 downto 0)
								:= (others => '0');
    signal MabMmrCLK	: std_logic;
    signal MabMmrCEN	: std_logic := MEM_DEASSERT;
    signal MabMmrWEN	: std_logic_vector(3 downto 0)
							:= (others => MEM_DEASSERT);
    signal MabMmrQ		: std_logic_vector(31 downto 0);
    signal NpuSramA		: std_logic_vector(11 downto 0);
    signal NpuSramD		: std_logic_vector(31 downto 0);
    signal NpuSramCLK	: std_logic;
    signal NpuSramCEN	: std_logic;
    signal NpuSramGWEN	: std_logic;
    signal NpuSramWEN	: std_logic_vector(3 downto 0);
    signal NpuSramQ		: std_logic_vector(31 downto 0);
    signal NpuActive	: std_logic;
    signal ThinkDoneIrq	: std_logic;

	signal NpuSramA_out	: std_logic_vector(11 downto 0);
    signal NpuSramD_out	: std_logic_vector(31 downto 0);
    signal NpuSramCLK_out	: std_logic;
    signal NpuSramCEN_out	: std_logic;
    signal NpuSramGWEN_out	: std_logic;
    signal NpuSramWEN_out	: std_logic_vector(3 downto 0);
    ----- MCU to SRAM Interface Signals (Testbench controlled)
    signal MabSramA		: std_logic_vector(11 downto 0)
							:= (others => '0');
    signal MabSramD		: std_logic_vector(31 downto 0)
							:= (others => '0');
    signal MabSramCLK	: std_logic;
    signal MabSramCEN	: std_logic := MEM_DEASSERT;
    signal MabSramGWEN	: std_logic := MEM_DEASSERT;
    signal MabSramWEN	: std_logic_vector(3 downto 0)
							:= (others => MEM_DEASSERT);
    signal MabSramPGEN	: std_logic := '0';
    signal MabSramQ		: std_logic_vector(31 downto 0);
    signal SramClkEn	: std_logic;

	shared variable sb : scoreboard;

begin
    ----- Component Instantiations
    -- NPU instantiation (without internal SRAM), at the MCU/chip generics (D10).
    NPU_INST: entity work.NPU
    generic map(
        X_M_BITS	=> X_M_BITS,
        W_M_BITS	=> W_M_BITS,
        Y_M_BITS	=> Y_M_BITS,
        N_BITS		=> N_BITS,
        RHO			=> RHO
    )
    port map(
        Clk			=> Clk,
        ResetN		=> ResetN,

        MabMmrA		=> MabMmrA,
        MabMmrD		=> MabMmrD,
        MabMmrCLK	=> MabMmrCLK,
        MabMmrCEN	=> MabMmrCEN,
        MabMmrWEN	=> MabMmrWEN,
        MabMmrQ		=> MabMmrQ,

		SramQ_in	=> NpuSramQ,
		SramA_in 	=> MabSramA,
		SramD_in 	=> MabSramD,
		SramCLK_in 	=> MabSramCLK,
		SramCEN_in 	=> MabSramCEN,
		SramGWEN_in => MabSramGWEN,
		SramWEN_in 	=> MabSramWEN,

        NpuSramA_out	=> NpuSramA_out,
        NpuSramD_out	=> NpuSramD_out,
        NpuSramCLK_out	=> NpuSramCLK_out,
        NpuSramCEN_out	=> NpuSramCEN_out,
        NpuSramGWEN_out	=> NpuSramGWEN_out,
        NpuSramWEN_out	=> NpuSramWEN_out,

        NpuActive	=> NpuActive,
        ThinkDoneIrq	=> ThinkDoneIrq
    );

    -- SRAM Clock Gate
    SRAM_CLK_CG: entity work.ClkGate
    port map(
        ClkIn	=> Clk,
        En		=> SramClkEn,
        ClkOut	=> MabSramCLK
    );

    -- Single-Port SRAM Instantiation (the NPU staging RAM)
    SRAM_INST: entity work.sram1p16k_hvt_pg
    port map(
        A		=> NpuSramA_out,
        D		=> NpuSramD_out,
        CLK		=> NpuSramCLK_out,
        CEN		=> NpuSramCEN_out,
        GWEN	=> NpuSramGWEN_out,
        WEN		=> NpuSramWEN_out,
        Q		=> NpuSramQ,
        EMA		=> "000",
        PGEN	=> MabSramPGEN,
        RETN	=> '1'
    );

    SramClkEn <= '1' when (MabSramCEN = MEM_ASSERT) else '0';
    MabSramQ  <= NpuSramQ;

	-- Clock Process
	CLK_PROCESS: process
	begin
		Clk	<= '0';
		wait for CLK_DELAY;
		Clk	<= '1';
		wait for CLK_DELAY;
	end process CLK_PROCESS;
	MabMmrCLK	<= Clk;

	-- Main Test Simulation Process
	SIM_PROCESS: process
		variable rd			: std_logic_vector(31 downto 0);
		variable ln			: line;
		variable ival		: integer;

		-- has_x: definedness check (D10 G-XCOLLAPSE).
		-- Written by hand, with no Is_X dependency, so it compiles cleanly under -V200X.
		-- Identical to the NPU_conv_tb / NPU_xnor_tb copy.
		function has_x(v : std_logic_vector) return boolean is
		begin
			for i in v'range loop
				if (v(i) = 'X') or (v(i) = 'U') or (v(i) = 'Z') or
				   (v(i) = 'W') or (v(i) = '-') then
					return true;
				end if;
			end loop;
			return false;
		end function;

		-- to_sl: integer 0/1 to std_logic, for packing the single-bit NPUCR fields.
		function to_sl(v : integer) return std_logic is
		begin
			if v = 0 then return '0'; else return '1'; end if;
		end function;

		----- MMR primitives, mirroring the falling-edge idiom of NPU_tb / NPU_conv_tb / NPU_xnor_tb -----
		procedure mmr_write(addr : natural; data : std_logic_vector(31 downto 0)) is
		begin
			wait until falling_edge(MabMmrCLK);
			MabMmrA   <= std_logic_vector(to_unsigned(addr, 4));
			MabMmrD   <= data;
			MabMmrWEN <= (others => MEM_ASSERT);
			wait until falling_edge(MabMmrCLK);
			MabMmrCEN <= MEM_ASSERT;
			wait until falling_edge(MabMmrCLK);
			MabMmrCEN <= MEM_DEASSERT;
			MabMmrWEN <= (others => MEM_DEASSERT);
		end procedure;

		procedure mmr_read(addr : natural; result : out std_logic_vector(31 downto 0)) is
		begin
			wait until falling_edge(MabMmrCLK);
			MabMmrA   <= std_logic_vector(to_unsigned(addr, 4));
			MabMmrCEN <= MEM_ASSERT;
			wait until falling_edge(MabMmrCLK);
			wait until falling_edge(MabMmrCLK);
			result := MabMmrQ;
			MabMmrCEN <= MEM_DEASSERT;
		end procedure;

		----- SRAM primitives (backdoor MCU-side access, mirroring NPU_tb / NPU_conv_tb / NPU_xnor_tb) -----
		-- MabSramCLK is a GATED clock: SramClkEn follows MabSramCEN = ASSERT through ClkGate, so it only toggles once CEN is already asserted.
		-- A burst of words is therefore: assert CEN (synchronized off the FREE-RUNNING Clk, which opens the gate), THEN wait on MabSramCLK edges for every word, and only deassert CEN once the whole burst is done.
		procedure sram_burst_start is
		begin
			wait until falling_edge(Clk);
			MabSramCEN <= MEM_ASSERT;
			wait until falling_edge(MabSramCLK);
		end procedure;

		procedure sram_burst_stop is
		begin
			MabSramWEN <= (others => MEM_DEASSERT);
			MabSramCEN <= MEM_DEASSERT;
		end procedure;

		-- One word, assuming a burst is already open (CEN asserted, WEN as the caller wants it).
		procedure sram_write_word(addr : natural; data : std_logic_vector(31 downto 0)) is
		begin
			MabSramA <= std_logic_vector(to_unsigned(addr, 12));
			MabSramD <= data;
			wait until falling_edge(MabSramCLK);
			MabSramGWEN <= MEM_ASSERT;
			wait until falling_edge(MabSramCLK);
			MabSramGWEN <= MEM_DEASSERT;
		end procedure;

		procedure sram_read_word(addr : natural; result : out std_logic_vector(31 downto 0)) is
		begin
			MabSramA <= std_logic_vector(to_unsigned(addr, 12));
			wait until falling_edge(MabSramCLK);
			wait until falling_edge(MabSramCLK);
			result := MabSramQ;
		end procedure;

		-- think_start: pokes IVSAR/WVSAR/OVSAR/NPUCFG1(M-1)/NPUCR for one case (D5/D10).
		-- NPUCR is written with MODE=GEMM, THINK=1, NI=K-1, NN=N-1 and BEN/AEN/ACTF as given.
		procedure think_start(m, k, n, ben, aen, actf, ivsar, wvsar, ovsar : integer) is
			variable cfg1, cr : std_logic_vector(31 downto 0);
		begin
			mmr_write(MmrAddrNPUIVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(ivsar, 12)));
			mmr_write(MmrAddrNPUWVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(wvsar, 12)));
			mmr_write(MmrAddrNPUOVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(ovsar, 12)));

			cfg1 := std_logic_vector(to_unsigned(0, 24)) &
			        std_logic_vector(to_unsigned(m - 1, 8));   -- NPUCFG1[7:0] = M-1
			mmr_write(MmrAddrNPUCFG1, cfg1);

			cr := std_logic_vector(to_unsigned(0, 6)) &          -- 31:26 unused
			      std_logic_vector(to_unsigned(actf, 3)) &       -- 25:23 ACTF
			      "011" &                                       -- 22:20 MODE=GEMM
			      '0' &                                         -- 19 TDIE
			      to_sl(ben) &                                  -- 18 BEN
			      to_sl(aen) &                                  -- 17 AEN
			      '1' &                                         -- 16 THINK
			      std_logic_vector(to_unsigned(k - 1, 8)) &     -- 15:8 NI = K-1
			      std_logic_vector(to_unsigned(n - 1, 8));      -- 7:0  NN = N-1
			mmr_write(MmrAddrNPUCR, cr);
		end procedure;

		-- think_poll: bounded poll of NPUCR bit 16 (THINK).
		-- GEMM has no zero-iteration path (D9), so unlike NPU_conv_tb's think_poll there is no "zero writes" side-channel to sample.
		procedure think_poll(bound : natural; ok : out boolean) is
			variable i : natural := 0;
		begin
			ok := false;
			MabMmrCEN <= MEM_ASSERT;
			MabMmrA   <= std_logic_vector(to_unsigned(MmrAddrNPUCR, 4));
			wait until falling_edge(MabMmrCLK);
			while i < bound loop
				if to_X01(MabMmrQ(16)) = '0' then
					ok := true;
					exit;
				end if;
				wait until falling_edge(MabMmrCLK);
				i := i + 1;
			end loop;
			MabMmrCEN <= MEM_DEASSERT;
		end procedure;

		-- run_gemm_case: loads npu_gemm_<case_name>_{cfg,in,w,exp}.txt (the D10 golden-file interface), runs the THINK, compares every output, and writes npu_gemm_<case_name>_act.txt with the actuals for post-mortem.
		--   check_no_x    : also assert each output is fully defined (G-XCOLLAPSE).
		--   corrupt_mid   : deliberately corrupt the MID-POSITION expected value, index (M*N)/2 with integer division (G-NEG).
		--   force_actf    : a value >=0 overrides the cfg file's ACTF, the P4.4 fallback poke used for G-AEN's ACTF=1 re-run, following the conv G-AEN precedent.
		--   exp_file_name : non-empty overrides the default npu_gemm_<case_name>_exp.txt (npu_actf_design.md D10/A2), so the force_actf=1 rerun compares against the LIVE ReLU golden and not the case's own sigmoid exp file.
		procedure run_gemm_case(case_name     : string;
		                        check_no_x    : boolean := false;
		                        corrupt_mid   : boolean := false;
		                        force_actf    : integer := -1;
		                        exp_file_name : string := "") is
			file cfg_f : text;
			file in_f  : text;
			file w_f   : text;
			file exp_f : text;
			file act_f : text;
			variable m_v, k_v, n_v : integer;
			variable ben_v, aen_v, actf_v, actf_use : integer;
			variable ivsar_v, wvsar_v, ovsar_v : integer;
			variable addr    : integer;
			variable exp_val : integer;
			variable act_val : integer;
			variable outc    : integer;
			variable mid_idx : integer;
			variable poll_ok : boolean;
			variable act_ln  : line;
		begin
			report "[NPU_GEMM_TB] === case: " & case_name & " ===" severity note;

			file_open(cfg_f, "npu_gemm_" & case_name & "_cfg.txt", read_mode);
			readline(cfg_f, ln); read(ln, m_v);
			readline(cfg_f, ln); read(ln, k_v);
			readline(cfg_f, ln); read(ln, n_v);
			readline(cfg_f, ln); read(ln, ben_v);
			readline(cfg_f, ln); read(ln, aen_v);
			readline(cfg_f, ln); read(ln, actf_v);
			readline(cfg_f, ln); read(ln, ivsar_v);
			readline(cfg_f, ln); read(ln, wvsar_v);
			readline(cfg_f, ln); read(ln, ovsar_v);
			file_close(cfg_f);

			if force_actf >= 0 then
				actf_use := force_actf;
			else
				actf_use := actf_v;
			end if;

			mid_idx := (m_v * n_v) / 2;

			report "  M=" & integer'image(m_v) & " K=" & integer'image(k_v) &
			       " N=" & integer'image(n_v) & " BEN=" & integer'image(ben_v) &
			       " AEN=" & integer'image(aen_v) & " ACTF=" & integer'image(actf_use) &
			       " IVSAR=" & integer'image(ivsar_v) & " WVSAR=" & integer'image(wvsar_v) &
			       " OVSAR=" & integer'image(ovsar_v) severity note;

			-- Load A (row-major M*K, from IVSAR) and B (column-major K*N, from WVSAR) in ONE SRAM burst.
			sram_burst_start;
			MabSramWEN <= (others => MEM_ASSERT);

			file_open(in_f, "npu_gemm_" & case_name & "_in.txt", read_mode);
			addr := ivsar_v;
			while not endfile(in_f) loop
				readline(in_f, ln);
				read(ln, ival);
				sram_write_word(addr, std_logic_vector(to_signed(ival, 32)));
				addr := addr + 1;
			end loop;
			file_close(in_f);

			file_open(w_f, "npu_gemm_" & case_name & "_w.txt", read_mode);
			addr := wvsar_v;
			while not endfile(w_f) loop
				readline(w_f, ln);
				read(ln, ival);
				sram_write_word(addr, std_logic_vector(to_signed(ival, 32)));
				addr := addr + 1;
			end loop;
			file_close(w_f);
			sram_burst_stop;

			think_start(m_v, k_v, n_v, ben_v, aen_v, actf_use, ivsar_v, wvsar_v, ovsar_v);
			think_poll(THINK_POLL_MAX, poll_ok);
			sb.check_true(case_name & ": THINK completes within " &
			              integer'image(THINK_POLL_MAX) & "-cycle bound", poll_ok);

			-- Compare outputs in flat row-major m*N+n order, writing the actuals out for post-mortem.
			if exp_file_name'length > 0 then
				file_open(exp_f, exp_file_name, read_mode);
			else
				file_open(exp_f, "npu_gemm_" & case_name & "_exp.txt", read_mode);
			end if;
			file_open(act_f, "npu_gemm_" & case_name & "_act.txt", write_mode);
			outc := 0;
			sram_burst_start;
			while not endfile(exp_f) loop
				readline(exp_f, ln);
				read(ln, exp_val);
				if corrupt_mid and (outc = mid_idx) then
					report "  NEGCTRL=1: deliberately corrupting expected output " &
					       integer'image(outc) & " (" & integer'image(exp_val) &
					       " -> " & integer'image(exp_val + 1) &
					       ") -- the comparison below MUST fail." severity warning;
					exp_val := exp_val + 1;
				end if;
				sram_read_word(ovsar_v + outc, rd);
				act_val := to_integer(signed(rd));
				write(act_ln, act_val);
				writeline(act_f, act_ln);
				if check_no_x then
					sb.check_true(case_name & ": output " & integer'image(outc) &
					              " fully defined (no X/U/Z/W/-)", not has_x(rd));
				end if;
				sb.check_true(case_name & ": output " & integer'image(outc) &
				              " match (exp=" & integer'image(exp_val) &
				              ", act=" & integer'image(act_val) & ")",
				              act_val = exp_val);
				outc := outc + 1;
			end loop;
			sram_burst_stop;
			file_close(exp_f);
			file_close(act_f);
			report "  compared " & integer'image(outc) & " output(s)." severity note;
		end procedure;

	begin
		----- Reset NPU -----
		report "[NPU_GEMM_TB] Starting NPU GEMM testbench (NEGCTRL=" &
		       integer'image(NEGCTRL) & ")..." severity note;
		ResetN <= '0';
		wait for 1 us;
		wait until falling_edge(Clk);
		ResetN <= '1';
		MabSramPGEN <= '0';
		wait for 1 us;
		report "[NPU_GEMM_TB] Reset complete." severity note;

		----------------------------------------------------------------
		-- G-BASE / G-XCOLLAPSE.
		-- The FIRST thing this bench does after reset is run the base case, with no other CFG pokes ahead of it, and every output checked for definedness.
		-- That is D10 G-XCOLLAPSE: it proves the added GEMM registers (gemm_m, mK, gemm_yptr, M_m1_run) cannot produce X on the SRAM interface after a cold reset.
		----------------------------------------------------------------
		run_gemm_case("base", check_no_x => true);

		----------------------------------------------------------------
		-- NPUCFG1 and reserved-offset readback smoke.
		-- D5/D9 contract: GEMM reuses NPUCFG1[7:0] only, and offsets 7 (NPUCFG3, no storage) and 8 (reserved) must read 0.
		-- Placed right after base and before the rest of the case list; harmless to any case's correctness since think_start fully overwrites NPUCFG1/NPUCR every time.
		----------------------------------------------------------------
		report "[NPU_GEMM_TB] === NPUCFG1/reserved-offset readback ===" severity note;
		mmr_write(MmrAddrNPUCFG1, std_logic_vector(to_signed(-12345, 32)));
		mmr_read(MmrAddrNPUCFG1, rd);
		sb.check_slv("NPUCFG1 readback exact (full 32-bit write/read)", rd,
		             std_logic_vector(to_signed(-12345, 32)));

		mmr_write(MmrAddrNPUCFG3, x"FFFFFFFF");
		mmr_read(MmrAddrNPUCFG3, rd);
		sb.check_slv("offset 7 (NPUCFG3, no storage) reads 0", rd, x"00000000");

		mmr_write(8, x"FFFFFFFF");
		mmr_read(8, rd);
		sb.check_slv("offset 8 (reserved) reads 0", rd, x"00000000");

		----------------------------------------------------------------
		-- Remaining GROUPs (D10): ordinary file-driven cases.
		-- G-NEG (NEGCTRL=1) corrupts the MID-POSITION expected value of "asym", the index/transpose/order-discriminant case; see the file header for why asym-mid rather than base-first.
		----------------------------------------------------------------
		run_gemm_case("asym", corrupt_mid => (NEGCTRL = 1));
		run_gemm_case("sat");
		run_gemm_case("degen_m1");
		run_gemm_case("degen_n1");
		run_gemm_case("degen_k1");
		run_gemm_case("degen_111");
		run_gemm_case("maxfit");

		-- G-AEN: ACTF=0 (sigmoid-legacy), then the P4.4 fallback poke with ACTF=1 reusing the SAME cfg/in/w data.
		-- ACTF=1 is now LIVE ReLU (the P4.4 inversion, npu_actf_design.md D10/A2, conv G-AEN precedent), so the rerun compares against the aen_relu golden, NOT the case's own sigmoid exp file.
		-- The aen accumulators are mixed-sign, so ReLU differs from sigmoid on every negative one; see gen_gemm_vectors.py's gen_aen_relu_exp.
		run_gemm_case("aen");
		run_gemm_case("aen", force_actf => 1, exp_file_name => "npu_gemm_aen_relu_exp.txt");

		----- Final verdict (D10 G-NEG bipartite banner) -----
		wait for 1 us;
		report "[NPU_GEMM_TB] All groups complete (" & integer'image(sb.errors) &
		       " check(s) failed)." severity note;

		-- Clean run: PASS demands a zero tally.
		if NEGCTRL = 0 then
			if sb.errors = 0 then
				report LF & LF &
					"    ##################################################" & LF &
					"    ##                                              ##" & LF &
					"    ##   NPU GEMM TB:  ALL CHECKS PASSED             ##" & LF &
					"    ##                                              ##" & LF &
					"    ##################################################" & LF
					severity note;
			else
				report LF & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
					"    !!                                              !!" & LF &
					"    !!   NPU GEMM TB FAIL: " & integer'image(sb.errors) &
					       " CHECK(S) FAILED" & LF &
					"    !!                                              !!" & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
					severity warning;
			end if;
		else
			-- Negative control: PASS demands exactly the one injected failure.
			if sb.errors = 1 then
				report LF & LF &
					"    ##################################################" & LF &
					"    ##                                              ##" & LF &
					"    ##   NPU GEMM TB NEGCTRL-PASS (exactly 1 expected fail)" & LF &
					"    ##                                              ##" & LF &
					"    ##################################################" & LF
					severity note;
			else
				report LF & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
					"    !!                                              !!" & LF &
					"    !!   NPU GEMM TB NEGCTRL-FAIL: expected EXACTLY 1 failure, got " &
					       integer'image(sb.errors) & LF &
					"    !!                                              !!" & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
					severity warning;
			end if;
		end if;

		stop;
		wait;
	end process SIM_PROCESS;
end testbench;
