----- VHDL Libraries
-- IEEE Standard Libraries
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
-- Standard libraries
library std;
use std.standard.all;
use std.textio.all;
use std.env.all;
library work;
use work.periph_tb_pkg.all;

-------------------------------------------------------------------------------
-- NPU_actf_tb.vhd -- ACTF activation-mux bench (NPUCR.MODE=0/MLP,
-- NPUCR.ACTF=NPUCR(25:23)), npu_actf_design.md D10 (P4.4). Clone of the
-- NPU_gemm_tb/NPU_conv_tb skeleton, at the SAME MCU/chip generics (X_M=0,
-- W_M=7, Y_M=7, N=24, RHO=2) and 25 MHz bench-driven closure rate.
--
-- MODE 0 (MLP) is deliberately the simplest way to stage an EXACT target
-- accumulator (npu_actf_design.md D10 KEY FINDING): every case here uses
-- NI=0 (ONE shared input X_HALF = 0.5 real, Q0.24) and BEN=0, so each
-- neuron's accumulator is a single MAC tap `acc = X_HALF * w_neuron`; the
-- golden generator (verification/npu/gen_actf_vectors.py) picks
-- `w_neuron = 2*target` so the tap lands EXACTLY on the desired signed
-- Q7.24 accumulator with zero rounding -- every boundary/knee value this
-- bench exercises is therefore exact.
--
-- Golden files (npu_actf_<case>_{cfg,in,w,exp}.txt) are generated by
-- gen_actf_vectors.py and reach this run directory as symlinks (the
-- npu_conv_*/npu_gemm_*/npu_xnor_* mechanism).
--
-- cfg header (FROZEN order, D10/kickoff): NI NN BEN AEN ACTF IVSAR WVSAR
-- OVSAR. in.txt holds NI+1 raw Q0.24 signed words (always 1 here); w.txt
-- holds (NN+1)*(NI+1+BEN) raw Q7.24 signed words, walked contiguously
-- exactly as think_layer()/the DUT's own weight pointer does; exp.txt
-- holds NN+1 raw signed words (post-activation, or the raw accumulator
-- when AEN=0).
--
-- Generic NEGCTRL (D10 G-NEG, MANDATORY LAST):
--   0 (default) -- clean run; ALL-PASS banner printed iff errors=0.
--   1           -- deliberately corrupts EXACTLY ONE expected value: the
--                  MID-POSITION output ((NN+1)/2, integer division) of the
--                  FINAL case invocation (a rerun of "tanh", positioned
--                  the absolute last action in this process per D10's
--                  explicit "G-NEG LAST" ordering requirement -- every
--                  other group/case in this bench is unaffected by
--                  NEGCTRL). NEGCTRL-PASS banner printed iff errors=1.
--
-- The "sigregress" case invocation is the FIRST thing this bench does
-- after ResetN deasserts (no warm-up CFG pokes ahead of it -- the D10
-- G-XCOLLAPSE proof: `actf_run` and the new act_out/relu_word/tanh_word/
-- clamp_word/exp_word nets must resolve to defined outputs from a cold,
-- X-filled staging RAM once CFG is written), and every one of its outputs
-- is additionally checked for definedness (no X/U/Z/W/- bit) before the
-- numeric compare. The NPUCR ACTF-field readback smoke runs immediately
-- after sigregress and before the rest of the case list (harmless to any
-- case's correctness since think_start fully overwrites NPUCR every
-- time).
-------------------------------------------------------------------------------
entity NPU_actf_tb is
	generic (
		NEGCTRL : integer := 0
	);
end NPU_actf_tb;

architecture testbench of NPU_actf_tb is
	----- Clock Information
	-- 25 MHz / 40 ns: the BENCH-DRIVEN closure rate (the digperiphs PERIOD
	-- DECISION -- the genus NPU close and its SDF are at 40 ns).
	constant CLK_FREQ   : integer 	:= 25e6;                 -- 25 MHz
	constant CLK_PERIOD : time		:= 1 sec / CLK_FREQ;     -- 40 ns
	constant CLK_DELAY	: time 		:= CLK_PERIOD/2;

	----- Constants
	constant MEM_ASSERT			: std_logic	:= '0';
	constant MEM_DEASSERT		: std_logic	:= '1';
	-- Memory Address Bus Constants (MemoryMap.vhd; NPU_tb/NPU_conv_tb/
	-- NPU_xnor_tb/NPU_gemm_tb precedent: define locally rather than
	-- pulling in work.MemoryMap here)
	constant MmrAddrNPUCR		: natural	:= 0;
	constant MmrAddrNPUIVSAR	: natural	:= 1;
	constant MmrAddrNPUWVSAR	: natural	:= 2;
	constant MmrAddrNPUOVSAR	: natural	:= 3;
	constant MmrAddrNPUSR		: natural	:= 4;
	constant MmrAddrNPUCFG1		: natural	:= 5;
	constant MmrAddrNPUCFG2		: natural	:= 6;
	constant MmrAddrNPUCFG3		: natural	:= 7;	-- no storage; always reads 0

	-- FROZEN MCU/chip generics (npu_actf_design.md binding inputs -- MUST
	-- match gen_actf_vectors.py's fixed-point encoding, not the legacy
	-- NPU_tb bench-default generics).
	constant X_M_BITS					: integer := 0;
    constant W_M_BITS					: integer := 7;
    constant Y_M_BITS					: integer := 7;
	constant N_BITS						: integer := 24;
	constant RHO						: integer := 2;

	-- Bounded poll ceiling: T = 1 + NN*(5*NI + 3*B + 1) + 2, NI=B=0 here,
	-- so the largest case (tanh, NN=7) predicts T=10 cycles. Generous bound.
	constant THINK_POLL_MAX				: natural := 500;

    ----- NPU Port Signals
    signal Clk			: std_logic;
    signal ResetN		: std_logic;
	signal  MabMmrA		: std_logic_vector(3 downto 0)
							:= (others => '0');
    signal MabMmrD		: std_logic_vector(31 downto 0)
								:= (others => '0');
    signal MabMmrCLK	: std_logic;
    signal MabMmrCEN	: std_logic := MEM_DEASSERT;
    signal MabMmrWEN	: std_logic_vector(3 downto 0)
							:= (others => MEM_DEASSERT);
    signal MabMmrQ		: std_logic_vector(31 downto 0);
    signal NpuSramA		: std_logic_vector(11 downto 0);
    signal NpuSramD		: std_logic_vector(31 downto 0);
    signal NpuSramCLK	: std_logic;
    signal NpuSramCEN	: std_logic;
    signal NpuSramGWEN	: std_logic;
    signal NpuSramWEN	: std_logic_vector(3 downto 0);
    signal NpuSramQ		: std_logic_vector(31 downto 0);
    signal NpuActive	: std_logic;
    signal ThinkDoneIrq	: std_logic;

	signal NpuSramA_out	: std_logic_vector(11 downto 0);
    signal NpuSramD_out	: std_logic_vector(31 downto 0);
    signal NpuSramCLK_out	: std_logic;
    signal NpuSramCEN_out	: std_logic;
    signal NpuSramGWEN_out	: std_logic;
    signal NpuSramWEN_out	: std_logic_vector(3 downto 0);
    ----- MCU to SRAM Interface Signals (Testbench controlled)
    signal MabSramA		: std_logic_vector(11 downto 0)
							:= (others => '0');
    signal MabSramD		: std_logic_vector(31 downto 0)
							:= (others => '0');
    signal MabSramCLK	: std_logic;
    signal MabSramCEN	: std_logic := MEM_DEASSERT;
    signal MabSramGWEN	: std_logic := MEM_DEASSERT;
    signal MabSramWEN	: std_logic_vector(3 downto 0)
							:= (others => MEM_DEASSERT);
    signal MabSramPGEN	: std_logic := '0';
    signal MabSramQ		: std_logic_vector(31 downto 0);
    signal SramClkEn	: std_logic;

	shared variable sb : scoreboard;

begin
    ----- Component Instantiations
    -- NPU Instantiation (without internal SRAM) -- MCU/chip generics (D10)
    NPU_INST: entity work.NPU
    generic map(
        X_M_BITS	=> X_M_BITS,
        W_M_BITS	=> W_M_BITS,
        Y_M_BITS	=> Y_M_BITS,
        N_BITS		=> N_BITS,
        RHO			=> RHO
    )
    port map(
        Clk			=> Clk,
        ResetN		=> ResetN,

        MabMmrA		=> MabMmrA,
        MabMmrD		=> MabMmrD,
        MabMmrCLK	=> MabMmrCLK,
        MabMmrCEN	=> MabMmrCEN,
        MabMmrWEN	=> MabMmrWEN,
        MabMmrQ		=> MabMmrQ,

		SramQ_in	=> NpuSramQ,
		SramA_in 	=> MabSramA,
		SramD_in 	=> MabSramD,
		SramCLK_in 	=> MabSramCLK,
		SramCEN_in 	=> MabSramCEN,
		SramGWEN_in => MabSramGWEN,
		SramWEN_in 	=> MabSramWEN,

        NpuSramA_out	=> NpuSramA_out,
        NpuSramD_out	=> NpuSramD_out,
        NpuSramCLK_out	=> NpuSramCLK_out,
        NpuSramCEN_out	=> NpuSramCEN_out,
        NpuSramGWEN_out	=> NpuSramGWEN_out,
        NpuSramWEN_out	=> NpuSramWEN_out,

        NpuActive	=> NpuActive,
        ThinkDoneIrq	=> ThinkDoneIrq
    );

    -- SRAM Clock Gate
    SRAM_CLK_CG: entity work.ClkGate
    port map(
        ClkIn	=> Clk,
        En		=> SramClkEn,
        ClkOut	=> MabSramCLK
    );

    -- Single-Port SRAM Instantiation (the NPU staging RAM)
    SRAM_INST: entity work.sram1p16k_hvt_pg
    port map(
        A		=> NpuSramA_out,
        D		=> NpuSramD_out,
        CLK		=> NpuSramCLK_out,
        CEN		=> NpuSramCEN_out,
        GWEN	=> NpuSramGWEN_out,
        WEN		=> NpuSramWEN_out,
        Q		=> NpuSramQ,
        EMA		=> "000",
        PGEN	=> MabSramPGEN,
        RETN	=> '1'
    );

    SramClkEn <= '1' when (MabSramCEN = MEM_ASSERT) else '0';
    MabSramQ  <= NpuSramQ;

	-- Clock Process
	CLK_PROCESS: process
	begin
		Clk	<= '0';
		wait for CLK_DELAY;
		Clk	<= '1';
		wait for CLK_DELAY;
	end process CLK_PROCESS;
	MabMmrCLK	<= Clk;

	-- Main Test Simulation Process
	SIM_PROCESS: process
		variable rd			: std_logic_vector(31 downto 0);
		variable ln			: line;
		variable ival		: integer;

		-- has_x: definedness check (D10 G-XCOLLAPSE). Written by hand (no
		-- Is_X dependency) so it compiles cleanly under -V200X. Identical to
		-- the NPU_conv_tb/NPU_xnor_tb/NPU_gemm_tb copy.
		function has_x(v : std_logic_vector) return boolean is
		begin
			for i in v'range loop
				if (v(i) = 'X') or (v(i) = 'U') or (v(i) = 'Z') or
				   (v(i) = 'W') or (v(i) = '-') then
					return true;
				end if;
			end loop;
			return false;
		end function;

		function to_sl(v : integer) return std_logic is
		begin
			if v = 0 then return '0'; else return '1'; end if;
		end function;

		----- MMR primitives (mirror NPU_tb/NPU_conv_tb/NPU_xnor_tb/
		----- NPU_gemm_tb's own falling-edge idiom) -----
		procedure mmr_write(addr : natural; data : std_logic_vector(31 downto 0)) is
		begin
			wait until falling_edge(MabMmrCLK);
			MabMmrA   <= std_logic_vector(to_unsigned(addr, 4));
			MabMmrD   <= data;
			MabMmrWEN <= (others => MEM_ASSERT);
			wait until falling_edge(MabMmrCLK);
			MabMmrCEN <= MEM_ASSERT;
			wait until falling_edge(MabMmrCLK);
			MabMmrCEN <= MEM_DEASSERT;
			MabMmrWEN <= (others => MEM_DEASSERT);
		end procedure;

		procedure mmr_read(addr : natural; result : out std_logic_vector(31 downto 0)) is
		begin
			wait until falling_edge(MabMmrCLK);
			MabMmrA   <= std_logic_vector(to_unsigned(addr, 4));
			MabMmrCEN <= MEM_ASSERT;
			wait until falling_edge(MabMmrCLK);
			wait until falling_edge(MabMmrCLK);
			result := MabMmrQ;
			MabMmrCEN <= MEM_DEASSERT;
		end procedure;

		----- SRAM primitives (backdoor MCU-side access, mirrors NPU_tb/
		----- NPU_conv_tb/NPU_xnor_tb/NPU_gemm_tb) -----
		procedure sram_burst_start is
		begin
			wait until falling_edge(Clk);
			MabSramCEN <= MEM_ASSERT;
			wait until falling_edge(MabSramCLK);
		end procedure;

		procedure sram_burst_stop is
		begin
			MabSramWEN <= (others => MEM_DEASSERT);
			MabSramCEN <= MEM_DEASSERT;
		end procedure;

		procedure sram_write_word(addr : natural; data : std_logic_vector(31 downto 0)) is
		begin
			MabSramA <= std_logic_vector(to_unsigned(addr, 12));
			MabSramD <= data;
			wait until falling_edge(MabSramCLK);
			MabSramGWEN <= MEM_ASSERT;
			wait until falling_edge(MabSramCLK);
			MabSramGWEN <= MEM_DEASSERT;
		end procedure;

		procedure sram_read_word(addr : natural; result : out std_logic_vector(31 downto 0)) is
		begin
			MabSramA <= std_logic_vector(to_unsigned(addr, 12));
			wait until falling_edge(MabSramCLK);
			wait until falling_edge(MabSramCLK);
			result := MabSramQ;
		end procedure;

		-- think_start: pokes IVSAR/WVSAR/OVSAR/NPUCR (MODE=MLP, THINK=1,
		-- NI/NN/BEN/AEN/ACTF as given) for one case.
		procedure think_start(ni, nn, ben, aen, actf, ivsar, wvsar, ovsar : integer) is
			variable cr : std_logic_vector(31 downto 0);
		begin
			mmr_write(MmrAddrNPUIVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(ivsar, 12)));
			mmr_write(MmrAddrNPUWVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(wvsar, 12)));
			mmr_write(MmrAddrNPUOVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(ovsar, 12)));

			cr := std_logic_vector(to_unsigned(0, 6)) &          -- 31:26 unused
			      std_logic_vector(to_unsigned(actf, 3)) &       -- 25:23 ACTF
			      "000" &                                       -- 22:20 MODE=MLP
			      '0' &                                         -- 19 TDIE
			      to_sl(ben) &                                  -- 18 BEN
			      to_sl(aen) &                                  -- 17 AEN
			      '1' &                                         -- 16 THINK
			      std_logic_vector(to_unsigned(ni, 8)) &        -- 15:8 NI
			      std_logic_vector(to_unsigned(nn, 8));         -- 7:0  NN
			mmr_write(MmrAddrNPUCR, cr);
		end procedure;

		-- think_poll: bounded poll of NPUCR bit16 (THINK).
		procedure think_poll(bound : natural; ok : out boolean) is
			variable i : natural := 0;
		begin
			ok := false;
			MabMmrCEN <= MEM_ASSERT;
			MabMmrA   <= std_logic_vector(to_unsigned(MmrAddrNPUCR, 4));
			wait until falling_edge(MabMmrCLK);
			while i < bound loop
				if to_X01(MabMmrQ(16)) = '0' then
					ok := true;
					exit;
				end if;
				wait until falling_edge(MabMmrCLK);
				i := i + 1;
			end loop;
			MabMmrCEN <= MEM_DEASSERT;
		end procedure;

		-- run_actf_case: loads npu_actf_<case_name>_{cfg,in,w,exp}.txt (D10
		-- golden-file interface: cfg = NI NN BEN AEN ACTF IVSAR WVSAR
		-- OVSAR), runs the THINK, and compares every output.
		--   check_no_x  : also assert each output is fully defined
		--                 (G-XCOLLAPSE).
		--   corrupt_mid : deliberately corrupt the MID-POSITION expected
		--                 value ((NN+1)/2, integer division) -- G-NEG.
		--   force_actf  : >=0 overrides the cfg file's ACTF (the
		--                 G-RESERVED/G-AEN0 fallback-poke idiom, conv/gemm
		--                 precedent).
		procedure run_actf_case(case_name     : string;
		                        check_no_x    : boolean := false;
		                        corrupt_mid   : boolean := false;
		                        force_actf    : integer := -1) is
			file cfg_f : text;
			file in_f  : text;
			file w_f   : text;
			file exp_f : text;
			variable ni_v, nn_v : integer;
			variable ben_v, aen_v, actf_v, actf_use : integer;
			variable ivsar_v, wvsar_v, ovsar_v : integer;
			variable addr    : integer;
			variable exp_val : integer;
			variable act_val : integer;
			variable outc    : integer;
			variable mid_idx : integer;
			variable poll_ok : boolean;
		begin
			report "[NPU_ACTF_TB] === case: " & case_name & " ===" severity note;

			file_open(cfg_f, "npu_actf_" & case_name & "_cfg.txt", read_mode);
			readline(cfg_f, ln); read(ln, ni_v);
			readline(cfg_f, ln); read(ln, nn_v);
			readline(cfg_f, ln); read(ln, ben_v);
			readline(cfg_f, ln); read(ln, aen_v);
			readline(cfg_f, ln); read(ln, actf_v);
			readline(cfg_f, ln); read(ln, ivsar_v);
			readline(cfg_f, ln); read(ln, wvsar_v);
			readline(cfg_f, ln); read(ln, ovsar_v);
			file_close(cfg_f);

			if force_actf >= 0 then
				actf_use := force_actf;
			else
				actf_use := actf_v;
			end if;

			mid_idx := (nn_v + 1) / 2;

			report "  NI=" & integer'image(ni_v) & " NN=" & integer'image(nn_v) &
			       " BEN=" & integer'image(ben_v) & " AEN=" & integer'image(aen_v) &
			       " ACTF=" & integer'image(actf_use) &
			       " IVSAR=" & integer'image(ivsar_v) & " WVSAR=" & integer'image(wvsar_v) &
			       " OVSAR=" & integer'image(ovsar_v) severity note;

			-- load X input(s) + weights in ONE SRAM burst
			sram_burst_start;
			MabSramWEN <= (others => MEM_ASSERT);

			file_open(in_f, "npu_actf_" & case_name & "_in.txt", read_mode);
			addr := ivsar_v;
			while not endfile(in_f) loop
				readline(in_f, ln);
				read(ln, ival);
				sram_write_word(addr, std_logic_vector(to_signed(ival, 32)));
				addr := addr + 1;
			end loop;
			file_close(in_f);

			file_open(w_f, "npu_actf_" & case_name & "_w.txt", read_mode);
			addr := wvsar_v;
			while not endfile(w_f) loop
				readline(w_f, ln);
				read(ln, ival);
				sram_write_word(addr, std_logic_vector(to_signed(ival, 32)));
				addr := addr + 1;
			end loop;
			file_close(w_f);
			sram_burst_stop;

			think_start(ni_v, nn_v, ben_v, aen_v, actf_use, ivsar_v, wvsar_v, ovsar_v);
			think_poll(THINK_POLL_MAX, poll_ok);
			sb.check_true(case_name & ": THINK completes within " &
			              integer'image(THINK_POLL_MAX) & "-cycle bound", poll_ok);

			-- compare outputs (flat neuron order)
			file_open(exp_f, "npu_actf_" & case_name & "_exp.txt", read_mode);
			outc := 0;
			sram_burst_start;
			while not endfile(exp_f) loop
				readline(exp_f, ln);
				read(ln, exp_val);
				if corrupt_mid and (outc = mid_idx) then
					report "  NEGCTRL=1: deliberately corrupting expected output " &
					       integer'image(outc) & " (" & integer'image(exp_val) &
					       " -> " & integer'image(exp_val + 1) &
					       ") -- the comparison below MUST fail." severity warning;
					exp_val := exp_val + 1;
				end if;
				sram_read_word(ovsar_v + outc, rd);
				act_val := to_integer(signed(rd));
				if check_no_x then
					sb.check_true(case_name & ": output " & integer'image(outc) &
					              " fully defined (no X/U/Z/W/-)", not has_x(rd));
				end if;
				sb.check_true(case_name & ": output " & integer'image(outc) &
				              " match (exp=" & integer'image(exp_val) &
				              ", act=" & integer'image(act_val) & ")",
				              act_val = exp_val);
				outc := outc + 1;
			end loop;
			sram_burst_stop;
			file_close(exp_f);
			report "  compared " & integer'image(outc) & " output(s)." severity note;
		end procedure;

	begin
		----- Reset NPU -----
		report "[NPU_ACTF_TB] Starting NPU ACTF testbench (NEGCTRL=" &
		       integer'image(NEGCTRL) & ")..." severity note;
		ResetN <= '0';
		wait for 1 us;
		wait until falling_edge(Clk);
		ResetN <= '1';
		MabSramPGEN <= '0';
		wait for 1 us;
		report "[NPU_ACTF_TB] Reset complete." severity note;

		----------------------------------------------------------------
		-- G-SIGMOID-REGRESS / G-XCOLLAPSE: the FIRST thing this bench does
		-- after reset is run the sigregress case, with no other CFG pokes
		-- ahead of it (D10 G-XCOLLAPSE -- proves the P4.4 `actf_run`/
		-- act_out/relu_word/tanh_word/clamp_word/exp_word nets cannot
		-- produce X on the SRAM interface after a cold reset) and every
		-- output checked for definedness. Also the ACTF=0 mux-collapse
		-- compatibility anchor (D1/GA1).
		----------------------------------------------------------------
		run_actf_case("sigregress", check_no_x => true);

		----------------------------------------------------------------
		-- NPUCR ACTF-field readback smoke (early, per the kickoff): a raw
		-- poke with THINK=0 (no launch) confirms bits 25:23 store/read
		-- back exactly. Harmless to any case's correctness -- think_start
		-- fully overwrites NPUCR every time.
		----------------------------------------------------------------
		report "[NPU_ACTF_TB] === NPUCR ACTF-field readback ===" severity note;
		mmr_write(MmrAddrNPUCR,
		          std_logic_vector(to_unsigned(0, 6)) &   -- 31:26 unused
		          "110" &                                 -- 25:23 ACTF probe = 6 (reserved)
		          "000" &                                 -- 22:20 MODE=MLP
		          "0000" &                                -- 19 TDIE, 18 BEN, 17 AEN, 16 THINK=0 (no launch)
		          std_logic_vector(to_unsigned(0, 8)) &   -- 15:8 NI
		          std_logic_vector(to_unsigned(0, 8)));   -- 7:0 NN
		mmr_read(MmrAddrNPUCR, rd);
		sb.check_slv("NPUCR ACTF field readback (bits 25:23, THINK=0 no launch)",
		             rd(25 downto 23), "110");

		----------------------------------------------------------------
		-- Remaining GROUPs (D10) -- ordinary file-driven cases.
		----------------------------------------------------------------
		run_actf_case("relu");
		run_actf_case("tanh");
		run_actf_case("clamp");
		run_actf_case("expa");

		-- G-RESERVED: ACTF=5 baked in cfg, then ACTF=7 forced -- both
		-- reserved codes MUST equal the SAME sigmoid golden (D6).
		run_actf_case("reserved");
		run_actf_case("reserved", force_actf => 7);

		-- G-AEN0: AEN=0, ACTF swept 0..4 -- output MUST be the raw
		-- accumulator (passthrough) for every ACTF (D1 master enable).
		run_actf_case("aen0", force_actf => 0);
		run_actf_case("aen0", force_actf => 1);
		run_actf_case("aen0", force_actf => 2);
		run_actf_case("aen0", force_actf => 3);
		run_actf_case("aen0", force_actf => 4);

		----------------------------------------------------------------
		-- G-NEG (MANDATORY LAST, D10): the absolute final action in this
		-- process -- a rerun of "tanh" that corrupts its mid-position
		-- expected output exactly once when NEGCTRL=1. Every group above
		-- is unaffected.
		----------------------------------------------------------------
		run_actf_case("tanh", corrupt_mid => (NEGCTRL = 1));

		----- Final verdict (D10 G-NEG bipartite banner) -----
		wait for 1 us;
		report "[NPU_ACTF_TB] All groups complete (" & integer'image(sb.errors) &
		       " check(s) failed)." severity note;

		if NEGCTRL = 0 then
			if sb.errors = 0 then
				report LF & LF &
					"    ##################################################" & LF &
					"    ##                                              ##" & LF &
					"    ##   NPU ACTF TB:  ALL CHECKS PASSED             ##" & LF &
					"    ##                                              ##" & LF &
					"    ##################################################" & LF
					severity note;
			else
				report LF & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
					"    !!                                              !!" & LF &
					"    !!   NPU ACTF TB FAIL: " & integer'image(sb.errors) &
					       " CHECK(S) FAILED" & LF &
					"    !!                                              !!" & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
					severity warning;
			end if;
		else
			if sb.errors = 1 then
				report LF & LF &
					"    ##################################################" & LF &
					"    ##                                              ##" & LF &
					"    ##   NPU ACTF TB NEGCTRL-PASS (exactly 1 expected fail)" & LF &
					"    ##                                              ##" & LF &
					"    ##################################################" & LF
					severity note;
			else
				report LF & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
					"    !!                                              !!" & LF &
					"    !!   NPU ACTF TB NEGCTRL-FAIL: expected EXACTLY 1 failure, got " &
					       integer'image(sb.errors) & LF &
					"    !!                                              !!" & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
					severity warning;
			end if;
		end if;

		stop;
		wait;
	end process SIM_PROCESS;
end testbench;
