----- VHDL Libraries
-- IEEE Standard Libraries
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
-- Standard libraries
library std;
use std.standard.all;
use std.textio.all;
use std.env.all;
library work;
use work.periph_tb_pkg.all;
-- Synthesizable Fixed Point libraries created by David Bishop for VHDL 2008
use work.fixed_float_types.all;
use work.fixed_pkg.all;

-------------------------------------------------------------------------------
-- NPU_conv_tb.vhd : CONV1D mode (NPUCR.MODE=1) bench, npu_conv_design.md D9.
--
-- A SEPARATE leg from NPU_tb, the mode-0 MLP compatibility fixture, which is left untouched.
-- It instantiates the SAME NPU entity and staging-RAM model at the MCU/chip generics (X_M=0, W_M=7, Y_M=7, N=24, RHO=2, NOT NPU_tb's bench defaults, the D9/G7 gotcha) and drives it through golden-file-driven GROUPs.
-- Golden files (npu_conv_<case>_{cfg,in,w,exp}.txt) are generated by verification/npu/gen_conv_vectors.py and reach this run directory as symlinks, the same mechanism as npu_fp_*.txt for NPU_tb.
--
-- Generic NEGCTRL (D9 G-NEG, mirrors NPU_tb's own IRQ negctrl generic):
--   0 (default) : clean run, every case's real expected data used as-is.
--                 The ALL-PASS banner is printed only if the running error tally is 0.
--   1           : deliberately corrupts EXACTLY ONE expected value, the first output of the G-BASE case, before comparison; every other case is untouched.
--                 The NEGCTRL-PASS banner is printed only if the tally is EXACTLY 1.
--
-- The G-BASE invocation is ALSO the D9 G-DUP4 "X-collapse" proof: it is the very first thing this bench does after ResetN deasserts, with no warm-up CFG pokes ahead of it, and every one of its outputs is additionally checked for definedness (no X/U/Z/W/- bit) before the numeric compare.
-------------------------------------------------------------------------------
entity NPU_conv_tb is
	generic (
		NEGCTRL : integer := 0
	);
end NPU_conv_tb;

architecture testbench of NPU_conv_tb is
	----- Clock Information
	-- 25 MHz / 40 ns is the BENCH-DRIVEN closure rate, the digperiphs PERIOD DECISION.
	-- The genus NPU close and its SDF are at 40 ns and the tb must drive the rate the netlist was closed at.
	-- The legacy NPU_tb's 100 MHz was cloned here by mistake and caught at SDF bring-up.
	constant CLK_FREQ   : integer 	:= 25e6;                 -- 25 MHz
	constant CLK_PERIOD : time		:= 1 sec / CLK_FREQ;     -- 40 ns
	constant CLK_DELAY	: time 		:= CLK_PERIOD/2;

	----- Constants
	constant MEM_ASSERT			: std_logic	:= '0';
	constant MEM_DEASSERT		: std_logic	:= '1';
	-- Memory address bus constants (MemoryMap.vhd), defined locally rather than pulling in work.MemoryMap here, following the NPU_tb precedent.
	constant MmrAddrNPUCR		: natural	:= 0;
	constant MmrAddrNPUIVSAR	: natural	:= 1;
	constant MmrAddrNPUWVSAR	: natural	:= 2;
	constant MmrAddrNPUOVSAR	: natural	:= 3;
	constant MmrAddrNPUSR		: natural	:= 4;
	constant MmrAddrNPUCFG1		: natural	:= 5;
	constant MmrAddrNPUCFG2		: natural	:= 6;
	constant MmrAddrNPUCFG3		: natural	:= 7;	-- no storage; always reads 0

	-- FROZEN MCU/chip generics, the npu_conv_design.md binding inputs.
	-- D9/G7: NPU_tb's own generic DEFAULTS are the bench config Q0.15/Q3.15, NOT these, and using them here would diverge from silicon and from gen_conv_vectors.py's golden model.
	constant X_M_BITS					: integer := 0;
    constant W_M_BITS					: integer := 7;
    constant Y_M_BITS					: integer := 7;
	constant N_BITS						: integer := 24;
	constant RHO						: integer := 2;

	-- Bounded poll ceiling: the largest predicted case (G-MULTI) is ~10.3k NpuClk cycles (D6).
	-- This sits comfortably above every case with margin, while staying far short of the 100 ms / 2.4M-cycle tb watchdog.
	constant THINK_POLL_MAX				: natural := 100000;

    ----- NPU Port Signals
    signal Clk			: std_logic;
    signal ResetN		: std_logic;
	signal  MabMmrA		: std_logic_vector(3 downto 0)
							:= (others => '0');
    signal MabMmrD		: std_logic_vector(31 downto 0)
								:= (others => '0');
    signal MabMmrCLK	: std_logic;
    signal MabMmrCEN	: std_logic := MEM_DEASSERT;
    signal MabMmrWEN	: std_logic_vector(3 downto 0)
							:= (others => MEM_DEASSERT);
    signal MabMmrQ		: std_logic_vector(31 downto 0);
    signal NpuSramA		: std_logic_vector(11 downto 0);
    signal NpuSramD		: std_logic_vector(31 downto 0);
    signal NpuSramCLK	: std_logic;
    signal NpuSramCEN	: std_logic;
    signal NpuSramGWEN	: std_logic;
    signal NpuSramWEN	: std_logic_vector(3 downto 0);
    signal NpuSramQ		: std_logic_vector(31 downto 0);
    signal NpuActive	: std_logic;
    signal ThinkDoneIrq	: std_logic;

	signal NpuSramA_out	: std_logic_vector(11 downto 0);
    signal NpuSramD_out	: std_logic_vector(31 downto 0);
    signal NpuSramCLK_out	: std_logic;
    signal NpuSramCEN_out	: std_logic;
    signal NpuSramGWEN_out	: std_logic;
    signal NpuSramWEN_out	: std_logic_vector(3 downto 0);
    ----- MCU to SRAM Interface Signals (Testbench controlled)
    signal MabSramA		: std_logic_vector(11 downto 0)
							:= (others => '0');
    signal MabSramD		: std_logic_vector(31 downto 0)
							:= (others => '0');
    signal MabSramCLK	: std_logic;
    signal MabSramCEN	: std_logic := MEM_DEASSERT;
    signal MabSramGWEN	: std_logic := MEM_DEASSERT;
    signal MabSramWEN	: std_logic_vector(3 downto 0)
							:= (others => MEM_DEASSERT);
    signal MabSramPGEN	: std_logic := '0';
    signal MabSramQ		: std_logic_vector(31 downto 0);
    signal SramClkEn	: std_logic;

	shared variable sb : scoreboard;

begin
    ----- Component Instantiations
    -- NPU instantiation (without internal SRAM), at the MCU/chip generics (D9).
    NPU_INST: entity work.NPU
    generic map(
        X_M_BITS	=> X_M_BITS,
        W_M_BITS	=> W_M_BITS,
        Y_M_BITS	=> Y_M_BITS,
        N_BITS		=> N_BITS,
        RHO			=> RHO
    )
    port map(
        Clk			=> Clk,
        ResetN		=> ResetN,

        MabMmrA		=> MabMmrA,
        MabMmrD		=> MabMmrD,
        MabMmrCLK	=> MabMmrCLK,
        MabMmrCEN	=> MabMmrCEN,
        MabMmrWEN	=> MabMmrWEN,
        MabMmrQ		=> MabMmrQ,

		SramQ_in	=> NpuSramQ,
		SramA_in 	=> MabSramA,
		SramD_in 	=> MabSramD,
		SramCLK_in 	=> MabSramCLK,
		SramCEN_in 	=> MabSramCEN,
		SramGWEN_in => MabSramGWEN,
		SramWEN_in 	=> MabSramWEN,

        NpuSramA_out	=> NpuSramA_out,
        NpuSramD_out	=> NpuSramD_out,
        NpuSramCLK_out	=> NpuSramCLK_out,
        NpuSramCEN_out	=> NpuSramCEN_out,
        NpuSramGWEN_out	=> NpuSramGWEN_out,
        NpuSramWEN_out	=> NpuSramWEN_out,

        NpuActive	=> NpuActive,
        ThinkDoneIrq	=> ThinkDoneIrq
    );

    -- SRAM Clock Gate
    SRAM_CLK_CG: entity work.ClkGate
    port map(
        ClkIn	=> Clk,
        En		=> SramClkEn,
        ClkOut	=> MabSramCLK
    );

    -- Single-Port SRAM Instantiation (the NPU staging RAM)
    SRAM_INST: entity work.sram1p16k_hvt_pg
    port map(
        A		=> NpuSramA_out,
        D		=> NpuSramD_out,
        CLK		=> NpuSramCLK_out,
        CEN		=> NpuSramCEN_out,
        GWEN	=> NpuSramGWEN_out,
        WEN		=> NpuSramWEN_out,
        Q		=> NpuSramQ,
        EMA		=> "000",
        PGEN	=> MabSramPGEN,
        RETN	=> '1'
    );

    SramClkEn <= '1' when (MabSramCEN = MEM_ASSERT) else '0';
    MabSramQ  <= NpuSramQ;

	-- Clock Process
	CLK_PROCESS: process
	begin
		Clk	<= '0';
		wait for CLK_DELAY;
		Clk	<= '1';
		wait for CLK_DELAY;
	end process CLK_PROCESS;
	MabMmrCLK	<= Clk;

	-- Main Test Simulation Process
	SIM_PROCESS: process
		variable rd			: std_logic_vector(31 downto 0);
		variable ln			: line;
		variable ival		: integer;

		-- has_x: definedness check (D9 G-DUP4).
		-- Written by hand, with no Is_X dependency, so it compiles cleanly under -V200X.
		function has_x(v : std_logic_vector) return boolean is
		begin
			for i in v'range loop
				if (v(i) = 'X') or (v(i) = 'U') or (v(i) = 'Z') or
				   (v(i) = 'W') or (v(i) = '-') then
					return true;
				end if;
			end loop;
			return false;
		end function;

		-- to_sl: integer 0/1 to std_logic, for packing the single-bit NPUCR fields.
		function to_sl(v : integer) return std_logic is
		begin
			if v = 0 then return '0'; else return '1'; end if;
		end function;

		-- calc_L: the same "exact valid conv, no padding" length formula gen_conv_vectors.py uses.
		-- L is NOT stored in the cfg file (D9).
		function calc_L(k, s, d, lout : integer) return integer is
		begin
			return d * (k - 1) + 1 + (lout - 1) * s;
		end function;

		----- MMR primitives (mirror NPU_tb's own falling-edge idiom) -----
		procedure mmr_write(addr : natural; data : std_logic_vector(31 downto 0)) is
		begin
			wait until falling_edge(MabMmrCLK);
			MabMmrA   <= std_logic_vector(to_unsigned(addr, 4));
			MabMmrD   <= data;
			MabMmrWEN <= (others => MEM_ASSERT);
			wait until falling_edge(MabMmrCLK);
			MabMmrCEN <= MEM_ASSERT;
			wait until falling_edge(MabMmrCLK);
			MabMmrCEN <= MEM_DEASSERT;
			MabMmrWEN <= (others => MEM_DEASSERT);
		end procedure;

		procedure mmr_read(addr : natural; result : out std_logic_vector(31 downto 0)) is
		begin
			wait until falling_edge(MabMmrCLK);
			MabMmrA   <= std_logic_vector(to_unsigned(addr, 4));
			MabMmrCEN <= MEM_ASSERT;
			wait until falling_edge(MabMmrCLK);
			wait until falling_edge(MabMmrCLK);
			result := MabMmrQ;
			MabMmrCEN <= MEM_DEASSERT;
		end procedure;

		----- SRAM primitives (backdoor MCU-side access, mirrors NPU_tb) -----
		-- MabSramCLK is a GATED clock: SramClkEn follows MabSramCEN = ASSERT through ClkGate, so it only toggles once CEN is already asserted.
		-- A burst of words is therefore: assert CEN (synchronized off the FREE-RUNNING Clk, which opens the gate), THEN wait on MabSramCLK edges for every word, and only deassert CEN once the whole burst is done.
		-- That is exactly NPU_tb's own idiom; waiting on MabSramCLK before CEN is ever asserted hangs forever, because the gate never opens.
		procedure sram_burst_start is
		begin
			wait until falling_edge(Clk);
			MabSramCEN <= MEM_ASSERT;
			wait until falling_edge(MabSramCLK);
		end procedure;

		procedure sram_burst_stop is
		begin
			MabSramWEN <= (others => MEM_DEASSERT);
			MabSramCEN <= MEM_DEASSERT;
		end procedure;

		-- One word, assuming a burst is already open (CEN asserted, WEN as the caller wants it).
		procedure sram_write_word(addr : natural; data : std_logic_vector(31 downto 0)) is
		begin
			MabSramA <= std_logic_vector(to_unsigned(addr, 12));
			MabSramD <= data;
			wait until falling_edge(MabSramCLK);
			MabSramGWEN <= MEM_ASSERT;
			wait until falling_edge(MabSramCLK);
			MabSramGWEN <= MEM_DEASSERT;
		end procedure;

		procedure sram_read_word(addr : natural; result : out std_logic_vector(31 downto 0)) is
		begin
			MabSramA <= std_logic_vector(to_unsigned(addr, 12));
			wait until falling_edge(MabSramCLK);
			wait until falling_edge(MabSramCLK);
			result := MabSramQ;
		end procedure;

		-- think_start: pokes IVSAR/WVSAR/OVSAR/NPUCFG1/NPUCFG2/NPUCR (MODE=CONV, THINK=1) for one case.
		-- l_calc is the derived input length.
		procedure think_start(k, cin, cout, lout, s, d, ben, aen, actf,
		                       ivsar, wvsar, ovsar : integer) is
			variable cfg1, cfg2, cr : std_logic_vector(31 downto 0);
			variable l_calc : integer;
		begin
			l_calc := calc_L(k, s, d, lout);
			mmr_write(MmrAddrNPUIVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(ivsar, 12)));
			mmr_write(MmrAddrNPUWVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(wvsar, 12)));
			mmr_write(MmrAddrNPUOVSAR, (31 downto 12 => '0') & std_logic_vector(to_unsigned(ovsar, 12)));

			cfg1 := std_logic_vector(to_unsigned(cin - 1, 8)) &
			        std_logic_vector(to_unsigned(l_calc, 16)) &
			        std_logic_vector(to_unsigned(d, 4)) &
			        std_logic_vector(to_unsigned(s, 4));
			mmr_write(MmrAddrNPUCFG1, cfg1);

			cfg2 := (31 downto 16 => '0') & std_logic_vector(to_unsigned(lout, 16));
			mmr_write(MmrAddrNPUCFG2, cfg2);

			cr := std_logic_vector(to_unsigned(0, 6)) &          -- 31:26 unused
			      std_logic_vector(to_unsigned(actf, 3)) &       -- 25:23 ACTF
			      "001" &                                       -- 22:20 MODE=CONV
			      '0' &                                         -- 19 TDIE
			      to_sl(ben) &                                  -- 18 BEN
			      to_sl(aen) &                                  -- 17 AEN
			      '1' &                                         -- 16 THINK
			      std_logic_vector(to_unsigned(k - 1, 8)) &      -- 15:8 NI = K-1
			      std_logic_vector(to_unsigned(cout - 1, 8));    -- 7:0  NN = Cout-1
			mmr_write(MmrAddrNPUCR, cr);
		end procedure;

		-- think_poll: bounded poll of NPUCR bit 16, also sampling the DUT's own NpuSramGWEN_out each cycle for the G-DEGEN L=0 "zero writes" proof.
		procedure think_poll(bound : natural; ok : out boolean; wrote : out boolean) is
			variable i : natural := 0;
		begin
			ok    := false;
			wrote := false;
			MabMmrCEN <= MEM_ASSERT;
			MabMmrA   <= std_logic_vector(to_unsigned(MmrAddrNPUCR, 4));
			wait until falling_edge(MabMmrCLK);
			while i < bound loop
				if to_X01(NpuSramGWEN_out) = '0' then
					wrote := true;
				end if;
				if to_X01(MabMmrQ(16)) = '0' then
					ok := true;
					exit;
				end if;
				wait until falling_edge(MabMmrCLK);
				i := i + 1;
			end loop;
			MabMmrCEN <= MEM_DEASSERT;
		end procedure;

		-- run_conv_case: loads npu_conv_<case_name>_{cfg,in,w,exp}.txt (the D9 golden-file interface), runs the THINK, and compares every output.
		--   corrupt_first : deliberately wrong first expected value (G-NEG).
		--   check_no_x    : also assert each output is fully defined (G-DUP4).
		--   force_actf    : a value >=0 overrides the cfg file's ACTF, the P4.1/P4.4 fallback poke used for G-AEN's ACTF=1 re-run.
		--   exp_file_name : non-empty overrides the default npu_conv_<case_name>_exp.txt (P4.4 npu_actf_design.md D10/A2), so the force_actf=1 rerun compares against the LIVE ReLU golden and not the case's own sigmoid exp file.
		procedure run_conv_case(case_name     : string;
		                        corrupt_first : boolean := false;
		                        check_no_x    : boolean := false;
		                        force_actf    : integer := -1;
		                        exp_file_name : string := "") is
			file cfg_f : text;
			file in_f  : text;
			file w_f   : text;
			file exp_f : text;
			variable k_v, cin_v, cout_v, lout_v, s_v, d_v : integer;
			variable ben_v, aen_v, actf_v, actf_use : integer;
			variable ivsar_v, wvsar_v, ovsar_v : integer;
			variable addr    : integer;
			variable exp_val : integer;
			variable act_val : integer;
			variable outc    : integer;
			variable poll_ok, wrote_any : boolean;
		begin
			report "[NPU_CONV_TB] === case: " & case_name & " ===" severity note;

			file_open(cfg_f, "npu_conv_" & case_name & "_cfg.txt", read_mode);
			readline(cfg_f, ln); read(ln, k_v);
			readline(cfg_f, ln); read(ln, cin_v);
			readline(cfg_f, ln); read(ln, cout_v);
			readline(cfg_f, ln); read(ln, lout_v);
			readline(cfg_f, ln); read(ln, s_v);
			readline(cfg_f, ln); read(ln, d_v);
			readline(cfg_f, ln); read(ln, ben_v);
			readline(cfg_f, ln); read(ln, aen_v);
			readline(cfg_f, ln); read(ln, actf_v);
			readline(cfg_f, ln); read(ln, ivsar_v);
			readline(cfg_f, ln); read(ln, wvsar_v);
			readline(cfg_f, ln); read(ln, ovsar_v);
			file_close(cfg_f);

			if force_actf >= 0 then
				actf_use := force_actf;
			else
				actf_use := actf_v;
			end if;

			report "  K=" & integer'image(k_v) & " Cin=" & integer'image(cin_v) &
			       " Cout=" & integer'image(cout_v) & " Lout=" & integer'image(lout_v) &
			       " S=" & integer'image(s_v) & " D=" & integer'image(d_v) &
			       " BEN=" & integer'image(ben_v) & " AEN=" & integer'image(aen_v) &
			       " ACTF=" & integer'image(actf_use) &
			       " IVSAR=" & integer'image(ivsar_v) & " WVSAR=" & integer'image(wvsar_v) &
			       " OVSAR=" & integer'image(ovsar_v) severity note;

			if lout_v = 0 then
				-- D10 G3: zero outputs, immediate done, NO staging-RAM writes.
				think_start(k_v, cin_v, cout_v, lout_v, s_v, d_v, ben_v, aen_v, actf_use,
				            ivsar_v, wvsar_v, ovsar_v);
				think_poll(200, poll_ok, wrote_any);
				sb.check_true(case_name & ": Lout=0 completes within bound", poll_ok);
				sb.check_true(case_name & ": Lout=0 issues zero staging-RAM writes", not wrote_any);
				return;
			end if;

			-- Load inputs and weights in ONE SRAM burst: channel-major inputs from IVSAR, then filter-major weights from WVSAR.
			sram_burst_start;
			MabSramWEN <= (others => MEM_ASSERT);

			file_open(in_f, "npu_conv_" & case_name & "_in.txt", read_mode);
			addr := ivsar_v;
			while not endfile(in_f) loop
				readline(in_f, ln);
				read(ln, ival);
				sram_write_word(addr, std_logic_vector(to_signed(ival, 32)));
				addr := addr + 1;
			end loop;
			file_close(in_f);

			file_open(w_f, "npu_conv_" & case_name & "_w.txt", read_mode);
			addr := wvsar_v;
			while not endfile(w_f) loop
				readline(w_f, ln);
				read(ln, ival);
				sram_write_word(addr, std_logic_vector(to_signed(ival, 32)));
				addr := addr + 1;
			end loop;
			file_close(w_f);
			sram_burst_stop;

			think_start(k_v, cin_v, cout_v, lout_v, s_v, d_v, ben_v, aen_v, actf_use,
			            ivsar_v, wvsar_v, ovsar_v);
			think_poll(THINK_POLL_MAX, poll_ok, wrote_any);
			sb.check_true(case_name & ": THINK completes within " &
			              integer'image(THINK_POLL_MAX) & "-cycle bound", poll_ok);

			-- Compare outputs, in flat f*Lout+j order.
			if exp_file_name'length > 0 then
				file_open(exp_f, exp_file_name, read_mode);
			else
				file_open(exp_f, "npu_conv_" & case_name & "_exp.txt", read_mode);
			end if;
			outc := 0;
			sram_burst_start;
			while not endfile(exp_f) loop
				readline(exp_f, ln);
				read(ln, exp_val);
				if corrupt_first and (outc = 0) then
					report "  NEGCTRL=1: deliberately corrupting expected output 0 (" &
					       integer'image(exp_val) & " -> " & integer'image(exp_val + 1) &
					       ") -- the comparison below MUST fail." severity warning;
					exp_val := exp_val + 1;
				end if;
				sram_read_word(ovsar_v + outc, rd);
				act_val := to_integer(signed(rd));
				if check_no_x then
					sb.check_true(case_name & ": output " & integer'image(outc) &
					              " fully defined (no X/U/Z/W/-)", not has_x(rd));
				end if;
				sb.check_true(case_name & ": output " & integer'image(outc) &
				              " match (exp=" & integer'image(exp_val) &
				              ", act=" & integer'image(act_val) & ")",
				              act_val = exp_val);
				outc := outc + 1;
			end loop;
			sram_burst_stop;
			file_close(exp_f);
			report "  compared " & integer'image(outc) & " output(s)." severity note;
		end procedure;

	begin
		----- Reset NPU -----
		report "[NPU_CONV_TB] Starting NPU CONV1D testbench (NEGCTRL=" &
		       integer'image(NEGCTRL) & ")..." severity note;
		ResetN <= '0';
		wait for 1 us;
		wait until falling_edge(Clk);
		ResetN <= '1';
		MabSramPGEN <= '0';
		wait for 1 us;
		report "[NPU_CONV_TB] Reset complete." severity note;

		----------------------------------------------------------------
		-- G-BASE / G-DUP4 (X-collapse) / G-NEG.
		-- The FIRST thing this bench does after reset is run the base conv case, with no other CFG pokes ahead of it, and every output checked for definedness.
		-- That is D9 G-DUP4: it proves the added conv registers cannot produce X on the SRAM interface after a cold reset.
		-- When NEGCTRL=1 this same invocation also deliberately corrupts exactly one expected value (D9 G-NEG).
		----------------------------------------------------------------
		run_conv_case("base", corrupt_first => (NEGCTRL = 1), check_no_x => true);

		----------------------------------------------------------------
		-- NPUCFG1/NPUCFG2/offset-7/offsets-8-15 readback pokes (D3 contract)
		----------------------------------------------------------------
		report "[NPU_CONV_TB] === NPUCFG1/NPUCFG2/reserved-offset readback ===" severity note;
		-- Pattern: Cin-1=6, L=1234, D=9, S=5 (packed exactly as think_start does)
		mmr_write(MmrAddrNPUCFG1, std_logic_vector(to_unsigned(6, 8)) &
		                          std_logic_vector(to_unsigned(1234, 16)) &
		                          std_logic_vector(to_unsigned(9, 4)) &
		                          std_logic_vector(to_unsigned(5, 4)));
		mmr_read(MmrAddrNPUCFG1, rd);
		sb.check_slv("NPUCFG1 readback exact (full 32-bit write/read)", rd,
		             std_logic_vector(to_unsigned(6, 8)) &
		             std_logic_vector(to_unsigned(1234, 16)) &
		             std_logic_vector(to_unsigned(9, 4)) &
		             std_logic_vector(to_unsigned(5, 4)));

		mmr_write(MmrAddrNPUCFG2, x"ABCD1234");
		mmr_read(MmrAddrNPUCFG2, rd);
		sb.check_slv("NPUCFG2 readback (lower 16 stored, upper 16 read 0)", rd, x"00001234");

		mmr_write(MmrAddrNPUCFG3, x"FFFFFFFF");
		mmr_read(MmrAddrNPUCFG3, rd);
		sb.check_slv("offset 7 (NPUCFG3, no storage) reads 0", rd, x"00000000");

		mmr_write(8, x"FFFFFFFF");
		mmr_read(8, rd);
		sb.check_slv("offset 8 (reserved) reads 0", rd, x"00000000");

		mmr_write(15, x"FFFFFFFF");
		mmr_read(15, rd);
		sb.check_slv("offset 15 (reserved) reads 0", rd, x"00000000");

		----------------------------------------------------------------
		-- Remaining GROUPs (D9): ordinary file-driven cases.
		----------------------------------------------------------------
		run_conv_case("asym");
		run_conv_case("stride_s2");
		run_conv_case("stride_s4");
		run_conv_case("dil_d2");
		run_conv_case("dil_d4");
		run_conv_case("dil_d8");
		run_conv_case("stride_dil");
		run_conv_case("ben");

		-- G-AEN: ACTF=0 (sigmoid-legacy), then the P4.4 fallback poke with ACTF=1 reusing the SAME cfg/in/w data.
		-- ACTF=1 is now LIVE ReLU (the P4.4 inversion, npu_actf_design.md D10/A2), so the rerun compares against the aen_relu golden, NOT the case's own sigmoid exp file.
		-- The aen accumulators are mixed-sign, so ReLU differs from sigmoid on every negative one; see gen_conv_vectors.py's gen_aen_relu_exp.
		run_conv_case("aen");
		run_conv_case("aen", force_actf => 1, exp_file_name => "npu_conv_aen_relu_exp.txt");

		run_conv_case("sat");
		run_conv_case("multi");
		run_conv_case("degen_l1");
		run_conv_case("degen_l0");

		----- Final verdict (D9 G-NEG bipartite banner) -----
		wait for 1 us;
		report "[NPU_CONV_TB] All groups complete (" & integer'image(sb.errors) &
		       " check(s) failed)." severity note;

		-- Clean run: PASS demands a zero tally.
		if NEGCTRL = 0 then
			if sb.errors = 0 then
				report LF & LF &
					"    ##################################################" & LF &
					"    ##                                              ##" & LF &
					"    ##   NPU CONV TB:  ALL CHECKS PASSED             ##" & LF &
					"    ##                                              ##" & LF &
					"    ##################################################" & LF
					severity note;
			else
				report LF & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
					"    !!                                              !!" & LF &
					"    !!   NPU CONV TB FAIL: " & integer'image(sb.errors) &
					       " CHECK(S) FAILED" & LF &
					"    !!                                              !!" & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
					severity warning;
			end if;
		else
			-- Negative control: PASS demands exactly the one injected failure.
			if sb.errors = 1 then
				report LF & LF &
					"    ##################################################" & LF &
					"    ##                                              ##" & LF &
					"    ##   NPU CONV TB NEGCTRL-PASS (exactly 1 expected fail)" & LF &
					"    ##                                              ##" & LF &
					"    ##################################################" & LF
					severity note;
			else
				report LF & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF &
					"    !!                                              !!" & LF &
					"    !!   NPU CONV TB NEGCTRL-FAIL: expected EXACTLY 1 failure, got " &
					       integer'image(sb.errors) & LF &
					"    !!                                              !!" & LF &
					"    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" & LF
					severity warning;
			end if;
		end if;

		stop;
		wait;
	end process SIM_PROCESS;
end testbench;
