#!/usr/bin/env python3
"""VestaRV: the generated register headers compile and every macro in them is usable.

Writes a translation unit that includes castalia_regs.h and uses every object-like macro, then
compiles it freestanding at -Wall -Werror; function-like macros and non-expression bodies are
counted and printed rather than passed over. A second unit includes MemoryMap.h alongside, the
case firmware migrating one call site at a time is in. Compiler $RISCV_CC.
"""

import os
import re
import subprocess
import sys
import tempfile

_DEFINE = re.compile(r'^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)(\(|\s|$)(.*)$')


def _defaultRegsDir():
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.dirname(os.path.dirname(os.path.dirname(here)))
    return os.path.join(repo, 'software', 'include', 'regs')


def _findCompiler():
    cc = os.environ.get('RISCV_CC', 'riscv-none-elf-gcc')
    try:
        import shutil
        if os.path.isabs(cc):
            return cc if os.path.exists(cc) else None
        return shutil.which(cc)
    except Exception:
        return cc


def collectMacros(regsDir):
    """([usable names], skippedFunctionLike, skippedNonExpression)."""
    names = []
    seen = set()
    funcLike = 0
    noValue = 0
    for fileName in sorted(os.listdir(regsDir)):
        if not fileName.endswith('.h'):
            continue
        with open(os.path.join(regsDir, fileName)) as f:
            for line in f:
                m = _DEFINE.match(line)
                if m is None:
                    continue
                name, sep, body = m.group(1), m.group(2), m.group(3).strip()
                if sep == '(':
                    funcLike += 1
                    continue
                if name.endswith('_H') and not body:
                    continue        # include guard
                if not body:
                    noValue += 1
                    continue
                if name in seen:
                    continue
                seen.add(name)
                names.append(name)
    return names, funcLike, noValue


def translationUnit(names):
    """A TU that reads every macro. `(void)(NAME);` is the only form that takes
       an integer constant and a volatile struct pointer alike, and -Wall has
       nothing to say about either."""
    L = ['#include <stdint.h>',
         '#include "castalia_regs.h"',
         '',
         '/* Generated by check_regs_headers.py: one use of every object-like macro',
         '   the register headers define. */',
         'void vesta_regs_touch_every_macro(void);',
         'void vesta_regs_touch_every_macro(void)',
         '{']
    for n in names:
        L.append('    (void)(%s);' % n)
    L.append('}')
    return '\n'.join(L) + '\n'


def checkHeaders(regsDir):
    regsDir = os.path.abspath(regsDir)
    umbrella = os.path.join(regsDir, 'castalia_regs.h')
    if not os.path.isfile(umbrella):
        sys.stderr.write('check_regs_headers: not found: ' + umbrella + '\n')
        return 2

    cc = _findCompiler()
    if cc is None:
        sys.stderr.write('check_regs_headers: RISC-V C compiler not found '
                         '(set RISCV_CC)\n')
        return 2

    names, funcLike, noValue = collectMacros(regsDir)
    if not names:
        sys.stderr.write('check_regs_headers: no macros found in ' + regsDir + '\n')
        return 2

    tmp = tempfile.mkdtemp()
    src = os.path.join(tmp, 'regs_touch.c')
    with open(src, 'w') as f:
        f.write(translationUnit(names))
    cmd = [cc, '-march=rv32ima', '-mabi=ilp32', '-ffreestanding', '-std=c11',
           '-Wall', '-Wextra', '-Werror', '-fsyntax-only', '-I', regsDir, src]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    out = proc.communicate()[0].decode('utf-8', 'replace')
    if proc.returncode != 0:
        sys.stdout.write(out)
        sys.stderr.write('check_regs_headers: FAILED (%s)\n' % ' '.join(cmd[:1] + cmd[1:8]))
        return 1
    print('check_regs_headers: OK')
    print('  headers        %d' % len([f for f in os.listdir(regsDir) if f.endswith('.h')]))
    print('  macros touched %d' % len(names))
    print('  skipped        %d function-like, %d valueless' % (funcLike, noValue))
    print('  flags          -march=rv32ima -mabi=ilp32 -ffreestanding -std=c11 '
          '-Wall -Wextra -Werror')
    return 0


def _coincludeUnit():
    return ('#include <stdint.h>\n'
            '#include "MemoryMap.h"\n'
            '#include "castalia_regs.h"\n'
            '\n'
            '/* Generated by check_regs_headers.py: the generated register headers and the\n'
            '   generator\'s MemoryMap.h in one translation unit, which is what firmware\n'
            '   migrating one call site at a time compiles. */\n'
            'unsigned vesta_regs_coinclude(void);\n'
            'unsigned vesta_regs_coinclude(void)\n'
            '{\n'
            '    return (unsigned)(UART0_BASE_ADDR) + (unsigned)(UART0_BASE);\n'
            '}\n')


def checkCoInclude(regsDir, memoryMapH, cc):
    tmp = tempfile.mkdtemp()
    src = os.path.join(tmp, 'regs_coinclude.c')
    with open(src, 'w') as f:
        f.write(_coincludeUnit())
    # MemoryMap.h pulls in <bits.h> and <custom_ops.S>, which are SDK-side headers
    # the generator does not emit into out/. Empty shims, searched after the
    # header's own directory, exactly as check_memorymap_h.py does and for the
    # same reason: the header only names those macros inside unexpanded
    # object-like #defines.
    for shim in ('bits.h', 'custom_ops.S'):
        with open(os.path.join(tmp, shim), 'w') as f:
            f.write('/* check_regs_headers shim (empty) */\n')
    cmd = [cc, '-march=rv32ima', '-mabi=ilp32', '-ffreestanding', '-std=c11',
           '-Wall', '-Wextra', '-Werror', '-fsyntax-only',
           '-I', regsDir, '-I', os.path.dirname(os.path.abspath(memoryMapH)),
           '-I', tmp, src]
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    out = proc.communicate()[0].decode('utf-8', 'replace')
    if proc.returncode != 0:
        sys.stdout.write(out)
        sys.stderr.write('check_regs_headers: MemoryMap.h + castalia_regs.h do not '
                         'co-compile\n')
        return 1
    print('  co-include     MemoryMap.h + castalia_regs.h: OK')
    return 0


def main(argv):
    rest = list(argv[1:])
    memoryMapH = None
    for i, a in enumerate(rest):
        if a == '--memorymap-h' and i + 1 < len(rest):
            memoryMapH = rest[i + 1]
            del rest[i:i + 2]
            break
        if a.startswith('--memorymap-h='):
            memoryMapH = a.split('=', 1)[1]
            del rest[i]
            break
    args = [a for a in rest if not a.startswith('--')]
    regsDir = args[0] if args else _defaultRegsDir()
    rc = checkHeaders(regsDir)
    if rc == 0 and memoryMapH:
        cc = _findCompiler()
        rc = checkCoInclude(regsDir, memoryMapH, cc)
    return rc


if __name__ == '__main__':
    sys.exit(main(sys.argv))
