#!/usr/bin/env python3
"""VestaRV: the generated register packages carry exactly the constants the RTL declared by hand.

The .rdl-vs-decode and package-vs-emission gates now share a source, so neither can catch a
value that was wrong in the .rdl from the start. This is the independent copy, frozen: every
number was transcribed from the last revision in which the entities held their own offsets and
tables. A failure moves the frozen column only with a written-down register change.
"""

import json
import os
import re
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
REGS_VHDL = os.path.join(REPO, 'hdl', 'common', 'regs', 'vhdl')

# Reading the package. The TRACKED text is parsed, not the emitter re-run: the
# file the RTL compiles is the thing under test.

def _read(path):
    with open(path) as f:
        return f.read()


def _naturals(src):
    return dict((m.group(1), int(m.group(2)))
                for m in re.finditer(r'constant\s+(\w+)\s*:\s*natural\s*:=\s*(\d+);', src))


def _vectors(src):
    """{name: int} for every `constant NAME : std_logic_vector(...) := "..."|x"...";`"""
    out = {}
    for m in re.finditer(r'constant\s+(\w+)\s*:\s*std_logic_vector\([^)]*\)\s*:=\s*'
                         r'(?:x"([0-9A-Fa-f]+)"|"([01]+)");', src):
        out[m.group(1)] = int(m.group(2), 16) if m.group(2) else int(m.group(3), 2)
    return out


def _table(src, constName, arrayType, keyed):
    m = re.search(r'constant\s+' + constName + r'\s*:\s*' + arrayType + r'\s*:=\s*\((.*?)\);',
                  src, re.S)
    if m is None:
        raise Exception('no `constant %s : %s` aggregate' % (constName, arrayType))
    body = m.group(1)
    if keyed:
        return dict((k, int(v, 16)) for k, v in
                    re.findall(r'(\w+)\s*=>\s*x"([0-9A-Fa-f]+)"', body))
    return [int(v, 16) for v in re.findall(r'x"([0-9A-Fa-f]+)"', body)]



# THE OTHER TWENTY-TWO.
#
# The frozen tables are in rdl_legacy_constants.json, written ONCE by
# platform/common/python/rdl_legacy_snapshot.py before any of these blocks
# migrated: twenty-two hand-transcribed tables would not have been read by anyone.
#
# READ A FAILURE ACCORDING TO WHICH HALF FAILED. `decodeConstants` was read out
# of the RTL text (a local SLOT_*, the memory-map package's RegSlot*, NPU's
# MmrAddr*, irq_router's W_*) and is an independent copy of the decode.
# `registers` and `fields` were frozen from the emission at
# that point, after every .rdl had been graded against its decode: they are
# independent in TIME rather than in source, and what they catch is an .rdl edit
# that moved a register nobody meant to move.
#
# The snapshot is NEVER regenerated by a gate. A deliberate register change edits
# it in the same commit as the .rdl, and nothing else may.

LEGACY_JSON = os.path.join(HERE, 'rdl_legacy_constants.json')


def _legacy():
    with open(LEGACY_JSON) as f:
        return json.load(f)


class TestFrozenSnapshotIsPresent(unittest.TestCase):

    def test_every_block_has_a_tracked_package(self):
        blocks = _legacy()['blocks']
        self.assertEqual(len(blocks), 22,
                         'the snapshot must carry all twenty-two peripherals')
        for name, entry in sorted(blocks.items()):
            self.assertTrue(os.path.isfile(os.path.join(REGS_VHDL, name + '.vhd')),
                            name + '.vhd is not in hdl/common/regs/vhdl')
            self.assertTrue(os.path.isfile(os.path.join(REPO, entry['rtl'])),
                            entry['rtl'] + ' is not in the tree')


class LegacyBlockTest(unittest.TestCase):
    """Base class; one subclass per block is generated below so a failure names
       the peripheral instead of a dictionary key."""

    PACKAGE = None

    @classmethod
    def setUpClass(cls):
        if cls.PACKAGE is None:
            raise unittest.SkipTest('base class')
        cls.entry = _legacy()['blocks'][cls.PACKAGE]
        cls.src = _read(os.path.join(REGS_VHDL, cls.PACKAGE + '.vhd'))
        cls.nat = _naturals(cls.src)
        cls.vec = _vectors(cls.src)

    def test_decode_constants(self):
        """The word constants the decode names, as the RTL declared them before
           the migration. This is the leg that does not run through SystemRDL."""
        for ident, (want, where) in sorted(self.entry['decodeConstants'].items()):
            self.assertIn(ident, self.nat,
                          '%s does not emit %s, which %s decodes with'
                          % (self.PACKAGE, ident, self.entry['rtl']))
            self.assertEqual(self.nat[ident], want,
                             '%s: %s is %d, frozen at %d from %s'
                             % (self.PACKAGE, ident, self.nat[ident], want, where))

    def test_register_words_resets_and_masks(self):
        for name, row in sorted(self.entry['registers'].items()):
            for key, table in (('word', self.nat), ('addr', self.nat),
                               ('reset', self.vec), ('impl', self.vec)):
                want = row[key]
                const = name + '_' + key.upper()
                if want is None:
                    self.assertNotIn(const, table,
                                     '%s emits %s, which the frozen table does not carry; a '
                                     'configuration-dependent constant has become '
                                     'configuration-independent, or the reverse.'
                                     % (self.PACKAGE, const))
                    continue
                self.assertIn(const, table, '%s does not emit %s' % (self.PACKAGE, const))
                self.assertEqual(table[const], want,
                                 '%s: %s is 0x%X, frozen at 0x%X'
                                 % (self.PACKAGE, const, table[const], want))

    def test_field_ranges_and_resets(self):
        for name, row in sorted(self.entry['fields'].items()):
            self.assertIn(name + '_MSB', self.nat,
                          '%s does not emit %s' % (self.PACKAGE, name))
            self.assertEqual(self.nat[name + '_MSB'], row['msb'], name + '_MSB')
            self.assertEqual(self.nat[name + '_LSB'], row['lsb'], name + '_LSB')
            if row['reset'] is None:
                # The field carries its register's name, so the register's own
                # _RESET is the only one emitted; see rdl_vhdl._registerGroups.
                continue
            self.assertEqual(self.vec.get(name + '_RESET'), row['reset'], name + '_RESET')

    def test_no_field_appeared_or_vanished(self):
        emitted = set(k[:-4] for k in self.nat if k.endswith('_MSB'))
        self.assertEqual(sorted(emitted), sorted(self.entry['fields']),
                         '%s emits a different field set than was frozen' % self.PACKAGE)

    def test_no_register_appeared(self):
        emitted = set(k[:-5] for k in self.nat if k.endswith('_WORD'))
        frozen = set(n for n, row in self.entry['registers'].items() if row['word'] is not None)
        self.assertEqual(sorted(emitted), sorted(frozen),
                         '%s emits a different set of word offsets than was frozen'
                         % self.PACKAGE)


def _makeLegacyTests():
    for package in sorted(_legacy()['blocks']):
        name = 'Test' + ''.join(p.capitalize() for p in package.split('_')[:-2])
        globals()[name] = type(name, (LegacyBlockTest,), {'PACKAGE': package})


_makeLegacyTests()



if __name__ == '__main__':
    unittest.main()
