#!/usr/bin/env python3
"""rdl_cheader_regs.py -- the firmware-facing register headers, from the chip
addrmap, through STOCK PeakRDL-cheader.

    software/include/regs/<block>_regs.h   one per peripheral BLOCK: the field
                                           masks, shifts, widths and reset
                                           values, the enumerated values, and
                                           the packed struct overlay of the
                                           block's registers
    software/include/regs/castalia_regs.h  the umbrella: every block header, one
                                           base address and one typed pointer
                                           per INSTANCE, and the interrupt vector

    tools/bin/bazel run //platform/common/python:rdl_regs_headers

WHAT THIS IS NOT. It is not a replacement for MemoryMap.h, which the chip
generator emits and which R5 owns. MemoryMap.h is address-major -- one
<INST><REG>_ADDRESS per register, plus the <FIELD>_MASK/_LSB defines the
existing firmware is written against. These headers are type-major: a struct per
peripheral and a pointer per instance, which is what lets firmware write
    AFE0_REGS->AFExCR = ...
instead of computing an address. The two describe the same chip, and
//platform/common:regs_headers_vs_memorymap_test is the gate that says so: every
base and every register address in these headers equals MemoryMap.h's.

WHY THE BLOCK HEADERS ARE EXPORTED PER BLOCK AND NOT PER INSTANCE. A block's
field geometry is identical in every instance; only the base address and the two
per-instance reset generics (GPIO's RstValPx*, I2C's default_SAD) differ. The
reset macros PeakRDL emits are therefore the BLOCK's, and castalia_regs.h carries
the per-instance overrides as <INST><REG>_RESET where the top addrmap assigns
one. Exporting per instance would multiply 359 registers by 34 instances for two
peripherals' worth of difference.

STOCK EXPORTER, ONE ADDITION. PeakRDL-cheader does not emit SystemRDL `encode`
members, so the enumerated values -- TIMER's DIV_1..DIV_32768, SPI's SPIDL_*,
AFE2's A_Dac_Vp select -- would be lost. They are appended by _enumLines() under
a banner that says they are this repo's addition, in the exporter's own
<REGTYPE>__<FIELD>__<MEMBER> spelling. Everything else in those files is stock
output and is not touched.
"""

import argparse
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import rdl_chip
import rdl_emit
import rdl_model

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT_REL = os.path.join('software', 'include', 'regs')
UMBRELLA = 'castalia_regs.h'

# Blocks that are real peripherals but cannot appear in the top addrmap.
# BIASG overlays words 9-13 of AFE2 SITE 0's sub-slot and SystemRDL has no way
# to say that two addrmaps share one address range (R2 section 1.6), so the top
# addrmap instantiates afe2_site there and biasg.rdl stands alone. Firmware
# still needs it: MemoryMap.h publishes AFE0BIASG0..CR at 0x6C24-0x6C34, and in
# the per-tile topology that is the only way to trim the shared bias generator.
# Its addrmap is BASED at the host's base -- its registers are declared at their
# absolute byte offsets inside the sub-slot -- so the pointer is the host's.
_OVERLAYS = (
    {'key': 'AFExBIASG', 'host': 'AFE0', 'inst': 'AFE0BIASG'},
)

BANNER = (
    '/* GENERATED by platform/common/python/rdl_cheader_regs.py from\n'
    '   hdl/common/periph/rdl/. DO NOT EDIT.\n'
    '\n'
    '     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers\n'
    '     gates:       //platform/common:regs_headers_identity_test   tracked == generated\n'
    '                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro\n'
    '                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses\n'
    '                                                                 equal MemoryMap.h\'s */\n')


def _blockFileStem(flag):
    """gpio.rdl -> gpio, pwr_ctrl.rdl -> pwr_ctrl. The .rdl name, so a header and
       the RTL it describes are one grep apart."""
    return os.path.splitext(os.path.basename(flag['source']))[0]


def _regTypeMacro(regNode):
    """PeakRDL-cheader's macro stem for a register: the TYPE name, uppercased."""
    return (regNode.type_name or regNode.inst_name).upper()


def _enumLines(root):
    """The `encode` members PeakRDL-cheader drops, in its own spelling."""
    lines = []
    for reg in root.registers():
        stem = _regTypeMacro(reg)
        rows = []
        for field in reg.fields():
            enc = field.get_property('encode')
            if enc is None:
                continue
            for member in enc:
                name = member.name
                # `AFESWAPEN_A_DAC_VP_VP` on field `AFESWAPEN` -> `A_DAC_VP_VP`
                if name.startswith(field.inst_name + '_'):
                    name = name[len(field.inst_name) + 1:]
                rows.append(('%s__%s__%s' % (stem, field.inst_name, name),
                             int(member.value),
                             (member.rdl_desc or '').strip()))
        if rows:
            lines.append('// enum - ' + (reg.type_name or reg.inst_name))
            for name, value, desc in rows:
                lines.append('#define %s 0x%x%s'
                             % (name, value, ('   // ' + desc) if desc else ''))
            lines.append('')
    return lines


def _splice(text, extra, banner):
    """Put `extra` inside the extern "C" block, and `banner` at the top.

    The anchor is the CLOSING `#ifdef __cplusplus`, the one that shuts the
    extern "C" the exporter opens, so the addition sits with the rest of the
    header's content and not after it."""
    if extra:
        at = text.rfind('#ifdef __cplusplus')
        if at < 0:
            at = text.rfind('#endif')
        text = text[:at] + '\n'.join(extra) + '\n' + text[at:]
    return banner + text


def emitBlockHeader(flag, outPath):
    from peakrdl_cheader.exporter import CHeaderExporter
    from systemrdl import RDLCompiler
    rdlc = RDLCompiler()
    rdlc.compile_file(os.path.join(rdl_model.RDL_DIR, flag['source']),
                      incl_search_paths=[rdl_model.RDL_DIR])
    root = rdlc.elaborate(top_def_name=flag['top']).top
    with tempfile.TemporaryDirectory() as tmp:
        # The exporter derives its include guard from the file NAME, so it is
        # written under the name it will be tracked as.
        tmpOut = os.path.join(tmp, os.path.basename(outPath))
        CHeaderExporter().export(root, tmpOut, instantiate=False)
        with open(tmpOut) as f:
            text = f.read()
    return _splice(text, _enumLines(root), BANNER)


def _fmthex(v):
    return '0x%Xu' % v


def emitUmbrella(binding, headers, over=()):
    """castalia_regs.h: every block header, then one base, one typed pointer and
       one vector per instance."""
    L = [BANNER.rstrip('\n'), '',
         '#ifndef CASTALIA_REGS_H', '#define CASTALIA_REGS_H', '',
         '#include <stdint.h>', '']
    for h in headers:
        L.append('#include "%s"' % h)
    L += ['',
          '/* Peripheral base addresses. These are the CPU byte addresses of the shared',
          '   peripheral window, the same numbers MemoryMap.h publishes as <INST>_BASE;',
          '   the name differs so the two headers can be included together and',
          '   //platform/common:regs_headers_vs_memorymap_test can compare them. */']
    for (instName, base, flag, block, idx) in binding:
        L.append('#define %-22s %s' % (instName + '_BASE_ADDR', _fmthex(base)))
    L += ['',
          '/* One typed pointer per instance. `AFE0_REGS->AFExCR = v;` writes site 0\'s',
          '   control register; the struct is the block\'s, so the member names carry the',
          '   template spelling (AFExCR, not AFE0CR) and the instance is in the pointer. */']
    for (instName, base, flag, block, idx) in binding:
        typ = flag['top'] + '_t'
        L.append('#define %-22s ((volatile %s *) %s)'
                 % (instName + '_REGS', typ, instName + '_BASE_ADDR'))
    if over:
        L += ['',
              '/* OVERLAY BLOCKS: real registers that the top addrmap cannot carry, because',
              '   SystemRDL has no way to say two addrmaps share one address range. Each one',
              '   sits inside a host peripheral\'s sub-slot at its own word offsets, so its',
              '   struct is based at the HOST\'s base address. */']
        byInst = dict((n, b) for (n, b, _f, _bl, _i) in binding)
        for (entry, flag, block) in over:
            host = entry['host']
            typ = flag['top'] + '_t'
            L.append('#define %-22s %s   /* overlaid on %s */'
                     % (entry['inst'] + '_BASE_ADDR', _fmthex(byInst[host]), host))
            L.append('#define %-22s ((volatile %s *) %s)'
                     % (entry['inst'] + '_REGS', typ, entry['inst'] + '_BASE_ADDR'))
    vectors = [(n, b.Vector) for (n, _base, _f, b, _i) in binding if b.Vector is not None]
    if vectors:
        L += ['',
              '/* The interrupt vector each instance owns, from the top addrmap. A block with',
              '   no vector (PWRCTRL, MUTEX, EVFAB, IRQROUTER) has no define here. The four',
              '   AFE sites SHARE vector 124 and demultiplex it through their own SR. */']
        for name, vec in vectors:
            L.append('#define %-22s %d' % (name + '_IRQ_VECTOR', vec))
    overrides = []
    templates = {}
    for (instName, base, flag, block, idx) in binding:
        if flag['source'] not in templates:
            templates[flag['source']] = rdl_model.loadBlock(flag['source'], flag['top'])
        tmpl = templates[flag['source']]
        byName = dict((rt.NameTemplate, rt) for rt in tmpl.RegisterTemplates)
        for rt in block.RegisterTemplates:
            ref = byName.get(rt.NameTemplate)
            if ref is None or ref.ResetValue == rt.ResetValue:
                continue
            name = rdl_chip.instanceRegisterName(rt.NameTemplate, flag.get('registerPrefix'), idx)
            overrides.append((name + '_RESET', rt.ResetValue))
    if overrides:
        L += ['',
              '/* PER-INSTANCE RESET VALUES. These registers reset differently in different',
              '   instances because the RTL takes the value as a GENERIC (GPIO\'s RstValPx*,',
              '   I2C\'s default_SAD), so the block header\'s <REG>_reset macro -- which is the',
              '   template\'s -- is WRONG for them. Use these. */']
        for name, value in overrides:
            L.append('#define %-22s %s' % (name, _fmthex(value)))
    L += ['', '#endif /* CASTALIA_REGS_H */', '']
    return '\n'.join(L)


def overlays(configPath):
    """[(entry, flag, block)] for the blocks _OVERLAYS names."""
    flags = dict((f['name'], f) for f in rdl_emit.loadFlags(configPath))
    out = []
    for entry in _OVERLAYS:
        flag = flags.get(entry['key'])
        if flag is None:
            continue
        out.append((entry, flag, rdl_model.loadBlock(flag['source'], flag['top'])))
    return out


def emitAll(topPath=None, configPath=None):
    """{relative path: text} for every generated header."""
    topPath = topPath or rdl_chip.DEFAULT_TOP
    configPath = configPath or rdl_emit.DEFAULT_CONFIG
    binding = rdl_chip.bind(topPath, configPath)
    over = overlays(configPath)
    out = {}
    headers = []
    seen = set()
    for (instName, base, flag, block, idx) in binding:
        stem = _blockFileStem(flag)
        if stem in seen:
            continue
        seen.add(stem)
        name = stem + '_regs.h'
        headers.append(name)
        out[os.path.join(OUT_REL, name)] = emitBlockHeader(flag, name)
    for (entry, flag, block) in over:
        stem = _blockFileStem(flag)
        if stem in seen:
            continue
        seen.add(stem)
        name = stem + '_regs.h'
        headers.append(name)
        out[os.path.join(OUT_REL, name)] = emitBlockHeader(flag, name)
    out[os.path.join(OUT_REL, UMBRELLA)] = emitUmbrella(binding, sorted(headers), over)
    return out


def writeAll(root, **kw):
    written = []
    for rel, text in sorted(emitAll(**kw).items()):
        path = os.path.join(root, rel)
        d = os.path.dirname(path)
        if not os.path.isdir(d):
            os.makedirs(d)
        with open(path, 'w') as f:
            f.write(text)
        written.append(rel)
    return written


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out', default=None, help='repository root to write into')
    ap.add_argument('--top', default=None)
    ap.add_argument('--config', default=None)
    args = ap.parse_args(argv)
    root = args.out or os.environ.get('BUILD_WORKSPACE_DIRECTORY') or REPO
    for rel in writeAll(root, topPath=args.top, configPath=args.config):
        print('[rdl_regs] ' + rel)
    return 0


if __name__ == '__main__':
    sys.exit(main())
