# VestaRV: the multi-hart testbench emitter.
# Generates out/hdl/riscv_tb.vhd from hdl_templates/riscv_tb.template.vhd on mcu_vhd.py's
# region-marker model, regenerating the numHarts-dependent --@GEN:<name>@ regions. At
# numHarts=4 every emitter reproduces the golden master byte-identically. The MCU keeps
# distinct a0_1..a0_(N-1) ports rather than a flattened bus, so the component declaration and
# port map must list them by name, which is why the testbench is generated at large N.
import re

REGION_NAMES = [
    'tb-a0-component-ports',
    'tb-a0-signals',
    # OVERLAY: two generic extension markers -- extra signal
    # declarations and extra models in the architecture body. Both emit nothing
    # with no overlay, so the file is unchanged and check_riscv_tb_vhd.py still
    # grades the golden master.
    'tb-overlay-signals',
    'tb-hart-passfail-signals',
    'tb-a0-portmap',
    'tb-overlay-models',
    'tb-hart-report',
    'tb-monitor-reset',
    'tb-monitor-edge',
]


def _header(nHarts):
    return [
        '-- VestaRV: ISA-regression testbench, ' + str(nHarts)
            + (' hart' if nHarts == 1 else ' harts'),
        ('-- Hart 0 is the pass/fail gate; there are no tile monitors.'
            if nHarts == 1 else
            '-- Hart 0 is the pass/fail gate; harts 1..' + str(nHarts - 1)
            + ' are watched through tile monitors a0_1..a0_' + str(nHarts - 1) + '.'),
        '-- Generated by platform/common (make chip / tb_vhd.py) from platform/common/hdl_templates/riscv_tb.template.vhd.',
        '-- Do not edit; change the template or python/tb_vhd.py and regenerate.',
        '',
    ]


class TbVhdEmitter():
    # SINGLE HART IS ALLOWED (asic_default). The floor was 2 because
    # every region below iterates harts 1..N-1 and N = 1 produced empty joins
    # ("if  then", "signal  : boolean") rather than an error.
    # Each region now folds away at N = 1, and the two regions that follow a
    # separator-carrying line -- the component port list and the DUT port map --
    # own that line so the separator can follow the hart count.
    # OVERLAY: `geo` is the SAME McuMpGeometry dict mcu_vhd.py
    # reads, so whatever an overlay put on the entity it also declares and
    # associates here -- entity and testbench cannot disagree about the port
    # list. Default {} => every overlay entry point below is inert.
    def __init__(self, nHarts, geo=None):
        if nHarts < 1:
            raise Exception('tb_vhd: numHarts must be >= 1 (got ' + str(nHarts) + ')')
        self.n = nHarts
        import overlay as _ovl
        self.overlay = _ovl
        _ovl.call('tbInit', emitter=self, geo=dict(geo or {}))

    def emitRegion(self, name):
        if name == 'tb-a0-component-ports':    return self.emitComponentPorts()
        if name == 'tb-a0-signals':            return self.emitA0Signals()
        if name.startswith('tb-overlay-'):     return self.overlay.lines('tbRegion', emitter=self, region=name)
        if name == 'tb-hart-passfail-signals': return self.emitPassFailSignals()
        if name == 'tb-a0-portmap':            return self.emitPortMap()
        if name == 'tb-hart-report':           return self.emitReport()
        if name == 'tb-monitor-reset':         return self.emitMonitorReset()
        if name == 'tb-monitor-edge':          return self.emitMonitorEdge()
        raise Exception('tb_vhd: unknown region "' + name + '"')

    # -- component ports: hart 0's a0, then a0_1..a0_(N-1); last has no ';'
    # The hart-0 port line moved in here from the template so that its trailing
    # semicolon can depend on whether any a0_h follows it. Emitted character for
    # character as the template carried it, so N >= 2 is unchanged.
    def emitComponentPorts(self):
        n = self.n
        extra = self.overlay.lines('tbPorts', emitter=self, indent=12, decl=True)
        lines = [' ' * 12 + '-- Test Port',
                 ' ' * 12 + 'a0  : out std_logic_vector(31 downto 0)'
                 + (';' if (n > 1 or extra) else '')]
        if n > 1:
            lines.append('')
            lines.append(' ' * 12 + '-- Per-hart pass/fail observation (a0 of the '
                         + str(n - 1) + ' private-memory harts)')
            for h in range(1, n):
                term = ';' if (h != n - 1 or extra) else ''
                lines.append(' ' * 12 + 'a0_' + str(h) + ' : out std_logic_vector(31 downto 0)' + term)
        lines.extend(extra)
        return lines

    # -- signal decl: signal a0_1, a0_2, ... : std_logic_vector(31 downto 0); ---
    def emitA0Signals(self):
        n = self.n
        if n == 1:
            return []
        names = ', '.join('a0_' + str(h) for h in range(1, n))
        return [
            ' ' * 4 + '-- a0 of the ' + str(n - 1) + ' private-memory harts',
            ' ' * 4 + 'signal ' + names + ' : std_logic_vector(31 downto 0);',
        ]

    # -- latched per-tile pass/fail booleans
    def emitPassFailSignals(self):
        n = self.n
        if n == 1:
            return []
        passn = ', '.join('h' + str(h) + '_pass' for h in range(1, n))
        failn = ', '.join('h' + str(h) + '_fail' for h in range(1, n))
        return [
            ' ' * 4 + '-- Latched pass/fail for private-memory harts 1-' + str(n - 1),
            ' ' * 4 + 'signal ' + passn + ' : boolean := false;',
            ' ' * 4 + 'signal ' + failn + ' : boolean := false;',
        ]

    # -- DUT port map: hart 0's a0, then a0_h => a0_h; last has no ','
    # As with the component ports, the hart-0 association line moved in here so
    # its trailing comma can follow the hart count.
    def emitPortMap(self):
        n = self.n
        extra = self.overlay.lines('tbPorts', emitter=self, indent=8, decl=False)
        lines = [' ' * 8 + '-- Test Port',
                 ' ' * 8 + 'a0          => a0' + (',' if (n > 1 or extra) else '')]
        if n > 1:
            lines.append('')
            lines.append(' ' * 8 + '-- Private-memory harts 1-' + str(n - 1))
            for h in range(1, n):
                term = ',' if (h != n - 1 or extra) else ''
                lines.append(' ' * 8 + ('a0_' + str(h)).ljust(12) + '=> a0_' + str(h) + term)
        lines.extend(extra)
        return lines

    # -- end-of-test report + fail/parked/pass verdict over all tiles
    def emitReport(self):
        n = self.n
        if n == 1:
            # No tile harts to report on: hart 0 is the whole chip and its own
            # verdict is printed by the lines that follow this region.
            return [' ' * 8 + '-- No tile harts in this configuration (hart 0 is the only hart).']
        lines = []
        for h in range(1, n):
            lines.append(' ' * 8 + 'report "HART' + str(h) + ' (tile) pass=" & boolean\'image(h'
                         + str(h) + '_pass) &')
            lines.append(' ' * 15 + '" fail=" & boolean\'image(h' + str(h) + '_fail) severity note;')
        failOr = ' or '.join('h' + str(h) + '_fail' for h in range(1, n))
        passAnd = ' and '.join('h' + str(h) + '_pass' for h in range(1, n))
        lines.append(' ' * 8 + 'if ' + failOr + ' then')
        lines.append(' ' * 12 + 'report "M12: a tile hart FAILED" severity failure;')
        lines.append(' ' * 8 + 'elsif not (' + passAnd + ') then')
        lines.append(' ' * 12 + 'report "M12 NOTE: tile hart(s) silent/parked (expected for single-hart tests)"')
        lines.append(' ' * 16 + 'severity note;')
        lines.append(' ' * 8 + 'else')
        lines.append(' ' * 12 + 'report "M12: all ' + str(n - 1)
                     + ' tile harts PASSED (concurrent w/ hart 0)" severity note;')
        lines.append(' ' * 8 + 'end if;')
        return lines

    # -- monitor_harts reset region
    def emitMonitorReset(self):
        n = self.n
        if n == 1:
            return [' ' * 12 + 'null;']
        passx = ' '.join('h' + str(h) + '_pass <= false;' for h in range(1, n))
        failx = ' '.join('h' + str(h) + '_fail <= false;' for h in range(1, n))
        return [' ' * 12 + passx, ' ' * 12 + failx]

    # -- monitor_harts rising-edge region
    def emitMonitorEdge(self):
        n = self.n
        if n == 1:
            return [' ' * 12 + 'null;']
        lines = []
        for h in range(1, n):
            lines.append(' ' * 12 + 'if a0_' + str(h) + ' = PASS_LABEL then h'
                         + str(h) + '_pass <= true; end if;')
        for h in range(1, n):
            lines.append(' ' * 12 + 'if a0_' + str(h) + ' = FAIL_LABEL then h'
                         + str(h) + '_fail <= true; end if;')
        return lines


def generateRiscvTbVhd(nHarts, templatePath, outPath, withHeader=True, geo=None):
    emitter = TbVhdEmitter(nHarts, geo)
    with open(templatePath, 'r', newline='') as f:
        templateLines = f.read().split('\n')
    out = list(_header(nHarts)) if withHeader else []
    marker = re.compile(r'^\s*--@GEN:([A-Za-z0-9:_-]+)@\s*$')
    seen = set()
    for line in templateLines:
        m = marker.match(line)
        if m is None:
            out.append(line)
            continue
        name = m.group(1)
        if name in seen:
            raise Exception('tb_vhd: duplicate region marker "' + name + '" in template')
        seen.add(name)
        out.extend(emitter.emitRegion(name))
    expected = set(REGION_NAMES)
    if seen != expected:
        raise Exception('tb_vhd: marker set mismatch. missing=' + str(expected - seen)
                        + ' extra=' + str(seen - expected))
    with open(outPath, 'w', newline='\n') as f:
        f.write('\n'.join(out))


if __name__ == '__main__':
    import sys, os
    here = os.path.dirname(os.path.abspath(__file__))
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    tpl = sys.argv[2] if len(sys.argv) > 2 else here + '/../hdl_templates/riscv_tb.template.vhd'
    outp = sys.argv[3] if len(sys.argv) > 3 else here + '/../out/hdl/riscv_tb.vhd'
    generateRiscvTbVhd(n, tpl, outp)
    print('tb_vhd: wrote ' + outp + ' (numHarts=' + str(n) + ')')
