#!/usr/bin/env python3
# =============================================================================
# zfinx_convert.py  --  X4 Stage 2c: mechanical rv32uf -> Zfinx conversion.
#
# Zfinx runs the F operation set on the X (integer) register file: there is NO
# separate f-register file, so
#     * flw/fsw            -> (do not exist; operands are already in x-regs)
#     * fmv.w.x / fmv.x.w  -> (do not exist; a plain `mv` / nothing)
#     * every  fXXX.s fD,fA,fB   becomes   fXXX.s xD,xA,xB
#
# GAS FINDING (recorded in the self-report): the repo toolchain
#   riscv-none-elf-gcc (xPack) 13.2.0
# accepts EVERY single-precision mnemonic with x-register operands under an
# arch string that carries `_zfinx` (e.g. -march=rv32imc_zfinx). Verified:
#   fadd.s a0,a1,a2   ->  0x00c5f553   (identical encoding to the F form)
#   fmadd.s / rounding-mode suffixes / csrr fflags|frm|fcsr all assemble.
# Therefore NO `.insn` fallback is needed -- the converted suite is emitted with
# ordinary Zfinx mnemonics and built with `-march=rv32imc_zfinx -mabi=ilp32`.
# (flw/fsw/fmv.w.x correctly REQUIRE `f` and are rejected under pure _zfinx --
#  that is why they are removed by the conversion, not just re-spelled.)
#
# HOW THE CONVERSION IS DONE (deterministic, no hand edits):
# The upstream rv32uf tests are thin shims that `#include "../rv64uf/<t>.S"`,
# and the real bodies are pure invocations of the TEST_FP_* macros from
# macros/scalar/test_macros.h (only fcvt_w has a few inline flw/fcvt).  So the
# mechanical conversion has two mechanical parts:
#   1. A converted macro header `test_macros_zfinx.h` (emitted below) that
#      #includes the stock test_macros.h and then #undef/#redefines ONLY the
#      floating-point TEST_FP_* macros so they load operands with `lw` into
#      fixed x-registers, run the op on x-registers (Zfinx), and read the
#      result with `mv` and fflags with an explicit csrrw.  The data sections
#      (.float/.result) are emitted byte-for-byte as upstream.
#   2. Per-test copies of the rv64uf bodies with three textual rewrites:
#         #include "test_macros.h"  -> #include "test_macros_zfinx.h"
#         RVTEST_RV64UF             -> RVTEST_RV32U   (init macro is never
#                                      invoked; RV32U avoids the dead FP-enable)
#         inline `flw f1,off(rs)` / `fcvt.*.s xD,f1` -> lw/fcvt on x-reg t3
#
# Re-running this script reproduces the committed suite byte-for-byte
# (convert-then-diff is clean).  HAND EDITS OF THE OUTPUT ARE FORBIDDEN.
#
# Usage:   python3 verification/isa/tools/zfinx_convert.py [--check]
#   (no args) : (re)generate tests/rv32uzf/*.S + test_macros_zfinx.h
#   --check   : regenerate into a temp area and diff against the committed
#               suite; non-zero exit if they differ (CI determinism gate).
# =============================================================================
import os, re, sys, difflib, tempfile

HERE      = os.path.dirname(os.path.abspath(__file__))
TESTS_DIR = os.path.normpath(os.path.join(HERE, "..", "tests"))
SRC_DIR   = os.path.join(TESTS_DIR, "rv64uf")
OUT_DIR   = os.path.join(TESTS_DIR, "rv32uzf")

# Upstream rv32uf suite = these 11 tests. We convert 8 and EXCLUDE 3 (each an
# accepted-deviation candidate flagged in the self-report):
#   ldst     -- pure flw/fsw load-store; Zfinx has no FP load/store (loads are
#               plain lw already covered by rv32ui). Nothing left to test.
#   move     -- fmv.w.x / fmv.x.w moves that DO NOT EXIST in Zfinx (operands
#               are already integer). The fsgnj* part is preserved instead as a
#               directed vector (gen_directed: dsgnj).
#   recoding -- exercises the internal NaN-boxing recoded representation, which
#               Zfinx explicitly does NOT have (RV32 single fills the register,
#               no boxing). Architecturally N/A.
CONVERT = ["fadd", "fdiv", "fclass", "fcmp", "fcvt", "fcvt_w", "fmadd", "fmin"]
EXCLUDE = {"ldst": "pure FP load/store; Zfinx loads are plain lw (rv32ui covers)",
           "move": "fmv.w.x/fmv.x.w do not exist in Zfinx; fsgnj kept as directed vector",
           "recoding": "tests NaN-boxing recoding; Zfinx has no NaN-boxing (N/A)"}

# --- the Zfinx-converted macro header -------------------------------------
# Fixed collision-free operand x-registers (none overlaps the harness's
# a0..a3 / gp / t1 / t2 / x7):  s2=op1  s3=op2  s4=op3(fma)  s5=result.
MACRO_HEADER = r'''// =====================================================================
// test_macros_zfinx.h  --  GENERATED by verification/isa/tools/zfinx_convert.py
// DO NOT HAND EDIT.  Zfinx (F-in-X) overrides of the floating-point test
// macros: operands live in x-registers, so flw->lw, fmv.x.s->mv, and every
// fXXX.s runs on x-registers.  Operand register assignment (collision-free
// with the harness's a0..a3/gp/t1/t2/x7):
//     s2 = operand 1 (was f10)   s3 = operand 2 (was f11)
//     s4 = operand 3 (was f12)   s5 = result    (was f13)
// The data sections (.float / .result) are emitted exactly as upstream.
// =====================================================================
#ifndef __TEST_MACROS_ZFINX_H
#define __TEST_MACROS_ZFINX_H

#include "test_macros.h"

// ---- single-precision harness (loads operands into x-regs) ----------
#undef TEST_FP_OP_S_INTERNAL
#define TEST_FP_OP_S_INTERNAL( testnum, flags, result, val1, val2, val3, code... ) \
test_ ## testnum: \
  li  TESTNUM, testnum; \
  la  a0, test_ ## testnum ## _data ;\
  lw  s2, 0(a0); \
  lw  s3, 4(a0); \
  lw  s4, 8(a0); \
  lw  a3, 12(a0); \
  code; \
  csrrw a1, fflags, x0; \
  li a2, flags; \
  bne a0, a3, fail; \
  bne a1, a2, fail; \
  .pushsection .data; \
  .align 2; \
  test_ ## testnum ## _data: \
  .float val1; \
  .float val2; \
  .float val3; \
  .result; \
  .popsection

// ---- op wrappers: run on x-regs, result read with `mv` --------------
#undef TEST_FP_OP1_S
#define TEST_FP_OP1_S( testnum, inst, flags, result, val1 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, float result, val1, 0.0, 0.0, \
                    inst s5, s2; mv a0, s5)

#undef TEST_FP_OP1_S_DWORD_RESULT
#define TEST_FP_OP1_S_DWORD_RESULT( testnum, inst, flags, result, val1 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, dword result, val1, 0.0, 0.0, \
                    inst s5, s2; mv a0, s5)

#undef TEST_FP_OP2_S
#define TEST_FP_OP2_S( testnum, inst, flags, result, val1, val2 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, float result, val1, val2, 0.0, \
                    inst s5, s2, s3; mv a0, s5)

#undef TEST_FP_OP3_S
#define TEST_FP_OP3_S( testnum, inst, flags, result, val1, val2, val3 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, float result, val1, val2, val3, \
                    inst s5, s2, s3, s4; mv a0, s5)

// ---- compares: integer result straight into a0 ---------------------
#undef TEST_FP_CMP_OP_S
#define TEST_FP_CMP_OP_S( testnum, inst, flags, result, val1, val2 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, word result, val1, val2, 0.0, \
                    inst a0, s2, s3)

// ---- float -> int convert (result integer in a0) -------------------
#undef TEST_FP_INT_OP_S
#define TEST_FP_INT_OP_S( testnum, inst, flags, result, val1, rm ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, word result, val1, 0.0, 0.0, \
                    inst a0, s2, rm)

// ---- int -> float convert (own body; no f-reg move) ----------------
#undef TEST_INT_FP_OP_S
#define TEST_INT_FP_OP_S( testnum, inst, result, val1 ) \
test_ ## testnum: \
  li  TESTNUM, testnum; \
  la  a0, test_ ## testnum ## _data ;\
  lw  a3, 0(a0); \
  li  a0, val1; \
  inst s5, a0; \
  csrrw x0, fflags, x0; \
  mv a0, s5; \
  bne a0, a3, fail; \
  .pushsection .data; \
  .align 2; \
  test_ ## testnum ## _data: \
  .float result; \
  .popsection

// ---- fclass: input in x-reg, no fmv needed -------------------------
#undef TEST_FCLASS_S
#define TEST_FCLASS_S(testnum, correct, input) \
  TEST_CASE(testnum, a0, correct, li s2, input; fclass.s a0, s2)

#endif // __TEST_MACROS_ZFINX_H
'''

# Inline-FP rewrites (only fcvt_w needs them: `flw f1` + `fcvt.*.s xD,f1`).
# f1 -> t3 (x28), a caller-saved temp unused by the harness.
def rewrite_inline_fp(text):
    # flw f1, off(reg)  ->  lw t3, off(reg)
    text = re.sub(r'\bflw\s+f1\s*,', 'lw t3,', text)
    # fcvt.{w,wu,l,lu}.s  xD, f1  ->  ... xD, t3
    text = re.sub(r'(\bfcvt\.(?:w|wu|l|lu)\.s\s+\w+\s*,\s*)f1\b', r'\1t3', text)
    return text

HDR = ("# GENERATED by verification/isa/tools/zfinx_convert.py from "
       "tests/rv64uf/{name}.S -- DO NOT HAND EDIT.\n"
       "# Zfinx conversion: f-registers -> x-registers, flw/fsw removed, "
       "fmv.* -> mv (see the script header).\n")

def convert_one(name):
    with open(os.path.join(SRC_DIR, name + ".S")) as f:
        body = f.read()
    body = body.replace('#include "test_macros.h"',
                        '#include "test_macros_zfinx.h"')
    # RVTEST_RV64UF token -> RVTEST_RV32U (whole-word)
    body = re.sub(r'\bRVTEST_RV64UF\b', 'RVTEST_RV32U', body)
    body = rewrite_inline_fp(body)
    return HDR.format(name=name) + body

def emit(outdir):
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "test_macros_zfinx.h"), "w") as f:
        f.write(MACRO_HEADER)
    for name in CONVERT:
        with open(os.path.join(outdir, name + ".S"), "w") as f:
            f.write(convert_one(name))

def main():
    check = "--check" in sys.argv[1:]
    if not check:
        emit(OUT_DIR)
        print("zfinx_convert: wrote test_macros_zfinx.h + %d tests to %s"
              % (len(CONVERT), OUT_DIR))
        print("  converted: " + " ".join(CONVERT))
        print("  excluded : " + ", ".join("%s (%s)" % (k, v)
                                           for k, v in EXCLUDE.items()))
        return 0
    # determinism gate
    tmp = tempfile.mkdtemp()
    emit(tmp)
    rc = 0
    for fn in ["test_macros_zfinx.h"] + [n + ".S" for n in CONVERT]:
        a = os.path.join(OUT_DIR, fn); b = os.path.join(tmp, fn)
        ta = open(a).read() if os.path.exists(a) else ""
        tb = open(b).read()
        if ta != tb:
            rc = 1
            sys.stderr.write("DIFF in %s\n" % fn)
            for line in difflib.unified_diff(ta.splitlines(), tb.splitlines(),
                                             a, b, lineterm=""):
                sys.stderr.write(line + "\n")
    print("zfinx_convert --check: %s" % ("CLEAN" if rc == 0 else "DIFFERENCES"))
    return rc

if __name__ == "__main__":
    sys.exit(main())
