-- =============================================================================
-- i3c_regs_pkg.vhd: GENERATED from hdl/common/periph/rdl/ by
-- platform/common/python/rdl_vhdl.py. DO NOT EDIT THIS FILE.
--
--   regenerate:  tools/bin/bazel run //platform/common/python:rdl_vhdl_pkgs
--   gates:       //platform/common:rdl_vhdl_pkg_test    tracked == regenerated
--                //platform/common:rdl_pkg_vs_legacy_test  == the hand-written
--                                                       constants it replaced
--                //platform/common:rdl_vs_vhdl_i3c_test
--
-- I3C controller (MIPI I3C basic, single-controller)
--
-- <REG>_WORD is the word offset inside the peripheral sub-slot, <REG>_ADDR the
-- byte offset, <REG>_RESET the reset word and <REG>_IMPL the mask of bits that
-- hold a software-written flop (hardware-owned status and single-pulse strobes
-- are excluded, which is the same rule the hand-written IMPL tables use).
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;

package i3c_regs_pkg is

    -- I3CxCR: I3C control register
    constant I3CxCR_WORD              : natural := 0;
    constant I3CxCR_ADDR              : natural := 0;
    constant I3CxCR_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000000000000100";
    constant I3CxCR_IMPL              : std_logic_vector(31 downto 0) := "00111111111111111111111100001111";
    constant I3CTXEIE_MSB             : natural := 29;
    constant I3CTXEIE_LSB             : natural := 29;
    constant I3CTXEIE_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CRXFIE_MSB             : natural := 28;
    constant I3CRXFIE_LSB             : natural := 28;
    constant I3CRXFIE_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CIBIIE_MSB             : natural := 27;
    constant I3CIBIIE_LSB             : natural := 27;
    constant I3CIBIIE_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CDAAIE_MSB             : natural := 26;
    constant I3CDAAIE_LSB             : natural := 26;
    constant I3CDAAIE_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CERRIE_MSB             : natural := 25;
    constant I3CERRIE_LSB             : natural := 25;
    constant I3CERRIE_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CTCIE_MSB              : natural := 24;
    constant I3CTCIE_LSB              : natural := 24;
    constant I3CTCIE_RESET            : std_logic_vector(0 downto 0) := "0";
    constant I3CPPBR_MSB              : natural := 23;
    constant I3CPPBR_LSB              : natural := 16;
    constant I3CPPBR_RESET            : std_logic_vector(7 downto 0) := "00000000";
    constant I3CODBR_MSB              : natural := 15;
    constant I3CODBR_LSB              : natural := 8;
    constant I3CODBR_RESET            : std_logic_vector(7 downto 0) := "00000000";
    constant I3CIBIEN_MSB             : natural := 3;
    constant I3CIBIEN_LSB             : natural := 3;
    constant I3CIBIEN_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CSDAPP_MSB             : natural := 2;
    constant I3CSDAPP_LSB             : natural := 2;
    constant I3CSDAPP_RESET           : std_logic_vector(0 downto 0) := "1";
    constant I3CBUSMODE_MSB           : natural := 1;
    constant I3CBUSMODE_LSB           : natural := 1;
    constant I3CBUSMODE_RESET         : std_logic_vector(0 downto 0) := "0";
    constant I3CEN_MSB                : natural := 0;
    constant I3CEN_LSB                : natural := 0;
    constant I3CEN_RESET              : std_logic_vector(0 downto 0) := "0";

    -- I3CxCMD: I3C command register
    constant I3CxCMD_WORD             : natural := 1;
    constant I3CxCMD_ADDR             : natural := 4;
    constant I3CxCMD_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxCMD_IMPL             : std_logic_vector(31 downto 0) := "11111111111111110011111111111111";
    constant I3CCCCOP_MSB             : natural := 31;
    constant I3CCCCOP_LSB             : natural := 24;
    constant I3CCCCOP_RESET           : std_logic_vector(7 downto 0) := "00000000";
    constant I3CDLEN_MSB              : natural := 23;
    constant I3CDLEN_LSB              : natural := 16;
    constant I3CDLEN_RESET            : std_logic_vector(7 downto 0) := "00000000";
    constant I3CDASA_MSB              : natural := 13;
    constant I3CDASA_LSB              : natural := 13;
    constant I3CDASA_RESET            : std_logic_vector(0 downto 0) := "0";
    constant I3CDAARUN_MSB            : natural := 12;
    constant I3CDAARUN_LSB            : natural := 12;
    constant I3CDAARUN_RESET          : std_logic_vector(0 downto 0) := "0";
    constant I3CCCCDIR_MSB            : natural := 11;
    constant I3CCCCDIR_LSB            : natural := 11;
    constant I3CCCCDIR_RESET          : std_logic_vector(0 downto 0) := "0";
    constant I3CCCC_MSB               : natural := 10;
    constant I3CCCC_LSB               : natural := 10;
    constant I3CCCC_RESET             : std_logic_vector(0 downto 0) := "0";
    constant I3CSTOPEN_MSB            : natural := 9;
    constant I3CSTOPEN_LSB            : natural := 9;
    constant I3CSTOPEN_RESET          : std_logic_vector(0 downto 0) := "0";
    constant I3CREPSTART_MSB          : natural := 8;
    constant I3CREPSTART_LSB          : natural := 8;
    constant I3CREPSTART_RESET        : std_logic_vector(0 downto 0) := "0";
    constant I3CRNW_MSB               : natural := 7;
    constant I3CRNW_LSB               : natural := 7;
    constant I3CRNW_RESET             : std_logic_vector(0 downto 0) := "0";
    constant I3CADDR_MSB              : natural := 6;
    constant I3CADDR_LSB              : natural := 0;
    constant I3CADDR_RESET            : std_logic_vector(6 downto 0) := "0000000";

    -- I3CxTX: I3C transmit data
    constant I3CxTX_WORD              : natural := 2;
    constant I3CxTX_ADDR              : natural := 8;
    constant I3CxTX_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxTX_IMPL              : std_logic_vector(31 downto 0) := "00000000000000000000000011111111";
    constant I3CTX_MSB                : natural := 7;
    constant I3CTX_LSB                : natural := 0;
    constant I3CTX_RESET              : std_logic_vector(7 downto 0) := "00000000";

    -- I3CxRX: I3C receive data
    constant I3CxRX_WORD              : natural := 3;
    constant I3CxRX_ADDR              : natural := 12;
    constant I3CxRX_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxRX_IMPL              : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CRX_MSB                : natural := 7;
    constant I3CRX_LSB                : natural := 0;
    constant I3CRX_RESET              : std_logic_vector(7 downto 0) := "00000000";

    -- I3CxSR: I3C status register
    constant I3CxSR_WORD              : natural := 4;
    constant I3CxSR_ADDR              : natural := 16;
    constant I3CxSR_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxSR_IMPL              : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CIBIWON_MSB            : natural := 10;
    constant I3CIBIWON_LSB            : natural := 10;
    constant I3CIBIWON_RESET          : std_logic_vector(0 downto 0) := "0";
    constant I3CIBIP_MSB              : natural := 9;
    constant I3CIBIP_LSB              : natural := 9;
    constant I3CIBIP_RESET            : std_logic_vector(0 downto 0) := "0";
    constant I3CDAAFULL_MSB           : natural := 8;
    constant I3CDAAFULL_LSB           : natural := 8;
    constant I3CDAAFULL_RESET         : std_logic_vector(0 downto 0) := "0";
    constant I3CDAADONE_MSB           : natural := 7;
    constant I3CDAADONE_LSB           : natural := 7;
    constant I3CDAADONE_RESET         : std_logic_vector(0 downto 0) := "0";
    constant I3CARBLOST_MSB           : natural := 6;
    constant I3CARBLOST_LSB           : natural := 6;
    constant I3CARBLOST_RESET         : std_logic_vector(0 downto 0) := "0";
    constant I3CEODF_MSB              : natural := 5;
    constant I3CEODF_LSB              : natural := 5;
    constant I3CEODF_RESET            : std_logic_vector(0 downto 0) := "0";
    constant I3CANACK_MSB             : natural := 4;
    constant I3CANACK_LSB             : natural := 4;
    constant I3CANACK_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CTXEIF_MSB             : natural := 3;
    constant I3CTXEIF_LSB             : natural := 3;
    constant I3CTXEIF_RESET           : std_logic_vector(0 downto 0) := "0";
    constant I3CRXFULL_MSB            : natural := 2;
    constant I3CRXFULL_LSB            : natural := 2;
    constant I3CRXFULL_RESET          : std_logic_vector(0 downto 0) := "0";
    constant I3CTCIF_MSB              : natural := 1;
    constant I3CTCIF_LSB              : natural := 1;
    constant I3CTCIF_RESET            : std_logic_vector(0 downto 0) := "0";
    constant I3CBUSY_MSB              : natural := 0;
    constant I3CBUSY_LSB              : natural := 0;
    constant I3CBUSY_RESET            : std_logic_vector(0 downto 0) := "0";

    -- I3CxDAT: Device Address Table window
    constant I3CxDAT_WORD             : natural := 5;
    constant I3CxDAT_ADDR             : natural := 20;
    constant I3CxDAT_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxDAT_IMPL             : std_logic_vector(31 downto 0) := "00000000000011111111111111111111";
    constant I3CSTATVALID_MSB         : natural := 19;
    constant I3CSTATVALID_LSB         : natural := 19;
    constant I3CSTATVALID_RESET       : std_logic_vector(0 downto 0) := "0";
    constant I3CSTATADDR_MSB          : natural := 18;
    constant I3CSTATADDR_LSB          : natural := 12;
    constant I3CSTATADDR_RESET        : std_logic_vector(6 downto 0) := "0000000";
    constant I3CDYNVALID_MSB          : natural := 11;
    constant I3CDYNVALID_LSB          : natural := 11;
    constant I3CDYNVALID_RESET        : std_logic_vector(0 downto 0) := "0";
    constant I3CDYNADDR_MSB           : natural := 10;
    constant I3CDYNADDR_LSB           : natural := 4;
    constant I3CDYNADDR_RESET         : std_logic_vector(6 downto 0) := "0000000";
    constant I3CEVALID_MSB            : natural := 3;
    constant I3CEVALID_LSB            : natural := 3;
    constant I3CEVALID_RESET          : std_logic_vector(0 downto 0) := "0";
    constant I3CIDX_MSB               : natural := 2;
    constant I3CIDX_LSB               : natural := 0;
    constant I3CIDX_RESET             : std_logic_vector(2 downto 0) := "000";

    -- I3CxDATPID: Provisional ID (low 32 bits) of the DAT entry selected by I3CIDX
    constant I3CxDATPID_WORD          : natural := 6;
    constant I3CxDATPID_ADDR          : natural := 24;
    constant I3CxDATPID_RESET         : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxDATPID_IMPL          : std_logic_vector(31 downto 0) := "11111111111111111111111111111111";
    constant I3CPIDLO_MSB             : natural := 31;
    constant I3CPIDLO_LSB             : natural := 0;
    constant I3CPIDLO_RESET           : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";

    -- I3CxDATINFO: High provisional-ID bits and the bus/device characteristic registers of the DAT entry selected by I3CIDX
    constant I3CxDATINFO_WORD         : natural := 7;
    constant I3CxDATINFO_ADDR         : natural := 28;
    constant I3CxDATINFO_RESET        : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxDATINFO_IMPL         : std_logic_vector(31 downto 0) := "11111111111111111111111111111111";
    constant I3CDCR_MSB               : natural := 31;
    constant I3CDCR_LSB               : natural := 24;
    constant I3CDCR_RESET             : std_logic_vector(7 downto 0) := "00000000";
    constant I3CBCR_MSB               : natural := 23;
    constant I3CBCR_LSB               : natural := 16;
    constant I3CBCR_RESET             : std_logic_vector(7 downto 0) := "00000000";
    constant I3CPIDHI_MSB             : natural := 15;
    constant I3CPIDHI_LSB             : natural := 0;
    constant I3CPIDHI_RESET           : std_logic_vector(15 downto 0) := "0000000000000000";

    -- I3CxIBI: In-band interrupt capture
    constant I3CxIBI_WORD             : natural := 8;
    constant I3CxIBI_ADDR             : natural := 32;
    constant I3CxIBI_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CxIBI_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant I3CIBIACKED_MSB          : natural := 17;
    constant I3CIBIACKED_LSB          : natural := 17;
    constant I3CIBIACKED_RESET        : std_logic_vector(0 downto 0) := "0";
    constant I3CIBIHASDATA_MSB        : natural := 16;
    constant I3CIBIHASDATA_LSB        : natural := 16;
    constant I3CIBIHASDATA_RESET      : std_logic_vector(0 downto 0) := "0";
    constant I3CIBIMDB_MSB            : natural := 15;
    constant I3CIBIMDB_LSB            : natural := 8;
    constant I3CIBIMDB_RESET          : std_logic_vector(7 downto 0) := "00000000";
    constant I3CIBIVALID_MSB          : natural := 7;
    constant I3CIBIVALID_LSB          : natural := 7;
    constant I3CIBIVALID_RESET        : std_logic_vector(0 downto 0) := "0";
    constant I3CIBIADDR_MSB           : natural := 6;
    constant I3CIBIADDR_LSB           : natural := 0;
    constant I3CIBIADDR_RESET         : std_logic_vector(6 downto 0) := "0000000";

    -- I3C.vhd's own decode identifiers: the word each register is
    -- decoded at, spelled the way that file already spells it, so adopting this
    -- package is a context clause plus a deletion and no assignment moves.
    constant SLOT_CR                  : natural := 0;
    constant SLOT_CMD                 : natural := 1;
    constant SLOT_TX                  : natural := 2;
    constant SLOT_RX                  : natural := 3;
    constant SLOT_SR                  : natural := 4;
    constant SLOT_DAT                 : natural := 5;
    constant SLOT_DATPID              : natural := 6;
    constant SLOT_DATINFO             : natural := 7;
    constant SLOT_IBI                 : natural := 8;

end package i3c_regs_pkg;
