-- =============================================================================
-- trng_regs_pkg.vhd: GENERATED from hdl/common/periph/rdl/ by
-- platform/common/python/rdl_vhdl.py. DO NOT EDIT THIS FILE.
--
--   regenerate:  tools/bin/bazel run //platform/common/python:rdl_vhdl_pkgs
--   gates:       //platform/common:rdl_vhdl_pkg_test    tracked == regenerated
--                //platform/common:rdl_pkg_vs_legacy_test  == the hand-written
--                                                       constants it replaced
--                //platform/common:rdl_vs_vhdl_trng_test
--
-- Ring-oscillator entropy source and harvest engine: a free-running ensemble of NRO ring oscillators (peripherals.trngRings, {4,8}) is XOR-reduced to one noisy bit, 2-FF synchronized into the free-running MCLK, decimated (one raw sample every 2^DECIM MCLK cycles) and direct-packed 32 raw bits at a time into a holding register
--
-- <REG>_WORD is the word offset inside the peripheral sub-slot, <REG>_ADDR the
-- byte offset, <REG>_RESET the reset word and <REG>_IMPL the mask of bits that
-- hold a software-written flop (hardware-owned status and single-pulse strobes
-- are excluded, which is the same rule the hand-written IMPL tables use).
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;

package trng_regs_pkg is

    -- TRNGxCR: TRNG control register
    constant TRNGxCR_WORD             : natural := 0;
    constant TRNGxCR_ADDR             : natural := 0;
    constant TRNGxCR_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant TRNGxCR_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000111111110111";
    constant TRNGDECIM_MSB            : natural := 11;
    constant TRNGDECIM_LSB            : natural := 8;
    constant TRNGDECIM_RESET          : std_logic_vector(3 downto 0) := "0000";
    constant TRNGROSEL_MSB            : natural := 7;
    constant TRNGROSEL_LSB            : natural := 4;
    constant TRNGROSEL_RESET          : std_logic_vector(3 downto 0) := "0000";
    constant TRNGALMIE_MSB            : natural := 2;
    constant TRNGALMIE_LSB            : natural := 2;
    constant TRNGALMIE_RESET          : std_logic_vector(0 downto 0) := "0";
    constant TRNGDRDYIE_MSB           : natural := 1;
    constant TRNGDRDYIE_LSB           : natural := 1;
    constant TRNGDRDYIE_RESET         : std_logic_vector(0 downto 0) := "0";
    constant TRNGEN_MSB               : natural := 0;
    constant TRNGEN_LSB               : natural := 0;
    constant TRNGEN_RESET             : std_logic_vector(0 downto 0) := "0";

    -- TRNGxSR: TRNG status register
    constant TRNGxSR_WORD             : natural := 1;
    constant TRNGxSR_ADDR             : natural := 4;
    constant TRNGxSR_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant TRNGxSR_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant TRNGRUN_MSB              : natural := 2;
    constant TRNGRUN_LSB              : natural := 2;
    constant TRNGRUN_RESET            : std_logic_vector(0 downto 0) := "0";
    constant TRNGALMF_MSB             : natural := 1;
    constant TRNGALMF_LSB             : natural := 1;
    constant TRNGALMF_RESET           : std_logic_vector(0 downto 0) := "0";
    constant TRNGDRDY_MSB             : natural := 0;
    constant TRNGDRDY_LSB             : natural := 0;
    constant TRNGDRDY_RESET           : std_logic_vector(0 downto 0) := "0";

    -- TRNGxDR: Entropy data register
    constant TRNGxDR_WORD             : natural := 2;
    constant TRNGxDR_ADDR             : natural := 8;
    constant TRNGxDR_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant TRNGxDR_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant TRNGDR_MSB               : natural := 31;
    constant TRNGDR_LSB               : natural := 0;
    constant TRNGDR_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";

    -- TRNGxHT: Health-test control/diagnostic register
    constant TRNGxHT_WORD             : natural := 3;
    constant TRNGxHT_ADDR             : natural := 12;
    constant TRNGxHT_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant TRNGxHT_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000000011111111";
    constant TRNGRUNLEN_MSB           : natural := 21;
    constant TRNGRUNLEN_LSB           : natural := 16;
    constant TRNGRUNLEN_RESET         : std_logic_vector(5 downto 0) := "000000";
    constant TRNGRCTC_MSB             : natural := 7;
    constant TRNGRCTC_LSB             : natural := 0;
    constant TRNGRCTC_RESET           : std_logic_vector(7 downto 0) := "00000000";

    -- TRNG.vhd's own decode identifiers: the word each register is
    -- decoded at, spelled the way that file already spells it, so adopting this
    -- package is a context clause plus a deletion and no assignment moves.
    constant SLOT_CR                  : natural := 0;
    constant SLOT_SR                  : natural := 1;
    constant SLOT_DR                  : natural := 2;
    constant SLOT_HT                  : natural := 3;

end package trng_regs_pkg;
