set_clock_latency -source -early -min -rise  -0.17958 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.16929 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.17958 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.16929 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.17958 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.16929 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.17958 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.16929 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.214744 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.201749 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.214744 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.201749 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.214744 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.201749 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.214744 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.201749 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.109441 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.101706 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.109441 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.101706 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.109441 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.101706 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.109441 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.101706 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.189852 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.183254 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.189852 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.183254 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.189852 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.183254 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.189852 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.183254 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.0942844 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.0857766 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.0942844 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.0857766 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.0942844 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.0857766 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.0942844 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.0857766 [get_pins {spi1/sck_in}] -clock clk_sck1 
