set_clock_latency -source -early -min -rise  -0.186229 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.174126 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.186229 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.174126 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.186229 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.174126 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.186229 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.174126 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.243858 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -fall  -0.239646 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -rise  -0.243858 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -fall  -0.239646 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -rise  -0.243858 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -fall  -0.239646 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -rise  -0.243858 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -fall  -0.239646 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -rise  -0.268674 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.254013 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.268674 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.254013 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.268674 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.254013 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.268674 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.254013 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.243609 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -fall  -0.239999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -rise  -0.243609 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -fall  -0.239999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -rise  -0.243609 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -fall  -0.239999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -rise  -0.243609 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -fall  -0.239999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -rise  -0.0920613 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.0827839 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.0920613 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.0827839 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.0920613 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.0827839 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.0920613 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.0827839 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.272273 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.257991 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.272273 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.257991 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.272273 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.257991 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.272273 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.257991 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.0967168 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.088188 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.0967168 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.088188 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.0967168 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.088188 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.0967168 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.088188 [get_pins {spi1/sck_in}] -clock clk_sck1 
