set_clock_latency -source -early -min -rise  -0.170409 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.158043 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.170409 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.158043 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.170409 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.158043 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.170409 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.158043 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.247684 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -fall  -0.241333 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -rise  -0.247684 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -fall  -0.241333 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -rise  -0.247684 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -fall  -0.241333 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -rise  -0.247684 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -fall  -0.241333 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -rise  -0.0742537 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -early -min -fall  -0.0679041 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -early -max -rise  -0.0742537 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -early -max -fall  -0.0679041 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -late -min -rise  -0.0742537 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -late -min -fall  -0.0679041 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -late -max -rise  -0.0742537 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -late -max -fall  -0.0679041 [get_pins {i2c0/SCL_IN}] -clock clk_scl0 
set_clock_latency -source -early -min -rise  -0.0595902 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -early -min -fall  -0.0543776 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -early -max -rise  -0.0595902 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -early -max -fall  -0.0543776 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -late -min -rise  -0.0595902 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -late -min -fall  -0.0543776 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -late -max -rise  -0.0595902 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -late -max -fall  -0.0543776 [get_pins {i2c1/SCL_IN}] -clock clk_scl1 
set_clock_latency -source -early -min -rise  -0.275369 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.260731 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.275369 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.260731 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.275369 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.260731 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.275369 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.260731 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.25138 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -fall  -0.245093 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -rise  -0.25138 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -fall  -0.245093 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -rise  -0.25138 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -fall  -0.245093 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -rise  -0.25138 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -fall  -0.245093 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -rise  -0.097951 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.0878375 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.097951 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.0878375 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.097951 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.0878375 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.097951 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.0878375 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.274316 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.264664 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.274316 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.264664 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.274316 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.264664 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.274316 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.264664 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.0984248 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.0893395 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.0984248 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.0893395 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.0984248 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.0893395 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.0984248 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.0893395 [get_pins {spi1/sck_in}] -clock clk_sck1 
