// =====================================================================
// test_macros_zfinx.h  --  GENERATED by verification/isa/tools/zfinx_convert.py
// DO NOT HAND EDIT.  Zfinx (F-in-X) overrides of the floating-point test
// macros: operands live in x-registers, so flw->lw, fmv.x.s->mv, and every
// fXXX.s runs on x-registers.  Operand register assignment (collision-free
// with the harness's a0..a3/gp/t1/t2/x7):
//     s2 = operand 1 (was f10)   s3 = operand 2 (was f11)
//     s4 = operand 3 (was f12)   s5 = result    (was f13)
// The data sections (.float / .result) are emitted exactly as upstream.
// =====================================================================
#ifndef __TEST_MACROS_ZFINX_H
#define __TEST_MACROS_ZFINX_H

#include "test_macros.h"

// ---- single-precision harness (loads operands into x-regs) ----------
#undef TEST_FP_OP_S_INTERNAL
#define TEST_FP_OP_S_INTERNAL( testnum, flags, result, val1, val2, val3, code... ) \
test_ ## testnum: \
  li  TESTNUM, testnum; \
  la  a0, test_ ## testnum ## _data ;\
  lw  s2, 0(a0); \
  lw  s3, 4(a0); \
  lw  s4, 8(a0); \
  lw  a3, 12(a0); \
  code; \
  csrrw a1, fflags, x0; \
  li a2, flags; \
  bne a0, a3, fail; \
  bne a1, a2, fail; \
  .pushsection .data; \
  .align 2; \
  test_ ## testnum ## _data: \
  .float val1; \
  .float val2; \
  .float val3; \
  .result; \
  .popsection

// ---- op wrappers: run on x-regs, result read with `mv` --------------
#undef TEST_FP_OP1_S
#define TEST_FP_OP1_S( testnum, inst, flags, result, val1 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, float result, val1, 0.0, 0.0, \
                    inst s5, s2; mv a0, s5)

#undef TEST_FP_OP1_S_DWORD_RESULT
#define TEST_FP_OP1_S_DWORD_RESULT( testnum, inst, flags, result, val1 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, dword result, val1, 0.0, 0.0, \
                    inst s5, s2; mv a0, s5)

#undef TEST_FP_OP2_S
#define TEST_FP_OP2_S( testnum, inst, flags, result, val1, val2 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, float result, val1, val2, 0.0, \
                    inst s5, s2, s3; mv a0, s5)

#undef TEST_FP_OP3_S
#define TEST_FP_OP3_S( testnum, inst, flags, result, val1, val2, val3 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, float result, val1, val2, val3, \
                    inst s5, s2, s3, s4; mv a0, s5)

// ---- compares: integer result straight into a0 ---------------------
#undef TEST_FP_CMP_OP_S
#define TEST_FP_CMP_OP_S( testnum, inst, flags, result, val1, val2 ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, word result, val1, val2, 0.0, \
                    inst a0, s2, s3)

// ---- float -> int convert (result integer in a0) -------------------
#undef TEST_FP_INT_OP_S
#define TEST_FP_INT_OP_S( testnum, inst, flags, result, val1, rm ) \
  TEST_FP_OP_S_INTERNAL( testnum, flags, word result, val1, 0.0, 0.0, \
                    inst a0, s2, rm)

// ---- int -> float convert (own body; no f-reg move) ----------------
#undef TEST_INT_FP_OP_S
#define TEST_INT_FP_OP_S( testnum, inst, result, val1 ) \
test_ ## testnum: \
  li  TESTNUM, testnum; \
  la  a0, test_ ## testnum ## _data ;\
  lw  a3, 0(a0); \
  li  a0, val1; \
  inst s5, a0; \
  csrrw x0, fflags, x0; \
  mv a0, s5; \
  bne a0, a3, fail; \
  .pushsection .data; \
  .align 2; \
  test_ ## testnum ## _data: \
  .float result; \
  .popsection

// ---- fclass: input in x-reg, no fmv needed -------------------------
#undef TEST_FCLASS_S
#define TEST_FCLASS_S(testnum, correct, input) \
  TEST_CASE(testnum, a0, correct, li s2, input; fclass.s a0, s2)

#endif // __TEST_MACROS_ZFINX_H
