#!/usr/bin/python3.6
"""check_d3_text_fixes.py -- the instrument for d3_spec section 3.

D3 carries four rule-12 TEXT fixes: comments and generated strings that
describe the design incorrectly.  They are frozen spec clauses like any other,
and the D1 lesson (R-D2-13(2)) is that a frozen clause with NO INSTRUMENT
SHIPS UNIMPLEMENTED.  A comment fix has no simulation behaviour, so the
instrument for it is a text check -- this file.

BLIND-AUTHORED 2026-08-06 against d3_spec.md section 3 and d3_cdc_spec.md
section 2 (both FROZEN).  Line numbers in the spec are stale by design
("re-grep, never trust them"), so this script SEARCHES FOR THE WRONG TEXT
rather than asserting a line number, and reports the line it found it on.

  /usr/bin/python3.6 tools/cosim/check_d3_text_fixes.py

rc 0 = every stale string is gone AND every replacement obligation is
       satisfied
rc 1 = at least one stale string survives (the fix did not land)
rc 2 = a file that must be checked is missing, or a check could not be made
       (never silently treated as a pass)

WHY EACH STRING IS WRONG -- so a future reader can tell a fix from a
regression:

  T1  debug_module.vhd  claims `ready` stays low "until valid is OBSERVED low"
      via a signal `req_busy`.  There is no such signal (one grep hit, the
      comment itself) and the implemented guard is a TIMER,
      `rsp_hold = 0 and rsp_arm = '0'`, whose window re-opens 9 mclk after a
      capture.  The distinction is the whole reason d3_cdc_spec 2 has a
      one-shot clause.
  T2  debug_module.vhd  calls `ready` "combinational from s_state".  It is
      registered: `dmi_req_ready <= ready_r`.
  T3  mcu_vhd.py        emits an MCU comment promising "11=busy" as a
      response op.  The DM has exactly two op constants, OP_OK "00" and
      OP_FAIL "10"; `grep '"11"'` over debug_module.vhd returns nothing.
      Busy is DTM-LOCAL.  A promise the RTL cannot keep is worse than
      silence: an acceptance check written against it is unsatisfiable.
  T4  the emitted product must agree with the emitter -- checked wherever a
      generated MCU.vhd is staged, because the emitter and the product are
      two different files and only one of them is regenerated by `make chip`.
"""

import os
import re
import sys

ROOT = os.environ.get('VESTA_ROOT',
                      os.path.join(os.path.expanduser('~'), 'vestarv'))

# (file, regex that must NOT appear, short name, why)
STALE = [
    ('hdl/common/debug_module.vhd', r'req_busy', 'T1',
     'the nonexistent req_busy signal / observed-low claim (the guard is a '
     '9-mclk timer: rsp_hold = 0 and rsp_arm = 0)'),
    ('hdl/common/debug_module.vhd', r'it is combinational from', 'T2',
     'ready described as combinational; it is registered (ready_r)'),
    ('platform/common/python/mcu_vhd.py', r'11=busy', 'T3',
     'the emitted MCU comment promises a response op the RTL cannot produce'),
]

# Generated products that must not carry the T3 string either.  Absent
# products are SKIPPED with a note, never counted as a pass.
PRODUCTS = [
    'xcelium/riscv_test/verify_castaliadebug/hdl/MCU.vhd',
    'xcelium/riscv_test/verify_argusdebug/hdl/MCU.vhd',
    'hdl/common/MCU.vhd',
]

# Positive obligations: after the fix, the corrected description must be
# PRESENT, not merely the wrong one absent.  A deletion is not a fix -- the
# rule-12 obligation is to describe the real mechanism.  Each entry is
# (file, list-of-alternatives, name, what it should say).
REQUIRED = [
    ('hdl/common/debug_module.vhd',
     [r'rsp_hold', r'rsp_arm'], 'T1b',
     'the accept guard must be described in terms of the signals that '
     'actually implement it'),
]


def readfile(path):
    with open(path, 'r', errors='replace') as fh:
        return fh.read().split('\n')


def main():
    problems = []
    notes = []

    for rel, pat, name, why in STALE:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print('check_d3_text_fixes: FATAL missing file: ' + rel)
            return 2
        rx = re.compile(pat)
        hits = [(i + 1, ln) for i, ln in enumerate(readfile(path))
                if rx.search(ln)]
        if hits:
            problems.append((name, rel, why, hits))

    for rel in PRODUCTS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            notes.append('SKIPPED (not staged): ' + rel)
            continue
        hits = [(i + 1, ln) for i, ln in enumerate(readfile(path))
                if '11=busy' in ln]
        if hits:
            problems.append(('T4', rel,
                             'a generated product still carries the "11=busy" '
                             'promise -- the emitter was fixed but this file '
                             'was not regenerated, or vice versa', hits))

    for rel, pats, name, why in REQUIRED:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print('check_d3_text_fixes: FATAL missing file: ' + rel)
            return 2
        body = '\n'.join(readfile(path))
        if not any(re.search(p, body) for p in pats):
            problems.append((name, rel, why, []))

    for n in notes:
        print('check_d3_text_fixes: ' + n)

    if problems:
        print('check_d3_text_fixes: FAIL -- %d rule-12 obligation(s) unmet'
              % len(problems))
        for name, rel, why, hits in problems:
            print('  [%s] %s' % (name, rel))
            print('        %s' % why)
            for ln, txt in hits[:4]:
                print('        :%d  %s' % (ln, txt.strip()[:100]))
        print('  These are d3_spec section 3 clauses.  A frozen clause with no')
        print('  instrument is how D1 shipped three of them unimplemented.')
        return 1

    print('check_d3_text_fixes: OK -- all d3_spec section 3 text fixes are in '
          'place (%d stale patterns absent, %d positive obligations met)'
          % (len(STALE) + len(PRODUCTS), len(REQUIRED)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
