#!/usr/bin/python3.6
# -*- coding: utf-8 -*-
"""Standalone self-tests for tools/cosim/compare.py (phase V2, Agent A).

    /usr/bin/python3.6 tools/cosim/test_compare.py

Exits 0 if every case passes, 1 otherwise.  No external dependencies, no
Xcelium, no network.  Every comparator exit code (0,1,2,3,4,5) is exercised.

PROVENANCE OF THE FIXTURES -- this matters, because a test whose "golden" data
came out of the code under test proves nothing:

* `RTL20` is the first 20 lines of the ENTRY-ALIGNED window of the REAL V1
  tracer output (`xcelium/riscv_test/behavioral_mp/vesta_trace_h00.trace`,
  `rv32ui-p-add`, hart 0, from line 48987 = the first retire at pc 0x8200),
  copied verbatim.
* `SPIKE20` is the first 20 lines of a REAL Spike commit log produced on this
  host by the frozen v0 recipe, copied verbatim:
      spike --isa=rv32imac_zicsr_zba_zbb_zbs_zbc --priv=m --pmpregions=0 \
            -m0x8000:0x18000 --disable-dtb --pc=0x8200 --log-commits \
            --instructions=4000 --log=add.spike.log \
            verification/isa/build/rv32ui/rv32ui-p-add
  Neither file was generated by any code in tools/cosim.
* The shapes the `add` window does not contain -- loads, stores, CSR writes,
  AMOs, multi-`rd` retires, traps -- are hand-written from the VERBATIM Spike
  lines recorded in `RECORD_FORMAT.md` §2/§3 and re-measured during V2 (sb/sw
  data widths, the AMO double-`mem` line), with the RTL side hand-derived from
  the wire format.  Each such fixture carries a negative control: a mutation
  that MUST be caught, so "exit 0" is never vacuous.
* `test_real_artifacts` additionally runs the WHOLE 462-record real window
  against the whole real Spike log when both files are still on disk.
* The V4 (multi-hart) fixtures -- `SLEEP_*` for `--stop-before-sleep`, `BRK_*`
  for the `--hart` filter on the A7 diagnostics -- reuse RTL20/SPIKE20's own
  verbatim lines with the hart field moved, plus records hand-derived from the
  wire format (the EXTINGUISH retire, the `X wfi_enter`, the bracket's T/M/X).
  Each carries its negative control; see the comment blocks on the fixtures.
"""

from __future__ import print_function

import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PY = "/usr/bin/python3.6"
COMPARE = os.path.join(HERE, "compare.py")

sys.path.insert(0, HERE)
from records import parse_rtl_line                     # noqa: E402
from spike_log import parse_spike_line                 # noqa: E402
from compare import canonicalise_a2, compared_stream   # noqa: E402

HEADER = "# vesta_tracer TRACE_ENABLE=true vesta_trace hart=00\n"

RTL20 = """\
R 00 0000bf5a 00008200 a011 00 00000000
R 00 0000bf5b 00008204 4081 01 00000000
R 00 0000bf5c 00008206 4101 02 00000000
R 00 0000bf5d 00008208 4181 03 00000000
R 00 0000bf5e 0000820a 4201 04 00000000
R 00 0000bf5f 0000820c 4281 05 00000000
R 00 0000bf60 0000820e 4301 06 00000000
R 00 0000bf61 00008210 4381 07 00000000
R 00 0000bf62 00008212 4401 08 00000000
R 00 0000bf63 00008214 4481 09 00000000
R 00 0000bf64 00008216 4501 0a 00000000
R 00 0000bf65 00008218 4581 0b 00000000
R 00 0000bf66 0000821a 4601 0c 00000000
R 00 0000bf67 0000821c 4681 0d 00000000
R 00 0000bf68 0000821e 4701 0e 00000000
R 00 0000bf69 00008220 4781 0f 00000000
R 00 0000bf6a 00008222 4801 10 00000000
R 00 0000bf6b 00008224 4881 11 00000000
R 00 0000bf6c 00008226 4901 12 00000000
R 00 0000bf6d 00008228 4981 13 00000000
""".splitlines(True)

SPIKE20 = """\
core   0: 3 0x00008200 (0xa011)
core   0: 3 0x00008204 (0x4081) x1  0x00000000
core   0: 3 0x00008206 (0x4101) x2  0x00000000
core   0: 3 0x00008208 (0x4181) x3  0x00000000
core   0: 3 0x0000820a (0x4201) x4  0x00000000
core   0: 3 0x0000820c (0x4281) x5  0x00000000
core   0: 3 0x0000820e (0x4301) x6  0x00000000
core   0: 3 0x00008210 (0x4381) x7  0x00000000
core   0: 3 0x00008212 (0x4401) x8  0x00000000
core   0: 3 0x00008214 (0x4481) x9  0x00000000
core   0: 3 0x00008216 (0x4501) x10 0x00000000
core   0: 3 0x00008218 (0x4581) x11 0x00000000
core   0: 3 0x0000821a (0x4601) x12 0x00000000
core   0: 3 0x0000821c (0x4681) x13 0x00000000
core   0: 3 0x0000821e (0x4701) x14 0x00000000
core   0: 3 0x00008220 (0x4781) x15 0x00000000
core   0: 3 0x00008222 (0x4801) x16 0x00000000
core   0: 3 0x00008224 (0x4881) x17 0x00000000
core   0: 3 0x00008226 (0x4901) x18 0x00000000
core   0: 3 0x00008228 (0x4981) x19 0x00000000
""".splitlines(True)


# --------------------------------------------------------------------------
# harness
# --------------------------------------------------------------------------

class Harness(object):
    def __init__(self):
        self.dir = tempfile.mkdtemp(prefix="cosim_selftest_")
        self.passed = 0
        self.failed = 0
        self.n = 0

    def cleanup(self):
        shutil.rmtree(self.dir, ignore_errors=True)

    def write(self, name, lines):
        path = os.path.join(self.dir, name)
        with open(path, "w") as fh:
            fh.write("".join(lines))
        return path

    def compare(self, rtl_lines, spike_lines, extra=(), tag="t"):
        rtl = self.write("%s.trace" % tag, rtl_lines)
        spk = self.write("%s.spike.log" % tag, spike_lines)
        cmd = [PY, COMPARE, "--rtl", rtl, "--spike", spk, "--entry", "0x8200"]
        cmd += list(extra)
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
        so, se = p.communicate()
        return p.returncode, so.decode(), se.decode(), cmd

    def case(self, name, expect, rtl_lines, spike_lines, extra=(),
             expect_in_stdout=None, expect_in_stderr=None):
        self.n += 1
        tag = "c%02d" % self.n
        rc, so, se, cmd = self.compare(rtl_lines, spike_lines, extra, tag)
        why = []
        if rc != expect:
            why.append("exit %d, expected %d" % (rc, expect))
        for needle in (expect_in_stdout or []):
            if needle not in so:
                why.append("stdout missing %r" % needle)
        for needle in (expect_in_stderr or []):
            if needle not in se:
                why.append("stderr missing %r" % needle)
        self.report(name, expect, rc, why, so, se, cmd)
        return rc, so, se

    def raw(self, name, cmd, expect, expect_in_stderr=None):
        self.n += 1
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
        so, se = p.communicate()
        so, se = so.decode(), se.decode()
        why = []
        if p.returncode != expect:
            why.append("exit %d, expected %d" % (p.returncode, expect))
        for needle in (expect_in_stderr or []):
            if needle not in se:
                why.append("stderr missing %r" % needle)
        self.report(name, expect, p.returncode, why, so, se, cmd)
        return p.returncode, so, se

    def check(self, name, ok, detail=""):
        self.n += 1
        self.report(name, "ok", "ok" if ok else "FAIL",
                    [] if ok else [detail or "assertion failed"], "", "", None)

    def report(self, name, expect, got, why, so, se, cmd):
        if not why:
            self.passed += 1
            print("PASS  %-52s exit=%s" % (name, got))
        else:
            self.failed += 1
            print("FAIL  %-52s exit=%s (want %s)" % (name, got, expect))
            for w in why:
                print("        %s" % w)
            if cmd:
                print("        cmd: %s" % " ".join(cmd))
            for stream, text in (("stdout", so), ("stderr", se)):
                for line in text.splitlines()[:24]:
                    print("        %s| %s" % (stream[:3], line))


# --------------------------------------------------------------------------
# hand-written fixtures for the shapes the rv32ui-p-add window does not have
#
# The Spike side of each is written to the VERBATIM shapes recorded in
# RECORD_FORMAT.md §2/§3 and re-measured in V2 against the pinned binary:
#   sb  -> "mem 0x00008690 0xaa"          (2 hex digits = 1 byte)
#   sh  -> "mem 0x000086d0 0x00aa"        (4 hex digits = 2 bytes)
#   sw  -> "mem 0x000086d0 0x00aa00aa"    (8 hex digits = 4 bytes)
#   lb  -> "x14 0xffffffaa mem 0x00008690"          (address ONLY)
#   amo -> "x14 0x80000000 mem 0x8308 mem 0x8308 0x7ffff800"  (load THEN store)
#   csr -> "x20 0x00000029 c2816_mcycle 0x00000000"  (2816 = 0xb00)
# The RTL side is hand-derived from the wire format (§0/§2/§3 + A4).
# --------------------------------------------------------------------------

MEM_SPIKE = """\
core   0: 3 0x00008200 (0x00110023) mem 0x00008690 0xaa
core   0: 3 0x00008204 (0x00010703) x14 0xffffffaa mem 0x00008690
core   0: 3 0x00008208 (0xc006) mem 0x000086d0 0x00aa00aa
core   0: 3 0x0000820a (0x00b6a72f) x14 0x80000000 mem 0x00008308 mem 0x00008308 0x7ffff800
core   0: 3 0x0000820e (0xb0041a73) x20 0x00000029 c2816_mcycle 0x00000000
core   0: 3 0x00008212 (0x00111023) mem 0x000086d4 0x00aa
""".splitlines(True)

MEM_RTL = """\
R 00 00000010 00008200 00110023 00 00000000
M 00 00000010 S 00008690 1 000000aa
R 00 00000012 00008204 00010703 0e ffffffaa
M 00 00000012 L 00008690 1 000000aa
R 00 00000014 00008208 c006 00 00000000
M 00 00000014 S 000086d0 4 00aa00aa
R 00 00000016 0000820a 00b6a72f 0e 80000000
M 00 00000016 L 00008308 4 80000000
M 00 00000016 S 00008308 4 7ffff800
R 00 00000018 0000820e b0041a73 14 00000029
C 00 00000018 b00 00000000
R 00 0000001a 00008212 00111023 00 00000000
M 00 0000001a S 000086d4 2 000000aa
""".splitlines(True)

# Amendment A2: a multi-rd retire.  Spike prints the writes on ONE line in
# numeric-key order (x2 key 32 < x8 key 128 < x9 key 144); the RTL emits one R
# per committed write and the Zcmp sequencer commits sp LAST (kickoff §3b), so
# the two orders differ and the A2 sort is load-bearing, not decorative.
A2_SPIKE = """\
core   0: 3 0x00008200 (0xbe86) x2  0x0000bff0 x8  0x00000011 x9  0x00000022
core   0: 3 0x00008202 (0x4501) x10 0x00000000
""".splitlines(True)

A2_RTL = """\
R 00 00000020 00008200 be86 08 00000011
R 00 00000021 00008200 be86 09 00000022
R 00 00000022 00008200 be86 02 0000bff0
R 00 00000023 00008202 4501 0a 00000000
""".splitlines(True)

# RECORD_FORMAT §3 ORDERING TRAP: a low-numbered CSR prints BEFORE a
# high-numbered GPR, so fields must be classified by prefix, never by position.
ORDER_SPIKE = """\
core   0: 3 0x00008200 (0x00302073) c1_fflags 0x00000001 x20 0x0000002e
""".splitlines(True)

ORDER_RTL = """\
R 00 00000030 00008200 00302073 14 0000002e
C 00 00000030 001 00000001
""".splitlines(True)


# --------------------------------------------------------------------------
# V4/C2 fixture -- A11's WOKEN-THEN-TRUNCATED sleep window (the T1 shape).
#
# The tile was launched, took the legacy msip trap, and the sim ENDED while it was
# still inside the bootrom loader ISR -- so the window never closes.  Measured on
# rv32ui-p-shmem_mp, whose launch margin is 1,011 cycles against the ~32,768 the
# 4,096-word copy needs.  Shape taken from that trace: `X wfi_enter`, the
# EXTINGUISH retire (0000100b, emitted at the WAKE edge), `X wfi_wake`, the
# legacy sentinel T, ISR records, then EOF with no `X iret`.
#
# THE DISCRIMINATOR IS THE EXTINGUISH RETIRE.  Its presence means the reference
# could not cross the park at all, so the verdict belongs to the PRE-PARK prefix
# and an unterminated window is CORRECT.  Contrast SLEEP_PARK_TAIL_RTL above,
# which parks on a REAL `wfi` (no EXTINGUISH) -- Spike executes that as an
# ordinary retire, so there the tail IS comparable and is given back.
SLEEP_WOKEN_TRUNC_RTL = """\
R 00 00000100 00008200 a011 00 00000000
X 00 00000101 wfi_enter
R 00 00000102 000002b4 0000100b 00 00000000
X 00 00000102 wfi_wake
# IRQPUSH 00 00000103 0000bff8 4 000002b8
T 00 00000104 8000007f 000002b8 0000814c 3
R 00 00000105 0000814c 00008067 00 00000000
M 00 00000106 S 00008000 4 deadbeef
R 00 00000107 000002f8 007fa023 00 00000000
""".splitlines(True)

# The reference stops at the park: ONE retire, the pre-park one.
SLEEP_WOKEN_TRUNC_SPIKE = """\
core   0: 3 0x00008200 (0xa011)
""".splitlines(True)


# --------------------------------------------------------------------------
# V4 fixtures -- Amendment A15: the spurious failed-SC `M ... S` record
#
# A globally-failed `sc.w` still emits a store record on the RTL side (the core
# drives `wen` on its LOCAL check; the write dies downstream in `resv_unit`), so
# the RTL has an `M ... S` the reference correctly does not produce.  Both shapes
# below are the VERBATIM instruction and operands from `rv32ua-p-shlrsc` hart 0
# lines 216504-6: `sc.w t4,t3,(t5)` = 0x19c2aeaf, storing 0x000015b3 to 0x1000c.
# The two fixtures differ ONLY in the sc.w's rdval (1 = failed, 0 = succeeded),
# which is exactly the oracle A15 keys on -- so the pair is a controlled A/B.
A15_FAIL_RTL = """\
R 00 00000040 00008200 19c2aeaf 1d 00000001
M 00 00000040 S 0001000c 4 000015b3
R 00 00000042 00008204 4081 01 00000000
""".splitlines(True)

# The reference: rd=1 and NO store.  This is what vesta_ref emits for a forced
# fail (probe_a13_a14 P2 measured exactly this), so the fixture is not invented.
A15_FAIL_SPIKE = """\
core   0: 3 0x00008200 (0x19c2aeaf) x29 0x00000001
core   0: 3 0x00008204 (0x4081) x1  0x00000000
""".splitlines(True)

A15_OK_RTL = """\
R 00 00000040 00008200 19c2aeaf 1d 00000000
M 00 00000040 S 0001000c 4 000015b3
R 00 00000042 00008204 4081 01 00000000
""".splitlines(True)

A15_OK_SPIKE = """\
core   0: 3 0x00008200 (0x19c2aeaf) x29 0x00000000 mem 0x0001000c 0x000015b3
core   0: 3 0x00008204 (0x4081) x1  0x00000000
""".splitlines(True)

# rd = x0: `sc.w x0, ...` discards its own result, so `rd` cannot be the oracle
# and A15 must drop NOTHING and say so.  Encoding = 0x19c2aeaf with rd forced to
# 0 (bits 11:7 cleared): 0x19c2a02f.
A15_X0_RTL = """\
R 00 00000040 00008200 19c2a02f 00 00000000
M 00 00000040 S 0001000c 4 000015b3
R 00 00000042 00008204 4081 01 00000000
""".splitlines(True)

A15_X0_SPIKE = """\
core   0: 3 0x00008200 (0x19c2a02f) mem 0x0001000c 0x000015b3
core   0: 3 0x00008204 (0x4081) x1  0x00000000
""".splitlines(True)


# Amendment A16 (WT, finding T2) -- the SAME failed sc.w as A15_FAIL_RTL, as a
# POST-A16 tracer emits it: no `M ... S` at all, and a `# SCGHOST` carrying the
# store that was withheld.  The diagnostic PRECEDES the retire because the
# tracer writes it at the SC_CHECK edge, before the retire group is flushed --
# the same binding direction as `# SCFAILRD`.
#
# This fixture is the A15 pair's third leg and it is what makes the negative
# control meaningful: against A15_FAIL_SPIKE it must exit 0 **with and without
# --no-a15**, because there is no longer a ghost record for A15 to remove.
A16_FAIL_RTL = """\
# SCGHOST 00 00000040 0001000c 4 000015b3
R 00 00000040 00008200 19c2aeaf 1d 00000001
R 00 00000042 00008204 4081 01 00000000
""".splitlines(True)


# --------------------------------------------------------------------------
# V4 (multi-hart) fixtures -- sleep truncation
#
# A tile hart (1..N-1) is launched by the bootrom loader, runs a handful of
# comparable retires and then executes `EXTINGUISH` -- a VestaRV CUSTOM
# instruction (`.insn r 0x0b,1,0`, encoding 0x0000100b) that the reference
# model cannot execute AT ALL.  The RTL was observed to emit
# `X <hart> <cycle> wfi_enter` IMMEDIATELY before that retire, which is the
# shape `--stop-before-sleep`'s adjacency assertion pins down.
#
# The retires and the Spike lines are RTL20/SPIKE20's own verbatim shapes with
# the hart field moved to 01 (`core   1:` on the Spike side, §1) -- the hart
# field is the only difference, so no new "golden" data is invented here.  The
# EXTINGUISH retire is written from the wire format: pc 0x820c, insn 0000100b,
# no register write.
# --------------------------------------------------------------------------

SLEEP_HDR = "# vesta_tracer TRACE_ENABLE=true vesta_trace hart=01\n"

SLEEP_RTL = """\
R 01 0000bf5a 00008200 a011 00 00000000
R 01 0000bf5b 00008204 4081 01 00000000
R 01 0000bf5c 00008206 4101 02 00000000
R 01 0000bf5d 00008208 4181 03 00000000
R 01 0000bf5e 0000820a 4201 04 00000000
""".splitlines(True)

SLEEP_SPIKE = """\
core   1: 3 0x00008200 (0xa011)
core   1: 3 0x00008204 (0x4081) x1  0x00000000
core   1: 3 0x00008206 (0x4101) x2  0x00000000
core   1: 3 0x00008208 (0x4181) x3  0x00000000
core   1: 3 0x0000820a (0x4201) x4  0x00000000
""".splitlines(True)

SLEEP_WFI = "X 01 0000bf5f wfi_enter\n"
SLEEP_WAKE = "X 01 0000bf60 wfi_wake\n"
SLEEP_EXT = "R 01 0000bf61 0000820c 0000100b 00 00000000\n"

# The interleaved shape the truncation must survive: hart 00 keeps retiring
# around hart 01's window and emits its OWN `wfi_enter` EARLIER in file order,
# so a cut computed before `--hart` filtering would land on the wrong record.
SLEEP_MIXED = """\
R 01 0000bf5a 00008200 a011 00 00000000
R 00 0000bf5a 00008300 4501 0a 00000000
R 01 0000bf5b 00008204 4081 01 00000000
X 00 0000bf5b wfi_enter
R 01 0000bf5c 00008206 4101 02 00000000
R 01 0000bf5d 00008208 4181 03 00000000
R 01 0000bf5e 0000820a 4201 04 00000000
X 01 0000bf5f wfi_enter
R 01 0000bf61 0000820c 0000100b 00 00000000
R 00 0000bf62 00008302 4581 0b 00000000
""".splitlines(True)

# --------------------------------------------------------------------------
# V4 fixtures -- the --hart filter on the A7 diagnostics
#
# `# IRETPOP` is a COMMENT, so the only sound association is "the LAST one of
# this tag in the line range" (compare.py `_DiagIndex.last_between`).  That
# means another hart's IRETPOP interleaved into the same file RETARGETS this
# hart's stacked-PC slot and flips the bracket from REDIRECTED to SEQUENTIAL.
#
# `BRK_RTL` is a REDIRECTED bracket: the ISR stores 00008210 to the very slot
# its own IRETPOP names, and the post-iret retire lands at 00008210, so the
# resume PC is verified against a value only the ISR's stores justify (it is
# NOT the T record's epc 00008204).  `BRK_ALIEN` is the contamination, and it
# is its own negative control: with it and without `--hart` the bracket
# collapses to SEQUENTIAL and the resume-PC verdict MISMATCHes.
# --------------------------------------------------------------------------

BRK_RTL = """\
R 00 00000100 00008200 a011 00 00000000
T 00 00000101 00000008 00008204 00000000 3
M 00 00000102 S 0000bfec 4 00008210
# IRETPOP 00 00000103 0000bfec
X 00 00000103 iret
R 00 00000104 00008210 4381 07 00000000
""".splitlines(True)

BRK_SPIKE = """\
core   0: 3 0x00008200 (0xa011)
core   0: 3 0x00008210 (0x4381) x7  0x00000000
""".splitlines(True)

BRK_ALIEN = "# IRETPOP 01 00000103 0000beef\n"


# --------------------------------------------------------------------------
# V4 fixtures -- Amendment A11, the SLEEP bracket
#
# A11 names two measured shapes and both are fixtured verbatim from its text:
#
#   WOKEN   `X wfi_enter`, the EXTINGUISH retire, `# IRQPUSH`, the legacy
#           sentinel `T`, the ISR body, `# IRETPOP`, `X iret` -- ONE window.
#           The `T` is INSIDE a window that opened earlier, so it must JOIN it,
#           never double-open: a second window would leave the outer one
#           unterminated and exit 1.  The ROM loader ISR overwrites the stacked
#           PC with the image ENTRY, so the bracket is REDIRECTED and the resume
#           PC is a value only the ISR's own store justifies (0x8210 -- NOT the
#           sentinel's epc 0x8202).
#   PARKED  `X wfi_enter` is the LAST record; no EXTINGUISH retire, no `T`, no
#           `iret`.  The window never closes and A11 says that is CORRECT.
#
# The retires reuse RTL20/SPIKE20's own verbatim lines; the EXTINGUISH retire
# (insn 0000100b), the `X` events and the sentinel `T` (cause 8000007f,
# tval = IVT entry 0x814c = slot 83 = CLINT msip, A8) are written from the wire
# format.  Negative controls are attached case by case below.
# --------------------------------------------------------------------------

SLEEP_BRK_RTL = """\
R 00 00000100 00008200 a011 00 00000000
X 00 00000101 wfi_enter
R 00 00000102 00008202 0000100b 00 00000000
# IRQPUSH 00 00000103 0000bfec 4 00008202
T 00 00000104 8000007f 00008202 0000814c 3
M 00 00000105 S 0000bfec 4 00008210
# IRETPOP 00 00000106 0000bfec
X 00 00000106 iret
R 00 00000107 00008210 4381 07 00000000
""".splitlines(True)

# Same two Spike lines as BRK_SPIKE: the reference executes the entry retire and
# then the landing retire, and nothing in between -- it cannot execute
# EXTINGUISH (A11) nor the legacy vectored ISR (A8) at all.
SLEEP_BRK_SPIKE = """\
core   0: 3 0x00008200 (0xa011)
core   0: 3 0x00008210 (0x4381) x7  0x00000000
""".splitlines(True)

# PARKED: the park is the last record.  Nothing follows, so nothing can be
# swallowed and there is nothing to realign to.
SLEEP_PARK_RTL = """\
R 00 00000100 00008200 a011 00 00000000
X 00 00000101 wfi_enter
""".splitlines(True)

SLEEP_PARK_SPIKE = """\
core   0: 3 0x00008200 (0xa011)
""".splitlines(True)

# PARKED with a tail: an un-closed sleep window must NOT swallow what follows
# it.  If it did, the RTL side would be one record short of the Spike side and
# the run would exit 2 -- which is exactly this case's negative control.
SLEEP_PARK_TAIL_RTL = """\
R 00 00000100 00008200 a011 00 00000000
X 00 00000101 wfi_enter
R 00 00000102 00008204 4081 01 00000000
""".splitlines(True)

SLEEP_PARK_TAIL_SPIKE = """\
core   0: 3 0x00008200 (0xa011)
core   0: 3 0x00008204 (0x4081) x1  0x00000000
""".splitlines(True)

# NESTED: a second `X wfi_enter` INSIDE the window takes its own stack level and
# is popped by its own `iret`; the outer window is closed only by the second
# one.  Exit 0 here is only reachable with stack nesting -- with a flag (or with
# the inner park ignored) the FIRST iret would close the window, the ISR's
# stacked-PC store would land outside it, and the resume PC would not verify.
SLEEP_NEST_RTL = """\
R 00 00000100 00008200 a011 00 00000000
X 00 00000101 wfi_enter
T 00 00000102 8000007f 00008202 0000814c 3
X 00 00000103 wfi_enter
X 00 00000104 iret
M 00 00000105 S 0000bfec 4 00008210
# IRETPOP 00 00000106 0000bfec
X 00 00000106 iret
R 00 00000107 00008210 4381 07 00000000
""".splitlines(True)

# A sleep window that CLOSES but carries neither an adopted `T` nor a store to
# the stacked-PC slot: no epc, no redirect, so no resume PC exists to verify.
# A11's woken shape always has one, so this must be refused, never realigned
# onto a guess.
SLEEP_BARE_RTL = """\
R 00 00000100 00008200 a011 00 00000000
X 00 00000101 wfi_enter
X 00 00000102 iret
R 00 00000103 00008204 4081 01 00000000
""".splitlines(True)


def sub(lines, index, old, new):
    """Copy `lines` with a substring replaced on one line (fixture mutation)."""
    out = list(lines)
    assert old in out[index], "fixture drift: %r not in %r" % (old, out[index])
    out[index] = out[index].replace(old, new)
    return out


def main():
    h = Harness()
    R = [HEADER] + RTL20
    S = list(SPIKE20)

    # ---------------- exit 0 : clean match -----------------------------
    h.case("exit0 clean match (real tracer vs real spike, 20 records)",
           0, R, S,
           expect_in_stderr=["compared records       20",
                             "both streams ended together"])
    h.case("exit0 --max-records bound", 0, R, S, extra=("--max-records", "5"),
           expect_in_stderr=["compared records       5"])
    h.case("exit0 --hart 00 selects the stream", 0, R, S,
           extra=("--hart", "00"))
    h.case("exit0 memory + CSR + AMO shapes (M L / M S / C)",
           0, [HEADER] + MEM_RTL, MEM_SPIKE,
           expect_in_stderr=["compared records       13"])
    h.case("exit0 an M L's size/data are NOT compared (§8)",
           0, [HEADER] + sub(MEM_RTL, 3, "L 00008690 1 000000aa",
                             "L 00008690 4 deadbeef"), MEM_SPIKE)
    h.case("exit0 Amendment A2 same-pc R run sorted by rd",
           0, [HEADER] + A2_RTL, A2_SPIKE,
           expect_in_stderr=["compared records       4"])
    h.case("exit0 §3 ordering trap: CSR field before a GPR field",
           0, [HEADER] + ORDER_RTL, ORDER_SPIKE)
    h.case("exit0 '#' diagnostics counted, not compared",
           0, [HEADER,
               "# CSRLEAK 00 0000bf60 12 300 00000000\n",
               "# CSRLEAK 00 0000bf61 12 300 00000000\n",
               "# SCFAILRD 00 0000bf62 00008308\n",
               "# TRAPSTORE 00 0000bf63 00008690\n",
               "# ADDRMISMATCH 00 0000bf64 00008690 00008694\n",
               "# LANEMISMATCH 00 0000bf65 00008691 0\n",
               "# INIT 00 00000001\n",
               "# IRETPHANTOM 00 0000bf66 00000000\n"] + RTL20, S,
           expect_in_stderr=["# CSRLEAK        2", "# SCFAILRD       1",
                             "# TRAPSTORE      1", "# ADDRMISMATCH   1",
                             "# LANEMISMATCH   1", "# INIT           1",
                             "# IRETPHANTOM    1"])
    h.case("exit0 X records are dropped, never compared (§5)",
           0, [HEADER] + RTL20[:3] + ["X 00 0000bf60 wfi_enter\n",
                                      "X 00 0000bf61 wfi_wake\n"] + RTL20[3:],
           S)
    h.case("exit0 missing tracer provenance header warns but does not fail",
           0, RTL20, S,
           expect_in_stderr=["no '# vesta_tracer"])

    # ---------------- exit 1 : divergence ------------------------------
    h.case("exit1 wrong rdval", 1, [HEADER] + sub(RTL20, 5,
           "05 00000000", "05 00000001"), S,
           expect_in_stdout=["DIVERGENCE at compared record #5",
                             "rdval: rtl=00000001 spike=00000000",
                             "; c.li t0,0"])
    h.case("exit1 missing R record", 1,
           [HEADER] + RTL20[:7] + RTL20[8:], S,
           expect_in_stdout=["DIVERGENCE at compared record #7",
                             "pc: rtl=00008212 spike=00008210"])
    h.case("exit1 extra M record", 1,
           [HEADER] + RTL20[:3] + ["M 00 0000bf60 L 00008690 4 00000000\n"]
           + RTL20[3:], S,
           expect_in_stdout=["record KIND differs: rtl=M spike=R"])
    h.case("exit1 wrong store size", 1,
           [HEADER] + sub(MEM_RTL, 1, "S 00008690 1", "S 00008690 2"),
           MEM_SPIKE, expect_in_stdout=["size: rtl=2 spike=1"])
    h.case("exit1 wrong store data", 1,
           [HEADER] + sub(MEM_RTL, 5, "4 00aa00aa", "4 00aa00ab"),
           MEM_SPIKE, expect_in_stdout=["data: rtl=00aa00ab spike=00aa00aa"])
    h.case("exit1 wrong load address (the L field that IS compared)", 1,
           [HEADER] + sub(MEM_RTL, 3, "L 00008690", "L 00008694"),
           MEM_SPIKE, expect_in_stdout=["addr: rtl=00008694 spike=00008690"])
    h.case("exit1 wrong CSR value", 1,
           [HEADER] + sub(MEM_RTL, 10, "b00 00000000", "b00 00000001"),
           MEM_SPIKE, expect_in_stdout=["val: rtl=00000001 spike=00000000"])
    h.case("exit1 A2 negative control: sorted run, one wrong rdval", 1,
           [HEADER] + sub(A2_RTL, 2, "02 0000bff0", "02 0000bff4"), A2_SPIKE,
           expect_in_stdout=["rdval: rtl=0000bff4 spike=0000bff0"])
    h.case("exit1 T record = control-flow divergence (§4)", 1,
           [HEADER] + RTL20[:3] + ["T 00 0000bf60 00000002 0000820e 00000000 3\n"]
           + RTL20[3:], S,
           expect_in_stdout=["CONTROL-FLOW DIVERGENCE",
                             "cause=00000002 epc=0000820e"])
    h.case("exit1 entry PC never reached on the RTL side", 1, R, S,
           extra=("--entry", "0x9999"),
           expect_in_stdout=["never reaches the entry PC 00009999"])
    h.case("exit1 entry PC never reached on the Spike side", 1,
           R + ["R 00 0000bf6e 00009000 4a01 14 00000000\n"], S,
           extra=("--entry", "0x9000"),
           expect_in_stdout=["Spike stream never reaches the entry PC"])

    # ---------------- exit 2 : RTL exhausted early ---------------------
    h.case("exit2 RTL stream exhausted early", 2, [HEADER] + RTL20[:10], S,
           expect_in_stdout=["RTL STREAM EXHAUSTED after 10 matching records",
                             "SPIKE context"])

    # ---------------- exit 3 : Spike exhausted (NEVER success) ---------
    h.case("exit3 truncated Spike log while RTL continues", 3, R, S[:10],
           expect_in_stdout=["SPIKE STREAM EXHAUSTED after 10 matching",
                             "THIS IS NEVER SUCCESS"])

    # ---------------- exit 4 : Amendment A5 x-corruption ---------------
    h.case("exit4 x nibble in an RTL rdval", 4,
           [HEADER] + sub(RTL20, 4, "04 00000000", "04 000000bx"), S,
           expect_in_stdout=["X-CORRUPTED RECORD after 4 matching records",
                             "[Amendment A5]"])
    h.case("exit4 x nibble in an RTL pc", 4,
           [HEADER] + sub(RTL20, 6, "0000820e", "000082xe"), S,
           expect_in_stdout=["X-CORRUPTED RECORD"])
    h.case("exit0 a pre-entry x record is counted, not fatal", 0,
           [HEADER, "R 00 00000001 00000070 0005a703 0e 000000bx\n"] + RTL20,
           S, expect_in_stderr=["x-tainted records      1 total "
                                "(1 pre-entry, 0 in the compared window)"])

    # ---------------- exit 5 : parse / usage ---------------------------
    h.case("exit5 RTL field width violation (§0)", 5,
           [HEADER] + sub(RTL20, 0, "00008200", "0008200"), S,
           expect_in_stderr=["field pc: width 7, expected 8"])
    h.case("exit5 RTL unknown record kind", 5,
           [HEADER, "Q 00 0000bf5a 00008200 a011 00 00000000\n"] + RTL20, S,
           expect_in_stderr=["unknown record kind 'Q'"])
    h.case("exit5 RTL uppercase hex (the wire format is lowercase)", 5,
           [HEADER] + sub(RTL20, 0, "a011", "A011"), S,
           expect_in_stderr=["is not lowercase hex"])
    h.case("exit5 Spike unrecognised trailing field", 5, R,
           sub(S, 0, "(0xa011)", "(0xa011) bogus 0x1"),
           expect_in_stderr=["unrecognised trailing field 'bogus'"])
    h.case("exit5 Spike x0 write breaks the rd=00 invariant (§1)", 5, R,
           sub(S, 1, "x1  0x", "x0  0x"),
           expect_in_stderr=["an x0 write appeared"])
    h.case("exit5 Spike non-commit line is not swallowed", 5, R,
           ["Warning: something happened\n"] + S,
           expect_in_stderr=["not a Spike commit line"])
    h.case("exit5 Spike 'mem' with no address", 5, R,
           sub(S, 0, "(0xa011)", "(0xa011) mem"),
           expect_in_stderr=["'mem' with no address"])
    h.case("exit5 Spike odd-width store data cannot encode a size", 5, R,
           sub(S, 0, "(0xa011)", "(0xa011) mem 0x00008690 0xaaa"),
           expect_in_stderr=["odd hex-digit count"])
    h.case("exit5 multi-hart stream without --hart", 5,
           [HEADER] + sub(RTL20, 3, "R 00 ", "R 01 "), S,
           expect_in_stderr=["pass --hart to select one"])

    rtl_ok = h.write("ok.trace", R)
    spk_ok = h.write("ok.spike.log", S)
    h.raw("exit5 missing --entry", [PY, COMPARE, "--rtl", rtl_ok,
                                   "--spike", spk_ok], 5,
          ["usage error"])
    h.raw("exit5 non-hex --entry", [PY, COMPARE, "--rtl", rtl_ok, "--spike",
                                    spk_ok, "--entry", "0xzz"], 5,
          ["--entry '0xzz' is not hex"])
    h.raw("exit5 --rtl file does not exist",
          [PY, COMPARE, "--rtl", rtl_ok + ".nope", "--spike", spk_ok,
           "--entry", "0x8200"], 5, ["cannot read --rtl"])
    h.raw("exit5 --spike file does not exist",
          [PY, COMPARE, "--rtl", rtl_ok, "--spike", spk_ok + ".nope",
           "--entry", "0x8200"], 5, ["cannot read --spike"])
    h.raw("exit0 --count prints the RTL window size",
          [PY, COMPARE, "--rtl", rtl_ok, "--spike", spk_ok, "--entry",
           "0x8200", "--count"], 0, ["--count: 20 compared RTL records"])
    h.raw("exit0 --quiet suppresses the summary",
          [PY, COMPARE, "--rtl", rtl_ok, "--spike", spk_ok, "--entry",
           "0x8200", "--quiet"], 0)

    # ---------------- V4 : --stop-before-sleep -------------------------
    # Every case pairs with something that proves it is not vacuous: the
    # truncation cases have a no-option control that FAILS, the adjacency
    # warning has the adjacent fixture that must NOT warn, and the no-op case
    # has the two truncating cases as its controls.
    h.case("exit0 --stop-before-sleep truncates at the X wfi_enter",
           0, [SLEEP_HDR] + SLEEP_RTL + [SLEEP_WFI, SLEEP_EXT], SLEEP_SPIKE,
           extra=("--stop-before-sleep",),
           expect_in_stderr=["the first wfi_enter",
                             "5 compared record(s) kept",
                             "wfi_enter immediately precedes the EXTINGUISH "
                             "retire, as observed",
                             "compared records       5",
                             "both streams ended together"])
    h.case("exit3 negative control: the same stream WITHOUT the option",
           3, [SLEEP_HDR] + SLEEP_RTL + [SLEEP_WFI, SLEEP_EXT], SLEEP_SPIKE,
           expect_in_stdout=["SPIKE STREAM EXHAUSTED after 5 matching",
                             "; extinguish"])
    h.case("exit0 --stop-before-sleep truncates at the EXTINGUISH retire",
           0, [SLEEP_HDR] + SLEEP_RTL + [SLEEP_EXT], SLEEP_SPIKE,
           extra=("--stop-before-sleep",),
           expect_in_stderr=["the first EXTINGUISH",
                             "5 compared record(s) kept",
                             "compared records       5"])
    h.case("exit0 --stop-before-sleep is a reported NO-OP with no trigger",
           0, [SLEEP_HDR] + SLEEP_RTL, SLEEP_SPIKE,
           extra=("--stop-before-sleep",),
           expect_in_stderr=["NO-OP: the entry-aligned window (5 record(s))",
                             "A hart that never sleeps is legitimate",
                             "compared records       5"])
    h.case("exit0 --stop-before-sleep warns when the triggers are NOT adjacent",
           0, [SLEEP_HDR] + SLEEP_RTL + [SLEEP_WFI, SLEEP_WAKE, SLEEP_EXT],
           SLEEP_SPIKE, extra=("--stop-before-sleep",),
           expect_in_stderr=["THE SLEEP-ENTRY SEQUENCE IS NOT THE OBSERVED "
                             "SHAPE",
                             "BOTH present but NOT ADJACENT",
                             "1 record(s)",
                             "compared records       5"])
    h.case("exit5 --stop-before-sleep leaving zero compared records is an error",
           5, [SLEEP_HDR, "R 01 0000bf5a 00008200 0000100b 00 00000000\n"]
           + SLEEP_RTL[1:], SLEEP_SPIKE, extra=("--stop-before-sleep",),
           expect_in_stdout=["WOULD LEAVE NOTHING TO COMPARE",
                             "would be VACUOUS"],
           expect_in_stderr=["0 compared record(s) kept"])
    h.case("exit0 --stop-before-sleep is computed AFTER --hart filtering",
           0, [SLEEP_HDR] + SLEEP_MIXED, SLEEP_SPIKE,
           extra=("--stop-before-sleep", "--hart", "01"),
           expect_in_stderr=["the first wfi_enter",
                             "5 compared record(s) kept",
                             "compared records       5"])

    # ---------------- V4 : --hart filters the A7 diagnostics -----------
    h.case("exit0 --bracket-isr REDIRECTED bracket verifies the resume PC",
           0, [HEADER] + BRK_RTL, BRK_SPIKE, extra=("--bracket-isr",),
           expect_in_stderr=["case=REDIRECTED",
                             "expected=00008210 actual=00008210  OK"])
    h.case("exit1 negative control: another hart's '# IRETPOP' retargets it",
           1, [HEADER] + BRK_RTL[:4] + [BRK_ALIEN] + BRK_RTL[4:], BRK_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stdout=["ISR BRACKET 0: RESUME PC MISMATCH",
                             "stacked-PC slot     : 0000beef"])
    h.case("exit0 --hart filters the RTL diagnostics, not just the records",
           0, [HEADER] + BRK_RTL[:4] + [BRK_ALIEN] + BRK_RTL[4:], BRK_SPIKE,
           extra=("--bracket-isr", "--hart", "00"),
           expect_in_stderr=["case=REDIRECTED",
                             "expected=00008210 actual=00008210  OK"])

    # ---------------- V4 : Amendment A11, the SLEEP bracket ------------
    # Each case's control is named in its comment; the two structural ones
    # (double-open, swallowed tail) are proved by exit codes that can only be
    # reached when the stack/giveback behaviour is right.
    h.case("exit0 A11 a bracket OPENS on 'X wfi_enter' (woken hart)",
           0, [HEADER] + SLEEP_BRK_RTL, SLEEP_BRK_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stderr=["kind=SLEEP+T", "wfi_enter",
                             "case=REDIRECTED",
                             "expected=00008210 actual=00008210  OK",
                             "compared records       2"])
    h.case("exit1 A11 negative control: the same stream WITHOUT --bracket-isr",
           1, [HEADER] + SLEEP_BRK_RTL, SLEEP_BRK_SPIKE,
           expect_in_stdout=["DIVERGENCE at compared record #1",
                             "; extinguish"])
    h.case("exit0 A11 the woken window's inner T JOINS it, never double-opens",
           0, [HEADER] + SLEEP_BRK_RTL, SLEEP_BRK_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stderr=["bracket census         1 bracket(s)",
                             "kind=SLEEP+T",
                             "ivt=0000814c src=83 (CLINT msip)"])
    h.case("exit0 A11 a never-closing sleep window is CORRECT, not an error",
           0, [HEADER] + SLEEP_PARK_RTL, SLEEP_PARK_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stderr=["kind=SLEEP ", "case=PARKED",
                             "the hart never woke",
                             "compared records       1",
                             "both streams ended together"])
    h.case("exit0 A11 a never-closing sleep window does NOT swallow the tail",
           0, [HEADER] + SLEEP_PARK_TAIL_RTL, SLEEP_PARK_TAIL_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stderr=["case=PARKED",
                             "1 compared record(s) after the park were LEFT IN",
                             "compared records       2",
                             "both streams ended together"])
    h.case("exit1 A11 negative control: the given-back tail IS still compared",
           1, [HEADER] + sub(SLEEP_PARK_TAIL_RTL, 2, "01 00000000",
                             "01 00000001"),
           SLEEP_PARK_TAIL_SPIKE, extra=("--bracket-isr",),
           expect_in_stdout=["DIVERGENCE at compared record #1",
                             "rdval: rtl=00000001 spike=00000000"])
    h.case("exit0 A11 sleep windows nest as a STACK (inner park, inner iret)",
           0, [HEADER] + SLEEP_NEST_RTL, SLEEP_BRK_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stderr=["bracket census         1 bracket(s)",
                             "nested=0 nested_sleep=1",
                             "case=REDIRECTED",
                             "expected=00008210 actual=00008210  OK"])
    h.case("exit1 A11 negative control: drop the inner iret -> UNTERMINATED",
           1, [HEADER] + SLEEP_NEST_RTL[:4] + SLEEP_NEST_RTL[5:],
           SLEEP_BRK_SPIKE, extra=("--bracket-isr",),
           expect_in_stdout=["IS UNTERMINATED",
                             "the SLEEP+T window opened at"])
    h.case("exit1 A11 the landing check still fires inside a sleep window",
           1, [HEADER] + sub(SLEEP_BRK_RTL, 5, "4 00008210", "4 0000beef"),
           SLEEP_BRK_SPIKE, extra=("--bracket-isr",),
           expect_in_stdout=["RESUME PC MISMATCH",
                             "sleep entry         : X 00 00000101 wfi_enter",
                             "case                : REDIRECTED",
                             "expected resume     : 0000beef",
                             "actual resume       : 00008210"])
    h.case("exit1 A11 a closed sleep window with no resume PC is refused",
           1, [HEADER] + SLEEP_BARE_RTL, SLEEP_PARK_TAIL_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stdout=["HAS NO DETERMINABLE RESUME PC",
                             "no '# IRETPOP'-named store and no trap `epc`"])

    # ---------------- in-process unit assertions -----------------------
    recs, nf = parse_spike_line(
        "core   0: 3 0x00008262 (0x00b6a72f) x14 0x80000000 "
        "mem 0x00008308 mem 0x00008308 0x7ffff800", "u", 1, 7)
    h.check("AMO explodes to R + M L + M S in that order",
            [r.kind for r in recs] == ["R", "M", "M"] and
            recs[1].f[0] == "L" and recs[2].f[0] == "S",
            "got %r" % (recs,))
    h.check("AMO load has no size/data (Spike emits address only)",
            recs[1].f[2] is None and recs[1].f[3] is None, "got %r" % (recs[1],))
    h.check("AMO store size/data normalised",
            recs[2].f[1:] == ("00008308", "4", "7ffff800"), "got %r" % (recs[2],))
    h.check("cycle on the Spike side is the retire ordinal",
            recs[0].cycle == "00000007", recs[0].cycle)
    h.check("rd is 2-digit HEX (x14 -> 0e)", recs[0].f[2] == "0e",
            recs[0].f[2])

    recs, _ = parse_spike_line(
        "core   0: 3 0x0000827a (0xb0041a73) x20 0x00000029 "
        "c2816_mcycle 0x00000000", "u", 1, 0)
    h.check("CSR decimal 2816 -> 3-hex-digit b00 and the name is discarded",
            recs[1].kind == "C" and recs[1].f == ("b00", "00000000"),
            "got %r" % (recs[1],))
    h.check("R precedes C in the emitted order (§0)",
            [r.kind for r in recs] == ["R", "C"], "got %r" % (recs,))

    recs, _ = parse_spike_line("core   0: 3 0x00008200 (0xa011)", "u", 1, 0)
    h.check("a 16-bit instruction keeps its 4-digit native width",
            recs[0].f[1] == "a011", recs[0].f[1])
    h.check("no register write -> rd=00 rdval=00000000",
            recs[0].f[2:] == ("00", "00000000"), "got %r" % (recs[0],))

    for data, size in (("0xaa", "1"), ("0x00aa", "2"), ("0x00aa00aa", "4")):
        recs, _ = parse_spike_line(
            "core   0: 3 0x00008200 (0x00110023) mem 0x00008690 %s" % data,
            "u", 1, 0)
        h.check("store data %-10s -> size %s byte(s)" % (data, size),
                recs[1].f[2] == size, "got %r" % (recs[1],))

    recs, _ = parse_spike_line(
        "core   0: 3 0x00008200 (0x00302073) c1_fflags 0x00000001 "
        "x20 0x0000002e", "u", 1, 0)
    h.check("prefix classification: c1_fflags before x20 is still a CSR",
            [r.kind for r in recs] == ["R", "C"] and
            recs[0].f[2] == "14" and recs[1].f[0] == "001",
            "got %r" % (recs,))

    a2_rtl = compared_stream([parse_rtl_line(l, "u", i) for i, l
                              in enumerate(A2_RTL)])
    a2_spk = []
    for i, l in enumerate(A2_SPIKE):
        got, _ = parse_spike_line(l, "u", i, i)
        a2_spk.extend(got)
    h.check("A2 negative control: the two streams DIFFER before sorting",
            [r.key() for r in a2_rtl] != [r.key() for r in a2_spk],
            "the A2 fixture does not exercise the sort")
    h.check("A2: the two streams AGREE after canonicalisation",
            [r.key() for r in canonicalise_a2(a2_rtl)] ==
            [r.key() for r in canonicalise_a2(a2_spk)],
            "canonicalise_a2 did not converge the fixture")

    # ---------------- the whole real 462-record window -----------------
    real_trace = os.path.join(
        HERE, "..", "..", "xcelium", "riscv_test", "behavioral_mp",
        "vesta_trace_h00.trace")
    real_spike = os.environ.get("COSIM_REAL_SPIKE_LOG", "")
    if os.path.exists(real_trace) and real_spike and os.path.exists(real_spike):
        h.raw("exit0 REAL rv32ui-p-add: 462-record entry-aligned window",
              [PY, COMPARE, "--rtl", real_trace, "--spike", real_spike,
               "--entry", "0x8200", "--max-records", "462"], 0,
              ["compared records       462"])
        h.raw("exit2 REAL unbounded: RTL ends at the a0 watch, Spike spins",
              [PY, COMPARE, "--rtl", real_trace, "--spike", real_spike,
               "--entry", "0x8200"], 2,
              ["RTL stream exhausted early after 462 matching records"])
    else:
        print("SKIP  real-artifact end-to-end case "
              "(set COSIM_REAL_SPIKE_LOG=<spike log for rv32ui-p-add>)")

    # ------- A11/C2: the WOKEN-then-truncated sleep window (T1 shape) ----
    # Regression guard for the C2 fix: keyed on `not adopted` this shape reported
    # DIVERGE on all three shmem_mp tiles for behaving exactly as T1 describes.
    h.case("exit0 A11 a WOKEN sleep window truncated mid-ISR is not a divergence",
           0, [HEADER] + SLEEP_WOKEN_TRUNC_RTL, SLEEP_WOKEN_TRUNC_SPIKE,
           extra=("--bracket-isr",),
           expect_in_stderr=["contains the EXTINGUISH retire",
                             "PRE-PARK prefix",
                             "the hart WAS woken",
                             "compared records       1"])
    # ...and the EXTINGUISH retire itself must never reach the comparison: the
    # reference cannot execute a custom opcode, so if it leaked in it would
    # diverge here rather than pass.
    h.check("A11/C2 the EXTINGUISH retire stayed OUT of the compared stream",
            True, "asserted by the exit-0 case above (spike has 1 record)")

    # ---------------- Amendment A15: the failed-SC ghost store ----------
    # THE POSITIVE and THE NEGATIVE CONTROL are the same two streams with and
    # without the option, which is the only way to show the mechanism is
    # load-bearing rather than decorative.
    h.case("exit0 A15 drops a FAILED sc.w's never-committed store",
           0, [HEADER] + A15_FAIL_RTL, A15_FAIL_SPIKE,
           expect_in_stderr=["A15 scfail ghost       1 sc.w retire(s), 1 failed",
                             "1 ghost store(s) dropped",
                             "pc 00008200 -> addr 0001000c  x1"])
    h.case("exit1 A15 NEGATIVE CONTROL: --no-a15 leaves the ghost and diverges",
           1, [HEADER] + A15_FAIL_RTL, A15_FAIL_SPIKE, extra=("--no-a15",),
           expect_in_stderr=["DISABLED by --no-a15"])
    h.case("exit0 A15 leaves a SUCCEEDING sc.w's real store alone",
           0, [HEADER] + A15_OK_RTL, A15_OK_SPIKE,
           expect_in_stderr=["1 sc.w retire(s), 0 failed", "0 ghost store(s)"])
    # The discriminator itself: a failed SC whose store is MISSING from the RTL
    # is left as a divergence -- A15 removes a record, it never invents one.
    h.case("exit1 A15 does not paper over a MISSING store on a SUCCESS",
           1, [HEADER] + [l for l in A15_OK_RTL if not l.startswith("M ")],
           A15_OK_SPIKE)
    h.case("exit0 A15 refuses to guess when rd is x0 (nothing dropped, reported)",
           0, [HEADER] + A15_X0_RTL, A15_X0_SPIKE,
           expect_in_stderr=["INDETERMINATE", "was NOT dropped"])

    # ---------------- Amendment A16: the ghost is gone at SOURCE ---------
    # Same failed sc.w, same reference, post-A16 trace. Two things must hold and
    # the second is the point of the amendment:
    #   * A15 finds nothing to drop and says WHY it found nothing -- naming
    #     A16, not the pre-A16 "the core declined the write locally", which
    #     would be a false statement about every cross-hart kill;
    #   * the `--no-a15` NEGATIVE CONTROL becomes INERT. V4 proved A15
    #     load-bearing by flipping this control 0 -> 1. That it no longer flips
    #     is the evidence that A16 removed the shape at source rather than
    #     moving numbers: the comparator no longer NEEDS the exception.
    h.case("exit0 A16 post-fix trace: no ghost to drop, and the note says A16",
           0, [HEADER] + A16_FAIL_RTL, A15_FAIL_SPIKE,
           expect_in_stderr=["0 ghost store(s) dropped",
                             "[# SCGHOST, Amendment A16]"])
    h.case("exit0 A16 makes --no-a15 INERT (V4's control flipped 0->1; now 0->0)",
           0, [HEADER] + A16_FAIL_RTL, A15_FAIL_SPIKE, extra=("--no-a15",))
    # And the shim is NOT dead: the pre-A16 trace still needs A15, both polarities.
    h.case("exit0 A15 SHIM still drops the ghost in a PRE-A16 trace",
           0, [HEADER] + A15_FAIL_RTL, A15_FAIL_SPIKE,
           expect_in_stderr=["1 ghost store(s) dropped"])
    h.case("exit1 A15 SHIM off + PRE-A16 trace still diverges (control alive)",
           1, [HEADER] + A15_FAIL_RTL, A15_FAIL_SPIKE, extra=("--no-a15",))

    # ---- §6.1 test_bracket_interior_load_dropped (A13's PARTITION) -------
    # This one tests mk_inject.py, not compare.py, but it belongs with the other
    # bracket tests: it pins the half of A13 that FIXES V3's structural hole.
    # An unmodelled-region load INSIDE a bracket must be DROPPED from the mainline
    # replay list (the reference never executes the interior, so it never asks for
    # the value and V3's emitted entry made vesta_ref die with exit 7
    # INJECT-MISMATCH), and the drop must be COUNTED, never silent.
    mkinj = os.path.join(HERE, "mk_inject.py")
    tdir = tempfile.mkdtemp(prefix="cosim_a13_")
    try:
        tr = os.path.join(tdir, "t_h00.trace")
        with open(tr, "w") as fh:
            fh.write(HEADER)
            fh.writelines([
                # one MMIO load OUTSIDE any bracket -> must be KEPT
                "R 00 00000010 00008200 00012083 01 000000aa\n",
                "M 00 00000010 L 00004204 4 000000aa\n",
                # a park, then an MMIO load and a plant-window load INSIDE it
                "X 00 00000011 wfi_enter\n",
                "R 00 00000012 000002b4 0000100b 00 00000000\n",
                "T 00 00000013 8000007f 000002b8 0000814c 3\n",
                "R 00 00000014 0000814c 00008067 00 00000000\n",
                "M 00 00000014 L 00004204 4 000000bb\n",       # interior MMIO
                "R 00 00000015 00000300 00012083 01 000000cc\n",
                "M 00 00000015 L 00010500 4 000000cc\n",       # interior PLANT
                "M 00 00000016 S 00008000 4 deadbeef\n",
                "# IRETPOP 00 00000017 0000bff8\n",
                "X 00 00000017 iret\n",
                "R 00 00000018 000082fc 00012083 01 000000dd\n",
                "M 00 00000018 L 00010504 4 000000dd\n",       # mainline PLANT
            ])
        inj = os.path.join(tdir, "t.inject"); brk = os.path.join(tdir, "t.bracket")
        p = subprocess.Popen(
            [PY, mkinj, "--rtl", tr, "-o", inj, "--bracket-out", brk,
             "--mmio", "0x4000:0x4000", "--plant", "0xc000:0x14000"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        _, se = p.communicate(); se = se.decode()
        ilines = [l.split() for l in open(inj) if l.strip() and not l.startswith("#")]
        blines = open(brk).read()
        h.check("A13 the OUTSIDE-bracket MMIO load is kept in the inject list",
                len(ilines) == 1 and ilines[0][0] == "00004204",
                "inject list = %r (want exactly the 00004204 record)" % (ilines,))
        h.check("A13 the INTERIOR MMIO load is DROPPED from the inject list",
                all(l[2] != "000000bb" for l in ilines),
                "the interior value 000000bb reached the mainline list: %r" % (ilines,))
        h.check("A13 the INTERIOR plant-window load emits no mainline P record",
                "P 1 00010500" not in blines and "00010500" not in
                "\n".join(l for l in blines.splitlines() if l.startswith("P ")),
                "an interior plant leaked into a P record")
        h.check("A13 the MAINLINE plant-window load DOES emit a P record",
                any(l.startswith("P ") and "00010504" in l
                    for l in blines.splitlines()),
                "the post-bracket plant is missing from %s" % brk)
        h.check("A13 the drop is COUNTED, never silent (census + annotation)",
                "DROPPED" in blines and "census:" in blines
                and "dropped load(s)" in se,
                "no DROPPED annotation / census; stderr was:\n%s" % se)
        h.check("A13 the census separates mmio from plant drops exactly",
                "1 mmio + 1 plant" in blines,
                "census does not read '1 mmio + 1 plant':\n%s"
                % "\n".join(l for l in blines.splitlines() if "census" in l))
    finally:
        shutil.rmtree(tdir, ignore_errors=True)

    # ---- A16 in mk_inject: the `ext` failure shape gets a real witness ---
    # Pre-A16 the injector inferred "resv_unit suppressed the write" from THE
    # PRESENCE OF A FOLLOWING STORE -- i.e. it read the defect A15 exists to
    # delete as its own instrument, so after A16 that census would silently
    # read 0. It now counts `# SCGHOST`. Both legs are exercised, because a
    # counter that has only ever been seen at 0 has not been tested (R-W4-2):
    #   leg 1  rd=1 + # SCGHOST      -> ext-shape=1, and NO warning
    #   leg 2  rd=0 + # SCGHOST      -> the new cross-check FIRES
    # Leg 2's shape cannot occur in the RTL (the core computes rd FROM
    # sc_fail_ext), which is exactly why it needs a fixture: it is the check
    # that would otherwise be added to the tool having never once run.
    tdir = tempfile.mkdtemp(prefix="cosim_a16_")
    try:
        for leg, rdval, want_ext, want_warn in (
                ("rd=1", "00000001", "ext-shape=1", False),
                ("rd=0", "00000000", "ext-shape=0", True)):
            tr = os.path.join(tdir, "g_h00.trace")
            with open(tr, "w") as fh:
                fh.write(HEADER)
                fh.writelines([
                    "# SCGHOST 00 00000040 0001000c 4 000015b3\n",
                    "R 00 00000040 00008200 19c2aeaf 1d %s\n" % rdval,
                    "R 00 00000042 00008204 4081 01 00000000\n",
                ])
            inj = os.path.join(tdir, "g.inject")
            brk = os.path.join(tdir, "g.bracket")
            p = subprocess.Popen(
                [PY, mkinj, "--rtl", tr, "-o", inj, "--bracket-out", brk,
                 "--mmio", "0x4000:0x4000", "--plant", "0xc000:0x14000"],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            _, se = p.communicate(); se = se.decode()
            h.check("A16 mk_inject counts # SCGHOST as the ext shape (%s)" % leg,
                    want_ext in se,
                    "census does not read %r; stderr was:\n%s" % (want_ext, se))
            fired = "SCGHOST" in se and "claims success" in se
            h.check("A16 rd/SCGHOST disagreement %s (%s)"
                    % ("is REPORTED" if want_warn else "is silent", leg),
                    fired == want_warn,
                    "warning %s; stderr was:\n%s"
                    % ("missing" if want_warn else "fired unexpectedly", se))
    finally:
        shutil.rmtree(tdir, ignore_errors=True)

    # ---- A13/A6 SUB-WORD PLANT LANE SELECT (vesta_ref) -------------------
    # A real bug, caught only by the full sh* suite: an `M ... L` data field is the
    # RAW BUS WORD (A6), so a plant of `size` bytes at `addr` must poke
    #     word >> 8*(addr mod 4)
    # not the word's low bytes. An `M ... S` data field is right-justified (§2), so
    # S must NOT be shifted -- the two record kinds genuinely differ, which is why
    # this went unnoticed while every Stage 2-5 shared access was word-wide.
    # Verified by EXECUTION against the built reference, both polarities, using the
    # verbatim numbers from rv32ui-p-shmem hart 0.
    vref = os.path.join(os.path.dirname(HERE), "..", "xcelium", "riscv_test",
                        "behavioral_mp", "cosim_work", "vesta_ref")
    vref = os.path.abspath(vref)
    env_sh = os.path.expanduser("~/local/spike_env.sh")
    if os.path.exists(vref) and os.path.exists(env_sh):
        tdir = tempfile.mkdtemp(prefix="cosim_lane_")
        try:
            # A 2-instruction RAM program at 0x8000:  lbu t2,9(t0) ; nop
            # t0 starts 0, so 9(t0) is address 0x9 -- inside --mem, byte offset 1.
            prog = os.path.join(tdir, "p.bin")
            with open(prog, "wb") as fh:
                #  0092c383 = lbu t2,9(t0)      0x00000013 = nop
                fh.write(b"\x83\xc3\x92\x00" + b"\x13\x00\x00\x00")
            inj = os.path.join(tdir, "e.inject")
            open(inj, "w").write("")           # no MMIO loads at all
            brk = os.path.join(tdir, "p.bracket")
            # plant the RAW WORD beef33ee for a 1-byte load at 0x9:
            # the addressed byte is (0xbeef33ee >> 8*(9 mod 4)) & 0xff = 0x33.
            open(brk, "w").write("P 0 00000009 1 beef33ee\n")
            log = os.path.join(tdir, "c.log")
            cmd = (". %s; %s cosim --rom %s --rom-base 0x0 --rom-format bin "
                   "--pc 0x8000 --mem 0x0:0x20000 --mmio 0x4000:0x4000 "
                   "--isa rv32imac_zicsr --priv m --instructions 1 "
                   "--inject %s --bracket %s --log %s"
                   % (env_sh, vref, prog, inj, brk, log))
            # --rom loads at 0x0; move the program to 0x8000 by padding instead.
            with open(prog, "wb") as fh:
                fh.write(b"\x00" * 0x8000 + b"\x83\xc3\x92\x00" + b"\x13\x00\x00\x00")
            p = subprocess.Popen(["bash", "-c", cmd], stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE)
            _, se = p.communicate()
            body = open(log).read() if os.path.exists(log) else ""
            h.check("A13/A6 a sub-word plant serves the ADDRESSED lane, not the low byte",
                    "0x00000033" in body,
                    "lbu t2,9(t0) with plant word beef33ee must commit x7=0x33; "
                    "0x000000ee means the lane select is missing. log=%r stderr=%r"
                    % (body.strip()[:200], se.decode()[-300:]))
            h.check("A13/A6 negative control: the LOW byte 0xee is NOT what commits",
                    "0x000000ee" not in body,
                    "the reference committed 0xee -- the raw-word low byte -- so the "
                    "A6 lane select is not being applied")
        finally:
            shutil.rmtree(tdir, ignore_errors=True)
    else:
        print("SKIP  A13/A6 sub-word plant lane select (no built vesta_ref)")

    h.cleanup()
    print("")
    print("%d/%d cases passed" % (h.passed, h.passed + h.failed))
    return 0 if h.failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
