set_clock_latency -source -early -min -rise  -0.479255 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.446732 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.479255 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.446732 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.479255 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.446732 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.479255 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.446732 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.651748 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -fall  -0.642242 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -rise  -0.651748 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -fall  -0.642242 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -rise  -0.651748 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -fall  -0.642242 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -rise  -0.651748 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -fall  -0.642242 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -rise  -0.700493 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.664033 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.700493 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.664033 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.700493 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.664033 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.700493 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.664033 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.645833 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -fall  -0.636999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -rise  -0.645833 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -fall  -0.636999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -rise  -0.645833 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -fall  -0.636999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -rise  -0.645833 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -fall  -0.636999 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -rise  -0.247688 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.21952 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.247688 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.21952 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.247688 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.21952 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.247688 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.21952 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.685751 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.645194 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.685751 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.645194 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.685751 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.645194 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.685751 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.645194 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.254637 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.223696 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.254637 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.223696 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.254637 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.223696 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.254637 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.223696 [get_pins {spi1/sck_in}] -clock clk_sck1 
