-- =============================================================================
-- afe2_regs_pkg.vhd: GENERATED from hdl/common/regs/rdl/ by
-- platform/common/python/rdl_vhdl.py. DO NOT EDIT THIS FILE.
--
--   regenerate:  tools/bin/bazel run //platform/common/python:rdl_vhdl_pkgs
--   gates:       //platform/common:rdl_vhdl_pkg_test    tracked == regenerated
--                //platform/common:rdl_pkg_vs_legacy_test  == the hand-written
--                                                       constants it replaced
--                //platform/common:rdl_vs_vhdl_afe2_test
--
-- One analog front-end site: the digital half of one anatop_pixel channel.
--
-- <REG>_WORD is the word offset inside the peripheral sub-slot, <REG>_ADDR the
-- byte offset, <REG>_RESET the reset word and <REG>_IMPL the mask of bits that
-- hold a software-written flop (hardware-owned status and single-pulse strobes
-- are excluded, which is the same rule the hand-written IMPL tables use).
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;

package afe2_regs_pkg is

    -- AFExCR: Control
    constant AFExCR_WORD              : natural := 0;
    constant AFExCR_ADDR              : natural := 0;
    constant AFExCR_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000011100000000";
    constant AFExCR_IMPL              : std_logic_vector(31 downto 0) := "00000000000000001111111111110011";
    constant AFECLKDIV_MSB            : natural := 15;
    constant AFECLKDIV_LSB            : natural := 12;
    constant AFECLKDIV_RESET          : std_logic_vector(3 downto 0) := "0000";
    constant AFESAMPLESTEP_MSB        : natural := 11;
    constant AFESAMPLESTEP_LSB        : natural := 8;
    constant AFESAMPLESTEP_RESET      : std_logic_vector(3 downto 0) := "0111";
    constant AFESWAPEN_MSB            : natural := 7;
    constant AFESWAPEN_LSB            : natural := 7;
    constant AFESWAPEN_RESET          : std_logic_vector(0 downto 0) := "0";
    constant AFEERRIE_MSB             : natural := 6;
    constant AFEERRIE_LSB             : natural := 6;
    constant AFEERRIE_RESET           : std_logic_vector(0 downto 0) := "0";
    constant AFEDRDYIE_MSB            : natural := 5;
    constant AFEDRDYIE_LSB            : natural := 5;
    constant AFEDRDYIE_RESET          : std_logic_vector(0 downto 0) := "0";
    constant AFESYNCEN_MSB            : natural := 4;
    constant AFESYNCEN_LSB            : natural := 4;
    constant AFESYNCEN_RESET          : std_logic_vector(0 downto 0) := "0";
    constant AFESYNC_MSB              : natural := 3;
    constant AFESYNC_LSB              : natural := 3;
    constant AFESYNC_RESET            : std_logic_vector(0 downto 0) := "0";
    constant AFESTART_MSB             : natural := 2;
    constant AFESTART_LSB             : natural := 2;
    constant AFESTART_RESET           : std_logic_vector(0 downto 0) := "0";
    constant AFECONT_MSB              : natural := 1;
    constant AFECONT_LSB              : natural := 1;
    constant AFECONT_RESET            : std_logic_vector(0 downto 0) := "0";
    constant AFEEN_MSB                : natural := 0;
    constant AFEEN_LSB                : natural := 0;
    constant AFEEN_RESET              : std_logic_vector(0 downto 0) := "0";

    -- AFExSR: Status
    constant AFExSR_WORD              : natural := 1;
    constant AFExSR_ADDR              : natural := 4;
    constant AFExSR_RESET             : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExSR_IMPL              : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFECNT_MSB               : natural := 11;
    constant AFECNT_LSB               : natural := 8;
    constant AFECNT_RESET             : std_logic_vector(3 downto 0) := "0000";
    constant AFETO_MSB                : natural := 4;
    constant AFETO_LSB                : natural := 4;
    constant AFETO_RESET              : std_logic_vector(0 downto 0) := "0";
    constant AFEREL_MSB               : natural := 3;
    constant AFEREL_LSB               : natural := 3;
    constant AFEREL_RESET             : std_logic_vector(0 downto 0) := "0";
    constant AFEOVF_MSB               : natural := 2;
    constant AFEOVF_LSB               : natural := 2;
    constant AFEOVF_RESET             : std_logic_vector(0 downto 0) := "0";
    constant AFEDRDY_MSB              : natural := 1;
    constant AFEDRDY_LSB              : natural := 1;
    constant AFEDRDY_RESET            : std_logic_vector(0 downto 0) := "0";
    constant AFEBUSY_MSB              : natural := 0;
    constant AFEBUSY_LSB              : natural := 0;
    constant AFEBUSY_RESET            : std_logic_vector(0 downto 0) := "0";

    -- AFExDATA: Result FIFO head, side-effect-free
    constant AFExDATA_WORD            : natural := 2;
    constant AFExDATA_ADDR            : natural := 8;
    constant AFExDATA_RESET           : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExDATA_IMPL            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFEVALID_MSB             : natural := 15;
    constant AFEVALID_LSB             : natural := 15;
    constant AFEVALID_RESET           : std_logic_vector(0 downto 0) := "0";
    constant AFEPHTAG_MSB             : natural := 14;
    constant AFEPHTAG_LSB             : natural := 14;
    constant AFEPHTAG_RESET           : std_logic_vector(0 downto 0) := "0";
    constant AFESELTAG_MSB            : natural := 13;
    constant AFESELTAG_LSB            : natural := 10;
    constant AFESELTAG_RESET          : std_logic_vector(3 downto 0) := "0000";
    constant AFECODE_MSB              : natural := 9;
    constant AFECODE_LSB              : natural := 0;
    constant AFECODE_RESET            : std_logic_vector(9 downto 0) := "0000000000";

    -- AFExTIA: Transimpedance feedback ladder: Rf = 18 kOhm + 6 kOhm N, N = RESEN + 64 popcount(THEN), 0 to 319. Active-high = insert
    constant AFExTIA_WORD             : natural := 3;
    constant AFExTIA_ADDR             : natural := 12;
    constant AFExTIA_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExTIA_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000001111111111";
    constant AFETHEN_MSB              : natural := 9;
    constant AFETHEN_LSB              : natural := 6;
    constant AFETHEN_RESET            : std_logic_vector(3 downto 0) := "0000";
    constant AFERESEN_MSB             : natural := 5;
    constant AFERESEN_LSB             : natural := 0;
    constant AFERESEN_RESET           : std_logic_vector(5 downto 0) := "000000";

    -- AFExDACVP: Potential-program DAC (A_Dac_Vp, 610.35 uV per code) and its enable
    constant AFExDACVP_WORD           : natural := 4;
    constant AFExDACVP_ADDR           : natural := 16;
    constant AFExDACVP_RESET          : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExDACVP_IMPL           : std_logic_vector(31 downto 0) := "00000000000000000001111111111111";
    constant AFEVPEN_MSB              : natural := 12;
    constant AFEVPEN_LSB              : natural := 12;
    constant AFEVPEN_RESET            : std_logic_vector(0 downto 0) := "0";
    constant AFEVP_MSB                : natural := 11;
    constant AFEVP_LSB                : natural := 0;
    constant AFEVP_RESET              : std_logic_vector(11 downto 0) := "000000000000";

    -- AFExDACVCM: Common-mode DAC (A_Dac_Vcm, 610.35 uV per code) and its enable
    constant AFExDACVCM_WORD          : natural := 5;
    constant AFExDACVCM_ADDR          : natural := 20;
    constant AFExDACVCM_RESET         : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExDACVCM_IMPL          : std_logic_vector(31 downto 0) := "00000000000000000001111111111111";
    constant AFEVCMEN_MSB             : natural := 12;
    constant AFEVCMEN_LSB             : natural := 12;
    constant AFEVCMEN_RESET           : std_logic_vector(0 downto 0) := "0";
    constant AFEVCM_MSB               : natural := 11;
    constant AFEVCM_LSB               : natural := 0;
    constant AFEVCM_RESET             : std_logic_vector(11 downto 0) := "000000000000";

    -- AFExBIAS: Local bias generator trim
    constant AFExBIAS_WORD            : natural := 6;
    constant AFExBIAS_ADDR            : natural := 24;
    constant AFExBIAS_RESET           : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExBIAS_IMPL            : std_logic_vector(31 downto 0) := "00000000000000000000000000111111";
    constant AFEBIASADJ_MSB           : natural := 5;
    constant AFEBIASADJ_LSB           : natural := 0;
    constant AFEBIASADJ_RESET         : std_logic_vector(5 downto 0) := "000000";

    -- AFExMUX: Converter input and analog test-port selects
    constant AFExMUX_WORD             : natural := 7;
    constant AFExMUX_ADDR             : natural := 28;
    constant AFExMUX_RESET            : std_logic_vector(31 downto 0) := "00000000000000000000000011110000";
    constant AFExMUX_IMPL             : std_logic_vector(31 downto 0) := "00000000000000000000000011111111";
    constant AFEATPSEL_MSB            : natural := 7;
    constant AFEATPSEL_LSB            : natural := 4;
    constant AFEATPSEL_RESET          : std_logic_vector(3 downto 0) := "1111";
    constant AFEADCSEL_MSB            : natural := 3;
    constant AFEADCSEL_LSB            : natural := 0;
    constant AFEADCSEL_RESET          : std_logic_vector(3 downto 0) := "0000";

    -- AFExSWAP: Excitation swap engine: the second potential code and the half period, in conversions
    constant AFExSWAP_WORD            : natural := 8;
    constant AFExSWAP_ADDR            : natural := 32;
    constant AFExSWAP_RESET           : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExSWAP_IMPL            : std_logic_vector(31 downto 0) := "11111111111111110000111111111111";
    constant AFEPERIOD_MSB            : natural := 31;
    constant AFEPERIOD_LSB            : natural := 16;
    constant AFEPERIOD_RESET          : std_logic_vector(15 downto 0) := "0000000000000000";
    constant AFEVP2_MSB               : natural := 11;
    constant AFEVP2_LSB               : natural := 0;
    constant AFEVP2_RESET             : std_logic_vector(11 downto 0) := "000000000000";

    -- AFE2.vhd's own decode identifiers. The index constants, the
    -- array type over them and the two tables indexed by it, so the entity
    -- declares none of them itself and no assignment in its body changes.
    constant W_CR                     : natural := 0;
    constant W_SR                     : natural := 1;
    constant W_DATA                   : natural := 2;
    constant W_TIA                    : natural := 3;
    constant W_DACVP                  : natural := 4;
    constant W_DACVCM                 : natural := 5;
    constant W_BIAS                   : natural := 6;
    constant W_MUX                    : natural := 7;
    constant W_SWAP                   : natural := 8;
    constant NSTORED                  : natural := 9;

    type reg_arr_t is array(0 to NSTORED-1) of std_logic_vector(31 downto 0);

    -- bits that hold a software-written flop; everything else reads 0 and drops writes
    constant IMPL     : reg_arr_t := (
        W_CR           => x"0000FFF3",
        W_SR           => x"00000000",
        W_DATA         => x"00000000",
        W_TIA          => x"000003FF",
        W_DACVP        => x"00001FFF",
        W_DACVCM       => x"00001FFF",
        W_BIAS         => x"0000003F",
        W_MUX          => x"000000FF",
        W_SWAP         => x"FFFF0FFF");

    -- reset word
    constant RSTVAL   : reg_arr_t := (
        W_CR           => x"00000700",
        W_SR           => x"00000000",
        W_DATA         => x"00000000",
        W_TIA          => x"00000000",
        W_DACVP        => x"00000000",
        W_DACVCM       => x"00000000",
        W_BIAS         => x"00000000",
        W_MUX          => x"000000F0",
        W_SWAP         => x"00000000");

    -- Write-1 strobes: software writes them, nothing stores them, so they are
    -- absent from IMPL. <FIELD>_LSB above is the bit each one occupies.
    constant AFExCR_SINGLEPULSE       : std_logic_vector(31 downto 0) := x"0000000C";

end package afe2_regs_pkg;
