-- =============================================================================
-- biasg_regs_pkg.vhd: GENERATED from hdl/common/regs/rdl/ by
-- platform/common/python/rdl_vhdl.py. DO NOT EDIT THIS FILE.
--
--   regenerate:  tools/bin/bazel run //platform/common/python:rdl_vhdl_pkgs
--   gates:       //platform/common:rdl_vhdl_pkg_test    tracked == regenerated
--                //platform/common:rdl_pkg_vs_legacy_test  == the hand-written
--                                                       constants it replaced
--                //platform/common:rdl_vs_vhdl_biasg_test
--
-- Shared bias generator (anatop_biasgen_g) control registers, overlaid on words 9 to 13 of AFE2 site 0's sub-slot.
--
-- <REG>_WORD is the word offset inside the peripheral sub-slot, <REG>_ADDR the
-- byte offset, <REG>_RESET the reset word and <REG>_IMPL the mask of bits that
-- hold a software-written flop (hardware-owned status and single-pulse strobes
-- are excluded, which is the same rule the hand-written IMPL tables use).
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;

package biasg_regs_pkg is

    -- AFExBIASG0: Shared bias generator (anatop_biasgen_g) R-2R code for rail bn, the NMOS cascode rail, driving the macro's code_bn pins
    constant AFExBIASG0_WORD          : natural := 9;
    constant AFExBIASG0_ADDR          : natural := 36;
    constant AFExBIASG0_RESET         : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExBIASG0_IMPL          : std_logic_vector(31 downto 0) := "00000000000000000011111111111111";
    constant AFEBGCODE0_MSB           : natural := 13;
    constant AFEBGCODE0_LSB           : natural := 0;
    constant AFEBGCODE0_RESET         : std_logic_vector(13 downto 0) := "00000000000000";

    -- AFExBIASG1: Shared bias generator (anatop_biasgen_g) R-2R code for rail bnc, the NMOS cascode gate rail, driving the macro's code_bnc pins
    constant AFExBIASG1_WORD          : natural := 10;
    constant AFExBIASG1_ADDR          : natural := 40;
    constant AFExBIASG1_RESET         : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExBIASG1_IMPL          : std_logic_vector(31 downto 0) := "00000000000000000011111111111111";
    constant AFEBGCODE1_MSB           : natural := 13;
    constant AFEBGCODE1_LSB           : natural := 0;
    constant AFEBGCODE1_RESET         : std_logic_vector(13 downto 0) := "00000000000000";

    -- AFExBIASG2: Shared bias generator (anatop_biasgen_g) R-2R code for rail bp, the PMOS cascode rail, driving the macro's code_bp pins
    constant AFExBIASG2_WORD          : natural := 11;
    constant AFExBIASG2_ADDR          : natural := 44;
    constant AFExBIASG2_RESET         : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExBIASG2_IMPL          : std_logic_vector(31 downto 0) := "00000000000000000011111111111111";
    constant AFEBGCODE2_MSB           : natural := 13;
    constant AFEBGCODE2_LSB           : natural := 0;
    constant AFEBGCODE2_RESET         : std_logic_vector(13 downto 0) := "00000000000000";

    -- AFExBIASG3: Shared bias generator (anatop_biasgen_g) R-2R code for rail bpc, the PMOS cascode gate rail, driving the macro's code_bpc pins
    constant AFExBIASG3_WORD          : natural := 12;
    constant AFExBIASG3_ADDR          : natural := 48;
    constant AFExBIASG3_RESET         : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExBIASG3_IMPL          : std_logic_vector(31 downto 0) := "00000000000000000011111111111111";
    constant AFEBGCODE3_MSB           : natural := 13;
    constant AFEBGCODE3_LSB           : natural := 0;
    constant AFEBGCODE3_RESET         : std_logic_vector(13 downto 0) := "00000000000000";

    -- AFExBIASGCR: Shared bias generator mode, enables and trim
    constant AFExBIASGCR_WORD         : natural := 13;
    constant AFExBIASGCR_ADDR         : natural := 52;
    constant AFExBIASGCR_RESET        : std_logic_vector(31 downto 0) := "00000000000000000000000000000000";
    constant AFExBIASGCR_IMPL         : std_logic_vector(31 downto 0) := "00000000000000000011111100001111";
    constant AFEBGADJ_MSB             : natural := 13;
    constant AFEBGADJ_LSB             : natural := 8;
    constant AFEBGADJ_RESET           : std_logic_vector(5 downto 0) := "000000";
    constant AFEBGEN_MSB              : natural := 3;
    constant AFEBGEN_LSB              : natural := 3;
    constant AFEBGEN_RESET            : std_logic_vector(0 downto 0) := "0";
    constant AFEBGENBUFINT_MSB        : natural := 2;
    constant AFEBGENBUFINT_LSB        : natural := 2;
    constant AFEBGENBUFINT_RESET      : std_logic_vector(0 downto 0) := "0";
    constant AFEBGENGEN_MSB           : natural := 1;
    constant AFEBGENGEN_LSB           : natural := 1;
    constant AFEBGENGEN_RESET         : std_logic_vector(0 downto 0) := "0";
    constant AFEBGUSEDAC_MSB          : natural := 0;
    constant AFEBGUSEDAC_LSB          : natural := 0;
    constant AFEBGUSEDAC_RESET        : std_logic_vector(0 downto 0) := "0";

    -- BIASG.vhd's own decode identifiers. The index constants, the
    -- array type over them and the two tables indexed by it, so the entity
    -- declares none of them itself and no assignment in its body changes.
    constant IDX_BIASG0               : natural := 0;
    constant IDX_BIASG1               : natural := 1;
    constant IDX_BIASG2               : natural := 2;
    constant IDX_BIASG3               : natural := 3;
    constant IDX_BIASGCR              : natural := 4;
    constant N_WORDS                  : natural := 5;
    constant WORD_BASE_DEFAULT        : natural := 9;   -- first word inside the host sub-slot

    type reg_array is array(0 to N_WORDS-1) of std_logic_vector(31 downto 0);

    -- bits that hold a software-written flop; everything else reads 0 and drops writes
    constant IMPL     : reg_array := (
        x"00003FFF",
        x"00003FFF",
        x"00003FFF",
        x"00003FFF",
        x"00003F0F");

    -- reset word
    constant RSTVAL   : reg_array := (
        x"00000000",
        x"00000000",
        x"00000000",
        x"00000000",
        x"00000000");

end package biasg_regs_pkg;
