/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/periph/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef AFE2_REGS_H
#define AFE2_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - AFExCR_t
#define AFEXCR_T__AFEEN_bm 0x1
#define AFEXCR_T__AFEEN_bp 0
#define AFEXCR_T__AFEEN_bw 1
#define AFEXCR_T__AFEEN_reset 0x0
#define AFEXCR_T__AFECONT_bm 0x2
#define AFEXCR_T__AFECONT_bp 1
#define AFEXCR_T__AFECONT_bw 1
#define AFEXCR_T__AFECONT_reset 0x0
#define AFEXCR_T__AFESTART_bm 0x4
#define AFEXCR_T__AFESTART_bp 2
#define AFEXCR_T__AFESTART_bw 1
#define AFEXCR_T__AFESTART_reset 0x0
#define AFEXCR_T__AFESYNC_bm 0x8
#define AFEXCR_T__AFESYNC_bp 3
#define AFEXCR_T__AFESYNC_bw 1
#define AFEXCR_T__AFESYNC_reset 0x0
#define AFEXCR_T__AFESYNCEN_bm 0x10
#define AFEXCR_T__AFESYNCEN_bp 4
#define AFEXCR_T__AFESYNCEN_bw 1
#define AFEXCR_T__AFESYNCEN_reset 0x0
#define AFEXCR_T__AFEDRDYIE_bm 0x20
#define AFEXCR_T__AFEDRDYIE_bp 5
#define AFEXCR_T__AFEDRDYIE_bw 1
#define AFEXCR_T__AFEDRDYIE_reset 0x0
#define AFEXCR_T__AFEERRIE_bm 0x40
#define AFEXCR_T__AFEERRIE_bp 6
#define AFEXCR_T__AFEERRIE_bw 1
#define AFEXCR_T__AFEERRIE_reset 0x0
#define AFEXCR_T__AFESWAPEN_bm 0x80
#define AFEXCR_T__AFESWAPEN_bp 7
#define AFEXCR_T__AFESWAPEN_bw 1
#define AFEXCR_T__AFESWAPEN_reset 0x0
#define AFEXCR_T__AFESAMPLESTEP_bm 0xf00
#define AFEXCR_T__AFESAMPLESTEP_bp 8
#define AFEXCR_T__AFESAMPLESTEP_bw 4
#define AFEXCR_T__AFESAMPLESTEP_reset 0x7
#define AFEXCR_T__AFECLKDIV_bm 0xf000
#define AFEXCR_T__AFECLKDIV_bp 12
#define AFEXCR_T__AFECLKDIV_bw 4
#define AFEXCR_T__AFECLKDIV_reset 0x0

// reg - AFExSR_t
#define AFEXSR_T__AFEBUSY_bm 0x1
#define AFEXSR_T__AFEBUSY_bp 0
#define AFEXSR_T__AFEBUSY_bw 1
#define AFEXSR_T__AFEBUSY_reset 0x0
#define AFEXSR_T__AFEDRDY_bm 0x2
#define AFEXSR_T__AFEDRDY_bp 1
#define AFEXSR_T__AFEDRDY_bw 1
#define AFEXSR_T__AFEDRDY_reset 0x0
#define AFEXSR_T__AFEOVF_bm 0x4
#define AFEXSR_T__AFEOVF_bp 2
#define AFEXSR_T__AFEOVF_bw 1
#define AFEXSR_T__AFEOVF_reset 0x0
#define AFEXSR_T__AFEREL_bm 0x8
#define AFEXSR_T__AFEREL_bp 3
#define AFEXSR_T__AFEREL_bw 1
#define AFEXSR_T__AFEREL_reset 0x0
#define AFEXSR_T__AFETO_bm 0x10
#define AFEXSR_T__AFETO_bp 4
#define AFEXSR_T__AFETO_bw 1
#define AFEXSR_T__AFETO_reset 0x0
#define AFEXSR_T__AFECNT_bm 0xf00
#define AFEXSR_T__AFECNT_bp 8
#define AFEXSR_T__AFECNT_bw 4
#define AFEXSR_T__AFECNT_reset 0x0

// reg - AFExDATA_t
#define AFEXDATA_T__AFECODE_bm 0x3ff
#define AFEXDATA_T__AFECODE_bp 0
#define AFEXDATA_T__AFECODE_bw 10
#define AFEXDATA_T__AFECODE_reset 0x0
#define AFEXDATA_T__AFESELTAG_bm 0x3c00
#define AFEXDATA_T__AFESELTAG_bp 10
#define AFEXDATA_T__AFESELTAG_bw 4
#define AFEXDATA_T__AFESELTAG_reset 0x0
#define AFEXDATA_T__AFEPHTAG_bm 0x4000
#define AFEXDATA_T__AFEPHTAG_bp 14
#define AFEXDATA_T__AFEPHTAG_bw 1
#define AFEXDATA_T__AFEPHTAG_reset 0x0
#define AFEXDATA_T__AFEVALID_bm 0x8000
#define AFEXDATA_T__AFEVALID_bp 15
#define AFEXDATA_T__AFEVALID_bw 1
#define AFEXDATA_T__AFEVALID_reset 0x0

// reg - AFExTIA_t
#define AFEXTIA_T__AFERESEN_bm 0x3f
#define AFEXTIA_T__AFERESEN_bp 0
#define AFEXTIA_T__AFERESEN_bw 6
#define AFEXTIA_T__AFERESEN_reset 0x0
#define AFEXTIA_T__AFETHEN_bm 0x3c0
#define AFEXTIA_T__AFETHEN_bp 6
#define AFEXTIA_T__AFETHEN_bw 4
#define AFEXTIA_T__AFETHEN_reset 0x0

// reg - AFExDACVP_t
#define AFEXDACVP_T__AFEVP_bm 0xfff
#define AFEXDACVP_T__AFEVP_bp 0
#define AFEXDACVP_T__AFEVP_bw 12
#define AFEXDACVP_T__AFEVP_reset 0x0
#define AFEXDACVP_T__AFEVPEN_bm 0x1000
#define AFEXDACVP_T__AFEVPEN_bp 12
#define AFEXDACVP_T__AFEVPEN_bw 1
#define AFEXDACVP_T__AFEVPEN_reset 0x0

// reg - AFExDACVCM_t
#define AFEXDACVCM_T__AFEVCM_bm 0xfff
#define AFEXDACVCM_T__AFEVCM_bp 0
#define AFEXDACVCM_T__AFEVCM_bw 12
#define AFEXDACVCM_T__AFEVCM_reset 0x0
#define AFEXDACVCM_T__AFEVCMEN_bm 0x1000
#define AFEXDACVCM_T__AFEVCMEN_bp 12
#define AFEXDACVCM_T__AFEVCMEN_bw 1
#define AFEXDACVCM_T__AFEVCMEN_reset 0x0

// reg - AFExBIAS_t
#define AFEXBIAS_T__AFEBIASADJ_bm 0x3f
#define AFEXBIAS_T__AFEBIASADJ_bp 0
#define AFEXBIAS_T__AFEBIASADJ_bw 6
#define AFEXBIAS_T__AFEBIASADJ_reset 0x0

// reg - AFExMUX_t
#define AFEXMUX_T__AFEADCSEL_bm 0xf
#define AFEXMUX_T__AFEADCSEL_bp 0
#define AFEXMUX_T__AFEADCSEL_bw 4
#define AFEXMUX_T__AFEADCSEL_reset 0x0
#define AFEXMUX_T__AFEATPSEL_bm 0xf0
#define AFEXMUX_T__AFEATPSEL_bp 4
#define AFEXMUX_T__AFEATPSEL_bw 4
#define AFEXMUX_T__AFEATPSEL_reset 0xf

// reg - AFExSWAP_t
#define AFEXSWAP_T__AFEVP2_bm 0xfff
#define AFEXSWAP_T__AFEVP2_bp 0
#define AFEXSWAP_T__AFEVP2_bw 12
#define AFEXSWAP_T__AFEVP2_reset 0x0
#define AFEXSWAP_T__AFEPERIOD_bm 0xffff0000
#define AFEXSWAP_T__AFEPERIOD_bp 16
#define AFEXSWAP_T__AFEPERIOD_bw 16
#define AFEXSWAP_T__AFEPERIOD_reset 0x0

// addrmap - afe2_site
typedef struct __attribute__ ((__packed__)) {
    uint32_t AFExCR;
    uint32_t AFExSR;
    uint32_t AFExDATA;
    uint32_t AFExTIA;
    uint32_t AFExDACVP;
    uint32_t AFExDACVCM;
    uint32_t AFExBIAS;
    uint32_t AFExMUX;
    uint32_t AFExSWAP;
} afe2_site_t;


static_assert(sizeof(afe2_site_t) == 0x24, "Packing error");

// enum - AFExCR_t
#define AFEXCR_T__AFEEN__CONVERTER_IN_RESET 0x0   // Converter in reset
#define AFEXCR_T__AFEEN__CONVERTER_RELEASED 0x1   // Converter released
#define AFEXCR_T__AFESWAPEN__A_DAC_VP_VP 0x0   // A_Dac_Vp = VP
#define AFEXCR_T__AFESWAPEN__A_DAC_VP_ALTERNATES 0x1   // A_Dac_Vp alternates VP / VP2

#ifdef __cplusplus
}
#endif

#endif /* AFE2_REGS_H */
