/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/regs/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef CLINT_REGS_H
#define CLINT_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - MSIP_t
#define MSIP_T__CLINTMSIPH_bm 0x1
#define MSIP_T__CLINTMSIPH_bp 0
#define MSIP_T__CLINTMSIPH_bw 1
#define MSIP_T__CLINTMSIPH_reset 0x0

// reg - MTIMEL_t
#define MTIMEL_T__CLINTMTIMEL_bm 0xffffffff
#define MTIMEL_T__CLINTMTIMEL_bp 0
#define MTIMEL_T__CLINTMTIMEL_bw 32
#define MTIMEL_T__CLINTMTIMEL_reset 0x0

// reg - MTIMEH_t
#define MTIMEH_T__CLINTMTIMEH_bm 0xffffffff
#define MTIMEH_T__CLINTMTIMEH_bp 0
#define MTIMEH_T__CLINTMTIMEH_bw 32
#define MTIMEH_T__CLINTMTIMEH_reset 0x0

// reg - MTIMECMPL_t
#define MTIMECMPL_T__CLINTMTIMECMPL_bm 0xffffffff
#define MTIMECMPL_T__CLINTMTIMECMPL_bp 0
#define MTIMECMPL_T__CLINTMTIMECMPL_bw 32
#define MTIMECMPL_T__CLINTMTIMECMPL_reset 0xffffffff

// reg - MTIMECMPH_t
#define MTIMECMPH_T__CLINTMTIMECMPH_bm 0xffffffff
#define MTIMECMPH_T__CLINTMTIMECMPH_bp 0
#define MTIMECMPH_T__CLINTMTIMECMPH_bw 32
#define MTIMECMPH_T__CLINTMTIMECMPH_reset 0xffffffff

// regfile - MTIMECMP_t
typedef struct __attribute__ ((__packed__)) {
    uint32_t MTIMECMPL;
    uint32_t MTIMECMPH;
} MTIMECMP_t_t;

// addrmap - clint
typedef struct __attribute__ ((__packed__)) {
    uint32_t MSIP[5];
    uint8_t RESERVED_14_1f[0xc];
    uint32_t MTIMEL;
    uint32_t MTIMEH;
    uint8_t RESERVED_28_2f[0x8];
    MTIMECMP_t_t MTIMECMP[5];
} clint_t;


static_assert(sizeof(clint_t) == 0x58, "Packing error");

// enum - MSIP_t
#define MSIP_T__CLINTMSIPH__NO_SOFTWARE_INTERRUPT_PENDING 0x0   // No software interrupt pending
#define MSIP_T__CLINTMSIPH__SOFTWARE_INTERRUPT_RAISED 0x1   // Software interrupt raised

#ifdef __cplusplus
}
#endif

#endif /* CLINT_REGS_H */
