/* VestaRV: DMA registers.
   Generated from hdl/common/regs/rdl/dma.rdl by platform/common/python/rdl_cheader_regs.py.
   Do not edit; regenerate with `bazel run //platform/common/python:rdl_regs_headers`. */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef DMA_REGS_H
#define DMA_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - DMAxCR_t
#define DMAXCR_T__DMAEN_bm 0x1
#define DMAXCR_T__DMAEN_bp 0
#define DMAXCR_T__DMAEN_bw 1
#define DMAXCR_T__DMAEN_reset 0x0
#define DMAXCR_T__DMAGO_bm 0x1e
#define DMAXCR_T__DMAGO_bp 1
#define DMAXCR_T__DMAGO_bw 4
#define DMAXCR_T__DMAGO_reset 0x0
#define DMAXCR_T__DMAABORT_bm 0x1e0
#define DMAXCR_T__DMAABORT_bp 5
#define DMAXCR_T__DMAABORT_bw 4
#define DMAXCR_T__DMAABORT_reset 0x0
#define DMAXCR_T__DMADONEIE_bm 0x1000
#define DMAXCR_T__DMADONEIE_bp 12
#define DMAXCR_T__DMADONEIE_bw 1
#define DMAXCR_T__DMADONEIE_reset 0x0
#define DMAXCR_T__DMAERRIE_bm 0x2000
#define DMAXCR_T__DMAERRIE_bp 13
#define DMAXCR_T__DMAERRIE_bw 1
#define DMAXCR_T__DMAERRIE_reset 0x0

// reg - DMAxSR_t
#define DMAXSR_T__DMABUSY_bm 0x1
#define DMAXSR_T__DMABUSY_bp 0
#define DMAXSR_T__DMABUSY_bw 1
#define DMAXSR_T__DMABUSY_reset 0x0
#define DMAXSR_T__DMADONE_bm 0x1e
#define DMAXSR_T__DMADONE_bp 1
#define DMAXSR_T__DMADONE_bw 4
#define DMAXSR_T__DMADONE_reset 0x0
#define DMAXSR_T__DMAERR_bm 0x1e0
#define DMAXSR_T__DMAERR_bp 5
#define DMAXSR_T__DMAERR_bw 4
#define DMAXSR_T__DMAERR_reset 0x0
#define DMAXSR_T__DMAACTIVECH_bm 0xe00
#define DMAXSR_T__DMAACTIVECH_bp 9
#define DMAXSR_T__DMAACTIVECH_bw 3
#define DMAXSR_T__DMAACTIVECH_reset 0x0

// reg - DMAxC0SRC_t
#define DMAXC0SRC_T__DMAC0SRC_bm 0xffffffff
#define DMAXC0SRC_T__DMAC0SRC_bp 0
#define DMAXC0SRC_T__DMAC0SRC_bw 32
#define DMAXC0SRC_T__DMAC0SRC_reset 0x0

// reg - DMAxC0DST_t
#define DMAXC0DST_T__DMAC0DST_bm 0xffffffff
#define DMAXC0DST_T__DMAC0DST_bp 0
#define DMAXC0DST_T__DMAC0DST_bw 32
#define DMAXC0DST_T__DMAC0DST_reset 0x0

// reg - DMAxC0LEN_t
#define DMAXC0LEN_T__DMAC0LEN_bm 0xffffffff
#define DMAXC0LEN_T__DMAC0LEN_bp 0
#define DMAXC0LEN_T__DMAC0LEN_bw 32
#define DMAXC0LEN_T__DMAC0LEN_reset 0x0

// reg - DMAxC0CFG_t
#define DMAXC0CFG_T__DMAC0SINC_bm 0x1
#define DMAXC0CFG_T__DMAC0SINC_bp 0
#define DMAXC0CFG_T__DMAC0SINC_bw 1
#define DMAXC0CFG_T__DMAC0SINC_reset 0x0
#define DMAXC0CFG_T__DMAC0DINC_bm 0x2
#define DMAXC0CFG_T__DMAC0DINC_bp 1
#define DMAXC0CFG_T__DMAC0DINC_bw 1
#define DMAXC0CFG_T__DMAC0DINC_reset 0x0
#define DMAXC0CFG_T__DMAC0TRIG_bm 0x3c
#define DMAXC0CFG_T__DMAC0TRIG_bp 2
#define DMAXC0CFG_T__DMAC0TRIG_bw 4
#define DMAXC0CFG_T__DMAC0TRIG_reset 0x0
#define DMAXC0CFG_T__DMAC0PRIO_bm 0x40
#define DMAXC0CFG_T__DMAC0PRIO_bp 6
#define DMAXC0CFG_T__DMAC0PRIO_bw 1
#define DMAXC0CFG_T__DMAC0PRIO_reset 0x0
#define DMAXC0CFG_T__DMAC0CRCEN_bm 0x80
#define DMAXC0CFG_T__DMAC0CRCEN_bp 7
#define DMAXC0CFG_T__DMAC0CRCEN_bw 1
#define DMAXC0CFG_T__DMAC0CRCEN_reset 0x0

// reg - DMAxC1SRC_t
#define DMAXC1SRC_T__DMAC1SRC_bm 0xffffffff
#define DMAXC1SRC_T__DMAC1SRC_bp 0
#define DMAXC1SRC_T__DMAC1SRC_bw 32
#define DMAXC1SRC_T__DMAC1SRC_reset 0x0

// reg - DMAxC1DST_t
#define DMAXC1DST_T__DMAC1DST_bm 0xffffffff
#define DMAXC1DST_T__DMAC1DST_bp 0
#define DMAXC1DST_T__DMAC1DST_bw 32
#define DMAXC1DST_T__DMAC1DST_reset 0x0

// reg - DMAxC1LEN_t
#define DMAXC1LEN_T__DMAC1LEN_bm 0xffffffff
#define DMAXC1LEN_T__DMAC1LEN_bp 0
#define DMAXC1LEN_T__DMAC1LEN_bw 32
#define DMAXC1LEN_T__DMAC1LEN_reset 0x0

// reg - DMAxC1CFG_t
#define DMAXC1CFG_T__DMAC1SINC_bm 0x1
#define DMAXC1CFG_T__DMAC1SINC_bp 0
#define DMAXC1CFG_T__DMAC1SINC_bw 1
#define DMAXC1CFG_T__DMAC1SINC_reset 0x0
#define DMAXC1CFG_T__DMAC1DINC_bm 0x2
#define DMAXC1CFG_T__DMAC1DINC_bp 1
#define DMAXC1CFG_T__DMAC1DINC_bw 1
#define DMAXC1CFG_T__DMAC1DINC_reset 0x0
#define DMAXC1CFG_T__DMAC1TRIG_bm 0x3c
#define DMAXC1CFG_T__DMAC1TRIG_bp 2
#define DMAXC1CFG_T__DMAC1TRIG_bw 4
#define DMAXC1CFG_T__DMAC1TRIG_reset 0x0
#define DMAXC1CFG_T__DMAC1PRIO_bm 0x40
#define DMAXC1CFG_T__DMAC1PRIO_bp 6
#define DMAXC1CFG_T__DMAC1PRIO_bw 1
#define DMAXC1CFG_T__DMAC1PRIO_reset 0x0
#define DMAXC1CFG_T__DMAC1CRCEN_bm 0x80
#define DMAXC1CFG_T__DMAC1CRCEN_bp 7
#define DMAXC1CFG_T__DMAC1CRCEN_bw 1
#define DMAXC1CFG_T__DMAC1CRCEN_reset 0x0

// reg - DMAxC2SRC_t
#define DMAXC2SRC_T__DMAC2SRC_bm 0xffffffff
#define DMAXC2SRC_T__DMAC2SRC_bp 0
#define DMAXC2SRC_T__DMAC2SRC_bw 32
#define DMAXC2SRC_T__DMAC2SRC_reset 0x0

// reg - DMAxC2DST_t
#define DMAXC2DST_T__DMAC2DST_bm 0xffffffff
#define DMAXC2DST_T__DMAC2DST_bp 0
#define DMAXC2DST_T__DMAC2DST_bw 32
#define DMAXC2DST_T__DMAC2DST_reset 0x0

// reg - DMAxC2LEN_t
#define DMAXC2LEN_T__DMAC2LEN_bm 0xffffffff
#define DMAXC2LEN_T__DMAC2LEN_bp 0
#define DMAXC2LEN_T__DMAC2LEN_bw 32
#define DMAXC2LEN_T__DMAC2LEN_reset 0x0

// reg - DMAxC2CFG_t
#define DMAXC2CFG_T__DMAC2SINC_bm 0x1
#define DMAXC2CFG_T__DMAC2SINC_bp 0
#define DMAXC2CFG_T__DMAC2SINC_bw 1
#define DMAXC2CFG_T__DMAC2SINC_reset 0x0
#define DMAXC2CFG_T__DMAC2DINC_bm 0x2
#define DMAXC2CFG_T__DMAC2DINC_bp 1
#define DMAXC2CFG_T__DMAC2DINC_bw 1
#define DMAXC2CFG_T__DMAC2DINC_reset 0x0
#define DMAXC2CFG_T__DMAC2TRIG_bm 0x3c
#define DMAXC2CFG_T__DMAC2TRIG_bp 2
#define DMAXC2CFG_T__DMAC2TRIG_bw 4
#define DMAXC2CFG_T__DMAC2TRIG_reset 0x0
#define DMAXC2CFG_T__DMAC2PRIO_bm 0x40
#define DMAXC2CFG_T__DMAC2PRIO_bp 6
#define DMAXC2CFG_T__DMAC2PRIO_bw 1
#define DMAXC2CFG_T__DMAC2PRIO_reset 0x0
#define DMAXC2CFG_T__DMAC2CRCEN_bm 0x80
#define DMAXC2CFG_T__DMAC2CRCEN_bp 7
#define DMAXC2CFG_T__DMAC2CRCEN_bw 1
#define DMAXC2CFG_T__DMAC2CRCEN_reset 0x0

// reg - DMAxC3SRC_t
#define DMAXC3SRC_T__DMAC3SRC_bm 0xffffffff
#define DMAXC3SRC_T__DMAC3SRC_bp 0
#define DMAXC3SRC_T__DMAC3SRC_bw 32
#define DMAXC3SRC_T__DMAC3SRC_reset 0x0

// reg - DMAxC3DST_t
#define DMAXC3DST_T__DMAC3DST_bm 0xffffffff
#define DMAXC3DST_T__DMAC3DST_bp 0
#define DMAXC3DST_T__DMAC3DST_bw 32
#define DMAXC3DST_T__DMAC3DST_reset 0x0

// reg - DMAxC3LEN_t
#define DMAXC3LEN_T__DMAC3LEN_bm 0xffffffff
#define DMAXC3LEN_T__DMAC3LEN_bp 0
#define DMAXC3LEN_T__DMAC3LEN_bw 32
#define DMAXC3LEN_T__DMAC3LEN_reset 0x0

// reg - DMAxC3CFG_t
#define DMAXC3CFG_T__DMAC3SINC_bm 0x1
#define DMAXC3CFG_T__DMAC3SINC_bp 0
#define DMAXC3CFG_T__DMAC3SINC_bw 1
#define DMAXC3CFG_T__DMAC3SINC_reset 0x0
#define DMAXC3CFG_T__DMAC3DINC_bm 0x2
#define DMAXC3CFG_T__DMAC3DINC_bp 1
#define DMAXC3CFG_T__DMAC3DINC_bw 1
#define DMAXC3CFG_T__DMAC3DINC_reset 0x0
#define DMAXC3CFG_T__DMAC3TRIG_bm 0x3c
#define DMAXC3CFG_T__DMAC3TRIG_bp 2
#define DMAXC3CFG_T__DMAC3TRIG_bw 4
#define DMAXC3CFG_T__DMAC3TRIG_reset 0x0
#define DMAXC3CFG_T__DMAC3PRIO_bm 0x40
#define DMAXC3CFG_T__DMAC3PRIO_bp 6
#define DMAXC3CFG_T__DMAC3PRIO_bw 1
#define DMAXC3CFG_T__DMAC3PRIO_reset 0x0
#define DMAXC3CFG_T__DMAC3CRCEN_bm 0x80
#define DMAXC3CFG_T__DMAC3CRCEN_bp 7
#define DMAXC3CFG_T__DMAC3CRCEN_bw 1
#define DMAXC3CFG_T__DMAC3CRCEN_reset 0x0

// reg - DMAxCRC_t
#define DMAXCRC_T__DMACRC_bm 0xffff
#define DMAXCRC_T__DMACRC_bp 0
#define DMAXCRC_T__DMACRC_bw 16
#define DMAXCRC_T__DMACRC_reset 0xffff

// reg - DMAxDESC_t
#define DMAXDESC_T__RESERVED_bm 0xffffffff
#define DMAXDESC_T__RESERVED_bp 0
#define DMAXDESC_T__RESERVED_bw 32
#define DMAXDESC_T__RESERVED_reset 0x0

// addrmap - dma
typedef struct __attribute__ ((__packed__)) {
    uint32_t DMAxCR;
    uint32_t DMAxSR;
    uint32_t DMAxC0SRC;
    uint32_t DMAxC0DST;
    uint32_t DMAxC0LEN;
    uint32_t DMAxC0CFG;
    uint32_t DMAxC1SRC;
    uint32_t DMAxC1DST;
    uint32_t DMAxC1LEN;
    uint32_t DMAxC1CFG;
    uint32_t DMAxC2SRC;
    uint32_t DMAxC2DST;
    uint32_t DMAxC2LEN;
    uint32_t DMAxC2CFG;
    uint32_t DMAxC3SRC;
    uint32_t DMAxC3DST;
    uint32_t DMAxC3LEN;
    uint32_t DMAxC3CFG;
    uint32_t DMAxCRC;
    uint32_t DMAxDESC;
} dma_t;


static_assert(sizeof(dma_t) == 0x50, "Packing error");

// enum - DMAxCR_t
#define DMAXCR_T__DMAEN__DISABLED 0x0   // Disabled
#define DMAXCR_T__DMAEN__ENABLED 0x1   // Enabled
#define DMAXCR_T__DMADONEIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define DMAXCR_T__DMADONEIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define DMAXCR_T__DMAERRIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define DMAXCR_T__DMAERRIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled

// enum - DMAxSR_t
#define DMAXSR_T__DMABUSY__IDLE 0x0   // Idle
#define DMAXSR_T__DMABUSY__BUSY 0x1   // Busy

// enum - DMAxC0CFG_t
#define DMAXC0CFG_T__DMAC0SINC__FIXED_SOURCE 0x0   // Fixed source
#define DMAXC0CFG_T__DMAC0SINC__INCREMENT_SOURCE 0x1   // Increment source
#define DMAXC0CFG_T__DMAC0DINC__FIXED_DESTINATION 0x0   // Fixed destination
#define DMAXC0CFG_T__DMAC0DINC__INCREMENT_DESTINATION 0x1   // Increment destination
#define DMAXC0CFG_T__DMAC0TRIG__SOFTWARE_MEM_TO_MEM 0x0   // Software / mem-to-mem
#define DMAXC0CFG_T__DMAC0TRIG__UART0_RECEIVE_COMPLETE 0x1   // UART0 receive-complete
#define DMAXC0CFG_T__DMAC0TRIG__QSPI0_RX_FULL 0x2   // QSPI0 RX-full
#define DMAXC0CFG_T__DMAC0TRIG__NFC0_PAYLOAD_READY 0x3   // NFC0 payload-ready
#define DMAXC0CFG_T__DMAC0PRIO__LOW_PRIORITY_CLASS 0x0   // Low priority class
#define DMAXC0CFG_T__DMAC0PRIO__HIGH_PRIORITY_CLASS 0x1   // High priority class
#define DMAXC0CFG_T__DMAC0CRCEN__NO_CRC 0x0   // No CRC
#define DMAXC0CFG_T__DMAC0CRCEN__ACCUMULATE_CRC 0x1   // Accumulate CRC

// enum - DMAxC1CFG_t
#define DMAXC1CFG_T__DMAC1SINC__FIXED_SOURCE 0x0   // Fixed source
#define DMAXC1CFG_T__DMAC1SINC__INCREMENT_SOURCE 0x1   // Increment source
#define DMAXC1CFG_T__DMAC1DINC__FIXED_DESTINATION 0x0   // Fixed destination
#define DMAXC1CFG_T__DMAC1DINC__INCREMENT_DESTINATION 0x1   // Increment destination
#define DMAXC1CFG_T__DMAC1TRIG__SOFTWARE_MEM_TO_MEM 0x0   // Software / mem-to-mem
#define DMAXC1CFG_T__DMAC1TRIG__UART0_RECEIVE_COMPLETE 0x1   // UART0 receive-complete
#define DMAXC1CFG_T__DMAC1TRIG__QSPI0_RX_FULL 0x2   // QSPI0 RX-full
#define DMAXC1CFG_T__DMAC1TRIG__NFC0_PAYLOAD_READY 0x3   // NFC0 payload-ready
#define DMAXC1CFG_T__DMAC1PRIO__LOW_PRIORITY_CLASS 0x0   // Low priority class
#define DMAXC1CFG_T__DMAC1PRIO__HIGH_PRIORITY_CLASS 0x1   // High priority class
#define DMAXC1CFG_T__DMAC1CRCEN__NO_CRC 0x0   // No CRC
#define DMAXC1CFG_T__DMAC1CRCEN__ACCUMULATE_CRC 0x1   // Accumulate CRC

// enum - DMAxC2CFG_t
#define DMAXC2CFG_T__DMAC2SINC__FIXED_SOURCE 0x0   // Fixed source
#define DMAXC2CFG_T__DMAC2SINC__INCREMENT_SOURCE 0x1   // Increment source
#define DMAXC2CFG_T__DMAC2DINC__FIXED_DESTINATION 0x0   // Fixed destination
#define DMAXC2CFG_T__DMAC2DINC__INCREMENT_DESTINATION 0x1   // Increment destination
#define DMAXC2CFG_T__DMAC2TRIG__SOFTWARE_MEM_TO_MEM 0x0   // Software / mem-to-mem
#define DMAXC2CFG_T__DMAC2TRIG__UART0_RECEIVE_COMPLETE 0x1   // UART0 receive-complete
#define DMAXC2CFG_T__DMAC2TRIG__QSPI0_RX_FULL 0x2   // QSPI0 RX-full
#define DMAXC2CFG_T__DMAC2TRIG__NFC0_PAYLOAD_READY 0x3   // NFC0 payload-ready
#define DMAXC2CFG_T__DMAC2PRIO__LOW_PRIORITY_CLASS 0x0   // Low priority class
#define DMAXC2CFG_T__DMAC2PRIO__HIGH_PRIORITY_CLASS 0x1   // High priority class
#define DMAXC2CFG_T__DMAC2CRCEN__NO_CRC 0x0   // No CRC
#define DMAXC2CFG_T__DMAC2CRCEN__ACCUMULATE_CRC 0x1   // Accumulate CRC

// enum - DMAxC3CFG_t
#define DMAXC3CFG_T__DMAC3SINC__FIXED_SOURCE 0x0   // Fixed source
#define DMAXC3CFG_T__DMAC3SINC__INCREMENT_SOURCE 0x1   // Increment source
#define DMAXC3CFG_T__DMAC3DINC__FIXED_DESTINATION 0x0   // Fixed destination
#define DMAXC3CFG_T__DMAC3DINC__INCREMENT_DESTINATION 0x1   // Increment destination
#define DMAXC3CFG_T__DMAC3TRIG__SOFTWARE_MEM_TO_MEM 0x0   // Software / mem-to-mem
#define DMAXC3CFG_T__DMAC3TRIG__UART0_RECEIVE_COMPLETE 0x1   // UART0 receive-complete
#define DMAXC3CFG_T__DMAC3TRIG__QSPI0_RX_FULL 0x2   // QSPI0 RX-full
#define DMAXC3CFG_T__DMAC3TRIG__NFC0_PAYLOAD_READY 0x3   // NFC0 payload-ready
#define DMAXC3CFG_T__DMAC3PRIO__LOW_PRIORITY_CLASS 0x0   // Low priority class
#define DMAXC3CFG_T__DMAC3PRIO__HIGH_PRIORITY_CLASS 0x1   // High priority class
#define DMAXC3CFG_T__DMAC3CRCEN__NO_CRC 0x0   // No CRC
#define DMAXC3CFG_T__DMAC3CRCEN__ACCUMULATE_CRC 0x1   // Accumulate CRC

#ifdef __cplusplus
}
#endif

#endif /* DMA_REGS_H */
