/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/periph/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef GPIO_REGS_H
#define GPIO_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - PxIN_t
#define PXIN_T__PXIN_bm 0xff
#define PXIN_T__PXIN_bp 0
#define PXIN_T__PXIN_bw 8
#define PXIN_T__PXIN_reset 0x0

// reg - PxOUT_t
#define PXOUT_T__PXOUT_bm 0xff
#define PXOUT_T__PXOUT_bp 0
#define PXOUT_T__PXOUT_bw 8
#define PXOUT_T__PXOUT_reset 0x0

// reg - PxOUTS_t
#define PXOUTS_T__PXOUTS_bm 0xff
#define PXOUTS_T__PXOUTS_bp 0
#define PXOUTS_T__PXOUTS_bw 8
#define PXOUTS_T__PXOUTS_reset 0x0

// reg - PxOUTC_t
#define PXOUTC_T__PXOUTC_bm 0xff
#define PXOUTC_T__PXOUTC_bp 0
#define PXOUTC_T__PXOUTC_bw 8
#define PXOUTC_T__PXOUTC_reset 0x0

// reg - PxOUTT_t
#define PXOUTT_T__PXOUTT_bm 0xff
#define PXOUTT_T__PXOUTT_bp 0
#define PXOUTT_T__PXOUTT_bw 8
#define PXOUTT_T__PXOUTT_reset 0x0

// reg - PxDIR_t
#define PXDIR_T__PXDIR_bm 0xff
#define PXDIR_T__PXDIR_bp 0
#define PXDIR_T__PXDIR_bw 8
#define PXDIR_T__PXDIR_reset 0x0

// reg - PxIF_t
#define PXIF_T__PXIF_bm 0xff
#define PXIF_T__PXIF_bp 0
#define PXIF_T__PXIF_bw 8
#define PXIF_T__PXIF_reset 0x0

// reg - PxIES_t
#define PXIES_T__PXIES_bm 0xff
#define PXIES_T__PXIES_bp 0
#define PXIES_T__PXIES_bw 8
#define PXIES_T__PXIES_reset 0x0

// reg - PxIE_t
#define PXIE_T__PXIE_bm 0xff
#define PXIE_T__PXIE_bp 0
#define PXIE_T__PXIE_bw 8
#define PXIE_T__PXIE_reset 0x0

// reg - PxSEL_t
#define PXSEL_T__PXSEL_bm 0xff
#define PXSEL_T__PXSEL_bp 0
#define PXSEL_T__PXSEL_bw 8
#define PXSEL_T__PXSEL_reset 0x0

// reg - PxREN_t
#define PXREN_T__PXREN_bm 0xff
#define PXREN_T__PXREN_bp 0
#define PXREN_T__PXREN_bw 8
#define PXREN_T__PXREN_reset 0x0

// reg - PxAFS_t
#define PXAFS_T__PXAFS0_bm 0x7
#define PXAFS_T__PXAFS0_bp 0
#define PXAFS_T__PXAFS0_bw 3
#define PXAFS_T__PXAFS0_reset 0x0
#define PXAFS_T__PXAFS1_bm 0x70
#define PXAFS_T__PXAFS1_bp 4
#define PXAFS_T__PXAFS1_bw 3
#define PXAFS_T__PXAFS1_reset 0x0
#define PXAFS_T__PXAFS2_bm 0x700
#define PXAFS_T__PXAFS2_bp 8
#define PXAFS_T__PXAFS2_bw 3
#define PXAFS_T__PXAFS2_reset 0x0
#define PXAFS_T__PXAFS3_bm 0x7000
#define PXAFS_T__PXAFS3_bp 12
#define PXAFS_T__PXAFS3_bw 3
#define PXAFS_T__PXAFS3_reset 0x0
#define PXAFS_T__PXAFS4_bm 0x70000
#define PXAFS_T__PXAFS4_bp 16
#define PXAFS_T__PXAFS4_bw 3
#define PXAFS_T__PXAFS4_reset 0x0
#define PXAFS_T__PXAFS5_bm 0x700000
#define PXAFS_T__PXAFS5_bp 20
#define PXAFS_T__PXAFS5_bw 3
#define PXAFS_T__PXAFS5_reset 0x0
#define PXAFS_T__PXAFS6_bm 0x7000000
#define PXAFS_T__PXAFS6_bp 24
#define PXAFS_T__PXAFS6_bw 3
#define PXAFS_T__PXAFS6_reset 0x0
#define PXAFS_T__PXAFS7_bm 0x70000000
#define PXAFS_T__PXAFS7_bp 28
#define PXAFS_T__PXAFS7_bw 3
#define PXAFS_T__PXAFS7_reset 0x0

// reg - PxTASK_t
#define PXTASK_T__PXTASK_bm 0xff
#define PXTASK_T__PXTASK_bp 0
#define PXTASK_T__PXTASK_bw 8
#define PXTASK_T__PXTASK_reset 0x0

// addrmap - gpio
typedef struct __attribute__ ((__packed__)) {
    uint8_t PxIN;
    uint8_t RESERVED_1_3[0x3];
    uint8_t PxOUT;
    uint8_t RESERVED_5_7[0x3];
    uint8_t PxOUTS;
    uint8_t RESERVED_9_b[0x3];
    uint8_t PxOUTC;
    uint8_t RESERVED_d_f[0x3];
    uint8_t PxOUTT;
    uint8_t RESERVED_11_13[0x3];
    uint8_t PxDIR;
    uint8_t RESERVED_15_17[0x3];
    uint8_t PxIF;
    uint8_t RESERVED_19_1b[0x3];
    uint8_t PxIES;
    uint8_t RESERVED_1d_1f[0x3];
    uint8_t PxIE;
    uint8_t RESERVED_21_23[0x3];
    uint8_t PxSEL;
    uint8_t RESERVED_25_27[0x3];
    uint8_t PxREN;
    uint8_t RESERVED_29_2b[0x3];
    uint32_t PxAFS;
    uint8_t PxTASK;
} gpio_t;


static_assert(sizeof(gpio_t) == 0x31, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* GPIO_REGS_H */
