/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/regs/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef IRQ_ROUTER_REGS_H
#define IRQ_ROUTER_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - HENL_t
#define HENL_T__IRQRHENL_bm 0xffffffff
#define HENL_T__IRQRHENL_bp 0
#define HENL_T__IRQRHENL_bw 32
#define HENL_T__IRQRHENL_reset 0x0

// reg - HENM_t
#define HENM_T__IRQRHENM_bm 0xffffffff
#define HENM_T__IRQRHENM_bp 0
#define HENM_T__IRQRHENM_bw 32
#define HENM_T__IRQRHENM_reset 0x0

// reg - HENU_t
#define HENU_T__IRQRHENU_bm 0xffffffff
#define HENU_T__IRQRHENU_bp 0
#define HENU_T__IRQRHENU_bw 32
#define HENU_T__IRQRHENU_reset 0x0

// reg - HENX_t
#define HENX_T__IRQRHENX_bm 0x1fffffff
#define HENX_T__IRQRHENX_bp 0
#define HENX_T__IRQRHENX_bw 29
#define HENX_T__IRQRHENX_reset 0x0

// regfile - HEN_t
typedef struct __attribute__ ((__packed__)) {
    uint32_t HENL;
    uint32_t HENM;
    uint32_t HENU;
    uint32_t HENX;
} HEN_t_t;

// reg - CLAIM_t
#define CLAIM_T__IRQRCLAIM_bm 0xffffffff
#define CLAIM_T__IRQRCLAIM_bp 0
#define CLAIM_T__IRQRCLAIM_bw 32
#define CLAIM_T__IRQRCLAIM_reset 0x0

// reg - PENDL_t
#define PENDL_T__IRQRPENDL_bm 0xffffffff
#define PENDL_T__IRQRPENDL_bp 0
#define PENDL_T__IRQRPENDL_bw 32
#define PENDL_T__IRQRPENDL_reset 0x0

// reg - PENDM_t
#define PENDM_T__IRQRPENDM_bm 0xffffffff
#define PENDM_T__IRQRPENDM_bp 0
#define PENDM_T__IRQRPENDM_bw 32
#define PENDM_T__IRQRPENDM_reset 0x0

// reg - PENDU_t
#define PENDU_T__IRQRPENDU_bm 0xffffffff
#define PENDU_T__IRQRPENDU_bp 0
#define PENDU_T__IRQRPENDU_bw 32
#define PENDU_T__IRQRPENDU_reset 0x0

// reg - PENDX_t
#define PENDX_T__IRQRPENDX_bm 0x1fffffff
#define PENDX_T__IRQRPENDX_bp 0
#define PENDX_T__IRQRPENDX_bw 29
#define PENDX_T__IRQRPENDX_reset 0x0

// reg - INSVCL_t
#define INSVCL_T__IRQRINSVCL_bm 0xffffffff
#define INSVCL_T__IRQRINSVCL_bp 0
#define INSVCL_T__IRQRINSVCL_bw 32
#define INSVCL_T__IRQRINSVCL_reset 0x0

// reg - INSVCM_t
#define INSVCM_T__IRQRINSVCM_bm 0xffffffff
#define INSVCM_T__IRQRINSVCM_bp 0
#define INSVCM_T__IRQRINSVCM_bw 32
#define INSVCM_T__IRQRINSVCM_reset 0x0

// reg - INSVCU_t
#define INSVCU_T__IRQRINSVCU_bm 0xffffffff
#define INSVCU_T__IRQRINSVCU_bp 0
#define INSVCU_T__IRQRINSVCU_bw 32
#define INSVCU_T__IRQRINSVCU_reset 0x0

// reg - INSVCX_t
#define INSVCX_T__IRQRINSVCX_bm 0x1fffffff
#define INSVCX_T__IRQRINSVCX_bp 0
#define INSVCX_T__IRQRINSVCX_bw 29
#define INSVCX_T__IRQRINSVCX_reset 0x0

// addrmap - irq_router
typedef struct __attribute__ ((__packed__)) {
    HEN_t_t HEN[5];
    uint8_t RESERVED_50_7ff[0x7b0];
    uint32_t CLAIM;
    uint8_t RESERVED_804_80f[0xc];
    uint32_t PENDL;
    uint32_t PENDM;
    uint32_t PENDU;
    uint32_t PENDX;
    uint32_t INSVCL;
    uint32_t INSVCM;
    uint32_t INSVCU;
    uint32_t INSVCX;
} irq_router_t;


static_assert(sizeof(irq_router_t) == 0x830, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* IRQ_ROUTER_REGS_H */
