/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/periph/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef MUTEX_BANK_REGS_H
#define MUTEX_BANK_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - MUTEX_t
#define MUTEX_T__MTXOWN_bm 0xf
#define MUTEX_T__MTXOWN_bp 0
#define MUTEX_T__MTXOWN_bw 4
#define MUTEX_T__MTXOWN_reset 0x0

// addrmap - mutex_bank
typedef struct __attribute__ ((__packed__)) {
    uint32_t MTX[16];
} mutex_bank_t;


static_assert(sizeof(mutex_bank_t) == 0x40, "Packing error");

// enum - MUTEX_t
#define MUTEX_T__MTXOWN__FREE 0x0   // Mutex free (a read returning this value claims the mutex)

#ifdef __cplusplus
}
#endif

#endif /* MUTEX_BANK_REGS_H */
