/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/regs/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef PWM_REGS_H
#define PWM_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - PWMxCR_t
#define PWMXCR_T__PWMEN_bm 0x1
#define PWMXCR_T__PWMEN_bp 0
#define PWMXCR_T__PWMEN_bw 1
#define PWMXCR_T__PWMEN_reset 0x0
#define PWMXCR_T__CH0EN_bm 0x2
#define PWMXCR_T__CH0EN_bp 1
#define PWMXCR_T__CH0EN_bw 1
#define PWMXCR_T__CH0EN_reset 0x0
#define PWMXCR_T__CH1EN_bm 0x4
#define PWMXCR_T__CH1EN_bp 2
#define PWMXCR_T__CH1EN_bw 1
#define PWMXCR_T__CH1EN_reset 0x0
#define PWMXCR_T__PEVIE_bm 0x80
#define PWMXCR_T__PEVIE_bp 7
#define PWMXCR_T__PEVIE_bw 1
#define PWMXCR_T__PEVIE_reset 0x0
#define PWMXCR_T__FLTIE_bm 0x100
#define PWMXCR_T__FLTIE_bp 8
#define PWMXCR_T__FLTIE_bw 1
#define PWMXCR_T__FLTIE_reset 0x0
#define PWMXCR_T__FLTEN_bm 0x1000
#define PWMXCR_T__FLTEN_bp 12
#define PWMXCR_T__FLTEN_bw 1
#define PWMXCR_T__FLTEN_reset 0x0
#define PWMXCR_T__FLTTRIG_bm 0x4000
#define PWMXCR_T__FLTTRIG_bp 14
#define PWMXCR_T__FLTTRIG_bw 1
#define PWMXCR_T__FLTTRIG_reset 0x0
#define PWMXCR_T__PSC_bm 0xf0000
#define PWMXCR_T__PSC_bp 16
#define PWMXCR_T__PSC_bw 4
#define PWMXCR_T__PSC_reset 0x0

// reg - PWMxPER_t
#define PWMXPER_T__PWMPER_bm 0xffff
#define PWMXPER_T__PWMPER_bp 0
#define PWMXPER_T__PWMPER_bw 16
#define PWMXPER_T__PWMPER_reset 0x0

// reg - PWMxDTY0_t
#define PWMXDTY0_T__PWMDTY0_bm 0xffff
#define PWMXDTY0_T__PWMDTY0_bp 0
#define PWMXDTY0_T__PWMDTY0_bw 16
#define PWMXDTY0_T__PWMDTY0_reset 0x0

// reg - PWMxDTY1_t
#define PWMXDTY1_T__PWMDTY1_bm 0xffff
#define PWMXDTY1_T__PWMDTY1_bp 0
#define PWMXDTY1_T__PWMDTY1_bw 16
#define PWMXDTY1_T__PWMDTY1_reset 0x0

// reg - PWMxDTY2_t
#define PWMXDTY2_T__RESERVED_bm 0xffffffff
#define PWMXDTY2_T__RESERVED_bp 0
#define PWMXDTY2_T__RESERVED_bw 32
#define PWMXDTY2_T__RESERVED_reset 0x0

// reg - PWMxDTY3_t
#define PWMXDTY3_T__RESERVED_bm 0xffffffff
#define PWMXDTY3_T__RESERVED_bp 0
#define PWMXDTY3_T__RESERVED_bw 32
#define PWMXDTY3_T__RESERVED_reset 0x0

// reg - PWMxPOL_t
#define PWMXPOL_T__POL0_bm 0x1
#define PWMXPOL_T__POL0_bp 0
#define PWMXPOL_T__POL0_bw 1
#define PWMXPOL_T__POL0_reset 0x0
#define PWMXPOL_T__POL1_bm 0x2
#define PWMXPOL_T__POL1_bp 1
#define PWMXPOL_T__POL1_bw 1
#define PWMXPOL_T__POL1_reset 0x0
#define PWMXPOL_T__SAFE0_bm 0x10
#define PWMXPOL_T__SAFE0_bp 4
#define PWMXPOL_T__SAFE0_bw 1
#define PWMXPOL_T__SAFE0_reset 0x0
#define PWMXPOL_T__SAFE1_bm 0x20
#define PWMXPOL_T__SAFE1_bp 5
#define PWMXPOL_T__SAFE1_bw 1
#define PWMXPOL_T__SAFE1_reset 0x0

// reg - PWMxDT_t
#define PWMXDT_T__RESERVED_bm 0xffffffff
#define PWMXDT_T__RESERVED_bp 0
#define PWMXDT_T__RESERVED_bw 32
#define PWMXDT_T__RESERVED_reset 0x0

// reg - PWMxSR_t
#define PWMXSR_T__FLTF_bm 0x1
#define PWMXSR_T__FLTF_bp 0
#define PWMXSR_T__FLTF_bw 1
#define PWMXSR_T__FLTF_reset 0x0
#define PWMXSR_T__PEVF_bm 0x2
#define PWMXSR_T__PEVF_bp 1
#define PWMXSR_T__PEVF_bw 1
#define PWMXSR_T__PEVF_reset 0x0
#define PWMXSR_T__UPDF_bm 0x4
#define PWMXSR_T__UPDF_bp 2
#define PWMXSR_T__UPDF_bw 1
#define PWMXSR_T__UPDF_reset 0x0

// addrmap - pwm
typedef struct __attribute__ ((__packed__)) {
    uint32_t PWMxCR;
    uint32_t PWMxPER;
    uint32_t PWMxDTY0;
    uint32_t PWMxDTY1;
    uint32_t PWMxDTY2;
    uint32_t PWMxDTY3;
    uint32_t PWMxPOL;
    uint32_t PWMxDT;
    uint32_t PWMxSR;
} pwm_t;


static_assert(sizeof(pwm_t) == 0x24, "Packing error");

// enum - PWMxCR_t
#define PWMXCR_T__PWMEN__DISABLED_COUNTER_HELD_OUTPUTS 0x0   // Disabled (counter held, outputs safe)
#define PWMXCR_T__PWMEN__RUNNING 0x1   // Running
#define PWMXCR_T__CH0EN__CH0_DRIVES_SAFE_LEVEL 0x0   // CH0 drives safe level
#define PWMXCR_T__CH0EN__CH0_DRIVES_THE_WAVEFORM 0x1   // CH0 drives the waveform
#define PWMXCR_T__CH1EN__CH1_DRIVES_SAFE_LEVEL 0x0   // CH1 drives safe level
#define PWMXCR_T__CH1EN__CH1_DRIVES_THE_WAVEFORM 0x1   // CH1 drives the waveform
#define PWMXCR_T__PEVIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define PWMXCR_T__PEVIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define PWMXCR_T__FLTIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define PWMXCR_T__FLTIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define PWMXCR_T__FLTEN__FAULT_SYSTEM_DISABLED_FLTTRIG 0x0   // Fault system disabled (FLTTRIG ignored)
#define PWMXCR_T__FLTEN__FAULT_SYSTEM_ENABLED 0x1   // Fault system enabled
#define PWMXCR_T__FLTTRIG__TRIP_THE_FAULT_IF 0x1   // Trip the fault (if FLTEN set)

// enum - PWMxPOL_t
#define PWMXPOL_T__POL0__ACTIVE_HIGH 0x0   // Active-high
#define PWMXPOL_T__POL0__ACTIVE_LOW_INVERT 0x1   // Active-low (invert)
#define PWMXPOL_T__POL1__ACTIVE_HIGH 0x0   // Active-high
#define PWMXPOL_T__POL1__ACTIVE_LOW_INVERT 0x1   // Active-low (invert)
#define PWMXPOL_T__SAFE0__DRIVE_LOW 0x0   // Drive low
#define PWMXPOL_T__SAFE0__DRIVE_HIGH 0x1   // Drive high
#define PWMXPOL_T__SAFE1__DRIVE_LOW 0x0   // Drive low
#define PWMXPOL_T__SAFE1__DRIVE_HIGH 0x1   // Drive high

// enum - PWMxSR_t
#define PWMXSR_T__FLTF__NO_FAULT 0x0   // No fault
#define PWMXSR_T__FLTF__FAULT_LATCHED_OUTPUTS_SAFE 0x1   // Fault latched (outputs safe)
#define PWMXSR_T__PEVF__NO_EVENT 0x0   // No event
#define PWMXSR_T__PEVF__PERIOD_EVENT 0x1   // Period event
#define PWMXSR_T__UPDF__STAGING_ABSORBED 0x0   // Staging absorbed
#define PWMXSR_T__UPDF__COMMIT_PENDING 0x1   // Commit pending

#ifdef __cplusplus
}
#endif

#endif /* PWM_REGS_H */
