/* VestaRV: PWR_CTRL registers.
   Generated from hdl/common/regs/rdl/pwr_ctrl.rdl by platform/common/python/rdl_cheader_regs.py.
   Do not edit; regenerate with `bazel run //platform/common/python:rdl_regs_headers`. */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef PWR_CTRL_REGS_H
#define PWR_CTRL_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - PWRCR_t
#define PWRCR_T__PWRH0_bm 0x1
#define PWRCR_T__PWRH0_bp 0
#define PWRCR_T__PWRH0_bw 1
#define PWRCR_T__PWRH0_reset 0x0
#define PWRCR_T__PWRGATE_bm 0x1e
#define PWRCR_T__PWRGATE_bp 1
#define PWRCR_T__PWRGATE_bw 4
#define PWRCR_T__PWRGATE_reset 0x0

// reg - PWRSR0_t
#define PWRSR0_T__PWRST0_bm 0xf
#define PWRSR0_T__PWRST0_bp 0
#define PWRSR0_T__PWRST0_bw 4
#define PWRSR0_T__PWRST0_reset 0x0
#define PWRSR0_T__PWRST_1_bm 0xf0
#define PWRSR0_T__PWRST_1_bp 4
#define PWRSR0_T__PWRST_1_bw 4
#define PWRSR0_T__PWRST_1_reset 0x0
#define PWRSR0_T__PWRST_2_bm 0xf00
#define PWRSR0_T__PWRST_2_bp 8
#define PWRSR0_T__PWRST_2_bw 4
#define PWRSR0_T__PWRST_2_reset 0x0
#define PWRSR0_T__PWRST_3_bm 0xf000
#define PWRSR0_T__PWRST_3_bp 12
#define PWRSR0_T__PWRST_3_bw 4
#define PWRSR0_T__PWRST_3_reset 0x0
#define PWRSR0_T__PWRST_4_bm 0xf0000
#define PWRSR0_T__PWRST_4_bp 16
#define PWRSR0_T__PWRST_4_bw 4
#define PWRSR0_T__PWRST_4_reset 0x0
#define PWRSR0_T__PWRST_5_bm 0xf00000
#define PWRSR0_T__PWRST_5_bp 20
#define PWRSR0_T__PWRST_5_bw 4
#define PWRSR0_T__PWRST_5_reset 0x0
#define PWRSR0_T__PWRST_6_bm 0xf000000
#define PWRSR0_T__PWRST_6_bp 24
#define PWRSR0_T__PWRST_6_bw 4
#define PWRSR0_T__PWRST_6_reset 0x0
#define PWRSR0_T__PWRST_7_bm 0xf0000000
#define PWRSR0_T__PWRST_7_bp 28
#define PWRSR0_T__PWRST_7_bw 4
#define PWRSR0_T__PWRST_7_reset 0x0

// reg - PWRWAKE_t
#define PWRWAKE_T__PWGATEEN_bm 0x1
#define PWRWAKE_T__PWGATEEN_bp 0
#define PWRWAKE_T__PWGATEEN_bw 1
#define PWRWAKE_T__PWGATEEN_reset 0x0
#define PWRWAKE_T__PWRLSPGOOD_bm 0x2
#define PWRWAKE_T__PWRLSPGOOD_bp 1
#define PWRWAKE_T__PWRLSPGOOD_bw 1
#define PWRWAKE_T__PWRLSPGOOD_reset 0x0
#define PWRWAKE_T__PWRLSFIELD_bm 0x4
#define PWRWAKE_T__PWRLSFIELD_bp 2
#define PWRWAKE_T__PWRLSFIELD_bw 1
#define PWRWAKE_T__PWRLSFIELD_reset 0x0
#define PWRWAKE_T__PWSWRLS_bm 0x8
#define PWRWAKE_T__PWSWRLS_bp 3
#define PWRWAKE_T__PWSWRLS_bw 1
#define PWRWAKE_T__PWSWRLS_reset 0x0
#define PWRWAKE_T__PWREHOLD_bm 0x10
#define PWRWAKE_T__PWREHOLD_bp 4
#define PWRWAKE_T__PWREHOLD_bw 1
#define PWRWAKE_T__PWREHOLD_reset 0x0

// reg - PWRSTS_t
#define PWRSTS_T__PWPGOODLIV_bm 0x1
#define PWRSTS_T__PWPGOODLIV_bp 0
#define PWRSTS_T__PWPGOODLIV_bw 1
#define PWRSTS_T__PWPGOODLIV_reset 0x0
#define PWRSTS_T__PWFIELDLIV_bm 0x2
#define PWRSTS_T__PWFIELDLIV_bp 1
#define PWRSTS_T__PWFIELDLIV_bw 1
#define PWRSTS_T__PWFIELDLIV_reset 0x0
#define PWRSTS_T__PWSTRAP_bm 0x4
#define PWRSTS_T__PWSTRAP_bp 2
#define PWRSTS_T__PWSTRAP_bw 1
#define PWRSTS_T__PWSTRAP_reset 0x0
#define PWRSTS_T__PWSTRAPVLD_bm 0x8
#define PWRSTS_T__PWSTRAPVLD_bp 3
#define PWRSTS_T__PWSTRAPVLD_bw 1
#define PWRSTS_T__PWSTRAPVLD_reset 0x0
#define PWRSTS_T__PWBOOTHOLD_bm 0x10
#define PWRSTS_T__PWBOOTHOLD_bp 4
#define PWRSTS_T__PWBOOTHOLD_bw 1
#define PWRSTS_T__PWBOOTHOLD_reset 0x0
#define PWRSTS_T__PWRRLSLATCH_bm 0x20
#define PWRSTS_T__PWRRLSLATCH_bp 5
#define PWRSTS_T__PWRRLSLATCH_bw 1
#define PWRSTS_T__PWRRLSLATCH_reset 0x0

// reg - TASKWKM_t
#define TASKWKM_T__RESERVED_bm 0x1
#define TASKWKM_T__RESERVED_bp 0
#define TASKWKM_T__RESERVED_bw 1
#define TASKWKM_T__RESERVED_reset 0x0
#define TASKWKM_T__PWRTASKWKM_bm 0x1e
#define TASKWKM_T__PWRTASKWKM_bp 1
#define TASKWKM_T__PWRTASKWKM_bw 4
#define TASKWKM_T__PWRTASKWKM_reset 0x0

// addrmap - pwr_ctrl
typedef struct __attribute__ ((__packed__)) {
    uint32_t PWRCR;
    uint32_t PWRSR0;
    uint8_t RESERVED_8_13[0xc];
    uint32_t PWRWAKE;
    uint32_t PWRSTS;
    uint32_t TASKWKM;
} pwr_ctrl_t;


static_assert(sizeof(pwr_ctrl_t) == 0x20, "Packing error");

// enum - PWRCR_t
#define PWRCR_T__PWRGATE__NONE 0x0   // All tile harts powered

#ifdef __cplusplus
}
#endif

#endif /* PWR_CTRL_REGS_H */
