/* VestaRV: RTC registers.
   Generated from hdl/common/regs/rdl/rtc.rdl by platform/common/python/rdl_cheader_regs.py.
   Do not edit; regenerate with `bazel run //platform/common/python:rdl_regs_headers`. */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef RTC_REGS_H
#define RTC_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - RTCxCR_t
#define RTCXCR_T__RTCEN_bm 0x1
#define RTCXCR_T__RTCEN_bp 0
#define RTCXCR_T__RTCEN_bw 1
#define RTCXCR_T__RTCEN_reset 0x0
#define RTCXCR_T__RTCALMEN_bm 0x2
#define RTCXCR_T__RTCALMEN_bp 1
#define RTCXCR_T__RTCALMEN_bw 1
#define RTCXCR_T__RTCALMEN_reset 0x0
#define RTCXCR_T__RTCTICKEN_bm 0x4
#define RTCXCR_T__RTCTICKEN_bp 2
#define RTCXCR_T__RTCTICKEN_bw 1
#define RTCXCR_T__RTCTICKEN_reset 0x0
#define RTCXCR_T__RTCALMIE_bm 0x8
#define RTCXCR_T__RTCALMIE_bp 3
#define RTCXCR_T__RTCALMIE_bw 1
#define RTCXCR_T__RTCALMIE_reset 0x0
#define RTCXCR_T__RTCTICKIE_bm 0x10
#define RTCXCR_T__RTCTICKIE_bp 4
#define RTCXCR_T__RTCTICKIE_bw 1
#define RTCXCR_T__RTCTICKIE_reset 0x0

// reg - RTCxSEC_t
#define RTCXSEC_T__RTCSEC_bm 0xffffffff
#define RTCXSEC_T__RTCSEC_bp 0
#define RTCXSEC_T__RTCSEC_bw 32
#define RTCXSEC_T__RTCSEC_reset 0x0

// reg - RTCxSUB_t
#define RTCXSUB_T__RTCSUB_bm 0x7fff
#define RTCXSUB_T__RTCSUB_bp 0
#define RTCXSUB_T__RTCSUB_bw 15
#define RTCXSUB_T__RTCSUB_reset 0x0

// reg - RTCxALM_t
#define RTCXALM_T__RTCALM_bm 0xffffffff
#define RTCXALM_T__RTCALM_bp 0
#define RTCXALM_T__RTCALM_bw 32
#define RTCXALM_T__RTCALM_reset 0x0

// reg - RTCxPER_t
#define RTCXPER_T__RTCPER_bm 0xffff
#define RTCXPER_T__RTCPER_bp 0
#define RTCXPER_T__RTCPER_bw 16
#define RTCXPER_T__RTCPER_reset 0x0

// reg - RTCxSR_t
#define RTCXSR_T__RTCSYNC_bm 0x1
#define RTCXSR_T__RTCSYNC_bp 0
#define RTCXSR_T__RTCSYNC_bw 1
#define RTCXSR_T__RTCSYNC_reset 0x0
#define RTCXSR_T__RTCALMF_bm 0x2
#define RTCXSR_T__RTCALMF_bp 1
#define RTCXSR_T__RTCALMF_bw 1
#define RTCXSR_T__RTCALMF_reset 0x0
#define RTCXSR_T__RTCTICKF_bm 0x4
#define RTCXSR_T__RTCTICKF_bp 2
#define RTCXSR_T__RTCTICKF_bw 1
#define RTCXSR_T__RTCTICKF_reset 0x0

// reg - RTCxTRIM_t
#define RTCXTRIM_T__RESERVED_bm 0xffffffff
#define RTCXTRIM_T__RESERVED_bp 0
#define RTCXTRIM_T__RESERVED_bw 32
#define RTCXTRIM_T__RESERVED_reset 0x0

// addrmap - rtc
typedef struct __attribute__ ((__packed__)) {
    uint32_t RTCxCR;
    uint32_t RTCxSEC;
    uint32_t RTCxSUB;
    uint32_t RTCxALM;
    uint32_t RTCxPER;
    uint32_t RTCxSR;
    uint32_t RTCxTRIM;
} rtc_t;


static_assert(sizeof(rtc_t) == 0x1c, "Packing error");

// enum - RTCxCR_t
#define RTCXCR_T__RTCEN__COUNTER_FROZEN 0x0   // Counter frozen
#define RTCXCR_T__RTCEN__COUNTING 0x1   // Counting
#define RTCXCR_T__RTCALMEN__ALARM_DISABLED 0x0   // Alarm disabled
#define RTCXCR_T__RTCALMEN__ALARM_ENABLED 0x1   // Alarm enabled
#define RTCXCR_T__RTCTICKEN__TICK_DISABLED 0x0   // Tick disabled
#define RTCXCR_T__RTCTICKEN__TICK_ENABLED 0x1   // Tick enabled
#define RTCXCR_T__RTCALMIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define RTCXCR_T__RTCALMIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define RTCXCR_T__RTCTICKIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define RTCXCR_T__RTCTICKIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled

// enum - RTCxSR_t
#define RTCXSR_T__RTCSYNC__IDLE_SAFE_TO_COMMIT 0x0   // Idle (safe to commit)
#define RTCXSR_T__RTCSYNC__COMMIT_IN_FLIGHT 0x1   // Commit in flight
#define RTCXSR_T__RTCALMF__NO_EVENT 0x0   // No event
#define RTCXSR_T__RTCALMF__ALARM_FIRED 0x1   // Alarm fired
#define RTCXSR_T__RTCTICKF__NO_EVENT 0x0   // No event
#define RTCXSR_T__RTCTICKF__TICK_FIRED 0x1   // Tick fired

#ifdef __cplusplus
}
#endif

#endif /* RTC_REGS_H */
