/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/periph/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef SYSTEM_REGS_H
#define SYSTEM_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - SYSCLKCR_t
#define SYSCLKCR_T__MCLKSEL_bm 0x3
#define SYSCLKCR_T__MCLKSEL_bp 0
#define SYSCLKCR_T__MCLKSEL_bw 2
#define SYSCLKCR_T__MCLKSEL_reset 0x0
#define SYSCLKCR_T__SMCLKSEL_bm 0xc
#define SYSCLKCR_T__SMCLKSEL_bp 2
#define SYSCLKCR_T__SMCLKSEL_bw 2
#define SYSCLKCR_T__SMCLKSEL_reset 0x0
#define SYSCLKCR_T__SMCLKOFF_bm 0x10
#define SYSCLKCR_T__SMCLKOFF_bp 4
#define SYSCLKCR_T__SMCLKOFF_bw 1
#define SYSCLKCR_T__SMCLKOFF_reset 0x0
#define SYSCLKCR_T__LFXTOFF_bm 0x20
#define SYSCLKCR_T__LFXTOFF_bp 5
#define SYSCLKCR_T__LFXTOFF_bw 1
#define SYSCLKCR_T__LFXTOFF_reset 0x0
#define SYSCLKCR_T__HFXTOFF_bm 0x40
#define SYSCLKCR_T__HFXTOFF_bp 6
#define SYSCLKCR_T__HFXTOFF_bw 1
#define SYSCLKCR_T__HFXTOFF_reset 0x0
#define SYSCLKCR_T__DCO0ON_bm 0x80
#define SYSCLKCR_T__DCO0ON_bp 7
#define SYSCLKCR_T__DCO0ON_bw 1
#define SYSCLKCR_T__DCO0ON_reset 0x0
#define SYSCLKCR_T__DCO1ON_bm 0x100
#define SYSCLKCR_T__DCO1ON_bp 8
#define SYSCLKCR_T__DCO1ON_bw 1
#define SYSCLKCR_T__DCO1ON_reset 0x0

// reg - CLKDIVCR_t
#define CLKDIVCR_T__SYSMCLKDIV_bm 0x7
#define CLKDIVCR_T__SYSMCLKDIV_bp 0
#define CLKDIVCR_T__SYSMCLKDIV_bw 3
#define CLKDIVCR_T__SYSMCLKDIV_reset 0x0
#define CLKDIVCR_T__SYSSMCLKDIV_bm 0x38
#define CLKDIVCR_T__SYSSMCLKDIV_bp 3
#define CLKDIVCR_T__SYSSMCLKDIV_bw 3
#define CLKDIVCR_T__SYSSMCLKDIV_reset 0x0

// reg - BLOCKPWR_t
#define BLOCKPWR_T__SYSROMOFF_bm 0x1
#define BLOCKPWR_T__SYSROMOFF_bp 0
#define BLOCKPWR_T__SYSROMOFF_bw 1
#define BLOCKPWR_T__SYSROMOFF_reset 0x0
#define BLOCKPWR_T__SYSRAM0OFF_bm 0x2
#define BLOCKPWR_T__SYSRAM0OFF_bp 1
#define BLOCKPWR_T__SYSRAM0OFF_bw 1
#define BLOCKPWR_T__SYSRAM0OFF_reset 0x0
#define BLOCKPWR_T__SYSRAM1OFF_bm 0x4
#define BLOCKPWR_T__SYSRAM1OFF_bp 2
#define BLOCKPWR_T__SYSRAM1OFF_bw 1
#define BLOCKPWR_T__SYSRAM1OFF_reset 0x0
#define BLOCKPWR_T__SYSSHB0OFF_bm 0x8
#define BLOCKPWR_T__SYSSHB0OFF_bp 3
#define BLOCKPWR_T__SYSSHB0OFF_bw 1
#define BLOCKPWR_T__SYSSHB0OFF_reset 0x0
#define BLOCKPWR_T__SYSSHB1OFF_bm 0x10
#define BLOCKPWR_T__SYSSHB1OFF_bp 4
#define BLOCKPWR_T__SYSSHB1OFF_bw 1
#define BLOCKPWR_T__SYSSHB1OFF_reset 0x0
#define BLOCKPWR_T__SYSSHB2OFF_bm 0x20
#define BLOCKPWR_T__SYSSHB2OFF_bp 5
#define BLOCKPWR_T__SYSSHB2OFF_bw 1
#define BLOCKPWR_T__SYSSHB2OFF_reset 0x0
#define BLOCKPWR_T__SYSSHB3OFF_bm 0x40
#define BLOCKPWR_T__SYSSHB3OFF_bp 6
#define BLOCKPWR_T__SYSSHB3OFF_bw 1
#define BLOCKPWR_T__SYSSHB3OFF_reset 0x0

// reg - CRCDATA_t
#define CRCDATA_T__SYSCRCDATA_bm 0xff
#define CRCDATA_T__SYSCRCDATA_bp 0
#define CRCDATA_T__SYSCRCDATA_bw 8
#define CRCDATA_T__SYSCRCDATA_reset 0x0

// reg - CRCSTATE_t
#define CRCSTATE_T__SYSCRCSTATE_bm 0xffff
#define CRCSTATE_T__SYSCRCSTATE_bp 0
#define CRCSTATE_T__SYSCRCSTATE_bw 16
#define CRCSTATE_T__SYSCRCSTATE_reset 0x0

// reg - WDTPASS_t
#define WDTPASS_T__SYSWDTPASS_bm 0xffffffff
#define WDTPASS_T__SYSWDTPASS_bp 0
#define WDTPASS_T__SYSWDTPASS_bw 32
#define WDTPASS_T__SYSWDTPASS_reset 0x0

// reg - WDTCR_t
#define WDTCR_T__SYSWDTHWRST_bm 0x1
#define WDTCR_T__SYSWDTHWRST_bp 0
#define WDTCR_T__SYSWDTHWRST_bw 1
#define WDTCR_T__SYSWDTHWRST_reset 0x0
#define WDTCR_T__SYSWDTIE_bm 0x2
#define WDTCR_T__SYSWDTIE_bp 1
#define WDTCR_T__SYSWDTIE_bw 1
#define WDTCR_T__SYSWDTIE_reset 0x0
#define WDTCR_T__SYSWDTCDIV_bm 0x3c
#define WDTCR_T__SYSWDTCDIV_bp 2
#define WDTCR_T__SYSWDTCDIV_bw 4
#define WDTCR_T__SYSWDTCDIV_reset 0x0
#define WDTCR_T__SYSWDTEN_bm 0x80
#define WDTCR_T__SYSWDTEN_bp 7
#define WDTCR_T__SYSWDTEN_bw 1
#define WDTCR_T__SYSWDTEN_reset 0x0

// reg - WDTSR_t
#define WDTSR_T__SYSWDTRF_bm 0x1
#define WDTSR_T__SYSWDTRF_bp 0
#define WDTSR_T__SYSWDTRF_bw 1
#define WDTSR_T__SYSWDTRF_reset 0x0
#define WDTSR_T__SYSWDTIF_bm 0x2
#define WDTSR_T__SYSWDTIF_bp 1
#define WDTSR_T__SYSWDTIF_bw 1
#define WDTSR_T__SYSWDTIF_reset 0x0

// reg - WDTVAL_t
#define WDTVAL_T__SYSWDTVAL_bm 0xffffff
#define WDTVAL_T__SYSWDTVAL_bp 0
#define WDTVAL_T__SYSWDTVAL_bw 24
#define WDTVAL_T__SYSWDTVAL_reset 0x0

// reg - DCO0BIAS_t
#define DCO0BIAS_T__SYSDCO0BIAS_bm 0xfff
#define DCO0BIAS_T__SYSDCO0BIAS_bp 0
#define DCO0BIAS_T__SYSDCO0BIAS_bw 12
#define DCO0BIAS_T__SYSDCO0BIAS_reset 0x800

// reg - DCO1BIAS_t
#define DCO1BIAS_T__SYSDCO1BIAS_bm 0xfff
#define DCO1BIAS_T__SYSDCO1BIAS_bp 0
#define DCO1BIAS_T__SYSDCO1BIAS_bw 12
#define DCO1BIAS_T__SYSDCO1BIAS_reset 0x800

// addrmap - system
typedef struct __attribute__ ((__packed__)) {
    uint16_t SYSCLKCR;
    uint8_t RESERVED_2_3[0x2];
    uint8_t CLKDIVCR;
    uint8_t RESERVED_5_7[0x3];
    uint8_t BLOCKPWR;
    uint8_t RESERVED_9_b[0x3];
    uint8_t CRCDATA;
    uint8_t RESERVED_d_f[0x3];
    uint16_t CRCSTATE;
    uint8_t RESERVED_12_2f[0x1e];
    uint32_t WDTPASS;
    uint8_t WDTCR;
    uint8_t RESERVED_35_37[0x3];
    uint8_t WDTSR;
    uint8_t RESERVED_39_3b[0x3];
    uint32_t WDTVAL;
    uint16_t DCO0BIAS;
    uint8_t RESERVED_42_43[0x2];
    uint16_t DCO1BIAS;
} system_t;


static_assert(sizeof(system_t) == 0x46, "Packing error");

// enum - SYSCLKCR_t
#define SYSCLKCR_T__MCLKSEL__HFXT 0x0   // High Frequency Crystal Clock
#define SYSCLKCR_T__MCLKSEL__SMCLK 0x1   // Submain Clock
#define SYSCLKCR_T__MCLKSEL__DCO0 0x2   // Digitally Controlled Oscillator 0
#define SYSCLKCR_T__MCLKSEL__DCO1 0x3   // Digitally Controlled Oscillator 1
#define SYSCLKCR_T__SMCLKSEL__HFXT 0x0   // High Frequency Crystal Clock
#define SYSCLKCR_T__SMCLKSEL__LFXT 0x1   // Low Frequency Crystal Clock
#define SYSCLKCR_T__SMCLKSEL__DCO0 0x2   // Digitally Controlled Oscillator 0
#define SYSCLKCR_T__SMCLKSEL__DCO1 0x3   // Digitally Controlled Oscillator 1
#define SYSCLKCR_T__SMCLKOFF__SMCLK_ENABLED 0x0   // SMCLK enabled
#define SYSCLKCR_T__SMCLKOFF__SMCLK_DISABLED 0x1   // SMCLK disabled
#define SYSCLKCR_T__LFXTOFF__LFXT_ENABLED 0x0   // LFXT enabled
#define SYSCLKCR_T__LFXTOFF__LFXT_DISABLED 0x1   // LFXT disabled
#define SYSCLKCR_T__HFXTOFF__HFXT_ENABLED 0x0   // HFXT enabled
#define SYSCLKCR_T__HFXTOFF__HFXT_DISABLED 0x1   // HFXT disabled
#define SYSCLKCR_T__DCO0ON__DCO0_POWERED_OFF 0x0   // DCO0 powered off
#define SYSCLKCR_T__DCO0ON__DCO0_POWERED_ON 0x1   // DCO0 powered on
#define SYSCLKCR_T__DCO1ON__DCO1_POWERED_OFF 0x0   // DCO1 powered off
#define SYSCLKCR_T__DCO1ON__DCO1_POWERED_ON 0x1   // DCO1 powered on

// enum - CLKDIVCR_t
#define CLKDIVCR_T__SYSMCLKDIV__1 0x0   // /1 (no division)
#define CLKDIVCR_T__SYSMCLKDIV__2 0x1   // /2
#define CLKDIVCR_T__SYSMCLKDIV__4 0x2   // /4
#define CLKDIVCR_T__SYSMCLKDIV__8 0x3   // /8
#define CLKDIVCR_T__SYSMCLKDIV__16 0x4   // /16
#define CLKDIVCR_T__SYSMCLKDIV__32 0x5   // /32
#define CLKDIVCR_T__SYSMCLKDIV__64 0x6   // /64
#define CLKDIVCR_T__SYSMCLKDIV__128 0x7   // /128
#define CLKDIVCR_T__SYSSMCLKDIV__1 0x0   // /1 (no division)
#define CLKDIVCR_T__SYSSMCLKDIV__2 0x1   // /2
#define CLKDIVCR_T__SYSSMCLKDIV__4 0x2   // /4
#define CLKDIVCR_T__SYSSMCLKDIV__8 0x3   // /8
#define CLKDIVCR_T__SYSSMCLKDIV__16 0x4   // /16
#define CLKDIVCR_T__SYSSMCLKDIV__32 0x5   // /32
#define CLKDIVCR_T__SYSSMCLKDIV__64 0x6   // /64
#define CLKDIVCR_T__SYSSMCLKDIV__128 0x7   // /128

// enum - BLOCKPWR_t
#define BLOCKPWR_T__SYSROMOFF__ROM_POWERED_ON 0x0   // ROM powered on
#define BLOCKPWR_T__SYSROMOFF__ROM_POWERED_OFF 0x1   // ROM powered off
#define BLOCKPWR_T__SYSRAM0OFF__RAM_BLOCK_0_POWERED 0x0   // RAM block 0 powered on
#define BLOCKPWR_T__SYSRAM0OFF__RAM_BLOCK_0_POWERED_2 0x1   // RAM block 0 powered off
#define BLOCKPWR_T__SYSRAM1OFF__RAM_BLOCK_1_POWERED 0x0   // RAM block 1 powered on
#define BLOCKPWR_T__SYSRAM1OFF__RAM_BLOCK_1_POWERED_2 0x1   // RAM block 1 powered off
#define BLOCKPWR_T__SYSSHB0OFF__BANK_0_POWERED_ON 0x0   // Bank 0 powered on
#define BLOCKPWR_T__SYSSHB0OFF__BANK_0_POWERED_OFF 0x1   // Bank 0 powered off (contents lost)
#define BLOCKPWR_T__SYSSHB1OFF__BANK_1_POWERED_ON 0x0   // Bank 1 powered on
#define BLOCKPWR_T__SYSSHB1OFF__BANK_1_POWERED_OFF 0x1   // Bank 1 powered off (contents lost)
#define BLOCKPWR_T__SYSSHB2OFF__BANK_2_POWERED_ON 0x0   // Bank 2 powered on
#define BLOCKPWR_T__SYSSHB2OFF__BANK_2_POWERED_OFF 0x1   // Bank 2 powered off (contents lost)
#define BLOCKPWR_T__SYSSHB3OFF__BANK_3_POWERED_ON 0x0   // Bank 3 powered on
#define BLOCKPWR_T__SYSSHB3OFF__BANK_3_POWERED_OFF 0x1   // Bank 3 powered off (contents lost)

// enum - WDTCR_t
#define WDTCR_T__SYSWDTHWRST__WATCHDOG_RESET_DISABLED 0x0   // Watchdog reset disabled
#define WDTCR_T__SYSWDTHWRST__WATCHDOG_RESET_ENABLED 0x1   // Watchdog reset enabled
#define WDTCR_T__SYSWDTIE__WATCHDOG_INTERRUPT_DISABLED 0x0   // Watchdog interrupt disabled
#define WDTCR_T__SYSWDTIE__WATCHDOG_INTERRUPT_ENABLED 0x1   // Watchdog interrupt enabled
#define WDTCR_T__SYSWDTCDIV__65536 0x0   // Bit 16: 65,536 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__131072 0x1   // Bit 17: 131,072 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__262144 0x2   // Bit 18: 262,144 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__524288 0x3   // Bit 19: 524,288 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__1048576 0x4   // Bit 20: 1,048,576 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__2097152 0x5   // Bit 21: 2,097,152 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__4194304 0x6   // Bit 22: 4,194,304 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__8388608 0x7   // Bit 23: 8,388,608 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__16777216 0x8   // Bit 24: 16,777,216 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__33554432 0x9   // Bit 25: 33,554,432 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__67108864 0xa   // Bit 26: 67,108,864 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__134217728 0xb   // Bit 27: 134,217,728 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__268435456 0xc   // Bit 28: 268,435,456 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__536870912 0xd   // Bit 29: 536,870,912 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__1073741824 0xe   // Bit 30: 1,073,741,824 MCLK cycles
#define WDTCR_T__SYSWDTCDIV__2147483648 0xf   // Bit 31: 2,147,483,648 MCLK cycles
#define WDTCR_T__SYSWDTEN__WATCHDOG_DISABLED 0x0   // Watchdog disabled
#define WDTCR_T__SYSWDTEN__WATCHDOG_ENABLED 0x1   // Watchdog enabled

// enum - WDTSR_t
#define WDTSR_T__SYSWDTRF__RESET_NOT_CAUSED_BY 0x0   // Reset not caused by watchdog
#define WDTSR_T__SYSWDTRF__RESET_CAUSED_BY_WATCHDOG 0x1   // Reset caused by watchdog
#define WDTSR_T__SYSWDTIF__NO_WATCHDOG_INTERRUPT_PENDING 0x0   // No watchdog interrupt pending
#define WDTSR_T__SYSWDTIF__WATCHDOG_INTERRUPT_OCCURRED 0x1   // Watchdog interrupt occurred

#ifdef __cplusplus
}
#endif

#endif /* SYSTEM_REGS_H */
