/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/regs/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef TIMER_REGS_H
#define TIMER_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - TIMxCR_t
#define TIMXCR_T__CMP0IE_bm 0x1
#define TIMXCR_T__CMP0IE_bp 0
#define TIMXCR_T__CMP0IE_bw 1
#define TIMXCR_T__CMP0IE_reset 0x0
#define TIMXCR_T__CMP1IE_bm 0x2
#define TIMXCR_T__CMP1IE_bp 1
#define TIMXCR_T__CMP1IE_bw 1
#define TIMXCR_T__CMP1IE_reset 0x0
#define TIMXCR_T__CMP2IE_bm 0x4
#define TIMXCR_T__CMP2IE_bp 2
#define TIMXCR_T__CMP2IE_bw 1
#define TIMXCR_T__CMP2IE_reset 0x0
#define TIMXCR_T__OVIE_bm 0x8
#define TIMXCR_T__OVIE_bp 3
#define TIMXCR_T__OVIE_bw 1
#define TIMXCR_T__OVIE_reset 0x0
#define TIMXCR_T__CAP0IE_bm 0x10
#define TIMXCR_T__CAP0IE_bp 4
#define TIMXCR_T__CAP0IE_bw 1
#define TIMXCR_T__CAP0IE_reset 0x0
#define TIMXCR_T__CAP1IE_bm 0x20
#define TIMXCR_T__CAP1IE_bp 5
#define TIMXCR_T__CAP1IE_bw 1
#define TIMXCR_T__CAP1IE_reset 0x0
#define TIMXCR_T__TEN_bm 0x40
#define TIMXCR_T__TEN_bp 6
#define TIMXCR_T__TEN_bw 1
#define TIMXCR_T__TEN_reset 0x0
#define TIMXCR_T__CMP2RST_bm 0x80
#define TIMXCR_T__CMP2RST_bp 7
#define TIMXCR_T__CMP2RST_bw 1
#define TIMXCR_T__CMP2RST_reset 0x0
#define TIMXCR_T__SSEL_bm 0x300
#define TIMXCR_T__SSEL_bp 8
#define TIMXCR_T__SSEL_bw 2
#define TIMXCR_T__SSEL_reset 0x0
#define TIMXCR_T__CAP0EN_bm 0x400
#define TIMXCR_T__CAP0EN_bp 10
#define TIMXCR_T__CAP0EN_bw 1
#define TIMXCR_T__CAP0EN_reset 0x0
#define TIMXCR_T__CAP1EN_bm 0x800
#define TIMXCR_T__CAP1EN_bp 11
#define TIMXCR_T__CAP1EN_bw 1
#define TIMXCR_T__CAP1EN_reset 0x0
#define TIMXCR_T__CAP0FE_bm 0x1000
#define TIMXCR_T__CAP0FE_bp 12
#define TIMXCR_T__CAP0FE_bw 1
#define TIMXCR_T__CAP0FE_reset 0x0
#define TIMXCR_T__CAP1FE_bm 0x2000
#define TIMXCR_T__CAP1FE_bp 13
#define TIMXCR_T__CAP1FE_bw 1
#define TIMXCR_T__CAP1FE_reset 0x0
#define TIMXCR_T__CMP0IH_bm 0x4000
#define TIMXCR_T__CMP0IH_bp 14
#define TIMXCR_T__CMP0IH_bw 1
#define TIMXCR_T__CMP0IH_reset 0x0
#define TIMXCR_T__CMP1IH_bm 0x8000
#define TIMXCR_T__CMP1IH_bp 15
#define TIMXCR_T__CMP1IH_bw 1
#define TIMXCR_T__CMP1IH_reset 0x0
#define TIMXCR_T__DIV_bm 0xf0000
#define TIMXCR_T__DIV_bp 16
#define TIMXCR_T__DIV_bw 4
#define TIMXCR_T__DIV_reset 0x0

// reg - TIMxSR_t
#define TIMXSR_T__CMP0IF_bm 0x1
#define TIMXSR_T__CMP0IF_bp 0
#define TIMXSR_T__CMP0IF_bw 1
#define TIMXSR_T__CMP0IF_reset 0x0
#define TIMXSR_T__CMP1IF_bm 0x2
#define TIMXSR_T__CMP1IF_bp 1
#define TIMXSR_T__CMP1IF_bw 1
#define TIMXSR_T__CMP1IF_reset 0x0
#define TIMXSR_T__CMP2IF_bm 0x4
#define TIMXSR_T__CMP2IF_bp 2
#define TIMXSR_T__CMP2IF_bw 1
#define TIMXSR_T__CMP2IF_reset 0x0
#define TIMXSR_T__OVIF_bm 0x8
#define TIMXSR_T__OVIF_bp 3
#define TIMXSR_T__OVIF_bw 1
#define TIMXSR_T__OVIF_reset 0x0
#define TIMXSR_T__CAP0IF_bm 0x10
#define TIMXSR_T__CAP0IF_bp 4
#define TIMXSR_T__CAP0IF_bw 1
#define TIMXSR_T__CAP0IF_reset 0x0
#define TIMXSR_T__CAP1IF_bm 0x20
#define TIMXSR_T__CAP1IF_bp 5
#define TIMXSR_T__CAP1IF_bw 1
#define TIMXSR_T__CAP1IF_reset 0x0
#define TIMXSR_T__CMP0OUT_bm 0x40
#define TIMXSR_T__CMP0OUT_bp 6
#define TIMXSR_T__CMP0OUT_bw 1
#define TIMXSR_T__CMP0OUT_reset 0x0
#define TIMXSR_T__CMP1OUT_bm 0x80
#define TIMXSR_T__CMP1OUT_bp 7
#define TIMXSR_T__CMP1OUT_bw 1
#define TIMXSR_T__CMP1OUT_reset 0x0

// reg - TIMxVAL_t
#define TIMXVAL_T__VAL_bm 0xffffffff
#define TIMXVAL_T__VAL_bp 0
#define TIMXVAL_T__VAL_bw 32
#define TIMXVAL_T__VAL_reset 0x0

// reg - TIMxCMP0_t
#define TIMXCMP0_T__CMP0_bm 0xffffffff
#define TIMXCMP0_T__CMP0_bp 0
#define TIMXCMP0_T__CMP0_bw 32
#define TIMXCMP0_T__CMP0_reset 0x0

// reg - TIMxCMP1_t
#define TIMXCMP1_T__CMP1_bm 0xffffffff
#define TIMXCMP1_T__CMP1_bp 0
#define TIMXCMP1_T__CMP1_bw 32
#define TIMXCMP1_T__CMP1_reset 0x0

// reg - TIMxCMP2_t
#define TIMXCMP2_T__CMP2_bm 0xffffffff
#define TIMXCMP2_T__CMP2_bp 0
#define TIMXCMP2_T__CMP2_bw 32
#define TIMXCMP2_T__CMP2_reset 0x0

// reg - TIMxCAP0_t
#define TIMXCAP0_T__CAP0_bm 0xffffffff
#define TIMXCAP0_T__CAP0_bp 0
#define TIMXCAP0_T__CAP0_bw 32
#define TIMXCAP0_T__CAP0_reset 0x0

// reg - TIMxCAP1_t
#define TIMXCAP1_T__CAP1_bm 0xffffffff
#define TIMXCAP1_T__CAP1_bp 0
#define TIMXCAP1_T__CAP1_bw 32
#define TIMXCAP1_T__CAP1_reset 0x0

// addrmap - timer
typedef struct __attribute__ ((__packed__)) {
    uint32_t TIMxCR;
    uint8_t TIMxSR;
    uint8_t RESERVED_5_7[0x3];
    uint32_t TIMxVAL;
    uint32_t TIMxCMP0;
    uint32_t TIMxCMP1;
    uint32_t TIMxCMP2;
    uint32_t TIMxCAP0;
    uint32_t TIMxCAP1;
} timer_t;


static_assert(sizeof(timer_t) == 0x20, "Packing error");

// enum - TIMxCR_t
#define TIMXCR_T__CMP0IE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TIMXCR_T__CMP0IE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TIMXCR_T__CMP1IE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TIMXCR_T__CMP1IE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TIMXCR_T__CMP2IE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TIMXCR_T__CMP2IE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TIMXCR_T__OVIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TIMXCR_T__OVIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TIMXCR_T__CAP0IE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TIMXCR_T__CAP0IE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TIMXCR_T__CAP1IE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TIMXCR_T__CAP1IE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TIMXCR_T__TEN__TIMER_DISABLED 0x0   // Timer disabled
#define TIMXCR_T__TEN__TIMER_ENABLED 0x1   // Timer enabled
#define TIMXCR_T__CMP2RST__FREE_RUNNING_MODE_RESETS 0x0   // Free-running mode (resets at 2³²-1)
#define TIMXCR_T__CMP2RST__RESETS_ON_TIMXVAL_TIMXCMP2 0x1   // Resets on TIMxVAL = TIMxCMP2
#define TIMXCR_T__SSEL__SMCLK 0x0   // SMCLK
#define TIMXCR_T__SSEL__MCLK 0x1   // MCLK
#define TIMXCR_T__SSEL__LFXT 0x2   // LFXT (low frequency crystal)
#define TIMXCR_T__SSEL__HFXT 0x3   // HFXT (high frequency crystal)
#define TIMXCR_T__CAP0EN__CAPTURE_0_DISABLED 0x0   // Capture 0 disabled
#define TIMXCR_T__CAP0EN__CAPTURE_0_ENABLED 0x1   // Capture 0 enabled
#define TIMXCR_T__CAP1EN__CAPTURE_1_DISABLED 0x0   // Capture 1 disabled
#define TIMXCR_T__CAP1EN__CAPTURE_1_ENABLED 0x1   // Capture 1 enabled
#define TIMXCR_T__CAP0FE__CAPTURE_ON_RISING_EDGE 0x0   // Capture on rising edge
#define TIMXCR_T__CAP0FE__CAPTURE_ON_FALLING_EDGE 0x1   // Capture on falling edge
#define TIMXCR_T__CAP1FE__CAPTURE_ON_RISING_EDGE 0x0   // Capture on rising edge
#define TIMXCR_T__CAP1FE__CAPTURE_ON_FALLING_EDGE 0x1   // Capture on falling edge
#define TIMXCR_T__CMP0IH__PWM_OUTPUT_STARTS_LOW 0x0   // PWM output starts LOW
#define TIMXCR_T__CMP0IH__PWM_OUTPUT_STARTS_HIGH 0x1   // PWM output starts HIGH
#define TIMXCR_T__CMP1IH__PWM_OUTPUT_STARTS_LOW 0x0   // PWM output starts LOW
#define TIMXCR_T__CMP1IH__PWM_OUTPUT_STARTS_HIGH 0x1   // PWM output starts HIGH
#define TIMXCR_T__DIV__1 0x0   // /1 (no division)
#define TIMXCR_T__DIV__2 0x1   // /2
#define TIMXCR_T__DIV__4 0x2   // /4
#define TIMXCR_T__DIV__8 0x3   // /8
#define TIMXCR_T__DIV__16 0x4   // /16
#define TIMXCR_T__DIV__32 0x5   // /32
#define TIMXCR_T__DIV__64 0x6   // /64
#define TIMXCR_T__DIV__128 0x7   // /128
#define TIMXCR_T__DIV__256 0x8   // /256
#define TIMXCR_T__DIV__512 0x9   // /512
#define TIMXCR_T__DIV__1024 0xa   // /1,024
#define TIMXCR_T__DIV__2048 0xb   // /2,048
#define TIMXCR_T__DIV__4096 0xc   // /4,096
#define TIMXCR_T__DIV__8192 0xd   // /8,192
#define TIMXCR_T__DIV__16384 0xe   // /16,384
#define TIMXCR_T__DIV__32768 0xf   // /32,768

// enum - TIMxSR_t
#define TIMXSR_T__CMP0IF__NO_PENDING_COMPARE_0 0x0   // No pending compare 0 interrupt
#define TIMXSR_T__CMP0IF__COMPARE_0_INTERRUPT_PENDING 0x1   // Compare 0 interrupt pending
#define TIMXSR_T__CMP1IF__NO_PENDING_COMPARE_1 0x0   // No pending compare 1 interrupt
#define TIMXSR_T__CMP1IF__COMPARE_1_INTERRUPT_PENDING 0x1   // Compare 1 interrupt pending
#define TIMXSR_T__CMP2IF__NO_PENDING_COMPARE_2 0x0   // No pending compare 2 interrupt
#define TIMXSR_T__CMP2IF__COMPARE_2_INTERRUPT_PENDING 0x1   // Compare 2 interrupt pending
#define TIMXSR_T__OVIF__NO_PENDING_OVERFLOW_INTERRUPT 0x0   // No pending overflow interrupt
#define TIMXSR_T__OVIF__OVERFLOW_INTERRUPT_PENDING 0x1   // Overflow interrupt pending
#define TIMXSR_T__CAP0IF__NO_PENDING_CAPTURE_0 0x0   // No pending capture 0 interrupt
#define TIMXSR_T__CAP0IF__CAPTURE_0_INTERRUPT_PENDING 0x1   // Capture 0 interrupt pending
#define TIMXSR_T__CAP1IF__NO_PENDING_CAPTURE_1 0x0   // No pending capture 1 interrupt
#define TIMXSR_T__CAP1IF__CAPTURE_1_INTERRUPT_PENDING 0x1   // Capture 1 interrupt pending
#define TIMXSR_T__CMP0OUT__TXCMP0_OUTPUT_LOW 0x0   // TxCMP0 output LOW
#define TIMXSR_T__CMP0OUT__TXCMP0_OUTPUT_HIGH 0x1   // TxCMP0 output HIGH
#define TIMXSR_T__CMP1OUT__TXCMP1_OUTPUT_LOW 0x0   // TxCMP1 output LOW
#define TIMXSR_T__CMP1OUT__TXCMP1_OUTPUT_HIGH 0x1   // TxCMP1 output HIGH

#ifdef __cplusplus
}
#endif

#endif /* TIMER_REGS_H */
