/* GENERATED by platform/common/python/rdl_cheader_regs.py from
   hdl/common/regs/rdl/. DO NOT EDIT.

     regenerate:  tools/bin/bazel run //platform/common/python:rdl_regs_headers
     gates:       //platform/common:regs_headers_identity_test   tracked == generated
                  //platform/common:regs_headers_compile_test    -Wall -Werror, every macro
                  //platform/common:regs_headers_vs_memorymap_test  bases and addresses
                                                                 equal MemoryMap.h's */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef TRNG_REGS_H
#define TRNG_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - TRNGxCR_t
#define TRNGXCR_T__TRNGEN_bm 0x1
#define TRNGXCR_T__TRNGEN_bp 0
#define TRNGXCR_T__TRNGEN_bw 1
#define TRNGXCR_T__TRNGEN_reset 0x0
#define TRNGXCR_T__TRNGDRDYIE_bm 0x2
#define TRNGXCR_T__TRNGDRDYIE_bp 1
#define TRNGXCR_T__TRNGDRDYIE_bw 1
#define TRNGXCR_T__TRNGDRDYIE_reset 0x0
#define TRNGXCR_T__TRNGALMIE_bm 0x4
#define TRNGXCR_T__TRNGALMIE_bp 2
#define TRNGXCR_T__TRNGALMIE_bw 1
#define TRNGXCR_T__TRNGALMIE_reset 0x0
#define TRNGXCR_T__TRNGROSEL_bm 0xf0
#define TRNGXCR_T__TRNGROSEL_bp 4
#define TRNGXCR_T__TRNGROSEL_bw 4
#define TRNGXCR_T__TRNGROSEL_reset 0x0
#define TRNGXCR_T__TRNGDECIM_bm 0xf00
#define TRNGXCR_T__TRNGDECIM_bp 8
#define TRNGXCR_T__TRNGDECIM_bw 4
#define TRNGXCR_T__TRNGDECIM_reset 0x0

// reg - TRNGxSR_t
#define TRNGXSR_T__TRNGDRDY_bm 0x1
#define TRNGXSR_T__TRNGDRDY_bp 0
#define TRNGXSR_T__TRNGDRDY_bw 1
#define TRNGXSR_T__TRNGDRDY_reset 0x0
#define TRNGXSR_T__TRNGALMF_bm 0x2
#define TRNGXSR_T__TRNGALMF_bp 1
#define TRNGXSR_T__TRNGALMF_bw 1
#define TRNGXSR_T__TRNGALMF_reset 0x0
#define TRNGXSR_T__TRNGRUN_bm 0x4
#define TRNGXSR_T__TRNGRUN_bp 2
#define TRNGXSR_T__TRNGRUN_bw 1
#define TRNGXSR_T__TRNGRUN_reset 0x0

// reg - TRNGxDR_t
#define TRNGXDR_T__TRNGDR_bm 0xffffffff
#define TRNGXDR_T__TRNGDR_bp 0
#define TRNGXDR_T__TRNGDR_bw 32
#define TRNGXDR_T__TRNGDR_reset 0x0

// reg - TRNGxHT_t
#define TRNGXHT_T__TRNGRCTC_bm 0xff
#define TRNGXHT_T__TRNGRCTC_bp 0
#define TRNGXHT_T__TRNGRCTC_bw 8
#define TRNGXHT_T__TRNGRCTC_reset 0x0
#define TRNGXHT_T__TRNGRUNLEN_bm 0x3f0000
#define TRNGXHT_T__TRNGRUNLEN_bp 16
#define TRNGXHT_T__TRNGRUNLEN_bw 6
#define TRNGXHT_T__TRNGRUNLEN_reset 0x0

// addrmap - trng
typedef struct __attribute__ ((__packed__)) {
    uint32_t TRNGxCR;
    uint32_t TRNGxSR;
    uint32_t TRNGxDR;
    uint32_t TRNGxHT;
} trng_t;


static_assert(sizeof(trng_t) == 0x10, "Packing error");

// enum - TRNGxCR_t
#define TRNGXCR_T__TRNGEN__DISABLED_RINGS_PARKED 0x0   // Disabled (rings parked)
#define TRNGXCR_T__TRNGEN__ENABLED 0x1   // Enabled
#define TRNGXCR_T__TRNGDRDYIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TRNGXCR_T__TRNGDRDYIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled
#define TRNGXCR_T__TRNGALMIE__INTERRUPT_DISABLED 0x0   // Interrupt disabled
#define TRNGXCR_T__TRNGALMIE__INTERRUPT_ENABLED 0x1   // Interrupt enabled

// enum - TRNGxSR_t
#define TRNGXSR_T__TRNGDRDY__NO_WORD_READY_A 0x0   // No word ready (a TRNG0DR read now returns 0 and does not consume)
#define TRNGXSR_T__TRNGDRDY__WORD_READY 0x1   // Word ready
#define TRNGXSR_T__TRNGALMF__NO_ALARM 0x0   // No alarm
#define TRNGXSR_T__TRNGALMF__REPETITION_COUNT_CUTOFF_REACHED 0x1   // Repetition-count cutoff reached
#define TRNGXSR_T__TRNGRUN__IDLE_HALTED 0x0   // Idle / halted
#define TRNGXSR_T__TRNGRUN__RUNNING 0x1   // Running

#ifdef __cplusplus
}
#endif

#endif /* TRNG_REGS_H */
