/* VestaRV: UART registers.
   Generated from hdl/common/regs/rdl/uart.rdl by platform/common/python/rdl_cheader_regs.py.
   Do not edit; regenerate with `bazel run //platform/common/python:rdl_regs_headers`. */
// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef UART_REGS_H
#define UART_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - UARTxCR_t
#define UARTXCR_T__TCIE_bm 0x1
#define UARTXCR_T__TCIE_bp 0
#define UARTXCR_T__TCIE_bw 1
#define UARTXCR_T__TCIE_reset 0x0
#define UARTXCR_T__TEIE_bm 0x2
#define UARTXCR_T__TEIE_bp 1
#define UARTXCR_T__TEIE_bw 1
#define UARTXCR_T__TEIE_reset 0x0
#define UARTXCR_T__CIE_bm 0x4
#define UARTXCR_T__CIE_bp 2
#define UARTXCR_T__CIE_bw 1
#define UARTXCR_T__CIE_reset 0x0
#define UARTXCR_T__PSEL_bm 0x8
#define UARTXCR_T__PSEL_bp 3
#define UARTXCR_T__PSEL_bw 1
#define UARTXCR_T__PSEL_reset 0x0
#define UARTXCR_T__UPEN_bm 0x10
#define UARTXCR_T__UPEN_bp 4
#define UARTXCR_T__UPEN_bw 1
#define UARTXCR_T__UPEN_reset 0x0
#define UARTXCR_T__UEN_bm 0x20
#define UARTXCR_T__UEN_bp 5
#define UARTXCR_T__UEN_bw 1
#define UARTXCR_T__UEN_reset 0x0

// reg - UARTxSR_t
#define UARTXSR_T__TCIF_bm 0x1
#define UARTXSR_T__TCIF_bp 0
#define UARTXSR_T__TCIF_bw 1
#define UARTXSR_T__TCIF_reset 0x0
#define UARTXSR_T__TEIF_bm 0x2
#define UARTXSR_T__TEIF_bp 1
#define UARTXSR_T__TEIF_bw 1
#define UARTXSR_T__TEIF_reset 0x0
#define UARTXSR_T__RCIF_bm 0x4
#define UARTXSR_T__RCIF_bp 2
#define UARTXSR_T__RCIF_bw 1
#define UARTXSR_T__RCIF_reset 0x0
#define UARTXSR_T__OVF_bm 0x8
#define UARTXSR_T__OVF_bp 3
#define UARTXSR_T__OVF_bw 1
#define UARTXSR_T__OVF_reset 0x0
#define UARTXSR_T__PEF_bm 0x10
#define UARTXSR_T__PEF_bp 4
#define UARTXSR_T__PEF_bw 1
#define UARTXSR_T__PEF_reset 0x0
#define UARTXSR_T__FEF_bm 0x20
#define UARTXSR_T__FEF_bp 5
#define UARTXSR_T__FEF_bw 1
#define UARTXSR_T__FEF_reset 0x0
#define UARTXSR_T__TXBF_bm 0x40
#define UARTXSR_T__TXBF_bp 6
#define UARTXSR_T__TXBF_bw 1
#define UARTXSR_T__TXBF_reset 0x0
#define UARTXSR_T__RXBF_bm 0x80
#define UARTXSR_T__RXBF_bp 7
#define UARTXSR_T__RXBF_bw 1
#define UARTXSR_T__RXBF_reset 0x0

// reg - UARTxBR_t
#define UARTXBR_T__BR_bm 0xfff
#define UARTXBR_T__BR_bp 0
#define UARTXBR_T__BR_bw 12
#define UARTXBR_T__BR_reset 0x0

// reg - UARTxRX_t
#define UARTXRX_T__RX_bm 0xff
#define UARTXRX_T__RX_bp 0
#define UARTXRX_T__RX_bw 8
#define UARTXRX_T__RX_reset 0x0

// reg - UARTxTX_t
#define UARTXTX_T__TX_bm 0xff
#define UARTXTX_T__TX_bp 0
#define UARTXTX_T__TX_bw 8
#define UARTXTX_T__TX_reset 0x0

// addrmap - uart
typedef struct __attribute__ ((__packed__)) {
    uint8_t UARTxCR;
    uint8_t RESERVED_1_3[0x3];
    uint8_t UARTxSR;
    uint8_t RESERVED_5_7[0x3];
    uint16_t UARTxBR;
    uint8_t RESERVED_a_b[0x2];
    uint8_t UARTxRX;
    uint8_t RESERVED_d_f[0x3];
    uint8_t UARTxTX;
} uart_t;


static_assert(sizeof(uart_t) == 0x11, "Packing error");

// enum - UARTxCR_t
#define UARTXCR_T__TCIE__TX_COMPLETE_INTERRUPT_DISABLED 0x0   // TX complete interrupt disabled
#define UARTXCR_T__TCIE__TX_COMPLETE_INTERRUPT_ENABLED 0x1   // TX complete interrupt enabled
#define UARTXCR_T__TEIE__TX_EMPTY_INTERRUPT_DISABLED 0x0   // TX empty interrupt disabled
#define UARTXCR_T__TEIE__TX_EMPTY_INTERRUPT_ENABLED 0x1   // TX empty interrupt enabled
#define UARTXCR_T__CIE__RX_COMPLETE_INTERRUPT_DISABLED 0x0   // RX complete interrupt disabled
#define UARTXCR_T__CIE__RX_COMPLETE_INTERRUPT_ENABLED 0x1   // RX complete interrupt enabled
#define UARTXCR_T__PSEL__EVEN_PARITY 0x0   // Even parity
#define UARTXCR_T__PSEL__ODD_PARITY 0x1   // Odd parity
#define UARTXCR_T__UPEN__PARITY_DISABLED 0x0   // Parity disabled
#define UARTXCR_T__UPEN__PARITY_ENABLED 0x1   // Parity enabled
#define UARTXCR_T__UEN__UART_DISABLED 0x0   // UART disabled
#define UARTXCR_T__UEN__UART_ENABLED 0x1   // UART enabled

// enum - UARTxSR_t
#define UARTXSR_T__TCIF__NO_PENDING_TX_COMPLETE 0x0   // No pending TX complete interrupt
#define UARTXSR_T__TCIF__TX_COMPLETE_INTERRUPT_PENDING 0x1   // TX complete interrupt pending
#define UARTXSR_T__TEIF__NO_PENDING_TX_EMPTY 0x0   // No pending TX empty interrupt
#define UARTXSR_T__TEIF__TX_EMPTY_INTERRUPT_PENDING 0x1   // TX empty interrupt pending
#define UARTXSR_T__RCIF__NO_PENDING_RX_COMPLETE 0x0   // No pending RX complete interrupt
#define UARTXSR_T__RCIF__RX_COMPLETE_INTERRUPT_PENDING 0x1   // RX complete interrupt pending
#define UARTXSR_T__OVF__NO_RECEIVE_DATA_OVERRUN 0x0   // No receive data overrun
#define UARTXSR_T__OVF__RECEIVE_DATA_OVERFLOW_DETECTED 0x1   // Receive data overflow detected
#define UARTXSR_T__PEF__NO_PARITY_ERROR 0x0   // No parity error
#define UARTXSR_T__PEF__PARITY_ERROR_DETECTED_ON 0x1   // Parity error detected on last reception
#define UARTXSR_T__FEF__NO_FRAMING_ERROR 0x0   // No framing error
#define UARTXSR_T__FEF__FRAMING_ERROR_DETECTED_ON 0x1   // Framing error detected on last reception
#define UARTXSR_T__TXBF__TRANSMITTER_IDLE 0x0   // Transmitter idle
#define UARTXSR_T__TXBF__TRANSMISSION_IN_PROGRESS 0x1   // Transmission in progress
#define UARTXSR_T__RXBF__RECEIVER_IDLE 0x0   // Receiver idle
#define UARTXSR_T__RXBF__RECEPTION_IN_PROGRESS 0x1   // Reception in progress

#ifdef __cplusplus
}
#endif

#endif /* UART_REGS_H */
