set_clock_latency -source -early -min -rise  -0.157815 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.145648 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.157815 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.145648 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.157815 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.145648 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.157815 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.145648 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.247389 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -fall  -0.239014 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -rise  -0.247389 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -fall  -0.239014 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -rise  -0.247389 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -fall  -0.239014 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -rise  -0.247389 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -fall  -0.239014 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -rise  -0.260237 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.24635 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.260237 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.24635 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.260237 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.24635 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.260237 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.24635 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.260725 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -fall  -0.251329 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -rise  -0.260725 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -fall  -0.251329 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -rise  -0.260725 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -fall  -0.251329 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -rise  -0.260725 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -fall  -0.251329 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -rise  -0.107474 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.0986142 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.107474 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.0986142 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.107474 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.0986142 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.107474 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.0986142 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.264377 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.251322 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.264377 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.251322 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.264377 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.251322 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.264377 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.251322 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.095835 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.0841787 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.095835 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.0841787 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.095835 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.0841787 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.095835 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.0841787 [get_pins {spi1/sck_in}] -clock clk_sck1 
