set_clock_latency -source -early -min -rise  -0.416768 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -fall  -0.379691 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -rise  -0.416768 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -max -fall  -0.379691 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -rise  -0.416768 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -min -fall  -0.379691 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -rise  -0.416768 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -late -max -fall  -0.379691 [get_pins {core/clk_cpu}] -clock clk_cpu 
set_clock_latency -source -early -min -rise  -0.657629 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -fall  -0.649362 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -rise  -0.657629 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -max -fall  -0.649362 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -rise  -0.657629 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -min -fall  -0.649362 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -rise  -0.657629 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -late -max -fall  -0.649362 [get_pins {system0/clk_lfxt_out}] -clock clk_lfxt 
set_clock_latency -source -early -min -rise  -0.703201 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -fall  -0.671766 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -rise  -0.703201 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -max -fall  -0.671766 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -rise  -0.703201 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -min -fall  -0.671766 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -rise  -0.703201 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -late -max -fall  -0.671766 [get_pins {system0/smclk_out}] -clock smclk 
set_clock_latency -source -early -min -rise  -0.688779 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -fall  -0.676016 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -rise  -0.688779 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -max -fall  -0.676016 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -rise  -0.688779 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -min -fall  -0.676016 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -rise  -0.688779 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -late -max -fall  -0.676016 [get_pins {system0/clk_hfxt_out}] -clock clk_hfxt 
set_clock_latency -source -early -min -rise  -0.2726 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -fall  -0.234855 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -rise  -0.2726 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -max -fall  -0.234855 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -rise  -0.2726 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -min -fall  -0.234855 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -rise  -0.2726 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -late -max -fall  -0.234855 [get_pins {spi0/sck_in}] -clock clk_sck0 
set_clock_latency -source -early -min -rise  -0.703947 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -fall  -0.67396 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -rise  -0.703947 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -max -fall  -0.67396 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -rise  -0.703947 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -min -fall  -0.67396 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -rise  -0.703947 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -late -max -fall  -0.67396 [get_pins {system0/mclk_out}] -clock mclk 
set_clock_latency -source -early -min -rise  -0.252655 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -min -fall  -0.2255 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -rise  -0.252655 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -early -max -fall  -0.2255 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -rise  -0.252655 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -min -fall  -0.2255 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -rise  -0.252655 [get_pins {spi1/sck_in}] -clock clk_sck1 
set_clock_latency -source -late -max -fall  -0.2255 [get_pins {spi1/sck_in}] -clock clk_sck1 
