# List of all rcf files (one per line)
# RCF source: ~/vestarv/verification/isa/rcf/  (built by make rv32ui-flash etc.)
# Run this script from ~/vestarv/xcelium/riscv_test/rcf/ to create symlinks there.
rcf_files=(
"/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32ui-p-simple.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-add.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-lb.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-lh.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-lw.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-lbu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-lhu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-addi.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-slli.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-slti.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxrv32ui-p-sltiu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-srli.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-srai.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-ori.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-andi.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxrv32ui-p-auipc.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-sb.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-sh.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-sw.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-sub.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-sll.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-slt.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-sltu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-xor.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-srl.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-sra.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxxrv32ui-p-or.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-and.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-lui.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-beq.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-bne.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-blt.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-bge.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-bltu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-bgeu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxrv32ui-p-jalr.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxxxxrv32ui-p-jal.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-div.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-divu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-mul.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-mulh.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxrv32um-p-mulhsu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-mulhu.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-rem.rcf"
# "/home/mseminario2/vestarv/verification/isa/rcf/xxxrv32um-p-remu.rcf"
)

# Loop over each file and create symlink in current directory
for file in "${rcf_files[@]}"; do
    ln -sf "$file" .
done
