#!/usr/bin/env python3
"""VestaRV: generate the FPGA board top level and its pin constraints for one chip configuration.

Inputs: the generated MCU.vhd (its entity gives the port list) and PadRing.json (the bonded
pins, their package numbers and functions). Outputs:

  fpga_top.vhd   entity fpga_top: MCU with every bonded GPIO pin as one inout port. A pin drives
                 when its prtN_dir bit is '0' (the pad's active-low output enable), so Vivado infers
                 an IOBUF per pin. HFXT and LFXT enter on dedicated clock ports, RESETN on its own
                 input, and pass_led is '1' while a0 = 0xCAFEBABE (the ISA-test pass label).
  fpga_pins.xdc  primary clocks on clk_hfxt / clk_lfxt, and one PACKAGE_PIN / IOSTANDARD line per
                 port, commented out, labelled with the chip pin and function to wire it to.

Pad-ring names count ports from 0 (P0.0 = GPIO0 = CS_FLASH); the VHDL counts from 1, so pad-ring
port k is prt(k+1). Unbonded MCU pins read '0' and their outputs are left open.

Usage: gen_fpga_top.py MCU.vhd PadRing.json fpga_top.vhd fpga_pins.xdc
"""

import json
import re
import sys

CLOCK_FUNCS = {"HFXT": ("clk_hfxt", "24 MHz crystal (the firmware's UART divisors assume 24 MHz)", 41.667),
               "LFXT": ("clk_lfxt", "32.768 kHz crystal, or tie low", 30517.578)}


def mcu_ports(mcu_vhd):
    text = open(mcu_vhd).read()
    m = re.search(r"^entity MCU is(.*?)^end", text, re.S | re.M)
    if not m:
        sys.exit("gen_fpga_top: no 'entity MCU' in %s" % mcu_vhd)
    ports = []
    for name, mode, typ in re.findall(r"^\s*(\w+)\s*:\s*(in|out|inout)\s+([^;\n-]+)", m.group(1), re.M):
        ports.append((name, mode, typ.strip().rstrip(")").strip() + (")" if "(" in typ else "")))
    return ports


def width(typ):
    m = re.search(r"\((\d+)\s+downto\s+0\)", typ)
    return int(m.group(1)) + 1 if m else 1


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__.strip().splitlines()[-1])
    mcu_vhd, padring_json, out_vhd, out_xdc = sys.argv[1:]
    ports = mcu_ports(mcu_vhd)
    names = {p[0]: p for p in ports}
    nports = sorted(int(re.match(r"prt(\d+)_in$", n).group(1)) for n in names if re.match(r"prt\d+_in$", n))
    if "resetn_in" not in names or not nports:
        sys.exit("gen_fpga_top: MCU entity lacks resetn_in or prtN_in ports")

    ring = json.load(open(padring_json))
    pins = []      # (vhdl_port, bit, pad_name, package_pin, function)
    clocks = {}    # func -> (vhdl_port, bit, pad_name, package_pin)
    for p in ring["pins"]:
        g = re.match(r"P(\d+)\.(\d+)$", p.get("gpio", ""))
        if not g:
            continue
        port, bit = int(g.group(1)) + 1, int(g.group(2))
        if port not in nports:
            continue
        func = p.get("af0", "")
        if not func and "(BOOT)" in p["name"]:
            func = "BOOT"
        if func in CLOCK_FUNCS:
            clocks[func] = (port, bit, p["gpio"], p["pin"])
        else:
            pins.append((port, bit, p["gpio"], p["pin"], func))
    pins.sort(key=lambda t: (t[0], t[1]))
    resetn_pin = next((p["pin"] for p in ring["pins"] if p["name"] == "RESETN"), None)
    pkg = ring.get("package", {})
    pkg_desc = "%s-%s" % (pkg.get("type", "?"), pkg.get("pinCount", "?"))

    def pname(port, bit):
        return "p%d_%d" % (port - 1, bit)

    # ---- fpga_top.vhd -------------------------------------------------------------------------
    v = []
    v.append("-- VestaRV: FPGA board top level. GENERATED by implementations/fpga/bringup/gen_fpga_top.py")
    v.append("-- from the configuration's MCU.vhd and PadRing.json (%s, %d bonded GPIO pins); do not edit." % (pkg_desc, len(pins) + len(clocks)))
    v.append("-- Each bonded pin is one inout port, driven while its prtN_dir bit is '0' (the pad's active-low output enable), so Vivado infers an IOBUF per pin.")
    v.append("-- Port pK_B is pad-ring pin PK.B, which the firmware headers call P(K+1).B. Pull resistors (prtN_ren) are not modelled: set PULLTYPE in the XDC.")
    v.append("library ieee;")
    v.append("use ieee.std_logic_1164.all;")
    v.append("")
    v.append("entity fpga_top is")
    v.append("    port (")
    decl = []
    for func in sorted(clocks):
        port, bit, gpio, pin = clocks[func]
        decl.append(("%s : in std_logic" % CLOCK_FUNCS[func][0], "%s (%s, chip pin %s): %s" % (func, gpio, pin, CLOCK_FUNCS[func][1])))
    decl.append(("resetn : in std_logic", "RESETN (chip pin %s), active low" % resetn_pin))
    decl.append(("pass_led : out std_logic", "'1' while a0 = 0xCAFEBABE, the ISA-test pass label"))
    for port, bit, gpio, pin, func in pins:
        decl.append(("%s : inout std_logic" % pname(port, bit), "%s, chip pin %s%s" % (gpio, pin, (", " + func) if func else "")))
    for i, (d, c) in enumerate(decl):
        v.append("        %-30s -- %s" % (d + (";" if i < len(decl) - 1 else ""), c))
    v.append("    );")
    v.append("end fpga_top;")
    v.append("")
    v.append("architecture generated of fpga_top is")
    v.append("")
    for name, mode, typ in ports:
        v.append("    signal %s : %s;" % (name, typ))
    v.append("")
    v.append("begin")
    v.append("")
    v.append("    mcu0: entity work.MCU")
    v.append("        port map (")
    for i, (name, mode, typ) in enumerate(ports):
        v.append("            %s => %s%s" % (name, name, "," if i < len(ports) - 1 else ""))
    v.append("        );")
    v.append("")
    v.append("    -- to_X01 is a wire in synthesis; in simulation it turns a weak pull ('L', 'H') into the 0 or 1 a pad delivers.")
    v.append("    resetn_in <= to_X01(resetn);")
    v.append("    pass_led  <= '1' when a0 = x\"CAFEBABE\" else '0';")
    v.append("")
    bonded = {(p[0], p[1]) for p in pins} | {(c[0], c[1]) for c in clocks.values()}
    for func in sorted(clocks):
        port, bit, gpio, pin = clocks[func]
        v.append("    prt%d_in(%d) <= %s;" % (port, bit, CLOCK_FUNCS[func][0]))
    for port, bit, gpio, pin, func in pins:
        n = pname(port, bit)
        v.append("    %s <= prt%d_out(%d) when prt%d_dir(%d) = '0' else 'Z';" % (n, port, bit, port, bit))
        v.append("    prt%d_in(%d) <= to_X01(%s);" % (port, bit, n))
    for port in nports:
        w = width(names["prt%d_in" % port][2])
        for bit in range(w):
            if (port, bit) not in bonded:
                v.append("    prt%d_in(%d) <= '0';  -- not bonded" % (port, bit))
    v.append("")
    v.append("end generated;")
    open(out_vhd, "w").write("\n".join(v) + "\n")

    # ---- fpga_pins.xdc ------------------------------------------------------------------------
    x = []
    x.append("# VestaRV: fpga_top pin constraints. GENERATED by implementations/fpga/bringup/gen_fpga_top.py; copy and edit.")
    x.append("# Fill in PACKAGE_PIN and IOSTANDARD for your board and uncomment. Each line names the chip pin the port")
    x.append("# replaces. The clocks below are the only timing constraints needed to bring the chip up at 24 MHz; the")
    x.append("# design's internal generated and multiplexed clocks are described in implementations/fpga/synth/fpga_default_ooc.xdc.")
    x.append("")
    for func in sorted(clocks):
        name, desc, period = CLOCK_FUNCS[func]
        x.append("create_clock -name %s -period %.3f [get_ports %s]" % (name, period, name))
    if len(clocks) == 2:
        x.append("set_clock_groups -asynchronous -group [get_clocks clk_hfxt] -group [get_clocks clk_lfxt]")
    x.append("set_false_path -from [get_ports resetn]")
    x.append("")
    rows = [(CLOCK_FUNCS[f][0], "%s %s, chip pin %s" % (f, clocks[f][2], clocks[f][3])) for f in sorted(clocks)]
    rows.append(("resetn", "RESETN, chip pin %s, active low" % resetn_pin))
    rows.append(("pass_led", "LED: on when the test payload passes"))
    rows += [(pname(p, b), "%s, chip pin %s%s" % (g, pin, (", " + f) if f else "")) for p, b, g, pin, f in pins]
    for name, desc in rows:
        x.append("# set_property -dict {PACKAGE_PIN <pin> IOSTANDARD LVCMOS33} [get_ports %-9s] ;# %s" % (name, desc))
    open(out_xdc, "w").write("\n".join(x) + "\n")


if __name__ == "__main__":
    main()
