# chip_top_padring.tcl -- GENERATED by platform/common (make chip); do not hand-edit.
# Ordered pad lists for the chip_top pad-ring flow (innovus/common, Flavor A/B):
#   source out/pnr/chip_top_padring.tcl
#   place_side left $PADRING_LEFT   ;# etc. (place_side/place_pad from chip_top.innovus.tcl)
# Derived from the same package model as config/PadRing.json + the TRM pinout
# (model "castalia-quad-qfn64", QFN-64). Lists are in placeInstance geometric order:
# +x for bottom/top rows, +y for left/right rows; QFN pin 1 is at the TOP of the
# left edge (top view, CCW numbering), so the left/top lists run pin-descending.
# Instance names are placeholders (PAD_<pad>); Flavor B binds cells and nets.

set PADRING_LEFT {}
lappend PADRING_LEFT PAD_P2_1        ;# pin 16: P2.1(GPIO17)/T0CMP1  [Digital I/O]
lappend PADRING_LEFT PAD_P2_2        ;# pin 15: P2.2(GPIO18)/T0CAP0  [Digital I/O]
lappend PADRING_LEFT PAD_P2_3        ;# pin 14: P2.3(GPIO19)/T0CAP1  [Digital I/O]
lappend PADRING_LEFT PAD_P2_5        ;# pin 13: P2.5(GPIO21)/T1CMP1  [Digital I/O]
lappend PADRING_LEFT PAD_P2_6        ;# pin 12: P2.6(GPIO22)/T1CAP0  [Digital I/O]
lappend PADRING_LEFT PAD_VSS         ;# pin 11: VSS  [Digital Core]
lappend PADRING_LEFT PAD_VDD         ;# pin 10: VDD  [Digital Core]
lappend PADRING_LEFT PAD_RESETN      ;# pin  9: RESETN  [Digital I/O]
lappend PADRING_LEFT PAD_P0_0        ;# pin  8: P0.0(GPIO0)/CS_FLASH  [Digital I/O]
lappend PADRING_LEFT PAD_P0_1        ;# pin  7: P0.1(GPIO1)/MISO0  [Digital I/O]
lappend PADRING_LEFT PAD_P0_2        ;# pin  6: P0.2(GPIO2)/MOSI0  [Digital I/O]
lappend PADRING_LEFT PAD_P0_3        ;# pin  5: P0.3(GPIO3)/SCK0  [Digital I/O]
lappend PADRING_LEFT PAD_P0_4        ;# pin  4: P0.4(GPIO4)/LFXT  [Digital I/O]
lappend PADRING_LEFT PAD_P0_5        ;# pin  3: P0.5(GPIO5)/HFXT  [Digital I/O]
lappend PADRING_LEFT PAD_P0_6        ;# pin  2: P0.6(GPIO6)/TRAP  [Digital I/O]
lappend PADRING_LEFT PAD_P0_7        ;# pin  1: P0.7(BOOT)  [Digital I/O]

set PADRING_BOTTOM {}
lappend PADRING_BOTTOM PAD_AVDD_2      ;# pin 17: AVDD_2  [Analog2]
lappend PADRING_BOTTOM PAD_RE2_2       ;# pin 18: RE2_2  [Analog2]
lappend PADRING_BOTTOM PAD_RE_2        ;# pin 19: RE_2  [Analog2]
lappend PADRING_BOTTOM PAD_WE_2        ;# pin 20: WE_2  [Analog2]
lappend PADRING_BOTTOM PAD_CE_2        ;# pin 21: CE_2  [Analog2]
lappend PADRING_BOTTOM PAD_AVSS_2      ;# pin 22: AVSS_2  [Analog2]
lappend PADRING_BOTTOM PAD_VDDPST      ;# pin 23: VDDPST  [Digital I/O]
lappend PADRING_BOTTOM PAD_P3_6        ;# pin 24: P3.6(GPIO30)/DTP2  [Digital I/O]
lappend PADRING_BOTTOM PAD_P3_7        ;# pin 25: P3.7(GPIO31)/DTP3  [Digital I/O]
lappend PADRING_BOTTOM PAD_VSSPST      ;# pin 26: VSSPST  [Digital I/O]
lappend PADRING_BOTTOM PAD_AVSS_3      ;# pin 27: AVSS_3  [Analog3]
lappend PADRING_BOTTOM PAD_CE_3        ;# pin 28: CE_3  [Analog3]
lappend PADRING_BOTTOM PAD_WE_3        ;# pin 29: WE_3  [Analog3]
lappend PADRING_BOTTOM PAD_RE_3        ;# pin 30: RE_3  [Analog3]
lappend PADRING_BOTTOM PAD_RE2_3       ;# pin 31: RE2_3  [Analog3]
lappend PADRING_BOTTOM PAD_AVDD_3      ;# pin 32: AVDD_3  [Analog3]

set PADRING_RIGHT {}
lappend PADRING_RIGHT PAD_P2_7        ;# pin 33: P2.7(GPIO23)/T1CAP1  [Digital I/O]
lappend PADRING_RIGHT PAD_P3_0        ;# pin 34: P3.0(GPIO24)/SDA0  [Digital I/O]
lappend PADRING_RIGHT PAD_P3_1        ;# pin 35: P3.1(GPIO25)/SCL0  [Digital I/O]
lappend PADRING_RIGHT PAD_P3_2        ;# pin 36: P3.2(GPIO26)/SDA1  [Digital I/O]
lappend PADRING_RIGHT PAD_P3_3        ;# pin 37: P3.3(GPIO27)/SCL1  [Digital I/O]
lappend PADRING_RIGHT PAD_VSS         ;# pin 38: VSS  [Digital Core]
lappend PADRING_RIGHT PAD_VDD         ;# pin 39: VDD  [Digital Core]
lappend PADRING_RIGHT PAD_POC         ;# pin 40: POC  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_0        ;# pin 41: P1.0(GPIO8)/CS1  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_1        ;# pin 42: P1.1(GPIO9)/MISO1  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_2        ;# pin 43: P1.2(GPIO10)/MOSI1  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_3        ;# pin 44: P1.3(GPIO11)/SCK1  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_4        ;# pin 45: P1.4(GPIO12)/TX0  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_5        ;# pin 46: P1.5(GPIO13)/RX0  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_6        ;# pin 47: P1.6(GPIO14)/TX1  [Digital I/O]
lappend PADRING_RIGHT PAD_P1_7        ;# pin 48: P1.7(GPIO15)/RX1  [Digital I/O]

set PADRING_TOP {}
lappend PADRING_TOP PAD_AVDD_0      ;# pin 64: AVDD_0  [Analog0]
lappend PADRING_TOP PAD_RE2_0       ;# pin 63: RE2_0  [Analog0]
lappend PADRING_TOP PAD_RE_0        ;# pin 62: RE_0  [Analog0]
lappend PADRING_TOP PAD_WE_0        ;# pin 61: WE_0  [Analog0]
lappend PADRING_TOP PAD_CE_0        ;# pin 60: CE_0  [Analog0]
lappend PADRING_TOP PAD_AVSS_0      ;# pin 59: AVSS_0  [Analog0]
lappend PADRING_TOP PAD_VDDPST      ;# pin 58: VDDPST  [Digital I/O]
lappend PADRING_TOP PAD_P3_4        ;# pin 57: P3.4(GPIO28)/DTP0  [Digital I/O]
lappend PADRING_TOP PAD_P3_5        ;# pin 56: P3.5(GPIO29)/DTP1  [Digital I/O]
lappend PADRING_TOP PAD_VSSPST      ;# pin 55: VSSPST  [Digital I/O]
lappend PADRING_TOP PAD_AVSS_1      ;# pin 54: AVSS_1  [Analog1]
lappend PADRING_TOP PAD_CE_1        ;# pin 53: CE_1  [Analog1]
lappend PADRING_TOP PAD_WE_1        ;# pin 52: WE_1  [Analog1]
lappend PADRING_TOP PAD_RE_1        ;# pin 51: RE_1  [Analog1]
lappend PADRING_TOP PAD_RE2_1       ;# pin 50: RE2_1  [Analog1]
lappend PADRING_TOP PAD_AVDD_1      ;# pin 49: AVDD_1  [Analog1]

