#!/usr/bin/env python3
# =============================================================================
# harvest_cg_enables.py -- regenerate the clock-gating path-group -through lists
# for chip_top_quad.sdc from the CURRENT netlist.
#
# WHY: the genus-emitted `cg_enable_group_*` group_path blocks hard-code
# RC_CG_HIER_INST<n> instance names. Any MCU re-synthesis renumbers them
# globally (the 2026-07-16 AFE-stub re-synth did exactly this, invalidating 855
# through-pins -> 855 TCLCMD-917). CQ8c REMOVED the stale blocks (group_path is
# an optimization-ordering hint that constrains no endpoint -> coverage-neutral).
# If a future flow wants the fine-grained CG path group back, run this against
# the current init_verilog set to emit a fresh, resolving block.
#
# This emits ONE consolidated `cg_enable_group_all` -through list of every real
# clock-gating enable pin under mcu0 (full hierarchical paths, deduped). It does
# NOT split by clock domain (that needs a timing tool's clock propagation; the
# per-clock `group_path -from [get_clocks ...]` groups already cover that intent
# without instance-number fragility). Paste its output before the
# set_clock_gating_check line in in/chip_top_quad.sdc, or -source it.
#
# Usage:  /usr/bin/python3 tcl/harvest_cg_enables.py     (from innovus/common)
# =============================================================================
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # innovus/common
NETS = [os.path.join(ROOT,"in","chip_top_quad.v"),
        os.path.join(ROOT,"in","MCU_MP_hier.pnr.v")]
TOP  = "chip_top_quad"
CG_ENABLE_PORT = "enable"   # RC_CG_MOD_* module's enable port

KW = set("module endmodule input output inout wire reg assign supply0 supply1 "
         "tri wand wor parameter localparam defparam generate endgenerate genvar "
         "for if else begin end initial always integer real time trireg".split())
inst_re = re.compile(r'^\s*([A-Za-z_]\w*)\s+(\\?[^\s(]+)\s*\(')

# module -> {inst: type}; also mark which module types are clock-gating cells
mods, is_cg = {}, set()
for nf in NETS:
    cur=None; in_hdr=False
    for line in open(nf):
        m=re.match(r'^\s*module\s+([A-Za-z_]\w*)',line)
        if m:
            cur=m.group(1); mods.setdefault(cur,{})
            if cur.startswith("RC_CG_MOD"): is_cg.add(cur)
            in_hdr=(';' not in line); continue
        if in_hdr:
            if ';' in line: in_hdr=False
            continue
        if re.match(r'^\s*endmodule',line): cur=None; continue
        if cur is None: continue
        im=inst_re.match(line)
        if im and im.group(1) not in KW:
            mods[cur][im.group(2)]=im.group(1)

pins=[]
def walk(modtype, path):
    for inst, typ in mods.get(modtype, {}).items():
        p = path + "/" + inst
        if typ in is_cg:
            pins.append(p + "/" + CG_ENABLE_PORT)
        else:
            walk(typ, p)
# start under mcu0 (skip pad-ring cells at chip_top_quad level)
for inst, typ in mods.get(TOP, {}).items():
    if inst == "mcu0":
        walk(typ, "mcu0")

pins = sorted(set(pins))
print("# GENERATED by tcl/harvest_cg_enables.py -- %d clock-gating enable pins" % len(pins))
print("group_path -weight 1.000000 -name cg_enable_group_all -through [list \\")
for i,p in enumerate(pins):
    tail = " ]" if i==len(pins)-1 else "  \\"
    print("  [get_pins %s]%s" % (p, tail))
